import type { CardPrint } from "../types";

// 3ED (Revised Edition). Revised is a 100% reprint set — it introduces no new
// cards — so this module is entirely CardPrint entries: each declares the
// per-edition Scryfall UUID (printId) and resolves printId -> definitionId ->
// a shared CardDefinition already implemented in lea/leb/arn/atq/leg/drk.
// See ADR 0014. Revised's English (3ed) art is hosted on Scryfall, so the
// printId renders correctly with no foreign-set image problem.
//
// Generated by scripts/generate-3ed-prints.mts from data/json/3ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 3ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: the 3 ante cards — Contract from Below, Darkpact, Demonic Attorney
// — are permanently out of scope (ADR 0010) and carry no print row. Every other
// non-basic Revised card resolves to an existing CardDefinition.

export const animateWall3ed: CardPrint = {
    printId: "dffd3a5f-066b-40c2-99e0-dba1771c899d",
    definitionId: "d5c83259-9b90-47c2-b48e-c7d78519e792", // Animate Wall
    setCode: "3ed",
    rarity: "rare",
};

export const armageddon3ed: CardPrint = {
    printId: "605e9a62-53e4-4771-9730-56c78237004a",
    definitionId: "5b6ddce7-b9c5-431d-a0b0-46d4aa93cbcb", // Armageddon
    setCode: "3ed",
    rarity: "rare",
};

export const balance3ed: CardPrint = {
    printId: "a21b08d4-b43d-4c93-99e7-39dfe83ced91",
    definitionId: "6f9ea46a-411f-40ce-a873-a905180093f4", // Balance
    setCode: "3ed",
    rarity: "rare",
};

export const benalishHero3ed: CardPrint = {
    printId: "63e06cd7-9f00-4343-86c2-9f74945193c2",
    definitionId: "11600105-56c6-4073-a4a6-8469030b39c9", // Benalish Hero
    setCode: "3ed",
    rarity: "common",
};

export const blackWard3ed: CardPrint = {
    printId: "c5b6b0a4-bda8-422c-bddb-b2a0ba545596",
    definitionId: "15967a39-303f-457d-bcde-51837c8d63e1", // Black Ward
    setCode: "3ed",
    rarity: "uncommon",
};

export const blessing3ed: CardPrint = {
    printId: "f64f6100-c26a-4b22-9fa6-ab3f287a94aa",
    definitionId: "f131fd27-18da-47ca-b59f-135bcac83abd", // Blessing
    setCode: "3ed",
    rarity: "rare",
};

export const blueWard3ed: CardPrint = {
    printId: "9b79eaa0-8a15-4828-9ab7-16c2aab5f19f",
    definitionId: "93f9f0f2-e1cc-4740-888c-1336c6de0a27", // Blue Ward
    setCode: "3ed",
    rarity: "uncommon",
};

export const castle3ed: CardPrint = {
    printId: "434f2329-ea4c-41ba-ab62-857076d76442",
    definitionId: "b0da8d56-3178-44c2-9344-95d2346d326f", // Castle
    setCode: "3ed",
    rarity: "uncommon",
};

export const circleOfProtectionBlack3ed: CardPrint = {
    printId: "c498313d-bb29-4ab9-ab2f-31bdc3d9f78a",
    definitionId: "fa47b4cd-8da4-4544-b011-ba92b7009203", // Circle of Protection: Black
    setCode: "3ed",
    rarity: "common",
};

export const circleOfProtectionBlue3ed: CardPrint = {
    printId: "539809fc-fdeb-4345-a920-37fdb782fdd8",
    definitionId: "848b1a7f-e8ba-40b5-92b7-af1e963a0319", // Circle of Protection: Blue
    setCode: "3ed",
    rarity: "common",
};

export const circleOfProtectionGreen3ed: CardPrint = {
    printId: "251e0407-b49a-4ee5-83a1-1523ff03a7a7",
    definitionId: "1ae32d20-b438-4f43-b603-e8f706ecfb03", // Circle of Protection: Green
    setCode: "3ed",
    rarity: "common",
};

export const circleOfProtectionRed3ed: CardPrint = {
    printId: "b66cadb3-705d-44d3-9277-5d53cd42dae1",
    definitionId: "b3dd94c5-42f6-4148-be6e-2a3a4226cc0e", // Circle of Protection: Red
    setCode: "3ed",
    rarity: "common",
};

export const circleOfProtectionWhite3ed: CardPrint = {
    printId: "7f113b87-8569-45b2-b644-fb3f4890c2ca",
    definitionId: "92df19c9-e127-42d9-8dd2-7fa5a7095428", // Circle of Protection: White
    setCode: "3ed",
    rarity: "common",
};

export const conversion3ed: CardPrint = {
    printId: "70182de2-253f-47d4-ac46-bec4a88b578e",
    definitionId: "13186bc9-8d9c-433b-ba15-121ef94dd68a", // Conversion
    setCode: "3ed",
    rarity: "uncommon",
};

export const crusade3ed: CardPrint = {
    printId: "5670c4c0-b8c3-4100-8cd9-c176b29fe01c",
    definitionId: "057986c7-20c0-4157-b4df-beae4ef5c66d", // Crusade
    setCode: "3ed",
    rarity: "rare",
};

export const deathWard3ed: CardPrint = {
    printId: "555011ea-f03a-4815-b593-cc5d92bba7bd",
    definitionId: "fa5466cc-aa57-4a7f-8b21-d92b2fe02e13", // Death Ward
    setCode: "3ed",
    rarity: "common",
};

export const disenchant3ed: CardPrint = {
    printId: "41859c6f-1017-42ae-9061-050fe0db9731",
    definitionId: "2722d7e2-61c6-4934-9c21-875ee78fd06c", // Disenchant
    setCode: "3ed",
    rarity: "common",
};

export const eyeForAnEye3ed: CardPrint = {
    printId: "23c35f2c-0442-46f3-966b-667bad6e0e27",
    definitionId: "2933ca2a-097b-44f4-ae56-ad524d26fd06", // Eye for an Eye
    setCode: "3ed",
    rarity: "rare",
};

export const farmstead3ed: CardPrint = {
    printId: "75a45b69-1b8d-4b66-a0bf-6142172c7d27",
    definitionId: "3455b006-9ea5-4aef-8ad2-d0701eb0cacf", // Farmstead
    setCode: "3ed",
    rarity: "rare",
};

export const greenWard3ed: CardPrint = {
    printId: "c1270551-607c-4ef3-88e7-45b4e2445045",
    definitionId: "1f6118b2-fe01-425a-a2ed-6d7c42286c8e", // Green Ward
    setCode: "3ed",
    rarity: "uncommon",
};

export const guardianAngel3ed: CardPrint = {
    printId: "74da83ea-8302-4927-a355-331636950572",
    definitionId: "0f84d676-5327-454c-a033-b4498a9d28e2", // Guardian Angel
    setCode: "3ed",
    rarity: "common",
};

export const healingSalve3ed: CardPrint = {
    printId: "3300b080-a6f5-4a4a-8faf-0206fbfe8988",
    definitionId: "e28de37e-84d5-4dc7-b36c-e14da5924729", // Healing Salve
    setCode: "3ed",
    rarity: "common",
};

export const holyArmor3ed: CardPrint = {
    printId: "e53412cc-2246-47b5-a212-edee7fac4a54",
    definitionId: "b01041d2-687e-4972-81c8-16690809275b", // Holy Armor
    setCode: "3ed",
    rarity: "common",
};

export const holyStrength3ed: CardPrint = {
    printId: "37414560-8187-4c5b-8245-05d77b25c454",
    definitionId: "e945a4cd-0eb1-4f54-898d-169ce2748a03", // Holy Strength
    setCode: "3ed",
    rarity: "common",
};

export const islandSanctuary3ed: CardPrint = {
    printId: "9973e59d-09ca-4647-85dd-15838cf63c2d",
    definitionId: "c15e8a42-89de-42bc-8d5f-33426d207c3a", // Island Sanctuary
    setCode: "3ed",
    rarity: "rare",
};

export const karma3ed: CardPrint = {
    printId: "b316838d-2414-4d0c-a25f-132b7462064a",
    definitionId: "6f30ad61-fcb7-4d55-ba86-94de1bf545e4", // Karma
    setCode: "3ed",
    rarity: "uncommon",
};

export const lance3ed: CardPrint = {
    printId: "d023e930-f974-40a8-8832-9357350bc7ae",
    definitionId: "ddb633f5-cc4d-4157-8217-def90cb15e24", // Lance
    setCode: "3ed",
    rarity: "uncommon",
};

export const mesaPegasus3ed: CardPrint = {
    printId: "ce7e6bfb-9038-48b5-bfaf-9450c503c69e",
    definitionId: "eaac88da-d19e-4771-944c-3709963d04e7", // Mesa Pegasus
    setCode: "3ed",
    rarity: "common",
};

export const northernPaladin3ed: CardPrint = {
    printId: "5ef69d3f-cbad-4069-82dc-4dbfb35377f4",
    definitionId: "6303233b-35eb-49ca-b844-ba6b9fe1cbd2", // Northern Paladin
    setCode: "3ed",
    rarity: "rare",
};

export const pearledUnicorn3ed: CardPrint = {
    printId: "a450ce98-4854-4378-8809-27019b3800c2",
    definitionId: "6daf1aab-1e58-4a5a-bc66-cb3f7c86e0e8", // Pearled Unicorn
    setCode: "3ed",
    rarity: "common",
};

export const personalIncarnation3ed: CardPrint = {
    printId: "e82a9dd8-653a-4410-b78f-303aaf69d11e",
    definitionId: "caf9cef4-0f2d-478a-b119-fe1967687f74", // Personal Incarnation
    setCode: "3ed",
    rarity: "rare",
};

export const purelace3ed: CardPrint = {
    printId: "b9e9b348-121b-42d3-b7be-d6a83dca9157",
    definitionId: "2facf462-55cd-4da4-997f-2cf4add75628", // Purelace
    setCode: "3ed",
    rarity: "rare",
};

export const redWard3ed: CardPrint = {
    printId: "e6a8157a-4c5e-4a08-83e3-c8fafa7a828b",
    definitionId: "e0c64c01-c2aa-470b-88c6-3d3e4a969649", // Red Ward
    setCode: "3ed",
    rarity: "uncommon",
};

export const resurrection3ed: CardPrint = {
    printId: "c159804d-8757-4172-a661-4f9ee068fce1",
    definitionId: "4fff6e6f-4ebd-4ec8-9443-59efb22d376c", // Resurrection
    setCode: "3ed",
    rarity: "uncommon",
};

export const reverseDamage3ed: CardPrint = {
    printId: "04e97dbe-39e1-4bf7-815a-839048463682",
    definitionId: "943baea8-b173-4863-a3ab-dd217d483cd9", // Reverse Damage
    setCode: "3ed",
    rarity: "rare",
};

export const reversePolarity3ed: CardPrint = {
    printId: "e77b2e9b-4db2-4dd2-ae55-bddb22ff87e5",
    definitionId: "da7ed8ba-3886-4779-a9b3-6892a7ed3527", // Reverse Polarity
    setCode: "3ed",
    rarity: "uncommon",
};

export const righteousness3ed: CardPrint = {
    printId: "d85954b4-306e-46d3-b913-240e16acdcac",
    definitionId: "d0ba7b76-f3d0-47d0-8a35-0c08e67200fb", // Righteousness
    setCode: "3ed",
    rarity: "rare",
};

export const samiteHealer3ed: CardPrint = {
    printId: "7545fe51-dbe5-4d4c-87a8-86d54734bf33",
    definitionId: "efba235e-04e5-449c-906c-0ac33f6d7929", // Samite Healer
    setCode: "3ed",
    rarity: "common",
};

export const savannahLions3ed: CardPrint = {
    printId: "ad41b1aa-1482-4d71-990b-031b30685cb1",
    definitionId: "d05b92bd-797e-413f-a8b0-32e0937a1ee0", // Savannah Lions
    setCode: "3ed",
    rarity: "rare",
};

export const serraAngel3ed: CardPrint = {
    printId: "97fa5f07-46ba-408d-a861-bdb1791cc188",
    definitionId: "f8ac5006-91bd-4803-93da-f87cf196dd2f", // Serra Angel
    setCode: "3ed",
    rarity: "uncommon",
};

export const swordsToPlowshares3ed: CardPrint = {
    printId: "057d2410-30d3-4b7a-9dc3-f2512c1cf31c",
    definitionId: "386ea9eb-abc1-4862-aa2d-8fb808d79490", // Swords to Plowshares
    setCode: "3ed",
    rarity: "uncommon",
};

export const veteranBodyguard3ed: CardPrint = {
    printId: "d55a1479-6654-4e8e-9a27-44e23753f8be",
    definitionId: "cbd9ab01-a833-4fa4-8dee-151bd9800835", // Veteran Bodyguard
    setCode: "3ed",
    rarity: "rare",
};

export const wallOfSwords3ed: CardPrint = {
    printId: "4390978b-f647-4720-8caa-00eeecff8471",
    definitionId: "99ec4723-b36c-4015-b361-736a6523e8f5", // Wall of Swords
    setCode: "3ed",
    rarity: "uncommon",
};

export const whiteKnight3ed: CardPrint = {
    printId: "ce573cee-40e0-4740-8b86-538ad8a16bce",
    definitionId: "50abfba8-c9f9-4ebf-965a-4b425fe83129", // White Knight
    setCode: "3ed",
    rarity: "uncommon",
};

export const whiteWard3ed: CardPrint = {
    printId: "bb38dcd5-4f12-461c-96a8-867a5b63c5c1",
    definitionId: "49b22665-1501-420a-82ad-f71f6768bcf8", // White Ward
    setCode: "3ed",
    rarity: "uncommon",
};

export const wrathOfGod3ed: CardPrint = {
    printId: "1c687a4e-a3f9-4d2d-9931-bf60e97f4095",
    definitionId: "a2788d69-6a3a-42f0-8736-cc6b57755ecd", // Wrath of God
    setCode: "3ed",
    rarity: "rare",
};

export const airElemental3ed: CardPrint = {
    printId: "22905294-4ba6-4567-a21f-f53b8317acda",
    definitionId: "69c3b2a3-0daa-4d42-832d-fcdfda6555ea", // Air Elemental
    setCode: "3ed",
    rarity: "uncommon",
};

export const animateArtifact3ed: CardPrint = {
    printId: "9704b5e2-43e8-4a80-a34b-dfcaad9ec0f9",
    definitionId: "664b46f5-0424-4f4e-9f26-6bd2cf5e0357", // Animate Artifact
    setCode: "3ed",
    rarity: "uncommon",
};

export const blueElementalBlast3ed: CardPrint = {
    printId: "0892ec35-8bab-4fe5-8cc9-a25032d4bc8d",
    definitionId: "20d666ef-39bf-4fbf-8201-5f1056539da2", // Blue Elemental Blast
    setCode: "3ed",
    rarity: "common",
};

export const braingeyser3ed: CardPrint = {
    printId: "f77f61a8-0b20-4f2e-8a24-844dc95c3a9e",
    definitionId: "62b19a12-6914-430e-81ce-dcfca47884df", // Braingeyser
    setCode: "3ed",
    rarity: "rare",
};

export const clone3ed: CardPrint = {
    printId: "b59fde1a-8d41-4f09-a4a1-4a15aaa704c7",
    definitionId: "f00d33dd-4eb2-4446-9813-1923d8e2d2f3", // Clone
    setCode: "3ed",
    rarity: "uncommon",
};

export const controlMagic3ed: CardPrint = {
    printId: "d8ab7fb5-9903-4723-a4a0-d142ef3aae8e",
    definitionId: "7b52f459-c703-4a0b-9114-ff69eec61287", // Control Magic
    setCode: "3ed",
    rarity: "uncommon",
};

export const copyArtifact3ed: CardPrint = {
    printId: "0d42f473-3e3f-4441-b7ee-6819a3a8f52e",
    definitionId: "fd5ed955-1193-4e6a-a3e2-f54c1f9bf063", // Copy Artifact
    setCode: "3ed",
    rarity: "rare",
};

export const counterspell3ed: CardPrint = {
    printId: "0a1b4e2e-5459-4fae-81d9-1e882647daac",
    definitionId: "0df55e3f-14de-46ef-b6b1-616618724d9e", // Counterspell
    setCode: "3ed",
    rarity: "uncommon",
};

export const creatureBond3ed: CardPrint = {
    printId: "131b80ad-1ffe-449d-a595-74c65f6605cd",
    definitionId: "ee4bd7d1-77e5-46e5-a594-c24469e88c4c", // Creature Bond
    setCode: "3ed",
    rarity: "common",
};

export const drainPower3ed: CardPrint = {
    printId: "4a8ffad1-9cb0-4ba6-8ae9-00c3b74b9b3f",
    definitionId: "ea3830c5-cc66-453e-9e53-0636e00ee0ee", // Drain Power
    setCode: "3ed",
    rarity: "rare",
};

export const energyFlux3ed: CardPrint = {
    printId: "9c4e6d03-68d5-4275-a76c-078d0a9a2b54",
    definitionId: "bd1f624b-e8f2-462f-838a-7cb9e8fda988", // Energy Flux
    setCode: "3ed",
    rarity: "uncommon",
};

export const feedback3ed: CardPrint = {
    printId: "dea6644f-cd2d-4d2b-b66e-b6f8285d2fe8",
    definitionId: "0eb8f591-d763-49bf-8ef9-86265aaa72f7", // Feedback
    setCode: "3ed",
    rarity: "uncommon",
};

export const flight3ed: CardPrint = {
    printId: "133aaa10-610b-41be-9327-591f517a4baa",
    definitionId: "67c7784b-6b79-4268-a714-895c82809aff", // Flight
    setCode: "3ed",
    rarity: "common",
};

export const hurkylSRecall3ed: CardPrint = {
    printId: "b871e9a7-ba3a-4891-adc6-68a11a4e4aa6",
    definitionId: "f32373dd-06d8-45d1-8777-3b1411bcb30a", // Hurkyl's Recall
    setCode: "3ed",
    rarity: "rare",
};

export const islandFishJasconius3ed: CardPrint = {
    printId: "11db42ba-f756-439c-bdd3-26e9cd4870a4",
    definitionId: "8537cb0f-4821-417b-80cc-ea57d51ee9b8", // Island Fish Jasconius
    setCode: "3ed",
    rarity: "rare",
};

export const jump3ed: CardPrint = {
    printId: "839b7b38-cb95-4406-af50-4d97884e2489",
    definitionId: "cb3f4b11-ad1b-48e2-a500-787d351b0174", // Jump
    setCode: "3ed",
    rarity: "common",
};

export const lifetap3ed: CardPrint = {
    printId: "f0049925-d95d-40ed-ba02-7f7fbe4cf6b5",
    definitionId: "11add837-7ee4-4104-b031-c161bce459ae", // Lifetap
    setCode: "3ed",
    rarity: "uncommon",
};

export const lordOfAtlantis3ed: CardPrint = {
    printId: "45066539-6bc2-467f-acfb-00938ba837ef",
    definitionId: "210c4a90-fc7a-4c76-aeaa-20a005e45386", // Lord of Atlantis
    setCode: "3ed",
    rarity: "rare",
};

export const magicalHack3ed: CardPrint = {
    printId: "61fb9f2d-be6b-4073-91d8-68ca58046da9",
    definitionId: "2bd4202c-0477-45aa-82fd-83c85d6d4bef", // Magical Hack
    setCode: "3ed",
    rarity: "rare",
};

export const mahamotiDjinn3ed: CardPrint = {
    printId: "4765276e-ad80-4734-b485-36eebf1b6ae1",
    definitionId: "36204ddd-ddf7-4b44-ae3c-b4a5a41ac9cb", // Mahamoti Djinn
    setCode: "3ed",
    rarity: "rare",
};

export const manaShort3ed: CardPrint = {
    printId: "0fec5898-f288-4fb6-a2d3-2ea6d20594bf",
    definitionId: "73e3e0b3-5284-464f-8c62-0f7801c966f5", // Mana Short
    setCode: "3ed",
    rarity: "rare",
};

export const merfolkOfThePearlTrident3ed: CardPrint = {
    printId: "2fad0078-f3cb-48a4-9ed4-b658e983314f",
    definitionId: "2b871039-6a66-4ac3-95e7-24759c1f2f92", // Merfolk of the Pearl Trident
    setCode: "3ed",
    rarity: "common",
};

export const phantasmalForces3ed: CardPrint = {
    printId: "7954f128-7f3d-4c5e-adea-6ff452186ba4",
    definitionId: "0631c7c8-9aa5-4333-8e20-20247fc47033", // Phantasmal Forces
    setCode: "3ed",
    rarity: "uncommon",
};

export const phantasmalTerrain3ed: CardPrint = {
    printId: "b8c578c4-a67f-45ac-aa13-7fba2a5f5f3f",
    definitionId: "1c371aa1-1619-41e3-8364-7bc9b8cf5d14", // Phantasmal Terrain
    setCode: "3ed",
    rarity: "common",
};

export const phantomMonster3ed: CardPrint = {
    printId: "75cb719c-7b7a-449b-bb1e-372a0e20c7f0",
    definitionId: "e46d2cf5-e8d0-4fb2-b950-252d52084b63", // Phantom Monster
    setCode: "3ed",
    rarity: "uncommon",
};

export const pirateShip3ed: CardPrint = {
    printId: "06e11710-fc99-4d86-9ca5-9d8c7ab03b24",
    definitionId: "d0a7cb23-d229-43c5-addd-dcf423984b0c", // Pirate Ship
    setCode: "3ed",
    rarity: "rare",
};

export const powerLeak3ed: CardPrint = {
    printId: "f6623e8b-4f4c-49c8-ad48-257b8695c4fe",
    definitionId: "ccc982b6-35b2-4e33-ace2-86cb79123e4f", // Power Leak
    setCode: "3ed",
    rarity: "common",
};

export const powerSink3ed: CardPrint = {
    printId: "1134aa48-b288-44ab-9d3a-efee12cb98a4",
    definitionId: "1b342dd3-09b9-4108-bf12-a65d4cef4eb9", // Power Sink
    setCode: "3ed",
    rarity: "common",
};

export const prodigalSorcerer3ed: CardPrint = {
    printId: "20f1411b-a5ad-4d49-915b-ad8a21d51342",
    definitionId: "e4dc1103-7bf1-47f6-9006-d3ed9ccd7a6a", // Prodigal Sorcerer
    setCode: "3ed",
    rarity: "common",
};

export const psychicVenom3ed: CardPrint = {
    printId: "47560f18-84fb-4d34-83cf-70e0ed8bf7ff",
    definitionId: "f3f5b68a-6b0e-431e-89f0-ff60f17687a5", // Psychic Venom
    setCode: "3ed",
    rarity: "common",
};

export const reconstruction3ed: CardPrint = {
    printId: "b4ba9d8c-686d-4f93-8001-fca27899651e",
    definitionId: "1aa2d27b-cc25-4baa-86f4-4db45b30e2a4", // Reconstruction
    setCode: "3ed",
    rarity: "common",
};

export const seaSerpent3ed: CardPrint = {
    printId: "4a05cbae-a0a1-452b-a9d1-a29478e705cd",
    definitionId: "d0b333b7-db4d-4439-b0de-60414cbf8d7b", // Sea Serpent
    setCode: "3ed",
    rarity: "common",
};

export const serendibEfreet3ed: CardPrint = {
    printId: "35415199-0f1d-4398-a48f-f78697a51105",
    definitionId: "cf56e862-3169-4f63-acd0-731080fa32f2", // Serendib Efreet
    setCode: "3ed",
    rarity: "rare",
};

export const sirenSCall3ed: CardPrint = {
    printId: "e84406bc-6db7-4672-be8c-307985213cd6",
    definitionId: "d992b336-3b6e-43e1-8662-d85664349b44", // Siren's Call
    setCode: "3ed",
    rarity: "uncommon",
};

export const sleightOfMind3ed: CardPrint = {
    printId: "563194a8-e7b2-4edb-ba02-f84cfd206771",
    definitionId: "d427790c-e322-446e-8d7d-a6b48ad41a42", // Sleight of Mind
    setCode: "3ed",
    rarity: "rare",
};

export const spellBlast3ed: CardPrint = {
    printId: "20fc852a-77b0-48a6-8343-6cf890da9adb",
    definitionId: "845734da-ab03-4dbc-bb5f-96481d3b8e88", // Spell Blast
    setCode: "3ed",
    rarity: "common",
};

export const stasis3ed: CardPrint = {
    printId: "fe4bf26c-cd9c-40e3-8a73-2f17f9a1d0e4",
    definitionId: "b6cef408-5b4b-49f6-9531-be544815b93f", // Stasis
    setCode: "3ed",
    rarity: "rare",
};

export const stealArtifact3ed: CardPrint = {
    printId: "df32e7de-dd96-454e-a229-31912d9600e7",
    definitionId: "83316930-d6ad-46ce-9b40-48eea856d95b", // Steal Artifact
    setCode: "3ed",
    rarity: "uncommon",
};

export const thoughtlace3ed: CardPrint = {
    printId: "851a8475-30d1-466f-b0be-6f1a0f2772b5",
    definitionId: "23749375-1416-47a4-9251-52f41fe2fae9", // Thoughtlace
    setCode: "3ed",
    rarity: "rare",
};

export const unstableMutation3ed: CardPrint = {
    printId: "fc24e53b-5074-4791-9277-46e14a70db3a",
    definitionId: "a79e9236-a39e-471a-b18a-2c2ba16e7774", // Unstable Mutation
    setCode: "3ed",
    rarity: "common",
};

export const unsummon3ed: CardPrint = {
    printId: "e7bf32d8-dad7-4192-8cb6-ae75d8204ba3",
    definitionId: "8512f2c1-6361-4b79-843f-80b6bceeeb99", // Unsummon
    setCode: "3ed",
    rarity: "common",
};

export const vesuvanDoppelganger3ed: CardPrint = {
    printId: "6d528ffd-89b3-44ee-a370-e4b53d6604be",
    definitionId: "768f3a05-bd06-4a23-b9f2-94f6e618fd9f", // Vesuvan Doppelganger
    setCode: "3ed",
    rarity: "rare",
};

export const volcanicEruption3ed: CardPrint = {
    printId: "6663f9e2-f752-42cf-97a0-01a14ca0aa1b",
    definitionId: "a80582b1-09db-45f8-b362-0e5207a5a8e6", // Volcanic Eruption
    setCode: "3ed",
    rarity: "rare",
};

export const wallOfAir3ed: CardPrint = {
    printId: "beb3874f-b3dc-41ca-becc-4dcbb0549b33",
    definitionId: "da56fdf3-6a8f-4833-a5c3-197650cc4889", // Wall of Air
    setCode: "3ed",
    rarity: "uncommon",
};

export const wallOfWater3ed: CardPrint = {
    printId: "14363981-7c27-49d4-91d6-e2a51b679784",
    definitionId: "41faed1a-ded8-49ee-8e2a-c60d377775d7", // Wall of Water
    setCode: "3ed",
    rarity: "uncommon",
};

export const waterElemental3ed: CardPrint = {
    printId: "55368e1d-2573-4779-ad7c-027071380447",
    definitionId: "8de940d6-98c0-46a9-b5fd-e2b0899ea19e", // Water Elemental
    setCode: "3ed",
    rarity: "uncommon",
};

export const animateDead3ed: CardPrint = {
    printId: "eed73f84-ad08-44f8-a4fe-cd324ec1da92",
    definitionId: "8fd7861d-925f-4b4c-a4ab-60be6f43d50b", // Animate Dead
    setCode: "3ed",
    rarity: "uncommon",
};

export const badMoon3ed: CardPrint = {
    printId: "9cb767eb-2161-4068-be80-c3cf68945393",
    definitionId: "43572906-ea74-4411-a549-5dc401591d2a", // Bad Moon
    setCode: "3ed",
    rarity: "rare",
};

export const blackKnight3ed: CardPrint = {
    printId: "eaa55b3c-acf4-4d2a-9f32-c7fce6672f3d",
    definitionId: "c1662949-0d69-49a3-8c69-daf10717ed4e", // Black Knight
    setCode: "3ed",
    rarity: "uncommon",
};

export const bogWraith3ed: CardPrint = {
    printId: "1173349b-beb9-44c8-aeb2-534ecf54fea0",
    definitionId: "6701874e-986e-4b81-9268-90b6171e6187", // Bog Wraith
    setCode: "3ed",
    rarity: "uncommon",
};

export const cursedLand3ed: CardPrint = {
    printId: "9640785c-be0d-4502-9995-f93ac00f1b2f",
    definitionId: "cf5f3c61-1e54-4eea-bf82-311cfa988e6a", // Cursed Land
    setCode: "3ed",
    rarity: "uncommon",
};

export const darkRitual3ed: CardPrint = {
    printId: "48cb9467-657e-453f-afc8-1bf7121570ad",
    definitionId: "ebb6664d-23ca-456e-9916-afcd6f26aa7f", // Dark Ritual
    setCode: "3ed",
    rarity: "common",
};

export const deathgrip3ed: CardPrint = {
    printId: "e42c32a2-9bbb-4701-85af-eb9686edce73",
    definitionId: "2371c126-f19a-472a-ba5f-3b1366274ea0", // Deathgrip
    setCode: "3ed",
    rarity: "uncommon",
};

export const deathlace3ed: CardPrint = {
    printId: "e4265106-78a8-4a10-a2fb-6440a8a7f5ce",
    definitionId: "6ff1cefc-62cb-4525-b0c5-2b09603b4314", // Deathlace
    setCode: "3ed",
    rarity: "rare",
};

export const demonicHordes3ed: CardPrint = {
    printId: "b4cfeebf-d893-4fdf-b3fc-f1f9528f4d04",
    definitionId: "6c9bb8b1-fb79-4b99-ba09-c6e6c860de50", // Demonic Hordes
    setCode: "3ed",
    rarity: "rare",
};

export const demonicTutor3ed: CardPrint = {
    printId: "881e5922-b464-4a1a-b074-664bd6c0a7f6",
    definitionId: "711d4d54-5520-4de8-9b93-79902ed8e562", // Demonic Tutor
    setCode: "3ed",
    rarity: "uncommon",
};

export const drainLife3ed: CardPrint = {
    printId: "d89c1d2f-87a1-4463-af21-b837da3e7d74",
    definitionId: "5d077a49-73d4-4958-b42a-31b814e110e8", // Drain Life
    setCode: "3ed",
    rarity: "common",
};

export const drudgeSkeletons3ed: CardPrint = {
    printId: "59145073-2cfd-4153-a6d8-47ad42e739c3",
    definitionId: "23614289-0d73-4747-a849-5cb67cc97d6a", // Drudge Skeletons
    setCode: "3ed",
    rarity: "common",
};

export const elHajjâj3ed: CardPrint = {
    printId: "c3591170-645f-4645-bc39-b90b7b6ddac7",
    definitionId: "c4b610d3-2005-4347-bcda-c30b5b7972e5", // El-Hajjâj
    setCode: "3ed",
    rarity: "rare",
};

export const ergRaiders3ed: CardPrint = {
    printId: "02104733-fb20-43bb-8370-1993528abbdf",
    definitionId: "35c73a97-531d-4dd5-8236-39b89c183c38", // Erg Raiders
    setCode: "3ed",
    rarity: "common",
};

export const evilPresence3ed: CardPrint = {
    printId: "d84730b2-53e4-45eb-9ac7-4557a59be5d4",
    definitionId: "0551d66e-8cd4-48f0-aa17-15f26be9d85f", // Evil Presence
    setCode: "3ed",
    rarity: "uncommon",
};

export const fear3ed: CardPrint = {
    printId: "6c6b2afc-d4f5-47fb-abda-fc3de8bdacaa",
    definitionId: "0cd927be-e63f-4371-a1d8-7a0489cb187e", // Fear
    setCode: "3ed",
    rarity: "common",
};

export const frozenShade3ed: CardPrint = {
    printId: "6cba931e-94b5-4fcc-8d5f-eb60664baf31",
    definitionId: "d0bd76c8-4cff-4c15-9686-7a299b589814", // Frozen Shade
    setCode: "3ed",
    rarity: "common",
};

export const gloom3ed: CardPrint = {
    printId: "fb2ce26e-8c53-4687-a80c-ba6a1c76299a",
    definitionId: "a8d10bc7-daeb-4c0d-9e4a-8eae8d11699f", // Gloom
    setCode: "3ed",
    rarity: "uncommon",
};

export const howlFromBeyond3ed: CardPrint = {
    printId: "d954e8a7-6b22-4f53-9435-ff1f7782a3d4",
    definitionId: "67ec17e1-174b-4d07-a27f-91a333c4b2fb", // Howl from Beyond
    setCode: "3ed",
    rarity: "common",
};

export const hypnoticSpecter3ed: CardPrint = {
    printId: "2c8bd2bc-f48d-43c4-b2aa-5a0905656e90",
    definitionId: "b43b900f-2d9b-442b-9699-058483604ec9", // Hypnotic Specter
    setCode: "3ed",
    rarity: "uncommon",
};

export const lordOfThePit3ed: CardPrint = {
    printId: "5b61cb02-7eb7-4d85-8ced-7978cb1a81d2",
    definitionId: "2926777a-4f6e-4965-ba83-22cf7df02602", // Lord of the Pit
    setCode: "3ed",
    rarity: "rare",
};

export const mindTwist3ed: CardPrint = {
    printId: "3230ac66-cb75-43cc-b652-b28e2962d163",
    definitionId: "eee9e106-a248-49d2-b8c8-6bbcd56ce739", // Mind Twist
    setCode: "3ed",
    rarity: "rare",
};

export const netherShadow3ed: CardPrint = {
    printId: "cd07c415-4f39-4011-b94a-4aab56dca7d7",
    definitionId: "f13ad58a-6f9b-420a-bac1-40929f5e616a", // Nether Shadow
    setCode: "3ed",
    rarity: "rare",
};

export const nettlingImp3ed: CardPrint = {
    printId: "94c40a45-6439-4405-8562-11a9000a1061",
    definitionId: "8105973c-a94d-444c-ba20-ab0fa978bee8", // Nettling Imp
    setCode: "3ed",
    rarity: "uncommon",
};

export const nightmare3ed: CardPrint = {
    printId: "659c0edb-3afa-4f87-8a94-9fe10578ea1a",
    definitionId: "b8cdd6a7-f772-4ccb-914f-63f52ed54d6b", // Nightmare
    setCode: "3ed",
    rarity: "rare",
};

export const paralyze3ed: CardPrint = {
    printId: "dbe8939d-c2f0-4dbc-b7dd-0483208f6876",
    definitionId: "be33a155-de26-43d1-88f1-c926f1b7cb7c", // Paralyze
    setCode: "3ed",
    rarity: "common",
};

export const pestilence3ed: CardPrint = {
    printId: "b6647e7d-b0ad-4170-8dce-ea4c89897c6a",
    definitionId: "d42a6350-b16b-4e10-a273-e6cbb55dcb7a", // Pestilence
    setCode: "3ed",
    rarity: "common",
};

export const plagueRats3ed: CardPrint = {
    printId: "47e21390-c661-4717-bbb9-71eb63c6f01e",
    definitionId: "b3724e40-0622-4aee-9334-6c9fff88bcd5", // Plague Rats
    setCode: "3ed",
    rarity: "common",
};

export const raiseDead3ed: CardPrint = {
    printId: "6f3c2902-e2c5-4618-9d4e-3fca34b610c8",
    definitionId: "ce07bede-2219-427c-a61a-56518751de42", // Raise Dead
    setCode: "3ed",
    rarity: "common",
};

export const royalAssassin3ed: CardPrint = {
    printId: "4945ec9e-eda7-42ad-88b7-ba14f9d95e54",
    definitionId: "59590768-fa96-4869-8763-9d5ab6ac22ad", // Royal Assassin
    setCode: "3ed",
    rarity: "rare",
};

export const sacrifice3ed: CardPrint = {
    printId: "76bc3b43-158c-420e-a3fb-7413334699ca",
    definitionId: "12164aee-6a27-4246-8d15-2d6dd20d92e9", // Sacrifice
    setCode: "3ed",
    rarity: "uncommon",
};

export const scatheZombies3ed: CardPrint = {
    printId: "6cbe576f-03d5-4d22-947a-187d9e20425d",
    definitionId: "e9be6dcf-5e25-4b8c-9cd0-badf3771f81e", // Scathe Zombies
    setCode: "3ed",
    rarity: "common",
};

export const scavengingGhoul3ed: CardPrint = {
    printId: "33a5daf6-ce4f-4d00-8458-b7d1a9e037bc",
    definitionId: "426984e0-88e1-4a2d-9a1c-798b95864df3", // Scavenging Ghoul
    setCode: "3ed",
    rarity: "uncommon",
};

export const sengirVampire3ed: CardPrint = {
    printId: "fa35113b-5242-41f4-a989-42f2cd8002b6",
    definitionId: "510840f4-7c0e-4b47-8ebf-23c20cac4bd9", // Sengir Vampire
    setCode: "3ed",
    rarity: "uncommon",
};

export const simulacrum3ed: CardPrint = {
    printId: "bc1b6d40-fdb0-40c3-983d-67a7bfb96cea",
    definitionId: "35c3a78d-cc79-4187-929a-8aa1d1469990", // Simulacrum
    setCode: "3ed",
    rarity: "uncommon",
};

export const sorceressQueen3ed: CardPrint = {
    printId: "b83d7331-e573-4dea-901a-de9150d4b5c0",
    definitionId: "94742003-f0f1-4483-b1a0-e7163995db1b", // Sorceress Queen
    setCode: "3ed",
    rarity: "rare",
};

export const terror3ed: CardPrint = {
    printId: "0eaf0ac8-f5a7-4689-8d3e-dd865763df44",
    definitionId: "21004958-2c7e-4a55-bc80-411c4d780106", // Terror
    setCode: "3ed",
    rarity: "common",
};

export const unholyStrength3ed: CardPrint = {
    printId: "3ac35077-91e9-446c-9cb2-e2cfb9fa2962",
    definitionId: "90563f90-0127-4164-b43b-f0321dc63a1d", // Unholy Strength
    setCode: "3ed",
    rarity: "common",
};

export const wallOfBone3ed: CardPrint = {
    printId: "4f9d6c2b-3492-4360-90cf-649608d4910f",
    definitionId: "ae20d442-a544-4a03-9ebf-5ecb137c67dd", // Wall of Bone
    setCode: "3ed",
    rarity: "uncommon",
};

export const warpArtifact3ed: CardPrint = {
    printId: "948a03b0-ce48-4fac-816f-8224b7ae936a",
    definitionId: "9e5e07a2-fbdf-4c4c-996a-fce40bab5de5", // Warp Artifact
    setCode: "3ed",
    rarity: "rare",
};

export const weakness3ed: CardPrint = {
    printId: "6774a228-ec9e-47d0-bc43-a92f5caf8398",
    definitionId: "36ca06a1-9b9a-49a2-9c47-9b72228621bc", // Weakness
    setCode: "3ed",
    rarity: "common",
};

export const willOTheWisp3ed: CardPrint = {
    printId: "551e5fdd-ed3a-4f44-b4d1-97900ef46373",
    definitionId: "a1a6f8e9-7bc1-4151-b55f-acf877b1a7a6", // Will-o'-the-Wisp
    setCode: "3ed",
    rarity: "rare",
};

export const zombieMaster3ed: CardPrint = {
    printId: "e868767f-b62e-4bb4-95e5-62feac05ff9d",
    definitionId: "3d4255a0-d445-4c00-b936-bbf07851e1c8", // Zombie Master
    setCode: "3ed",
    rarity: "rare",
};

export const atog3ed: CardPrint = {
    printId: "976121fd-a21d-42cd-a7d0-310c8648e307",
    definitionId: "2249fc40-4412-48fd-800a-7ea3678aee3f", // Atog
    setCode: "3ed",
    rarity: "common",
};

export const burrowing3ed: CardPrint = {
    printId: "c2b99b30-a972-4e5d-a772-06884719ac7c",
    definitionId: "a14c05e4-8df3-450b-8a98-5028e73b14c1", // Burrowing
    setCode: "3ed",
    rarity: "uncommon",
};

export const chaoslace3ed: CardPrint = {
    printId: "37df20a7-9299-434c-84ca-8019851ee31b",
    definitionId: "72ea2048-57bc-43d5-8987-33ca727f1a97", // Chaoslace
    setCode: "3ed",
    rarity: "rare",
};

export const disintegrate3ed: CardPrint = {
    printId: "ce71d4c8-3835-4065-8089-82a64846dbcb",
    definitionId: "8712c49e-f171-4669-bed9-87575a37af11", // Disintegrate
    setCode: "3ed",
    rarity: "common",
};

export const dragonWhelp3ed: CardPrint = {
    printId: "643d6f5b-6a17-434d-945a-6b9a05015493",
    definitionId: "6bbf1eab-bc32-4835-b566-8634b1fe81b0", // Dragon Whelp
    setCode: "3ed",
    rarity: "uncommon",
};

export const dwarvenWarriors3ed: CardPrint = {
    printId: "6caeadf8-1b40-497d-be7c-667fbb98f848",
    definitionId: "2d4d87a3-5f8b-4152-9a8b-538ab49d62e8", // Dwarven Warriors
    setCode: "3ed",
    rarity: "common",
};

export const dwarvenWeaponsmith3ed: CardPrint = {
    printId: "c83929b1-4826-4b84-823d-0997560b6bdc",
    definitionId: "0848d94a-2704-460f-986b-b192dd6d26b7", // Dwarven Weaponsmith
    setCode: "3ed",
    rarity: "uncommon",
};

export const earthElemental3ed: CardPrint = {
    printId: "e2285cf5-f1c0-42d2-8203-297d2a5b9ec2",
    definitionId: "b24b5864-44c0-4bc8-8705-9504f83b2c03", // Earth Elemental
    setCode: "3ed",
    rarity: "uncommon",
};

export const earthbind3ed: CardPrint = {
    printId: "7ec1650e-8ecb-460a-9319-0f59de48c824",
    definitionId: "a6d492b7-b0b3-420e-8d00-6dacb11de77e", // Earthbind
    setCode: "3ed",
    rarity: "common",
};

export const earthquake3ed: CardPrint = {
    printId: "603d1f86-2098-4af5-a038-c5a314ba7184",
    definitionId: "e68ac362-6cdc-48a6-bdd3-4f8ea32add64", // Earthquake
    setCode: "3ed",
    rarity: "rare",
};

export const fireElemental3ed: CardPrint = {
    printId: "63539181-5393-41b8-baf3-9a690d17f4ce",
    definitionId: "da237992-2919-4e37-8f56-2164095f59b5", // Fire Elemental
    setCode: "3ed",
    rarity: "uncommon",
};

export const fireball3ed: CardPrint = {
    printId: "dafb512f-536f-4f96-8440-03f1d20d8a5a",
    definitionId: "b7623c00-144b-4a8f-9c6c-f5e9e4f65ece", // Fireball
    setCode: "3ed",
    rarity: "common",
};

export const firebreathing3ed: CardPrint = {
    printId: "16682a6e-8d86-4ad6-a6b1-3171000cc708",
    definitionId: "3eb27381-505d-4e47-bf66-9e7ba91a5075", // Firebreathing
    setCode: "3ed",
    rarity: "common",
};

export const flashfires3ed: CardPrint = {
    printId: "7b23de17-d867-41f8-b965-9b3eb00db701",
    definitionId: "ee8a05a4-0ce3-4abe-bb60-08af53cf08e5", // Flashfires
    setCode: "3ed",
    rarity: "uncommon",
};

export const fork3ed: CardPrint = {
    printId: "a33a1695-db21-4dc5-9dc1-dd05d12e6b40",
    definitionId: "e6b43916-fe2d-417a-a550-d7c795023297", // Fork
    setCode: "3ed",
    rarity: "rare",
};

export const goblinBalloonBrigade3ed: CardPrint = {
    printId: "c31c14c0-71a4-40e0-b447-6c7124c84059",
    definitionId: "5129b422-7a35-4bc5-b14b-c814012a0d8f", // Goblin Balloon Brigade
    setCode: "3ed",
    rarity: "uncommon",
};

export const goblinKing3ed: CardPrint = {
    printId: "e3094187-d666-414b-a1fd-ae0ef55c3fcb",
    definitionId: "5873672d-37ea-4c0f-97f3-12b74fde112d", // Goblin King
    setCode: "3ed",
    rarity: "rare",
};

export const graniteGargoyle3ed: CardPrint = {
    printId: "03dfa7f7-8f08-49f6-96fd-eebf16ceb499",
    definitionId: "f15bf2b2-6848-4fbd-b89a-8d8da8ae1cdc", // Granite Gargoyle
    setCode: "3ed",
    rarity: "rare",
};

export const grayOgre3ed: CardPrint = {
    printId: "e26041ad-b326-40e6-a7fd-eacfcb0ab17e",
    definitionId: "73ae5276-b607-4f23-a9d2-e8cc7b8e3693", // Gray Ogre
    setCode: "3ed",
    rarity: "common",
};

export const hillGiant3ed: CardPrint = {
    printId: "c987a3ec-a775-4140-ad49-18025e59dc3d",
    definitionId: "0ddb98e8-13fe-4786-83f7-b72c56db135a", // Hill Giant
    setCode: "3ed",
    rarity: "common",
};

export const hurloonMinotaur3ed: CardPrint = {
    printId: "f6de6b0d-dd8c-4ab9-8de3-b083a36b24b7",
    definitionId: "78a9088f-8755-47cb-aa93-51d992ccab90", // Hurloon Minotaur
    setCode: "3ed",
    rarity: "common",
};

export const keldonWarlord3ed: CardPrint = {
    printId: "ad3abbfb-320a-41ad-808c-dd93964efb44",
    definitionId: "8fe3fd83-969c-4add-888f-86f4306b067c", // Keldon Warlord
    setCode: "3ed",
    rarity: "uncommon",
};

export const kirdApe3ed: CardPrint = {
    printId: "967a26e0-8dca-4215-9935-b77a7dd4dde0",
    definitionId: "ebe8845e-df1c-481c-949c-aab84af99a05", // Kird Ape
    setCode: "3ed",
    rarity: "common",
};

export const lightningBolt3ed: CardPrint = {
    printId: "cb9b9a9d-ae4c-4e04-bf9d-cae48f01292c",
    definitionId: "d573ef03-4730-45aa-93dd-e45ac1dbaf4a", // Lightning Bolt
    setCode: "3ed",
    rarity: "common",
};

export const magneticMountain3ed: CardPrint = {
    printId: "dc95e03d-5521-4a01-8028-200b8467ce86",
    definitionId: "95fde48b-e40a-4183-b324-1ec276dde015", // Magnetic Mountain
    setCode: "3ed",
    rarity: "rare",
};

export const manaFlare3ed: CardPrint = {
    printId: "b59d2329-5a0c-407b-aed2-2e19feaf70ed",
    definitionId: "7fb99a26-beeb-4aca-bb02-b2d2ce0595f9", // Mana Flare
    setCode: "3ed",
    rarity: "rare",
};

export const manabarbs3ed: CardPrint = {
    printId: "8b16d8b7-3ff8-4481-bd4a-aa283b78bead",
    definitionId: "6121f72f-680f-4bb4-ae4d-37ee4ebed4d8", // Manabarbs
    setCode: "3ed",
    rarity: "rare",
};

export const mijaeDjinn3ed: CardPrint = {
    printId: "7e0c6c15-fba2-447a-a84c-01bb837b912e",
    definitionId: "d3ddbe51-cd1a-4b2c-849a-7c82d622122a", // Mijae Djinn
    setCode: "3ed",
    rarity: "rare",
};

export const monsSGoblinRaiders3ed: CardPrint = {
    printId: "6e81e219-c840-4844-be87-0449ab0fa645",
    definitionId: "b4eb3db3-6a7c-488a-9433-d5d1d3133816", // Mons's Goblin Raiders
    setCode: "3ed",
    rarity: "common",
};

export const orcishArtillery3ed: CardPrint = {
    printId: "574650db-2af2-4e80-a83a-a20584e3a8a9",
    definitionId: "a97208b1-a91b-4129-8a00-2f97b418accc", // Orcish Artillery
    setCode: "3ed",
    rarity: "uncommon",
};

export const orcishOriflamme3ed: CardPrint = {
    printId: "71a941f4-3bdc-40b6-8b24-d73136283f51",
    definitionId: "911538ea-322c-4c40-a9c3-35e47fe60fce", // Orcish Oriflamme
    setCode: "3ed",
    rarity: "uncommon",
};

export const powerSurge3ed: CardPrint = {
    printId: "9f521a52-f4e3-4043-9db3-a3c89afce3b9",
    definitionId: "62858604-ca5a-4f69-a045-a7515ebfabf2", // Power Surge
    setCode: "3ed",
    rarity: "rare",
};

export const redElementalBlast3ed: CardPrint = {
    printId: "2d83a2a3-5495-4457-8eb7-9f9a75da6cc3",
    definitionId: "776ad9be-3309-4f1d-9f27-6219d9477662", // Red Elemental Blast
    setCode: "3ed",
    rarity: "common",
};

export const rocOfKherRidges3ed: CardPrint = {
    printId: "ad034b0a-655b-465b-a8bb-3d4eee59abdf",
    definitionId: "731a4b86-c213-4d8e-bf01-0a0e8cff0ff1", // Roc of Kher Ridges
    setCode: "3ed",
    rarity: "rare",
};

export const rockHydra3ed: CardPrint = {
    printId: "c2a08993-d6c5-45ad-82dc-093c8b912a56",
    definitionId: "410ac9e6-fbc1-4cc8-84db-84e2eb1bab97", // Rock Hydra
    setCode: "3ed",
    rarity: "rare",
};

export const sedgeTroll3ed: CardPrint = {
    printId: "485d3707-59ce-4350-9ec8-9df232f88c04",
    definitionId: "b13bf496-f3c0-4c13-8282-e7abfab6a198", // Sedge Troll
    setCode: "3ed",
    rarity: "rare",
};

export const shatter3ed: CardPrint = {
    printId: "93ff3216-aaaf-4c8f-8355-82e1fc61a747",
    definitionId: "50dc7fc1-cb6a-4c68-b993-1a25cf16226e", // Shatter
    setCode: "3ed",
    rarity: "common",
};

export const shatterstorm3ed: CardPrint = {
    printId: "52e5e508-afc6-409d-b912-33cf1d2351d1",
    definitionId: "0987461a-45c0-4956-8627-cd27a7e038d0", // Shatterstorm
    setCode: "3ed",
    rarity: "uncommon",
};

export const shivanDragon3ed: CardPrint = {
    printId: "69199dd2-dbac-4039-b4da-eb2b0671645f",
    definitionId: "fefbf149-f988-4f8b-9f53-56f5878116a6", // Shivan Dragon
    setCode: "3ed",
    rarity: "rare",
};

export const smoke3ed: CardPrint = {
    printId: "7b20087c-355d-4157-bd4e-b4dc2be49b69",
    definitionId: "7c67788e-d713-47c3-ab9f-b8a6212ae24f", // Smoke
    setCode: "3ed",
    rarity: "rare",
};

export const stoneGiant3ed: CardPrint = {
    printId: "a3b8a84d-44d8-4ad3-b04d-a94634e25453",
    definitionId: "7ffaedb9-25f8-4304-9085-e12505b93312", // Stone Giant
    setCode: "3ed",
    rarity: "uncommon",
};

export const stoneRain3ed: CardPrint = {
    printId: "35c7176a-694c-4e1d-8dca-dcd718d94250",
    definitionId: "57ff74cb-a2ed-4123-ac42-f72f9820049e", // Stone Rain
    setCode: "3ed",
    rarity: "common",
};

export const tunnel3ed: CardPrint = {
    printId: "7b379eeb-4d7e-4421-8fc4-b5255eb373f5",
    definitionId: "b21ebc9f-a93e-4d18-b3e8-8459e3abbf31", // Tunnel
    setCode: "3ed",
    rarity: "uncommon",
};

export const uthdenTroll3ed: CardPrint = {
    printId: "0403aef5-b5f3-4d07-a350-4874801b27e8",
    definitionId: "2ff21a6f-83a7-4bf3-a078-294e303232cc", // Uthden Troll
    setCode: "3ed",
    rarity: "uncommon",
};

export const wallOfFire3ed: CardPrint = {
    printId: "f7fbd53b-d1b2-41b7-a402-91227670a1d7",
    definitionId: "efcf12cd-fb70-444e-9641-73ffa0e8f16e", // Wall of Fire
    setCode: "3ed",
    rarity: "uncommon",
};

export const wallOfStone3ed: CardPrint = {
    printId: "667c227f-a3b7-4040-8b67-75a6fc209e67",
    definitionId: "140e567c-6e4a-42b0-8084-d6c9695ae802", // Wall of Stone
    setCode: "3ed",
    rarity: "uncommon",
};

export const wheelOfFortune3ed: CardPrint = {
    printId: "c14c07d4-6971-483a-add1-f3cdf18feae9",
    definitionId: "67b369c4-faa8-45c8-a1b9-98f228b69682", // Wheel of Fortune
    setCode: "3ed",
    rarity: "rare",
};

export const aspectOfWolf3ed: CardPrint = {
    printId: "7248db64-c901-4e87-9322-e122d2d32ddc",
    definitionId: "fd9ac9e6-1395-4fbd-80e2-645f0d910c29", // Aspect of Wolf
    setCode: "3ed",
    rarity: "rare",
};

export const birdsOfParadise3ed: CardPrint = {
    printId: "01e7b0bc-1c6c-48f4-8b72-1a809f536c6c",
    definitionId: "55fe6449-1f23-43dc-adee-d144cd505b5c", // Birds of Paradise
    setCode: "3ed",
    rarity: "rare",
};

export const channel3ed: CardPrint = {
    printId: "bc0cea66-7c61-4308-af2f-3622fbb82983",
    definitionId: "c1862c47-71cc-45a3-8805-a5ddc62e55ea", // Channel
    setCode: "3ed",
    rarity: "uncommon",
};

export const cockatrice3ed: CardPrint = {
    printId: "3c5d9117-135f-4a88-950a-41bf164ebc21",
    definitionId: "9cd91814-6177-4a3d-a1c1-a3be7d7c7957", // Cockatrice
    setCode: "3ed",
    rarity: "rare",
};

export const crawWurm3ed: CardPrint = {
    printId: "a5e4a23b-3b05-4240-9565-bdd8f3f3ef12",
    definitionId: "bfed1a95-bd67-4e16-a781-81866028af2f", // Craw Wurm
    setCode: "3ed",
    rarity: "common",
};

export const crumble3ed: CardPrint = {
    printId: "32123652-4f71-4f0b-b317-39e6df039b4f",
    definitionId: "d2101f86-8d3c-4ba8-ac42-bd3df0644280", // Crumble
    setCode: "3ed",
    rarity: "uncommon",
};

export const desertTwister3ed: CardPrint = {
    printId: "88cbcf7e-9d66-4e1b-b056-8edf708fca84",
    definitionId: "0d77c149-cca2-45c7-bc83-5ba1872ad5e0", // Desert Twister
    setCode: "3ed",
    rarity: "uncommon",
};

export const elvishArchers3ed: CardPrint = {
    printId: "24547919-0272-4502-9b3a-e9a0eb6a90d2",
    definitionId: "1cb9d405-f2b5-4e10-a405-feafd2a87d90", // Elvish Archers
    setCode: "3ed",
    rarity: "rare",
};

export const fastbond3ed: CardPrint = {
    printId: "c71123b5-6be5-4c3c-972a-0aad3db1a694",
    definitionId: "a575a9af-e1de-4a1d-91d8-440585377e4f", // Fastbond
    setCode: "3ed",
    rarity: "rare",
};

export const fog3ed: CardPrint = {
    printId: "637cbc3f-f2c0-42db-b9f9-6c084846cb03",
    definitionId: "cfba606d-bb55-43ba-aa0c-299649958788", // Fog
    setCode: "3ed",
    rarity: "common",
};

export const forceOfNature3ed: CardPrint = {
    printId: "56cb88db-2c6b-4d17-be16-2a89218efe4c",
    definitionId: "21551cb6-3a53-42dd-9bbd-4bc56304d6d3", // Force of Nature
    setCode: "3ed",
    rarity: "rare",
};

export const fungusaur3ed: CardPrint = {
    printId: "6f80ad09-ebff-47cb-93ab-9bc7e0e10056",
    definitionId: "5ad89f0d-b09b-40a0-84d6-3ee60dec7e23", // Fungusaur
    setCode: "3ed",
    rarity: "rare",
};

export const gaeaSLiege3ed: CardPrint = {
    printId: "6c36ac7d-2ff0-4350-9b10-968f94b19842",
    definitionId: "e2b15221-c8b0-4861-9f8b-8a65834ad499", // Gaea's Liege
    setCode: "3ed",
    rarity: "rare",
};

export const giantGrowth3ed: CardPrint = {
    printId: "d33fe386-d165-4874-aa6b-07b7df9b6209",
    definitionId: "367dbefe-3366-408e-9fcf-7dc00f8cc201", // Giant Growth
    setCode: "3ed",
    rarity: "common",
};

export const giantSpider3ed: CardPrint = {
    printId: "5440ff00-e7fa-46ac-b46c-3fa4e10712b0",
    definitionId: "77636b4c-faea-4bf5-b88c-dd5bb88dc930", // Giant Spider
    setCode: "3ed",
    rarity: "common",
};

export const grizzlyBears3ed: CardPrint = {
    printId: "886959ca-83fd-4b50-a99a-08ef0c5415db",
    definitionId: "ce2d603a-3231-4a8c-bf39-1617586ea870", // Grizzly Bears
    setCode: "3ed",
    rarity: "common",
};

export const hurricane3ed: CardPrint = {
    printId: "bfba7442-ffdf-43cf-97b3-c69ff80e6fde",
    definitionId: "52f5a19f-16e4-4d35-89e1-969ac8202f88", // Hurricane
    setCode: "3ed",
    rarity: "uncommon",
};

export const instillEnergy3ed: CardPrint = {
    printId: "d919330b-5023-4b9c-b82f-20095354326c",
    definitionId: "5bd38716-874c-4e3c-a315-837839a6258c", // Instill Energy
    setCode: "3ed",
    rarity: "uncommon",
};

export const ironrootTreefolk3ed: CardPrint = {
    printId: "6e6cfaae-ea9e-4c54-858e-381f8bf441a9",
    definitionId: "b93c5869-7777-44bb-967a-e9439b25ced4", // Ironroot Treefolk
    setCode: "3ed",
    rarity: "common",
};

export const kudzu3ed: CardPrint = {
    printId: "b1466b4c-407d-4220-b5ee-474d7d8a24a7",
    definitionId: "b2b72dcd-9ea1-4729-baae-ecd262fdff67", // Kudzu
    setCode: "3ed",
    rarity: "rare",
};

export const leyDruid3ed: CardPrint = {
    printId: "ea2c2bf3-357d-4595-9b24-3451bd2d0179",
    definitionId: "f9232508-d363-4ef3-987a-741f6bff331f", // Ley Druid
    setCode: "3ed",
    rarity: "uncommon",
};

export const lifeforce3ed: CardPrint = {
    printId: "ca28f9ec-897a-46fd-8e3d-16330ad43d24",
    definitionId: "e292577e-6232-44fa-a9c2-cc09949c6ed3", // Lifeforce
    setCode: "3ed",
    rarity: "uncommon",
};

export const lifelace3ed: CardPrint = {
    printId: "5fc40d6f-1f1c-4f50-8971-9de5f477038b",
    definitionId: "38cb601b-a35c-412e-b386-e77dad3daa54", // Lifelace
    setCode: "3ed",
    rarity: "rare",
};

export const livingArtifact3ed: CardPrint = {
    printId: "e62fec16-b5a0-47a6-9ccf-cebe79043627",
    definitionId: "c9e753a2-a7d0-4d37-ae65-b5a1b5039a6e", // Living Artifact
    setCode: "3ed",
    rarity: "rare",
};

export const livingLands3ed: CardPrint = {
    printId: "aa710039-5378-440c-b584-e9d72d1683c9",
    definitionId: "80be0580-7948-4d8e-8c0f-5e2797ac411b", // Living Lands
    setCode: "3ed",
    rarity: "rare",
};

export const llanowarElves3ed: CardPrint = {
    printId: "6d6deae3-3ed4-47eb-bf4a-4a766ce18135",
    definitionId: "d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb", // Llanowar Elves
    setCode: "3ed",
    rarity: "common",
};

export const lure3ed: CardPrint = {
    printId: "3561cc9a-9270-4c75-90ca-1425b2724abc",
    definitionId: "2a87b26e-0431-42e9-b44f-94ba8546111a", // Lure
    setCode: "3ed",
    rarity: "uncommon",
};

export const regeneration3ed: CardPrint = {
    printId: "6cd37ba7-b821-444e-b31b-aa667a8914e9",
    definitionId: "b7b7aa34-b4f8-41b4-82ce-ab2e204c3bf4", // Regeneration
    setCode: "3ed",
    rarity: "common",
};

export const regrowth3ed: CardPrint = {
    printId: "396aae79-41d5-4b16-8903-5af8fde65eee",
    definitionId: "badc73ec-3728-4246-90c7-5f4eb7051ed5", // Regrowth
    setCode: "3ed",
    rarity: "uncommon",
};

export const scrybSprites3ed: CardPrint = {
    printId: "1b9e1d37-47cd-41d7-9fee-b8504c689462",
    definitionId: "6d929c38-91e6-457c-937a-d1884f4bba44", // Scryb Sprites
    setCode: "3ed",
    rarity: "common",
};

export const shanodinDryads3ed: CardPrint = {
    printId: "bf1889aa-59e9-4d67-ab53-9aec071ab67a",
    definitionId: "814cf35c-f1ad-4bf4-8c10-a5592c3b1be8", // Shanodin Dryads
    setCode: "3ed",
    rarity: "common",
};

export const streamOfLife3ed: CardPrint = {
    printId: "bab7e4b7-acdd-4316-ae64-b182e4d9cacd",
    definitionId: "aa1c4d4b-2645-4cd9-823e-3c9bb2eb48f9", // Stream of Life
    setCode: "3ed",
    rarity: "common",
};

export const thicketBasilisk3ed: CardPrint = {
    printId: "05a60435-7b5e-47c1-8186-1ca30a243992",
    definitionId: "e92cce01-b3bd-4307-aae5-9a7c8fa386ab", // Thicket Basilisk
    setCode: "3ed",
    rarity: "uncommon",
};

export const timberWolves3ed: CardPrint = {
    printId: "3aea108b-367b-43d9-b50d-c18954b2a82d",
    definitionId: "bc2570a4-eef9-430d-b6c2-cd51d29b9d01", // Timber Wolves
    setCode: "3ed",
    rarity: "rare",
};

export const titaniaSSong3ed: CardPrint = {
    printId: "c022abd7-bb1a-4f61-b4e1-6b802d337484",
    definitionId: "583a53af-2e2a-4f3f-8eab-bd874c6ed80a", // Titania's Song
    setCode: "3ed",
    rarity: "rare",
};

export const tranquility3ed: CardPrint = {
    printId: "5722c349-bf3d-4ac0-8fdd-bf170401c419",
    definitionId: "774cc5a6-3a69-4812-add4-eb5eb6389238", // Tranquility
    setCode: "3ed",
    rarity: "common",
};

export const tsunami3ed: CardPrint = {
    printId: "6a578955-7f77-42f1-a3e3-5e2b46216c43",
    definitionId: "9ed67d61-cf47-446b-b454-eb404a8686b7", // Tsunami
    setCode: "3ed",
    rarity: "uncommon",
};

export const verduranEnchantress3ed: CardPrint = {
    printId: "354de08d-41a8-4d6c-85d6-2413393ac181",
    definitionId: "9f87178b-1221-4d7a-a7a5-20d7f01b8089", // Verduran Enchantress
    setCode: "3ed",
    rarity: "rare",
};

export const wallOfBrambles3ed: CardPrint = {
    printId: "b27862c3-8589-41ab-8f84-34727e5a93be",
    definitionId: "af2a4558-db6e-41b2-aff6-b164d93282a0", // Wall of Brambles
    setCode: "3ed",
    rarity: "uncommon",
};

export const wallOfIce3ed: CardPrint = {
    printId: "b0af9d4c-b3e5-4953-b4ca-7f34f67bdbeb",
    definitionId: "cc743a03-867c-4bb0-8fb0-2bcaa0a8a756", // Wall of Ice
    setCode: "3ed",
    rarity: "uncommon",
};

export const wallOfWood3ed: CardPrint = {
    printId: "9d4f8eb6-2c3c-49e7-a41d-33c138d853c9",
    definitionId: "8df80424-3bd9-4982-ad79-e55d9ba3b43d", // Wall of Wood
    setCode: "3ed",
    rarity: "common",
};

export const wanderlust3ed: CardPrint = {
    printId: "3fd08a5d-0dad-4bce-86c0-dea431038859",
    definitionId: "220a03ca-8c9b-4acb-821d-f6577fbb20fb", // Wanderlust
    setCode: "3ed",
    rarity: "uncommon",
};

export const warMammoth3ed: CardPrint = {
    printId: "5c99e36f-b11d-4270-8b88-66be8907c9bd",
    definitionId: "c8d6081e-f686-4263-a0a2-21c0d9af5fdb", // War Mammoth
    setCode: "3ed",
    rarity: "common",
};

export const web3ed: CardPrint = {
    printId: "00012bd8-ed68-4978-a22d-f450c8a6e048",
    definitionId: "37c7890a-86dc-4a97-a7ce-1436fa22d0c0", // Web
    setCode: "3ed",
    rarity: "rare",
};

export const wildGrowth3ed: CardPrint = {
    printId: "8000c8f8-d4c3-4dbc-a73e-9b82b0478061",
    definitionId: "fd896dfa-66c0-4327-8e5b-489bbe350c95", // Wild Growth
    setCode: "3ed",
    rarity: "common",
};

export const aladdinSLamp3ed: CardPrint = {
    printId: "2c7e444a-dba1-406f-bfdc-1a54102083a8",
    definitionId: "8fecc5d2-5298-4d47-b085-f160603f220e", // Aladdin's Lamp
    setCode: "3ed",
    rarity: "rare",
};

export const aladdinSRing3ed: CardPrint = {
    printId: "40cb7c36-135b-40d0-bc7b-62fbcd508f49",
    definitionId: "bb2b74a2-cb74-4b54-b9c6-78c63f14cf5b", // Aladdin's Ring
    setCode: "3ed",
    rarity: "rare",
};

export const ankhOfMishra3ed: CardPrint = {
    printId: "617599f1-69d9-4767-9656-982739728df0",
    definitionId: "f594b7aa-d44e-47c4-989b-565f881e25f1", // Ankh of Mishra
    setCode: "3ed",
    rarity: "rare",
};

export const armageddonClock3ed: CardPrint = {
    printId: "ee486c26-f0bc-4275-ab1b-a9e57721f036",
    definitionId: "44a31889-6a8d-450c-a73d-381a7ff28bf9", // Armageddon Clock
    setCode: "3ed",
    rarity: "rare",
};

export const basaltMonolith3ed: CardPrint = {
    printId: "4f0b7b8e-45b0-4947-9a95-bccc6b725a37",
    definitionId: "66a74c89-6f86-4ec8-af17-391cd5026054", // Basalt Monolith
    setCode: "3ed",
    rarity: "uncommon",
};

export const blackVise3ed: CardPrint = {
    printId: "1bae1867-d5bb-4204-9fb1-59d6663bc161",
    definitionId: "76ac72f8-5b1e-4d67-a796-ef69cde27424", // Black Vise
    setCode: "3ed",
    rarity: "uncommon",
};

export const bottleOfSuleiman3ed: CardPrint = {
    printId: "6c1c2ea2-09ba-4a0e-b5b6-c06068f0da75",
    definitionId: "c474cd6b-5610-49eb-ac98-918d900efe8b", // Bottle of Suleiman
    setCode: "3ed",
    rarity: "rare",
};

export const brassMan3ed: CardPrint = {
    printId: "0ba1daee-a5ac-4d9e-b681-3e3c7a3eb095",
    definitionId: "1a364362-e42b-415c-9d95-b6ec7139f5e7", // Brass Man
    setCode: "3ed",
    rarity: "uncommon",
};

export const celestialPrism3ed: CardPrint = {
    printId: "2bc5e073-2903-4a28-9c23-07a0482ae09a",
    definitionId: "a47417cb-1ea7-4f65-ba06-e27a99373114", // Celestial Prism
    setCode: "3ed",
    rarity: "uncommon",
};

export const clockworkBeast3ed: CardPrint = {
    printId: "8224d6e3-c9de-4129-ae3e-300a82c4bd00",
    definitionId: "27f916a2-0ace-44b5-99dc-72979af34db9", // Clockwork Beast
    setCode: "3ed",
    rarity: "rare",
};

export const conservator3ed: CardPrint = {
    printId: "2e7d8bc5-9d87-43e3-9b81-311d01fdf0e5",
    definitionId: "c7824e2a-4eff-4f72-9216-0db30a4f4252", // Conservator
    setCode: "3ed",
    rarity: "uncommon",
};

export const crystalRod3ed: CardPrint = {
    printId: "f973046b-ce81-4e35-89f3-a6e857d751b8",
    definitionId: "76693233-7961-4b7e-80f2-ed90e494c4aa", // Crystal Rod
    setCode: "3ed",
    rarity: "uncommon",
};

export const dancingScimitar3ed: CardPrint = {
    printId: "e3d92537-7934-4191-8836-2f61ff6ab2fa",
    definitionId: "1eb2e494-1414-4d1f-91d2-7cb20acdb128", // Dancing Scimitar
    setCode: "3ed",
    rarity: "rare",
};

export const dingusEgg3ed: CardPrint = {
    printId: "ce56c997-202c-4175-809b-2dd65cd2ab2a",
    definitionId: "65eb6cda-e512-40a8-9c1f-335b713409ff", // Dingus Egg
    setCode: "3ed",
    rarity: "rare",
};

export const disruptingScepter3ed: CardPrint = {
    printId: "af4f8926-9a9e-4b2d-8224-118655f12809",
    definitionId: "ca571ee8-07a2-43b8-9acf-89cbfd3cf7c9", // Disrupting Scepter
    setCode: "3ed",
    rarity: "rare",
};

export const dragonEngine3ed: CardPrint = {
    printId: "42c1fd91-001d-4c94-bb0a-d3fc570c7f12",
    definitionId: "07793a71-1106-4303-b620-e403bd378020", // Dragon Engine
    setCode: "3ed",
    rarity: "rare",
};

export const ebonyHorse3ed: CardPrint = {
    printId: "396360d2-3604-499c-9fc3-75b75970c047",
    definitionId: "9ae81ec7-2b7d-4301-8114-032be5e6b663", // Ebony Horse
    setCode: "3ed",
    rarity: "rare",
};

export const flyingCarpet3ed: CardPrint = {
    printId: "7e46b461-a38e-44f8-8e15-7cefe8aea46a",
    definitionId: "4b71ff49-ee0a-4065-9131-380468d62a30", // Flying Carpet
    setCode: "3ed",
    rarity: "rare",
};

export const glassesOfUrza3ed: CardPrint = {
    printId: "a7d975c6-ca94-4255-8ac5-56113da9f97e",
    definitionId: "cafc2350-5d64-4379-9198-79a114654d45", // Glasses of Urza
    setCode: "3ed",
    rarity: "uncommon",
};

export const helmOfChatzuk3ed: CardPrint = {
    printId: "1a3068eb-2250-4c7b-8ed5-2366ff6cd0e1",
    definitionId: "3792c6ef-c4e6-4923-9a51-7d28fbc5c393", // Helm of Chatzuk
    setCode: "3ed",
    rarity: "rare",
};

export const howlingMine3ed: CardPrint = {
    printId: "fc6fbf54-698d-4a99-ad98-b0115df403a0",
    definitionId: "51f8f6e1-a451-4262-90d3-5107caf54175", // Howling Mine
    setCode: "3ed",
    rarity: "rare",
};

export const ironStar3ed: CardPrint = {
    printId: "5ffb4de8-505e-4e83-8a8b-05c968a03f04",
    definitionId: "5786de12-cade-43c2-a6b0-0c5b294b9d0e", // Iron Star
    setCode: "3ed",
    rarity: "uncommon",
};

export const ivoryCup3ed: CardPrint = {
    printId: "b1dd930a-a7d8-4cdd-9c4f-78b2b249ce38",
    definitionId: "9964d8d8-dc97-4e5f-9f52-173f7e2c37fd", // Ivory Cup
    setCode: "3ed",
    rarity: "uncommon",
};

export const ivoryTower3ed: CardPrint = {
    printId: "2bd6f6a8-153f-4263-941a-e3387c2a22ad",
    definitionId: "a5f23039-45ca-4c15-af50-bfd40ea26453", // Ivory Tower
    setCode: "3ed",
    rarity: "rare",
};

export const jadeMonolith3ed: CardPrint = {
    printId: "4ff44808-a1a9-4173-a39c-d726c51490fb",
    definitionId: "4a77e0f1-449d-4a7d-9fa0-ba7598f7a73a", // Jade Monolith
    setCode: "3ed",
    rarity: "rare",
};

export const jandorSRing3ed: CardPrint = {
    printId: "2b56c9ed-c912-4829-9be0-e80303759c9c",
    definitionId: "71504078-a16f-4dc4-9626-0ecc42b1e93b", // Jandor's Ring
    setCode: "3ed",
    rarity: "rare",
};

export const jandorSSaddlebags3ed: CardPrint = {
    printId: "af96e332-1c77-4650-b66b-417e6c47bc3b",
    definitionId: "bc4f4b92-7d4e-4b03-8cb4-e6b356c338b4", // Jandor's Saddlebags
    setCode: "3ed",
    rarity: "rare",
};

export const jayemdaeTome3ed: CardPrint = {
    printId: "e8661e0a-faf8-4c16-b988-55622707de6f",
    definitionId: "cac8c421-5b92-481d-b2de-560c0231ab58", // Jayemdae Tome
    setCode: "3ed",
    rarity: "rare",
};

export const juggernaut3ed: CardPrint = {
    printId: "490fafd4-3cd0-4cd8-9f07-01a92121d39d",
    definitionId: "dcd6a291-5282-4f49-8203-d9b416083c48", // Juggernaut
    setCode: "3ed",
    rarity: "uncommon",
};

export const kormusBell3ed: CardPrint = {
    printId: "7071d294-842c-4539-aba1-c68cd5c79848",
    definitionId: "3f4ef7a1-148d-44ac-89ed-0ef379cca0c6", // Kormus Bell
    setCode: "3ed",
    rarity: "rare",
};

export const libraryOfLeng3ed: CardPrint = {
    printId: "0634ab23-4691-4c77-9b8f-bfd9d99b31a1",
    definitionId: "2340edcb-8cd5-4ccd-99e2-b9a29f72c495", // Library of Leng
    setCode: "3ed",
    rarity: "uncommon",
};

export const livingWall3ed: CardPrint = {
    printId: "516858c9-7679-4a65-a787-36a2cf175ede",
    definitionId: "4a98ada6-923a-44a5-bdef-ea6a160b481e", // Living Wall
    setCode: "3ed",
    rarity: "uncommon",
};

export const manaVault3ed: CardPrint = {
    printId: "5cbc686e-a8ef-40de-b79a-803ef42f8384",
    definitionId: "19499cb7-eccb-4e69-af32-6002d447a160", // Mana Vault
    setCode: "3ed",
    rarity: "rare",
};

export const meekstone3ed: CardPrint = {
    printId: "56854867-d135-4bed-8d3a-dcc24d757558",
    definitionId: "13a68a17-22ee-47c9-870a-83e911862b94", // Meekstone
    setCode: "3ed",
    rarity: "rare",
};

export const millstone3ed: CardPrint = {
    printId: "21aabfa6-c299-4cf8-b8b5-097ef6f4029a",
    definitionId: "107646bc-2181-49f4-8821-1eaa46291855", // Millstone
    setCode: "3ed",
    rarity: "rare",
};

export const mishraSWarMachine3ed: CardPrint = {
    printId: "1a93e9bd-6c31-4363-93b0-b7d355bd2867",
    definitionId: "8f6b4652-a1d4-418f-a89b-6a977a920a9e", // Mishra's War Machine
    setCode: "3ed",
    rarity: "rare",
};

export const nevinyrralSDisk3ed: CardPrint = {
    printId: "ba5fcfc5-0715-4c6c-8325-3b54a138634e",
    definitionId: "12926dc8-8e6f-4a47-a12b-4d674189615a", // Nevinyrral's Disk
    setCode: "3ed",
    rarity: "rare",
};

export const obsianusGolem3ed: CardPrint = {
    printId: "ef24fb75-49c7-48eb-a0b3-dc08d7f691ec",
    definitionId: "4c8e9f5c-deba-4443-bf9d-fb2be75c5418", // Obsianus Golem
    setCode: "3ed",
    rarity: "uncommon",
};

export const onulet3ed: CardPrint = {
    printId: "0d84e378-dc64-4e69-a49d-1c210ca3506c",
    definitionId: "d77fe8e2-8438-473e-ace5-01baddd2c4ed", // Onulet
    setCode: "3ed",
    rarity: "rare",
};

export const ornithopter3ed: CardPrint = {
    printId: "b3654fd6-f8ac-471a-8559-ba4ed0fe75c3",
    definitionId: "59cc9bdb-7cf2-4795-bac7-ffff605c9eb0", // Ornithopter
    setCode: "3ed",
    rarity: "uncommon",
};

export const primalClay3ed: CardPrint = {
    printId: "d057a91c-d2a7-48ec-aa16-f033499de166",
    definitionId: "ab9d0e3f-cf7c-41f8-bcd7-bb08ea8cc2f8", // Primal Clay
    setCode: "3ed",
    rarity: "rare",
};

export const rocketLauncher3ed: CardPrint = {
    printId: "919f184b-421c-413c-a95c-05bb145f93ba",
    definitionId: "d5bb2093-78a8-4a6c-abe7-9a5afc181ec5", // Rocket Launcher
    setCode: "3ed",
    rarity: "rare",
};

export const rodOfRuin3ed: CardPrint = {
    printId: "964abd0f-812e-418d-a01b-73dc724c8429",
    definitionId: "af957200-c538-4f52-b105-6db7a7abb4dc", // Rod of Ruin
    setCode: "3ed",
    rarity: "uncommon",
};

export const solRing3ed: CardPrint = {
    printId: "803fd65f-4ca6-4fe4-abc2-72aa32ebb3a5",
    definitionId: "c4300d24-1cae-4dd5-be7e-38cc677cf5bd", // Sol Ring
    setCode: "3ed",
    rarity: "uncommon",
};

export const soulNet3ed: CardPrint = {
    printId: "3a80be5d-cf6f-487d-8602-9396d9b6252b",
    definitionId: "2b814198-814b-4619-a158-327af675f8f2", // Soul Net
    setCode: "3ed",
    rarity: "uncommon",
};

export const sunglassesOfUrza3ed: CardPrint = {
    printId: "4babb2a9-b6b3-4a85-8add-90828726adb4",
    definitionId: "c0d433a4-76c0-4f27-836d-4c0c13a511fb", // Sunglasses of Urza
    setCode: "3ed",
    rarity: "rare",
};

export const theHive3ed: CardPrint = {
    printId: "09b82c6b-9b14-4607-95d5-2964b926ec37",
    definitionId: "544a7138-eae8-4ff9-9e17-680bfa717183", // The Hive
    setCode: "3ed",
    rarity: "rare",
};

export const theRack3ed: CardPrint = {
    printId: "2a600805-dd79-419d-9866-f8c29643f0f8",
    definitionId: "ec0686ba-1277-4412-a397-7a6227808311", // The Rack
    setCode: "3ed",
    rarity: "uncommon",
};

export const throneOfBone3ed: CardPrint = {
    printId: "8b08a20c-59ee-4323-8a00-af88b82d6b76",
    definitionId: "a2931ae0-7836-4000-b9ec-f2029ebf5d96", // Throne of Bone
    setCode: "3ed",
    rarity: "uncommon",
};

export const winterOrb3ed: CardPrint = {
    printId: "f5c6d64b-f49c-4b41-bd25-3d29c896a9a8",
    definitionId: "9359f60c-9a27-4e53-b35b-964a121a6fba", // Winter Orb
    setCode: "3ed",
    rarity: "rare",
};

export const woodenSphere3ed: CardPrint = {
    printId: "157a28e2-61f6-4c95-b377-e945fc8dade2",
    definitionId: "bcae01a2-171b-47cd-87be-f1e4e5314326", // Wooden Sphere
    setCode: "3ed",
    rarity: "uncommon",
};

export const badlands3ed: CardPrint = {
    printId: "56058359-3c0b-49db-a0ce-9ded4c3f4372",
    definitionId: "717f6d10-9144-4ade-9ac6-a481cc66b875", // Badlands
    setCode: "3ed",
    rarity: "rare",
};

export const bayou3ed: CardPrint = {
    printId: "56355ff3-2232-4a11-b868-aec9a50b9ee5",
    definitionId: "412ceddd-2b9a-4551-a6bf-ae2830a2010a", // Bayou
    setCode: "3ed",
    rarity: "rare",
};

export const plateau3ed: CardPrint = {
    printId: "c6ae9cff-8646-4069-8761-df734e067beb",
    definitionId: "6eafa00b-c628-40f6-86eb-88e1361fc7a0", // Plateau
    setCode: "3ed",
    rarity: "rare",
};

export const savannah3ed: CardPrint = {
    printId: "5ae71290-c133-406c-8b17-9ea22b437806",
    definitionId: "94f7e24c-2546-41b6-81ad-5e920b07e64e", // Savannah
    setCode: "3ed",
    rarity: "rare",
};

export const scrubland3ed: CardPrint = {
    printId: "472034a2-0ba9-4876-ab7a-aa7013d603bb",
    definitionId: "bebe39d4-21fb-46a4-a1ec-b97102e46c15", // Scrubland
    setCode: "3ed",
    rarity: "rare",
};

export const taiga3ed: CardPrint = {
    printId: "54c5c65a-a444-4e0f-ae44-a3722cdd32a1",
    definitionId: "60df6592-0b3b-4b87-aeb2-8fa94b4fb7be", // Taiga
    setCode: "3ed",
    rarity: "rare",
};

export const tropicalIsland3ed: CardPrint = {
    printId: "a0f5c6bc-65dc-42a1-a62d-a0b101310a1f",
    definitionId: "a9c6c759-aabf-44e7-ba8c-33c5df232b56", // Tropical Island
    setCode: "3ed",
    rarity: "rare",
};

export const tundra3ed: CardPrint = {
    printId: "9c9d5f72-e199-4d5b-ae7e-cc5b9bdfae99",
    definitionId: "a03e8c5b-f4ed-4fd7-ba05-db813ccc05eb", // Tundra
    setCode: "3ed",
    rarity: "rare",
};

export const undergroundSea3ed: CardPrint = {
    printId: "1f35877c-e66c-4ef0-842a-f68cd233ae4b",
    definitionId: "ff76ac86-8a8a-47fe-9388-8950ca3e26c3", // Underground Sea
    setCode: "3ed",
    rarity: "rare",
};

export const volcanicIsland3ed: CardPrint = {
    printId: "b12e5430-0e80-47dd-80ac-85728b656a24",
    definitionId: "0324641d-af55-4c53-b4dc-c8262e967da5", // Volcanic Island
    setCode: "3ed",
    rarity: "rare",
};

// Basic lands (art variants — one print per collector number).

export const plains3ed: CardPrint = {
    printId: "275c03f9-f9d2-45c5-a332-b3bee54e7065",
    definitionId: "b1623d57-4729-4796-b3f7-f1837a05c6ed", // Plains
    setCode: "3ed",
    rarity: "common",
};

export const plains23ed: CardPrint = {
    printId: "cc0bcdbe-be63-446a-8838-8790bda308a3",
    definitionId: "b1623d57-4729-4796-b3f7-f1837a05c6ed", // Plains
    setCode: "3ed",
    rarity: "common",
};

export const plains33ed: CardPrint = {
    printId: "a4901260-073a-4d06-8167-c322c55ab210",
    definitionId: "b1623d57-4729-4796-b3f7-f1837a05c6ed", // Plains
    setCode: "3ed",
    rarity: "common",
};

export const island3ed: CardPrint = {
    printId: "22f6e971-349d-498b-ae01-ab81ce21772c",
    definitionId: "90a57c0e-fa61-45ef-955d-d296403967d5", // Island
    setCode: "3ed",
    rarity: "common",
};

export const island23ed: CardPrint = {
    printId: "a000777b-e8fe-4fd6-a455-01bc9056a873",
    definitionId: "90a57c0e-fa61-45ef-955d-d296403967d5", // Island
    setCode: "3ed",
    rarity: "common",
};

export const island33ed: CardPrint = {
    printId: "bec8018f-a12c-4adf-9735-c2093298062d",
    definitionId: "90a57c0e-fa61-45ef-955d-d296403967d5", // Island
    setCode: "3ed",
    rarity: "common",
};

export const swamp3ed: CardPrint = {
    printId: "95e936cf-3bbb-4f3b-8e1a-4be1d4702b99",
    definitionId: "6176936d-72e2-4205-8871-4c5a4f1cb2d8", // Swamp
    setCode: "3ed",
    rarity: "common",
};

export const swamp23ed: CardPrint = {
    printId: "459d175e-2b9c-4f30-be03-4e05cd3c68ef",
    definitionId: "6176936d-72e2-4205-8871-4c5a4f1cb2d8", // Swamp
    setCode: "3ed",
    rarity: "common",
};

export const swamp33ed: CardPrint = {
    printId: "515eff31-24f6-462e-bbd4-b49540421a75",
    definitionId: "6176936d-72e2-4205-8871-4c5a4f1cb2d8", // Swamp
    setCode: "3ed",
    rarity: "common",
};

export const mountain3ed: CardPrint = {
    printId: "30345500-d430-4280-bfe3-de297309f136",
    definitionId: "eace2c85-976c-425e-9800-5a6ccbd91b56", // Mountain
    setCode: "3ed",
    rarity: "common",
};

export const mountain23ed: CardPrint = {
    printId: "5a240d1b-8430-4986-850d-32afa0e812b2",
    definitionId: "eace2c85-976c-425e-9800-5a6ccbd91b56", // Mountain
    setCode: "3ed",
    rarity: "common",
};

export const mountain33ed: CardPrint = {
    printId: "1b0f41e8-cf27-489b-812a-d566a75cf7f7",
    definitionId: "eace2c85-976c-425e-9800-5a6ccbd91b56", // Mountain
    setCode: "3ed",
    rarity: "common",
};

export const forest3ed: CardPrint = {
    printId: "b6e1c2e9-5572-4242-985d-f509d628092b",
    definitionId: "6f1c8cb0-38eb-408b-94e8-16db83999b3b", // Forest
    setCode: "3ed",
    rarity: "common",
};

export const forest23ed: CardPrint = {
    printId: "4d1e4241-42ef-4b51-8f9b-2ab6aca31dbb",
    definitionId: "6f1c8cb0-38eb-408b-94e8-16db83999b3b", // Forest
    setCode: "3ed",
    rarity: "common",
};

export const forest33ed: CardPrint = {
    printId: "b38ce16b-3258-4019-9e86-156e4738aa89",
    definitionId: "6f1c8cb0-38eb-408b-94e8-16db83999b3b", // Forest
    setCode: "3ed",
    rarity: "common",
};
