// APC — multicolor cards, split by colour per ADR 0043. The registry's
// `import * as apc from "./sets/apc"` resolves through apc/index.ts.
// Cards are classified by the colour identity of their mana cost (CR 202.2):
// lands and colourless artifacts (no coloured cost) live in colorless.ts.
import type { CardDefinition } from "../../types";
import { PERMANENT_TYPES } from "../../types";
import { defineSplitCard } from "../../splitCard";

// Vindicate — "Destroy target permanent." (CR 701.8 destroy.) `type: "any"`
// matches only the CR 115.4 damageable types (creature/planeswalker/battle/
// player); "target permanent" of any type uses the full CR 300.1 permanent-type
// set (incl. Land) instead.
export const vindicate: CardDefinition = {
    id: "2a1bfefd-dae8-49e9-9d56-cc852e3dc93b",
    rarity: "rare",
    name: "Vindicate",
    oracleText: "Destroy target permanent.",
    manaCost: { X: 1, W: 1, B: 1 },
    types: ["Sorcery"],
    targetRequirement: { type: [...PERMANENT_TYPES], count: 1 },
    effects: [{ op: "destroy", target: { target: 0 } }],
};

// ─────────────────────────────────────────────────────────────────────────
// Split card (CR 709.1–709.4, ADR 0121 §6 slice 2, issue #3308)
//
// CR 709.4b makes Life // Death a GOLD card — "a split card's colors and mana
// value are determined from its combined mana cost", and {G} + {1}{B} is
// {1}{B}{G}: green AND black, mana value 3. That is what every graveyard
// reader sees (a tutor, a deck-legality check, the Bot's valuation), which is
// why the card lives here and not in green.ts or black.ts.
//
// It declares no top-level `name`, `manaCost` or `types`: CR 709.4 makes those
// three a FUNCTION of the halves, and `defineSplitCard` is the only thing that
// writes them (`cards/splitCard.ts`, ADR 0121 §1).
// ─────────────────────────────────────────────────────────────────────────

// Life // Death — {G} // {1}{B}, Sorcery // Sorcery. "All lands you control
// become 1/1 creatures until end of turn. They're still lands." // "Return
// target creature card from your graveyard to the battlefield. You lose life
// equal to its mana value."
//
// LIFE is the half with the real rules content. "All lands you control become
// 1/1 creatures until end of turn" is a continuous effect generated by a
// RESOLVING SPELL, so CR 611.2c fixes its set of objects the moment it begins:
// "the set of objects it affects is determined when that continuous effect
// begins. After that point, the set won't change." A land that enters the
// battlefield later this turn is NOT animated. `forEach` is exactly that
// semantics already — its member set is frozen at construct entry — so the
// clause needs no new Op and no new duration: ONE `animate` per land that was
// there at resolution, each with its own end-of-turn expiry.
//
// The animation itself is `animate`'s own layer split (CR 613.1d/f): the
// Creature card type lands in layer 4 and the 1/1 base P/T in layer 7b, and
// the type is ADDED rather than replacing the printed line — CR 205.1b's "in
// addition to its other types", which is what "They're still lands" says. The
// animated land is a land and a creature at once, so it keeps tapping for mana
// and it dies to the CR 704.5f state-based action the moment something drops
// its toughness to 0.
//
// DEATH is ordinary reanimation over already-exercised Ops, and it is
// Reanimate's script (`tmp/black.ts`) narrowed to `controller: "you"` — "your
// graveyard", not "a graveyard". `bind` + `ref.manaValue` snapshots the card's
// mana value BEFORE the zone change (CR 608.2h last-known information), since
// "its mana value" is the card's, read off the object that just left the
// graveyard.
//
// Guard C — neither Oracle line has a compiler slot yet: the mass-animation
// template ("All lands you control become …") has no lowering at all, and the
// reanimation line's "You lose life equal to its mana value." rider is the
// bound-snapshot shape the grammar cannot yet express.
// compiler-gap: "All lands you control become 1/1 creatures until end of turn. They're still lands." (#2693)
// compiler-gap: "Return target creature card from your graveyard to the battlefield. You lose life equal to its mana value." (#2693)
export const lifeDeath: CardDefinition = defineSplitCard({
    id: "7ab75cdb-93a1-4f78-b404-37566295c321",
    rarity: "uncommon",
    oracleText:
        "All lands you control become 1/1 creatures until end of turn. They're still lands.\nReturn target creature card from your graveyard to the battlefield. You lose life equal to its mana value.",
    halves: [
        {
            name: "Life",
            manaCost: { G: 1 },
            types: ["Sorcery"],
            oracleText:
                "All lands you control become 1/1 creatures until end of turn. They're still lands.",
            effects: [
                {
                    op: "forEach",
                    select: {
                        set: "permanents",
                        zone: "battlefield",
                        controller: "controller",
                        filter: { type: "Land" },
                    },
                    effects: [
                        {
                            op: "animate",
                            target: { ref: "$each" },
                            power: 1,
                            toughness: 1,
                            duration: { phase: "end-of-turn" },
                        },
                    ],
                },
            ],
        },
        {
            name: "Death",
            manaCost: { X: 1, B: 1 },
            types: ["Sorcery"],
            oracleText:
                "Return target creature card from your graveyard to the battlefield. You lose life equal to its mana value.",
            targetRequirement: {
                type: "Creature",
                count: 1,
                zone: "graveyard",
                controller: "you",
            },
            effects: [
                {
                    op: "moveZone",
                    target: { target: 0 },
                    to: "battlefield",
                    bind: "$reanimated",
                },
                {
                    op: "loseLife",
                    player: "controller",
                    amount: { ref: "$reanimated.manaValue" },
                },
            ],
        },
    ],
});
