// Guard C's BASELINE — the hand-written cards that do not round-trip through
// the Oracle compiler today (issue #2701, PRD #2693).
//
// ── What this list is ──────────────────────────────────────────────────────
//
// Guard C (`compilerRoundTrip.test.ts`) requires every hand-written card to
// either compile back into its own definition or name the fragment that stops
// it in a `compiler-gap: <fragment> (#issue)` marker. Grammar v0 reads a
// minority of the catalogue, so imposing that on 1756 pre-existing cards
// at once would mean 1756 markers written blind in one commit — noise that
// would say nothing about any card and would have to be re-derived every time
// a grammar slot ships. This file is the one-time amnesty instead.
//
// ── SHRINK-ONLY ────────────────────────────────────────────────────────────
//
// Generated ONCE, at the commit that introduced Guard C. It has no generator
// script on purpose: a regeneration command is a re-baseline command, and a
// baseline anybody can re-take is not a baseline. Three mechanisms hold it
// one-directional, all asserted in `compilerRoundTrip.test.ts`:
//
//   1. A card that starts round-tripping must LEAVE — a stale row (a card that
//      passes, or a name no card carries) reds the guard. So the list drains
//      by itself as grammar slots ship.
//   2. A card whose gap gets DOCUMENTED must leave — a valid `compiler-gap:`
//      marker and a baseline row are mutually exclusive, so writing the marker
//      is what removes the row.
//   3. It may never GROW — `BASELINE_CEILING` is a literal a human has to
//      lower, never raise. A new hand-written card cannot be APPENDED here; it
//      round-trips or it carries a marker.
//
// What mechanism 3 does NOT stop, stated plainly rather than overclaimed: a
// diff that deletes a graduating row and spends the freed slot on a new failing
// card. The count does not grow, nothing reads as stale, and the guard stays
// green. No in-repo artifact can close that — a frozen snapshot to diff against
// would be just as editable as this file — so what catches it is the same thing
// that catches a bogus `KEYWORD_ALLOWLIST` row: the deletion and the insertion
// are both in the diff, on adjacent lines, under review. Treat a baseline edit
// that is not a pure deletion as a change that needs a reason in the PR body.
//
// Sorted by name (code-unit order), one per line, so a diff reads as the list
// of cards a change graduated.
export const COMPILER_ROUND_TRIP_BASELINE: readonly string[] = [
    "Aang's Iceberg",
    "Abandoned Air Temple",
    "Abeyance",
    "Absorb",
    "Abu Ja'far",
    "Abyssal Specter",
    "Accumulated Knowledge",
    "Acid Rain",
    "Active Volcano",
    "Adarkar Unicorn",
    "Adarkar Wastes",
    "Addle",
    "Adeline, Resplendent Cathar",
    "Adun Oakenshield",
    "Adventurers' Guildhouse",
    "Aegis of the Meek",
    "Aeolipile",
    "Aerathi Berserker",
    "Aether Rift",
    "Aggression",
    "Aggressive Urge",
    "Agonizing Demise",
    "Akron Legionnaire",
    "Alabaster Leech",
    "Alabaster Potion",
    "Aladdin",
    "Aladdin's Lamp",
    "Alchor's Tomb",
    "Ali from Cairo",
    "Allied Strategies",
    "Alloy Golem",
    "Altar of Bone",
    "Amnesia",
    "Amphibious Kavu",
    "Amrou Kithkin",
    "Amulet of Kroog",
    "Anarchy",
    "Ancient Cornucopia",
    "Ancient Kavu",
    "Ancient Tomb",
    "Andradite Leech",
    "Angelic Voices",
    "Angry Mob",
    "Angus Mackenzie",
    "Animate Artifact",
    "Animate Dead",
    "Animate Wall",
    "Anje's Ravager",
    "Ankh of Mishra",
    "Annihilate",
    "Annul",
    "Anti-Magic Aura",
    "Arboria",
    "Arc Lightning",
    "Arc Mage",
    "Arcades Sabboth",
    "Archaeological Dig",
    "Archon of Cruelty",
    "Arctic Foxes",
    "Arctic Merfolk",
    "Arcum's Sleigh",
    "Arcum's Weathervane",
    "Arcum's Whistle",
    "Ardent Soldier",
    "Arenson's Aura",
    "Argivian Archaeologist",
    "Argivian Blacksmith",
    "Argothian Enchantress",
    "Argothian Pixies",
    "Argothian Treefolk",
    "Arid Mesa",
    "Armadillo Cloak",
    "Armageddon",
    "Armageddon Clock",
    "Armor of Faith",
    "Armored Guardian",
    "Army of Allah",
    "Arnjlot's Ascent",
    "Artifact Blast",
    "Artifact Mutation",
    "Artifact Possession",
    "Artifact Ward",
    "Arwen, Mortal Queen",
    "Ashen Ghoul",
    "Ashes to Ashes",
    "Ashnod's Altar",
    "Ashnod's Battle Gear",
    "Ashnod's Transmogrant",
    "Aspect of Wolf",
    "Astrologian's Planisphere",
    "Atraxa, Grand Unifier",
    "Aura Blast",
    "Aura Mutation",
    "Aura Shards",
    "Aura of Silence",
    "Aurochs",
    "Aurora Griffin",
    "Avalanche",
    "Azure Beastbinder",
    "Backfire",
    "Backlash",
    "Badgermole Cub",
    "Badlands",
    "Balance",
    "Balduvian Conjurer",
    "Balduvian Hydra",
    "Balduvian Shaman",
    "Ball Lightning",
    "Balm of Restoration",
    "Banishing Light",
    "Banshee",
    "Barbarian Guides",
    "Barbarian Ring",
    "Barbed Sextant",
    "Barl's Cage",
    "Barrin's Spite",
    "Barrowgoyf",
    "Bartel Runeaxe",
    "Basking Rootwalla",
    "Battering Ram",
    "Batterskull",
    "Battle Cry",
    "Battle Frenzy",
    "Bayou",
    "Bazaar of Baghdad",
    "Beasts of Bogardan",
    "Benalish Emissary",
    "Benalish Lancer",
    "Bend or Break",
    "Berserk",
    "Bind",
    "Binding Grasp",
    "Birds of Paradise",
    "Bitter Triumph",
    "Black Knight",
    "Black Lotus",
    "Black Mana Battery",
    "Black Scarab",
    "Black Vise",
    "Black Ward",
    "Blackcleave Cliffs",
    "Blastoderm",
    "Blaze of Glory",
    "Blazemire Verge",
    "Blazing Rootwalla",
    "Blazing Specter",
    "Bleachbone Verge",
    "Blessed Wine",
    "Blessing",
    "Blight",
    "Blightsteel Colossus",
    "Blind Seer",
    "Blizzard",
    "Blood Crypt",
    "Blood Lust",
    "Blood Moon",
    "Bloodchief's Thirst",
    "Bloodstained Mire",
    "Bloodtithe Harvester",
    "Blooming Marsh",
    "Blue Elemental Blast",
    "Blue Mana Battery",
    "Blue Scarab",
    "Blue Ward",
    "Blurred Mongoose",
    "Bog Down",
    "Bog Rats",
    "Bog Wraith",
    "Bolas's Citadel",
    "Bone Flute",
    "Bone Shaman",
    "Bone Shards",
    "Boris Devilboon",
    "Botanical Sanctum",
    "Bottle of Suleiman",
    "Bottomless Vault",
    "Brain Freeze",
    "Brainstorm",
    "Brand of Ill Omen",
    "Brass Man",
    "Brassclaw Orcs",
    "Breath of Darigaaz",
    "Breath of Dreams",
    "Breeding Pit",
    "Breeding Pool",
    "Brightglass Gearhulk",
    "Brine Shaman",
    "Bristly Bill, Spine Sower",
    "Broadside Bombardiers",
    "Brothers of Fire",
    "Brown Ouphe",
    "Brushland",
    "Burnt Offering",
    "Burrowing",
    "Burst Lightning",
    "Cabal Ritual",
    "Caldera Kavu",
    "Call to Arms",
    "Callous Giant",
    "Camel",
    "Camouflage",
    "Candelabra of Tawnos",
    "Canopy Surge",
    "Captain Sisay",
    "Caribou Range",
    "Carnage Interpreter",
    "Cat Warriors",
    "Cathedral of Serra",
    "Cave People",
    "Cavern Harpy",
    "Caverns of Despair",
    "Celestial Colonnade",
    "Celestial Prism",
    "Celestial Sword",
    "Chain Lightning",
    "Chain of Vapor",
    "Chandra, Torch of Defiance",
    "Channel",
    "Chaos Lord",
    "Chaos Moon",
    "Chaoslace",
    "Chaotic Strike",
    "Chromatic Armor",
    "Chromatic Sphere",
    "Chromatic Star",
    "Chrome Mox",
    "Chromium",
    "Chub Toad",
    "Circle of Protection: Artifacts",
    "Circle of Protection: Black",
    "Circle of Protection: Blue",
    "Circle of Protection: Green",
    "Circle of Protection: Red",
    "Circle of Protection: White",
    "Citanul Druid",
    "City of Brass",
    "City of Shadows",
    "City of Traitors",
    "Clairvoyance",
    "Cleanse",
    "Clergy of the Holy Nimbus",
    "Cloak of Confusion",
    "Clockwork Avian",
    "Clockwork Beast",
    "Clone",
    "Cloud Cover",
    "Coalition Victory",
    "Cockatrice",
    "Cocoon",
    "Cold Snap",
    "Collapsing Borders",
    "Collective Restraint",
    "Combat Medic",
    "Commercial District",
    "Concealed Courtyard",
    "Conch Horn",
    "Confound",
    "Conquer",
    "Consecrate Land",
    "Conservator",
    "Consider",
    "Consult the Star Charts",
    "Consuming Aetherborn",
    "Containment Priest",
    "Control Magic",
    "Conversion",
    "Cooperation",
    "Copper Tablet",
    "Copperline Gorge",
    "Copy Artifact",
    "Cori-Steel Cutter",
    "Corpse Dance",
    "Cosmic Horror",
    "Counterspell",
    "Courser of Kruphix",
    "Coveted Jewel",
    "Craterhoof Behemoth",
    "Craw Giant",
    "Craw Wurm",
    "Creature Bond",
    "Creeping Tar Pit",
    "Cremate",
    "Crested Sunmare",
    "Crimson Acolyte",
    "Crosis's Catacombs",
    "Crown of Flames",
    "Crown of the Ages",
    "Crucible of Worlds",
    "Crumble",
    "Crusading Knight",
    "Crypt Angel",
    "Crystal Rod",
    "Cuombajj Witches",
    "Currency Converter",
    "Curse Artifact",
    "Curse of Marit Lage",
    "Cursed Flesh",
    "Cursed Land",
    "Cursed Rack",
    "Cursed Scroll",
    "Cyclone",
    "Cyclopean Mummy",
    "Cyclopean Tomb",
    "D'Avenant Archer",
    "Dack Fayden",
    "Dakkon Blackblade",
    "Damnation",
    "Dance of Many",
    "Dance of the Dead",
    "Dandân",
    "Darigaaz's Caldera",
    "Darigaaz's Charm",
    "Daring Leap",
    "Dark Confidant",
    "Dark Ritual",
    "Dark Sphere",
    "Dark Suspicions",
    "Darkness",
    "Darkslick Shores",
    "Dauthi Voidwalker",
    "Day of Judgment",
    "Daze",
    "Death Bomb",
    "Death or Glory",
    "Death-Greeter's Champion",
    "Deathgrip",
    "Deathlace",
    "Deathrite Shaman",
    "Deceit",
    "Deceiver Exarch",
    "Deep Forest Hermit",
    "Deep Spawn",
    "Deep Water",
    "Deflection",
    "Delif's Cone",
    "Delif's Cube",
    "Delighted Halfling",
    "Demonic Consultation",
    "Demonic Hordes",
    "Demonic Tutor",
    "Derelor",
    "Desert",
    "Desert Nomads",
    "Desert Twister",
    "Desperate Research",
    "Despotic Scepter",
    "Destructive Flow",
    "Detonate",
    "Devouring Deep",
    "Devouring Strossus",
    "Diabolic Intent",
    "Diabolic Vision",
    "Dingus Egg",
    "Dire Wolves",
    "Disciple of Kangee",
    "Disintegrate",
    "Dismantling Blow",
    "Displacer Kitten",
    "Disrupt",
    "Disrupting Scepter",
    "Distorting Wake",
    "Divine Intervention",
    "Divine Offering",
    "Divine Presence",
    "Divine Transformation",
    "Do or Die",
    "Dominaria's Judgment",
    "Dominate",
    "Doomsday",
    "Doomsday Specter",
    "Draco",
    "Drafna's Restoration",
    "Dragon Whelp",
    "Dragon's Rage Channeler",
    "Drain Life",
    "Drain Power",
    "Dralnu's Crusade",
    "Dread Wight",
    "Dream Thrush",
    "Dreams of the Dead",
    "Dredge",
    "Drift of the Dead",
    "Dromar's Cavern",
    "Dromar's Charm",
    "Dromar, the Banisher",
    "Drop of Honey",
    "Drought",
    "Dueling Grounds",
    "Duress",
    "Duskwalker",
    "Dust to Dust",
    "Dwarven Armorer",
    "Dwarven Armory",
    "Dwarven Catapult",
    "Dwarven Hold",
    "Dwarven Soldier",
    "Dwarven Song",
    "Dwarven Warriors",
    "Eagles of the North",
    "Earth Elemental",
    "Earthbind",
    "Earthcraft",
    "Earthlink",
    "Earthlore",
    "Earthquake",
    "Eater of the Dead",
    "Ebon Praetor",
    "Ebony Horse",
    "Echo of Eons",
    "El-Hajjâj",
    "Eladamri's Call",
    "Elder Druid",
    "Electric Eel",
    "Elegant Parlor",
    "Elemental Augury",
    "Elephant Grass",
    "Elfhame Sanctuary",
    "Elite Spellbinder",
    "Elkin Bottle",
    "Elven Riders",
    "Elves of Deep Shadow",
    "Elvish Champion",
    "Elvish Farmer",
    "Elvish Healer",
    "Elvish Hunter",
    "Elvish Scout",
    "Emperor of Bones",
    "Empress Galina",
    "Empty the Warrens",
    "Emrakul, the Aeons Torn",
    "Emry, Lurker of the Loch",
    "Enchanted Being",
    "Enchantress's Presence",
    "Endurance",
    "Enduring Innocence",
    "Enduring Renewal",
    "Energy Flux",
    "Energy Storm",
    "Energy Tap",
    "Enervate",
    "Entomb",
    "Ephemerate",
    "Equinox",
    "Erg Raiders",
    "Erhnam Djinn",
    "Erode",
    "Erosion",
    "Errantry",
    "Ertai, the Corrupted",
    "Escape Routes",
    "Essence Filter",
    "Essence Flare",
    "Essence Vortex",
    "Eternal Flame",
    "Eternal Warrior",
    "Eternal Witness",
    "Everflowing Chalice",
    "Evil Presence",
    "Exalted Angel",
    "Exclude",
    "Exhume",
    "Exotic Curse",
    "Exotic Disease",
    "Expedition Map",
    "Exploration",
    "Explosive Growth",
    "Expressive Iteration",
    "Eye for an Eye",
    "Fable of the Mirror-Breaker",
    "Fabled Passage",
    "Fact or Fiction",
    "Faerie Mastermind",
    "Faerie Squadron",
    "Faithless Looting",
    "Falling Timber",
    "False Orders",
    "Fanatic of Rhonas",
    "Fanatical Fever",
    "Farmstead",
    "Farrel's Mantle",
    "Farrel's Zealot",
    "Farrelite Priest",
    "Fastbond",
    "Fasting",
    "Fatal Push",
    "Fear",
    "Fear of Missing Out",
    "Feedback",
    "Feldon's Cane",
    "Fellwar Stone",
    "Fertile Ground",
    "Fiery Justice",
    "Fight or Flight",
    "Figure of Destiny",
    "Figure of Fable",
    "Fire Covenant",
    "Fire Elemental",
    "Fire and Brimstone",
    "Fireball",
    "Fireblast",
    "Firebrand Ranger",
    "Firebreathing",
    "Fishliver Oil",
    "Flametongue Kavu",
    "Flare",
    "Flash",
    "Flash Counter",
    "Flash Flood",
    "Flash of Insight",
    "Flashfires",
    "Fleetfoot Panther",
    "Flickerwisp",
    "Flight",
    "Flooded Strand",
    "Flooded Woodlands",
    "Flow of Maggots",
    "Fog",
    "Foil",
    "Forbidden Lore",
    "Force Spike",
    "Force Void",
    "Force of Nature",
    "Force of Negation",
    "Force of Vigor",
    "Force of Will",
    "Forcefield",
    "Forest",
    "Forgotten Lore",
    "Fork",
    "Formation",
    "Formidable Speaker",
    "Forsaken City",
    "Forth Eorlingas!",
    "Fortified Area",
    "Foul Familiar",
    "Foxfire",
    "Fractured Identity",
    "Frantic Search",
    "Frenzied Tilling",
    "Freyalise Supplicant",
    "Freyalise's Charm",
    "Freyalise's Winds",
    "Frogmite",
    "Frost Giant",
    "Fumarole",
    "Fungusaur",
    "Fury",
    "Fylgja",
    "Fyndhorn Pollen",
    "Gaea's Avenger",
    "Gaea's Blessing",
    "Gaea's Cradle",
    "Gaea's Liege",
    "Gaea's Might",
    "Gaea's Touch",
    "Gainsay",
    "Galina's Knight",
    "Galvanic Discharge",
    "Game of Chaos",
    "Gangrenous Zombies",
    "Garruk Wildspeaker",
    "Gate to Phyrexia",
    "Gauntlet of Might",
    "Gaze of Pain",
    "General Jarkeld",
    "Generous Ent",
    "Generous Plunderer",
    "Gerrard's Command",
    "Ghazbán Ogre",
    "Ghitu Fire",
    "Ghostly Flame",
    "Giant Shark",
    "Giant Strength",
    "Giant Tortoise",
    "Giant Trap Door Spider",
    "Giant Turtle",
    "Gitaxian Probe",
    "Giver of Runes",
    "Glacial Chasm",
    "Glacial Crevasses",
    "Glaciers",
    "Glasses of Urza",
    "Glimmer Lens",
    "Gloom",
    "Glyph of Destruction",
    "Glyph of Life",
    "Goblin Artisans",
    "Goblin Cadets",
    "Goblin Caves",
    "Goblin Flotilla",
    "Goblin King",
    "Goblin Kites",
    "Goblin Lyre",
    "Goblin Mutant",
    "Goblin Patrol",
    "Goblin Rock Sled",
    "Goblin Sappers",
    "Goblin Shrine",
    "Goblin Ski Patrol",
    "Goblin Snowman",
    "Goblin Spy",
    "Goblin Warrens",
    "Goblin Wizard",
    "Goblins of the Flarg",
    "Godless Shrine",
    "Goham Djinn",
    "Golgothian Sylex",
    "Gorilla Pack",
    "Gravebind",
    "Gravity Sphere",
    "Gray Ogre",
    "Great Defender",
    "Great Wall",
    "Greater Realm of Preservation",
    "Green Mana Battery",
    "Green Scarab",
    "Green Sun's Zenith",
    "Green Ward",
    "Grief",
    "Grist, the Hunger Tide",
    "Grizzled Wolverine",
    "Grizzly Bears",
    "Guard Dogs",
    "Guardian Angel",
    "Guardian Beast",
    "Guardian Scalelord",
    "Guide of Souls",
    "Gush",
    "Gut, True Soul Zealot",
    "Halam Djinn",
    "Halfdane",
    "Hallowed Fountain",
    "Halls of Mist",
    "Hand of Justice",
    "Hanna, Ship's Navigator",
    "Harrow",
    "Harsh Judgment",
    "Harvester of Misery",
    "Hasran Ogress",
    "Hate Weaver",
    "Haunting Wind",
    "Haywire Mite",
    "Headliner Scarlett",
    "Heal",
    "Healing Salve",
    "Hecatomb",
    "Hedge Maze",
    "Hell Swarm",
    "Hell's Caretaker",
    "Hellfire",
    "Hematite Talisman",
    "Heroic Defiance",
    "Heroism",
    "Hibernation",
    "Hidden Path",
    "High Tide",
    "Hill Giant",
    "Hipparion",
    "History of Benalia",
    "Hobble",
    "Hogaak, Arisen Necropolis",
    "Hollow Trees",
    "Holy Armor",
    "Holy Day",
    "Holy Light",
    "Holy Strength",
    "Homarid",
    "Homarid Spawning Bed",
    "Homarid Warrior",
    "Honden of Seeing Winds",
    "Honorable Scout",
    "Horned Cheetah",
    "Horned Kavu",
    "Horror of Horrors",
    "Hot Springs",
    "Howl from Beyond",
    "Howling Mine",
    "Hull Breach",
    "Hullbreacher",
    "Hunding Gjornersen",
    "Hunting Drake",
    "Hunting Kavu",
    "Hurkyl's Recall",
    "Hurloon Minotaur",
    "Hurricane",
    "Hyalopterous Lemure",
    "Hydroblast",
    "Hymn of Rebirth",
    "Hyperion Blacksmith",
    "Hypnotic Cloud",
    "Hypnotic Specter",
    "Icatian Javelineers",
    "Icatian Moneychanger",
    "Icatian Skirmishers",
    "Icatian Store",
    "Icatian Town",
    "Ice Cauldron",
    "Ice Floe",
    "Iceberg",
    "Icequake",
    "Icetill Explorer",
    "Icy Prison",
    "Ifh-Bíff Efreet",
    "Illusionary Forces",
    "Illusionary Mask",
    "Illusionary Presence",
    "Illusionary Terrain",
    "Illusionary Wall",
    "Illusions of Grandeur",
    "Immolation",
    "Imperial Seal",
    "Implements of Sacrifice",
    "Implode",
    "Imposing Visage",
    "Impulse",
    "In the Eye of Chaos",
    "Incinerate",
    "Indatha Triome",
    "Indestructible Aura",
    "Infernal Darkness",
    "Infernal Denizen",
    "Inferno",
    "Infinite Authority",
    "Infinite Hourglass",
    "Infuse",
    "Initiates of the Ebon Hand",
    "Innocent Blood",
    "Inquisition",
    "Inquisition of Kozilek",
    "Insolence",
    "Inspiring Vantage",
    "Instill Energy",
    "Inti, Seneschal of the Sun",
    "Invisibility",
    "Iron Star",
    "Iron-Shield Elf",
    "Ironclaw Orcs",
    "Ironroot Treefolk",
    "Island",
    "Island Fish Jasconius",
    "Island Sanctuary",
    "Island of Wak-Wak",
    "Ivory Cup",
    "Ivory Guardians",
    "Ivory Tower",
    "Jace, Vryn's Prodigy",
    "Jace, the Mind Sculptor",
    "Jackal Pup",
    "Jacked Rabbit",
    "Jade Leech",
    "Jade Monolith",
    "Jade Statue",
    "Jalum Tome",
    "Jandor's Ring",
    "Jester's Cap",
    "Jester's Mask",
    "Jetmir's Garden",
    "Jeweled Amulet",
    "Jihad",
    "Johtull Wurm",
    "Jokulhaups",
    "Jovial Evil",
    "Juggernaut",
    "Juntu Stakes",
    "Junún Efreet",
    "Justice",
    "Kaldra Compleat",
    "Kappa Cannoneer",
    "Karma",
    "Karmic Justice",
    "Karn, Scion of Urza",
    "Karplusan Forest",
    "Karplusan Giant",
    "Karplusan Yeti",
    "Kavu Aggressor",
    "Kavu Chameleon",
    "Kavu Lair",
    "Kavu Monarch",
    "Kavu Recluse",
    "Kavu Runner",
    "Kavu Scout",
    "Kavu Titan",
    "Kei Takahashi",
    "Keldon Mantle",
    "Keldon Twilight",
    "Keldon Warlord",
    "Ketria Triome",
    "Khabál Ghoul",
    "Kird Ape",
    "Kismet",
    "Kjeldoran Dead",
    "Kjeldoran Elite Guard",
    "Kjeldoran Frostbeast",
    "Kjeldoran Guard",
    "Kjeldoran Royal Guard",
    "Knight of Stromgald",
    "Knights of Thorn",
    "Kobold Drill Sergeant",
    "Kobold Overlord",
    "Kobold Taskmaster",
    "Kormus Bell",
    "Krosan Reclamation",
    "Krovikan Elementalist",
    "Krovikan Fetish",
    "Krovikan Sorcerer",
    "Krovikan Vampire",
    "Kudzu",
    "Laelia, the Blade Reforged",
    "Lance",
    "Land Cap",
    "Lapis Lazuli Talisman",
    "Lashknife Barrier",
    "Lava Burst",
    "Lava Dart",
    "Lava Spike",
    "Lava Tubes",
    "Lava Zombie",
    "Lavaspur Boots",
    "Ledger Shredder",
    "Legion Extruder",
    "Legions of Lim-Dûl",
    "Leovold, Emissary of Trest",
    "Leshrac's Rite",
    "Leshrac's Sigil",
    "Leyline Binding",
    "Lhurgoyf",
    "Liberate",
    "Library of Alexandria",
    "Library of Leng",
    "Lich",
    "Lifeblood",
    "Lifeforce",
    "Lifelace",
    "Lifetap",
    "Lightning Blow",
    "Lightning Dart",
    "Lightning Greaves",
    "Liliana of the Veil",
    "Lim-Dûl's Cohort",
    "Lim-Dûl's Hex",
    "Lingering Souls",
    "Lion Sash",
    "Lion's Eye Diamond",
    "Living Armor",
    "Living Artifact",
    "Living Lands",
    "Livonya Silone",
    "Llanowar Elite",
    "Llanowar Knight",
    "Loafing Giant",
    "Lobotomy",
    "Loran of the Third Path",
    "Lord of Atlantis",
    "Lord of the Pit",
    "Lord of the Undead",
    "Lorehold Charm",
    "Lost Order of Jarkeld",
    "Lost Soul",
    "Lotus Guardian",
    "Lotus Petal",
    "Lure",
    "Lurker",
    "Lurrus of the Dream-Den",
    "Lush Portico",
    "Lutri, the Spellchaser",
    "Lórien Revealed",
    "Maddening Wind",
    "Maggot Carrier",
    "Magical Hack",
    "Magma Burst",
    "Magnetic Mountain",
    "Magnigoth Treefolk",
    "Magus of the Unseen",
    "Malachite Talisman",
    "Malcolm, Alluring Scoundrel",
    "Malevolent Rumble",
    "Malicious Advice",
    "Mana Clash",
    "Mana Confluence",
    "Mana Crypt",
    "Mana Cylix",
    "Mana Drain",
    "Mana Flare",
    "Mana Leak",
    "Mana Matrix",
    "Mana Short",
    "Mana Tithe",
    "Mana Vault",
    "Mana Vortex",
    "Manabarbs",
    "Maniacal Rage",
    "Manifold Key",
    "Manipulate Fate",
    "Marauding Knight",
    "Marauding Mako",
    "March of Souls",
    "Marhault Elsdragon",
    "Marsh Crocodile",
    "Marsh Flats",
    "Marsh Gas",
    "Marsh Goblins",
    "Marsh Viper",
    "Martyr's Cry",
    "Martyrs of Korlis",
    "Master of Death",
    "Master of the Hunt",
    "Maze of Ith",
    "Meddling Mage",
    "Meekstone",
    "Melee",
    "Melting",
    "Memory Jar",
    "Memory Lapse",
    "Mercenaries",
    "Merfolk Assassin",
    "Merfolk of the Pearl Trident",
    "Merieke Ri Berit",
    "Merseine",
    "Mesmeric Trance",
    "Metallic Rebuke",
    "Metamorphosis",
    "Metathran Aerostat",
    "Metathran Transport",
    "Meteor Crater",
    "Meteor Shower",
    "Meticulous Archive",
    "Might Weaver",
    "Mijae Djinn",
    "Millstone",
    "Mind Bomb",
    "Mind Ravel",
    "Mind Rot",
    "Mind Warp",
    "Mind Whip",
    "Mindstab Thrull",
    "Mine Collapse",
    "Minion of Leshrac",
    "Minion of Tevesh Szat",
    "Minsc & Boo, Timeless Heroes",
    "Miracle Worker",
    "Mire Kavu",
    "Mirri's Guile",
    "Mirror Universe",
    "Mirrorwood Treefolk",
    "Miscalculation",
    "Mishra's Bauble",
    "Mishra's Factory",
    "Mishra's War Machine",
    "Mishra's Workshop",
    "Mistfolk",
    "Misty Rainforest",
    "Moat",
    "Mogg Fanatic",
    "Mogg Jailer",
    "Mold Demon",
    "Mole Worms",
    "Molimo, Maro-Sorcerer",
    "Mons's Goblin Raiders",
    "Monsoon",
    "Moonshadow",
    "Moor Fiend",
    "Morale",
    "Mother of Runes",
    "Mountain",
    "Mountain Goat",
    "Mountain Stronghold",
    "Mountain Titan",
    "Mountain Yeti",
    "Mourning",
    "Mox Diamond",
    "Mox Opal",
    "Mudslide",
    "Multani's Harmony",
    "Multiversal Passage",
    "Murk Dwellers",
    "Musician",
    "Mystic Might",
    "Mystic Remora",
    "Mystical Tutor",
    "Márton Stromgald",
    "Nacre Talisman",
    "Nadu, Winged Wisdom",
    "Nafs Asp",
    "Naked Singularity",
    "Nameless Race",
    "Narset, Parter of Veils",
    "Natural Emergence",
    "Natural Order",
    "Natural Selection",
    "Nature's Lore",
    "Necrite",
    "Necromancy",
    "Necropolis",
    "Necropotence",
    "Nemata, Grove Guardian",
    "Nether Shadow",
    "Nether Void",
    "Nethergoyf",
    "Nettlecyst",
    "Nettling Imp",
    "Nevinyrral's Disk",
    "Nicol Bolas",
    "Night Soil",
    "Night's Whisper",
    "Nightmare",
    "Nightscape Battlemage",
    "Nightscape Familiar",
    "No More Lies",
    "Nomadic Elf",
    "Norritt",
    "North Star",
    "Northern Paladin",
    "Noxious Vapors",
    "Oasis",
    "Oath of Lim-Dûl",
    "Obelisk of Undoing",
    "Obliterate",
    "Obsianus Golem",
    "Obsidian Acolyte",
    "Occult Epiphany",
    "Ocelot Pride",
    "Oko, Thief of Crowns",
    "Old Man of the Sea",
    "Oliphaunt",
    "Omnath, Locus of Creation",
    "Once Upon a Time",
    "Onyx Talisman",
    "Opalescence",
    "Opt",
    "Orc General",
    "Orcish Artillery",
    "Orcish Bowmasters",
    "Orcish Cannoneers",
    "Orcish Captain",
    "Orcish Conscripts",
    "Orcish Farmer",
    "Orcish Healer",
    "Orcish Lumberjack",
    "Orcish Spy",
    "Orcish Squatters",
    "Orcish Veteran",
    "Order of Leitbur",
    "Order of the Ebon Hand",
    "Order of the Sacred Torch",
    "Order of the White Shield",
    "Ordered Migration",
    "Orgg",
    "Orim's Chant",
    "Orim's Touch",
    "Osai Vultures",
    "Otharri, Suns' Glory",
    "Oubliette",
    "Ouroboroid",
    "Overgrown Tomb",
    "Overload",
    "Palace Jailer",
    "Pale Bears",
    "Palladia-Mors",
    "Panic",
    "Parallax Tide",
    "Parallax Wave",
    "Paralyze",
    "Part Water",
    "Path to Exile",
    "Pearled Unicorn",
    "Pendelhaven",
    "Pentad Prism",
    "Pentagram of the Ages",
    "People of the Woods",
    "Personal Incarnation",
    "Pest Infestation",
    "Pestilence",
    "Pestilence Rats",
    "Petra Sphinx",
    "Phantasmal Forces",
    "Phantasmal Image",
    "Phantasmal Mount",
    "Phantasmal Terrain",
    "Phelia, Exuberant Shepherd",
    "Phlage, Titan of Fire's Fury",
    "Phyrexian Altar",
    "Phyrexian Battleflies",
    "Phyrexian Bloodstock",
    "Phyrexian Delver",
    "Phyrexian Dreadnought",
    "Phyrexian Gremlins",
    "Phyrexian Infiltrator",
    "Phyrexian Lens",
    "Phyrexian Metamorph",
    "Phyrexian Reaper",
    "Phyrexian Scuta",
    "Phyrexian Slayer",
    "Phyrexian Tyranny",
    "Piety",
    "Pincer Spider",
    "Pirate Ship",
    "Plague Rats",
    "Plague Spitter",
    "Plague Spores",
    "Plains",
    "Planar Overlay",
    "Planar Portal",
    "Planeswalker's Fury",
    "Planeswalker's Mischief",
    "Plateau",
    "Polar Kraken",
    "Pollen Remedy",
    "Polluted Delta",
    "Ponder",
    "Portable Hole",
    "Portal to Phyrexia",
    "Portent",
    "Pouncing Kavu",
    "Powder Keg",
    "Power Armor",
    "Power Artifact",
    "Power Leak",
    "Power Sink",
    "Power Surge",
    "Powerleech",
    "Pox",
    "Preacher",
    "Preordain",
    "Presence of the Master",
    "Price of Progress",
    "Priest of Yawgmoth",
    "Primal Clay",
    "Primal Growth",
    "Primordial Ooze",
    "Prismatic Vista",
    "Prismatic Ward",
    "Prison Barricade",
    "Prohibit",
    "Psionic Blast",
    "Psionic Entity",
    "Psychic Allergy",
    "Psychic Frog",
    "Psychic Venom",
    "Purelace",
    "Pygmy Allosaurus",
    "Pygmy Kavu",
    "Pyknite",
    "Pyramids",
    "Pyroblast",
    "Pyroclasm",
    "Pyrogoyf",
    "Pyrokinesis",
    "Quandrix Charm",
    "Questing Beast",
    "Questing Phelddagrif",
    "Quirion Dryad",
    "Quirion Elves",
    "Quirion Explorer",
    "Quirion Sentinel",
    "Quirion Trailblazer",
    "Rabid Wombat",
    "Radiant Kavu",
    "Raffine's Tower",
    "Rag Man",
    "Ragavan, Nimble Pilferer",
    "Rage Weaver",
    "Raging River",
    "Raiding Party",
    "Rainbow Crow",
    "Rainbow Vale",
    "Raise Dead",
    "Rakalite",
    "Rally",
    "Ramunap Excavator",
    "Rapid Fire",
    "Rasputin Dreamweaver",
    "Raucous Theater",
    "Raugrin Triome",
    "Ravenous Rats",
    "Ray of Command",
    "Ray of Erasure",
    "Razing Snidd",
    "Razorverge Thicket",
    "Reality Twist",
    "Reanimate",
    "Recall",
    "Reckless Spite",
    "Reclamation",
    "Recoil",
    "Reconstruction",
    "Recover",
    "Red Elemental Blast",
    "Red Mana Battery",
    "Red Scarab",
    "Red Ward",
    "Reflecting Mirror",
    "Regeneration",
    "Regrowth",
    "Relic of Sauron",
    "Remand",
    "Remove Enchantments",
    "Remove Soul",
    "Repentant Blacksmith",
    "Replenish",
    "Reprieve",
    "Repulse",
    "Reset",
    "Restock",
    "Restrain",
    "Resurrection",
    "Retrofitter Foundry",
    "Reverse Damage",
    "Reverse Polarity",
    "Reviving Dose",
    "Reviving Vapors",
    "Rewards of Diversity",
    "Reya Dawnbringer",
    "Righteous Avengers",
    "Rime Dryad",
    "Ring of Renewal",
    "Riptide",
    "Rith's Charm",
    "Rith's Grove",
    "Rith, the Awakener",
    "Ritual of Subdual",
    "River Delta",
    "River Merfolk",
    "Riverpyre Verge",
    "Robber of the Rich",
    "Rock Hydra",
    "Rocket Launcher",
    "Rogue Kavu",
    "Root Greevil",
    "Rooting Kavu",
    "Rout",
    "Ruby Leech",
    "Ruham Djinn",
    "Rukh Egg",
    "Runed Arch",
    "Rushing River",
    "Sabertooth Nishoba",
    "Sacred Boon",
    "Sacred Foundry",
    "Sacred Ground",
    "Sacrifice",
    "Safe Haven",
    "Samite Archer",
    "Samite Elder",
    "Samite Healer",
    "Samite Pilgrim",
    "Sand Silos",
    "Sandstorm",
    "Sandstorm Salvager",
    "Sapphire Leech",
    "Saproling Infestation",
    "Saproling Symbiosis",
    "Satya, Aetherflux Genius",
    "Satyr Wayfinder",
    "Savaen Elves",
    "Savage Offensive",
    "Savai Triome",
    "Savannah",
    "Savannah Lions",
    "Sawtooth Loon",
    "Scalding Tarn",
    "Scarecrow",
    "Scarred Puma",
    "Scarwood Bandits",
    "Scarwood Hag",
    "Scathe Zombies",
    "Scavenged Weaponry",
    "Scavenging Ghoul",
    "Scorching Lava",
    "Scrubland",
    "Scythecat Cub",
    "Sea Kings' Blessing",
    "Sea Serpent",
    "Sea Snidd",
    "Seachrome Coast",
    "Seafarer's Quay",
    "Seal of Fire",
    "Searing Rays",
    "Seasinger",
    "Season of the Witch",
    "Sedge Troll",
    "Seeker",
    "Seer's Vision",
    "Segovian Leviathan",
    "Seizures",
    "Sengir Vampire",
    "Sensei's Divining Top",
    "Sentinel of the Nameless City",
    "Seraph",
    "Serendib Djinn",
    "Serra's Sanctum",
    "Sevinne's Reclamation",
    "Shackles",
    "Shadowy Backstreet",
    "Shallow Grave",
    "Shanodin Dryads",
    "Shapeshifter",
    "Shatterstorm",
    "Shelkin Brownie",
    "Shelldock Isle",
    "Sheoldred's Edict",
    "Sheoldred, the Apocalypse",
    "Shield Wall",
    "Shield of the Ages",
    "Shifting Woodland",
    "Shimmering Wings",
    "Shivan Emissary",
    "Shivan Wurm",
    "Shivan Zombie",
    "Show and Tell",
    "Shyft",
    "Sibilant Spirit",
    "Silence",
    "Silver Drake",
    "Silverquill Charm",
    "Simoon",
    "Simulacrum",
    "Sin, Spira's Punishment",
    "Singe",
    "Singing Tree",
    "Sinister Strength",
    "Siren's Call",
    "Sisay's Ingenuity",
    "Skeleton Ship",
    "Skitter Eel",
    "Skittish Kavu",
    "Skizzik",
    "Skull of Orm",
    "Skullclamp",
    "Sky Weaver",
    "Skyclave Apparition",
    "Skyship Weatherlight",
    "Skyshroud Blessing",
    "Slay",
    "Sleeper's Robe",
    "Sleeping Potion",
    "Sleight of Mind",
    "Slimy Kavu",
    "Slinking Serpent",
    "Smoke",
    "Smoldering Tar",
    "Smuggler's Copter",
    "Snapcaster Mage",
    "Sneak Attack",
    "Snow Devil",
    "Snow Fortress",
    "Snow Hound",
    "Snow-Covered Forest",
    "Snow-Covered Island",
    "Snow-Covered Mountain",
    "Snow-Covered Plains",
    "Snow-Covered Swamp",
    "Snowblind",
    "Snowfall",
    "Snuff Out",
    "Sol'kanar the Swamp King",
    "Soldevi Golem",
    "Soldevi Machinist",
    "Soldevi Simulacrum",
    "Solitary Confinement",
    "Solitude",
    "Songs of the Damned",
    "Sorceress Queen",
    "Sorin, Lord of Innistrad",
    "Sorrow's Path",
    "Soul Barrier",
    "Soul Burn",
    "Soul Exchange",
    "Soul Kiss",
    "Soul Net",
    "Soul-Guide Lantern",
    "Spara's Headquarters",
    "Sparkcaster",
    "Sparring Golem",
    "Spectral Cloak",
    "Spectral Shield",
    "Spell Blast",
    "Spell Pierce",
    "Spellseeker",
    "Spinal Embrace",
    "Spirebluff Canal",
    "Spirit Link",
    "Spirit Shackle",
    "Spirit Shield",
    "Spirit Weaver",
    "Spiritual Sanctuary",
    "Spitting Slug",
    "Splinter Twin",
    "Spoils of Evil",
    "Spoils of War",
    "Spore Cloud",
    "Spore Flower",
    "Spreading Plague",
    "Springheart Nantuko",
    "Squee, Goblin Nabob",
    "Squirrel Nest",
    "Staff of the Ages",
    "Staff of the Storyteller",
    "Stampede",
    "Stand or Fall",
    "Standing Stones",
    "Star Compass",
    "Starting Town",
    "Stasis",
    "Steal Artifact",
    "Steam Vents",
    "Steel Leaf Paladin",
    "Stench of Evil",
    "Sterling Grove",
    "Stern Scolding",
    "Stifle",
    "Stock Up",
    "Stomping Ground",
    "Stone Giant",
    "Stone Spirit",
    "Stoneforge Mystic",
    "Stonehands",
    "Storm Seeker",
    "Stormscape Battlemage",
    "Stormscape Familiar",
    "Stormscape Master",
    "Stratadon",
    "Strength of Unity",
    "Stromgald Cabal",
    "Stun",
    "Stunted Growth",
    "Su-Chi",
    "Subtlety",
    "Sulam Djinn",
    "Sulfuric Vortex",
    "Sulfurous Springs",
    "Sunfall",
    "Sunglasses of Urza",
    "Sunken City",
    "Sunken Hope",
    "Sunscape Familiar",
    "Sunscape Master",
    "Sunstone",
    "Super Shredder",
    "Suplex",
    "Surprise Deployment",
    "Survival of the Fittest",
    "Swamp",
    "Sway of Illusion",
    "Sword of the Meek",
    "Swords to Plowshares",
    "Sylvan Caryatid",
    "Sylvan Library",
    "Sylvan Paradise",
    "Syphon Soul",
    "Tablet of Epityr",
    "Tahngarth, Talruum Hero",
    "Taiga",
    "Tainted Well",
    "Talisman of Conviction",
    "Talisman of Creativity",
    "Talisman of Curiosity",
    "Talisman of Dominance",
    "Talisman of Progress",
    "Tamiyo, Inquisitive Student",
    "Tangle",
    "Tawnos's Coffin",
    "Tawnos's Wand",
    "Tawnos's Weaponry",
    "Tear Asunder",
    "Tectonic Instability",
    "Teferi's Care",
    "Teferi's Moat",
    "Teferi, Hero of Dominaria",
    "Teferi, Time Raveler",
    "Tek",
    "Teleport",
    "Temple Garden",
    "Tendrils of Agony",
    "Terminal Moraine",
    "Territorial Kavu",
    "Terror",
    "Tetravus",
    "Thalia, Guardian of Thraben",
    "Thallid",
    "Thallid Devourer",
    "Thassa's Oracle",
    "The Abyss",
    "The Brute",
    "The Fallen",
    "The Hive",
    "The One Ring",
    "The Rack",
    "The Tabernacle at Pendrell Vale",
    "Thelon's Chant",
    "Thelon's Curse",
    "Thelonite Druid",
    "Thelonite Monk",
    "Thermokarst",
    "Thicket Basilisk",
    "Third Path Iconoclast",
    "Thopter Foundry",
    "Thorn Thallid",
    "Thornscape Battlemage",
    "Thornscape Familiar",
    "Thornscape Master",
    "Thornspire Verge",
    "Thought Monitor",
    "Thought Scour",
    "Thoughtcast",
    "Thoughtlace",
    "Thoughtleech",
    "Thoughtseize",
    "Thraben Inspector",
    "Throne of Bone",
    "Thrull Champion",
    "Thrull Retainer",
    "Thrull Wizard",
    "Thundering Falls",
    "Thunderscape Battlemage",
    "Thunderscape Familiar",
    "Thunderscape Master",
    "Thwart",
    "Tidal Flats",
    "Tidal Influence",
    "Tidal Visionary",
    "Timberline Ridge",
    "Time Bomb",
    "Time Spiral",
    "Time Vault",
    "Time Walk",
    "Time Warp",
    "Timetwister",
    "Tinder Wall",
    "Tinker",
    "Tireless Tracker",
    "Tishana's Tidebinder",
    "Titania's Song",
    "Titania, Protector of Argoth",
    "Tivadar's Crusade",
    "Tolaria",
    "Tolarian Academy",
    "Tormod's Crypt",
    "Torsten, Founder of Benalia",
    "Total War",
    "Touch of Darkness",
    "Touch of Death",
    "Touch of Vitae",
    "Tourach's Chant",
    "Tourach's Gate",
    "Tower of Coireall",
    "Toxic Deluge",
    "Tracker",
    "Trailblazer",
    "Tranquility",
    "Transmute Artifact",
    "Traumatic Critique",
    "Traveler's Cloak",
    "Treefolk Healer",
    "Treva's Charm",
    "Treva's Ruins",
    "Treva, the Renewer",
    "Tribal Flames",
    "Triskelion",
    "Troll of Khazad-dûm",
    "Tropical Island",
    "Tsabo Tavoc",
    "Tsabo's Assassin",
    "Tsabo's Web",
    "Tsunami",
    "Tundra",
    "Twiddle",
    "Twilight Diviner",
    "Twilight's Call",
    "Two-Headed Giant of Foriys",
    "Typhoon",
    "Umezawa's Jitte",
    "Uncle Istvan",
    "Undercity Sewers",
    "Underground Mortuary",
    "Underground River",
    "Underground Sea",
    "Undermine",
    "Undertow",
    "Underworld Breach",
    "Unearth",
    "Unholy Citadel",
    "Unholy Heat",
    "Unholy Strength",
    "Unstable Mutation",
    "Updraft",
    "Upheaval",
    "Urborg Drake",
    "Urborg Shambler",
    "Urborg Skeleton",
    "Urborg, Tomb of Yawgmoth",
    "Uro, Titan of Nature's Wrath",
    "Urza's Avenger",
    "Urza's Bauble",
    "Urza's Chalice",
    "Urza's Filter",
    "Urza's Guilt",
    "Urza's Mine",
    "Urza's Miter",
    "Urza's Power Plant",
    "Urza's Rage",
    "Urza's Saga",
    "Urza's Tower",
    "Urza, Lord High Artificer",
    "Utopia Tree",
    "Vaevictis Asmadi",
    "Vampiric Tutor",
    "Vaultborn Tyrant",
    "Veldt",
    "Venarian Gold",
    "Venom",
    "Venomous Breath",
    "Verdant Catacombs",
    "Verduran Emissary",
    "Verduran Enchantress",
    "Vertigo",
    "Vesuvan Doppelganger",
    "Veteran Bodyguard",
    "Vexing Arcanix",
    "Vibrance",
    "Vibrating Sphere",
    "Vicious Kavu",
    "Vicious Rivalry",
    "Vile Consumption",
    "Viridian Joiner",
    "Vision Charm",
    "Visions",
    "Vivi Ornitier",
    "Vodalian Knights",
    "Vodalian Mage",
    "Vodalian Merchant",
    "Vodalian Serpent",
    "Vodalian War Machine",
    "Vodalian Zombie",
    "Voice of All",
    "Volcanic Eruption",
    "Volcanic Island",
    "Voldaren Epicure",
    "Voracious Cobra",
    "Walking Ballista",
    "Walking Wall",
    "Wall of Brambles",
    "Wall of Caltrops",
    "Wall of Light",
    "Wall of Tombstones",
    "Wall of Vapor",
    "Wall of Wonder",
    "Wallop",
    "Wandering Stream",
    "Wanderlust",
    "Warning",
    "Warp Artifact",
    "Warped Devotion",
    "Wash Out",
    "Wastewood Verge",
    "Water Elemental",
    "Water Wurm",
    "Waterspout Elemental",
    "Watery Grave",
    "Wayfaring Giant",
    "Weakness",
    "Web",
    "Well-Laid Plans",
    "Wheel of Fortune",
    "Whip Silk",
    "Whippoorwill",
    "Whirling Dervish",
    "White Knight",
    "White Mana Battery",
    "White Scarab",
    "White Ward",
    "Whiteout",
    "Wiitigo",
    "Wild Growth",
    "Winds of Change",
    "Windswept Heath",
    "Wings of Aesthir",
    "Wings of Hope",
    "Winnow",
    "Winter Blast",
    "Winter Orb",
    "Winter's Chill",
    "Wishclaw Talisman",
    "Wistfulness",
    "Witch Hunter",
    "Witherbloom Charm",
    "Withering Wisps",
    "Wolverine Pack",
    "Wooded Foothills",
    "Wooden Sphere",
    "Woolly Mammoths",
    "Woolly Spider",
    "Word of Binding",
    "Word of Blasting",
    "Word of Command",
    "Word of Undoing",
    "Worldly Counsel",
    "Worldspine Wurm",
    "Worms of the Earth",
    "Wormwood Treefolk",
    "Wrath of God",
    "Wrath of Marit Lage",
    "Wrenn and Six",
    "Xander's Lounge",
    "Xantid Swarm",
    "Xenic Poltergeist",
    "Yavimaya Barbarian",
    "Yavimaya Kavu",
    "Yavimaya, Cradle of Growth",
    "Yawgmoth Demon",
    "Yawgmoth's Will",
    "Ydwen Efreet",
    "Zagoth Triome",
    "Zanam Djinn",
    "Zap",
    "Zelyon Sword",
    "Ziatora's Proving Ground",
    "Zombie Master",
    "Zur's Weirding",
    "Zuran Enchanter",
];
