// dsk — white cards (ADR 0043 colour split).
//
// Modern Scryfall oracle text is authoritative (ADR 0004); canonical
// name/cost/types/P-T are from Scryfall (id = DSK paper printing).

import type { CardDefinition, EffectOp } from "../../types";
import { diedTrigger } from "../../abilities/triggers/diedTrigger";
import { enteredTrigger } from "../../abilities/triggers/enteredTrigger";

// ─────────────────────────────────────────────────────────────────────────
// Enduring Innocence (issue #2084, ADR 0087) — the DSK "Enduring" cycle's
// one-shot layer-4 card-type SET.
// ─────────────────────────────────────────────────────────────────────────
//
// "When Enduring Innocence dies, if it was a creature, return it to the
//  battlefield under its owner's control. It's an enchantment. (It's not a
//  creature.)" — quoted from the Scryfall oracle (ADR 0004), which names the
//  card rather than using the "this creature" shorthand.
//
// The card is `layout: normal` on Scryfall — single-faced, nothing transforms
// (CR 712). What the trigger creates is a continuous type-changing effect
// generated by the resolution of a triggered ability (CR 611.2c), applied in
// layer 4 (CR 613.1d): a card-type SET, not a transform and not a removal.
//
// The whole body is ONE already-exercised Op (per-Op test regime, ADR
// 0045/0046) — `moveZone`'s self-reanimation shape carrying the `entersAs`
// type line (issue #2993):
//
//   `moveZone { target: { ref: "$source" }, from: "graveyard",
//    to: "battlefield", entersAs: { types: ["Enchantment"], subtypes: [] } }`
//
//   The self-reanimation half is the issue #737 Ashen Ghoul / #1469 shape: the
//   `$source` recovery re-derives the card in the graveyard the trigger fired
//   from. "Under its OWNER's control" needs NO `controller` field — `moveZone`'s
//   reanimation branch already defaults the new controller to the source pile's
//   owner (CR 400.7 / 108.3: a card is always put into ITS OWNER's graveyard, so
//   a Control-Magic'd Innocence comes back to the player who owns it, not the
//   thief who last controlled it). Naming `controller: "controller"` here would
//   be the BUG — the trigger is controlled by the last controller (CR 603.6d),
//   which is exactly the player the Oracle text declines to give it to.
//
//   `entersAs.types: ["Enchantment"]` — CR 205.1a, "the new card type(s)
//   replaces any existing card types". A SET, never a `remove: ["Creature"]`:
//   the Gatherer ruling for a nontoken COPY of Enduring Innocence is explicit —
//   "It won't have any card types other than enchantment" — so a copy carrying
//   extra printed types loses those too. Encoding this card's own printed type
//   line into the effect would also be the card-shaped-primitive mistake
//   (ADR 0102).
//
//   `entersAs.subtypes: []` — CR 205.1a's correlated-subtype clause: "If an
//   object's card type is removed, the subtypes correlated with that card type
//   will remain if they are also the subtypes of a card type the object
//   currently has; otherwise, they are also removed." Sheep and Glimmer are
//   creature types only and Enchantment claims neither, so both leave — the
//   Gatherer ruling says exactly that ("Enduring Innocence won't have those
//   creature types … because it won't be a creature"). Stated by the author,
//   not derived: the engine has no subtype → card-type classifier (ADR 0087
//   § Amendment), which is why the field is REQUIRED rather than optional.
//
// IT ENTERS AS AN ENCHANTMENT — it does not enter and then stop being a
// creature (issue #2993). The type line is applied inside the entry funnel,
// after the CR 400.7 entry-side reset and before `emitPermanentEntered`, so the
// PERMANENT_ENTERED event announces `types: ["Enchantment"]` with no `power`.
// The shipped composition — `moveZone` then `setCardTypes` then `setSubtype` —
// could not: the entry-side reset (`resetBattlefieldTransientState` →
// `revertTypeLine`) wipes a line set BEFORE the move, and a line set AFTER it
// arrives too late for the entry event, so this card's own sibling ("whenever
// one or more OTHER creatures you control with power 2 or less enter") drew a
// card off a permanent that is not a creature (CR 603.6a).
//
// LOOP SAFETY. Once back as an enchantment it is not a creature, so it cannot
// die AS a creature: `CREATURE_DIED` is only emitted for a permanent that
// `wasCreature` (gre/state.ts), and the intervening-if would fail regardless
// (CR 603.4 — checked at trigger AND again at resolution). The cycle
// terminates after exactly one return. Covered by a test.
const enduringInnocenceReturnAsEnchantment: EffectOp[] = [
    {
        op: "moveZone",
        target: { ref: "$source" },
        from: "graveyard",
        to: "battlefield",
        entersAs: { types: ["Enchantment"], subtypes: [] },
    },
];

export const enduringInnocence: CardDefinition = {
    id: "08f79439-b8f8-418f-9772-26d81844749e",
    name: "Enduring Innocence",
    rarity: "rare",
    manaCost: { X: 1, W: 2 },
    types: ["Enchantment", "Creature"],
    subtypes: ["Sheep", "Glimmer"],
    power: 2,
    toughness: 1,
    oracleText:
        "Lifelink\nWhenever one or more other creatures you control with power 2 or less enter, draw a card. This ability triggers only once each turn.\nWhen Enduring Innocence dies, if it was a creature, return it to the battlefield under its owner's control. It's an enchantment. (It's not a creature.)",
    staticAbilities: ["lifelink"],
    triggeredAbilities: [
        // CR 603.3b — "whenever ONE OR MORE other creatures … enter" collapses
        // a simultaneous batch of entries to a single trigger
        // (`oncePerEventBatch`), and CR 603.2's per-turn TRIGGER cap
        // ("only once each turn") is `maxTriggersPerTurn: 1` — a cap on
        // TRIGGERING, so past it no stack item is created at all.
        // "with power 2 or less" is read off the entering permanent's
        // EFFECTIVE power snapshotted on the event (CR 613.4), so a creature
        // entering under an anthem or with +1/+1 counters is measured with
        // continuous effects applied.
        enteredTrigger({
            id: "enduring-innocence-draw",
            oracleText:
                "Whenever one or more other creatures you control with power 2 or less enter, draw a card. This ability triggers only once each turn.",
            scope: "another-yours",
            filter: { types: ["Creature"], powerAtMost: 2 },
            oncePerEventBatch: true,
            maxTriggersPerTurn: 1,
            effects: [{ op: "draw", player: "controller", count: 1 }],
        }),
        // CR 700.4 / 603.4 — "if it WAS a creature" is an intervening-if read
        // off the death event's CR 603.10 last-known-information type line,
        // not off the card in the graveyard: the object that died is gone, and
        // re-reading the graveyard card would answer with its PRINTED types.
        // Re-checked at resolution (CR 603.4); the event snapshot is immutable,
        // so a trigger that fired legally never fizzles here.
        diedTrigger({
            id: "enduring-innocence-return",
            oracleText:
                "When Enduring Innocence dies, if it was a creature, return it to the battlefield under its owner's control. It's an enchantment. (It's not a creature.)",
            scope: "self",
            interveningIf: (event) => event.creatureTypes.includes("Creature"),
            effects: enduringInnocenceReturnAsEnchantment,
        }),
    ],
};
