// ELD — multicolor cards, split by colour per ADR 0043. The registry's
// `import * as eld from "./sets/eld"` resolves through eld/index.ts.
// Cards are classified by the colour identity of their mana cost (CR 202.2):
// lands and colourless artifacts (no coloured cost) live in colorless.ts.

import type { CardDefinition } from "../../types";
import { FOOD_TOKEN } from "../../sharedTokens";

// Oko, Thief of Crowns — {1}{G}{U} Legendary Planeswalker — Oko, loyalty 4
// (issue #2361, ADR 0058 loyalty framework; the loyalty cost system itself is
// a cost-system capability, not an Effect Op — see mechanicsRegistry.ts).
//
//   • +2 — "Create a Food token." CR 111.10b defines the Food token exactly
//     (a colorless Food artifact token with "{2}, {T}, Sacrifice this token:
//     You gain 3 life."), so this is the shared `FOOD_TOKEN` spec through the
//     ordinary `createToken` Op — no Food-specific verb.
//
//   • +1 — "Target artifact or creature loses all abilities and becomes a
//     green Elk creature with base power and toughness 3/3." One Oracle
//     sentence, FIVE continuous effects, each applied in its own CR 613 layer,
//     all INDEFINITE (CR 611.2c — generated by a resolving ability, so they
//     survive Oko leaving; printed ruling: "The effects of Oko's second
//     ability lasts indefinitely"). The Op list below IS that decomposition,
//     in layer order:
//       layer 4  `setCardTypes ["Creature"]`  — CR 205.1a, the new card types
//                REPLACE the old ones, so an artifact target stops being an
//                artifact ("loses any other card types it has (such as
//                artifact)"). SUPERTYPES survive (a legendary target stays
//                legendary) because they live on their own field.
//       layer 4  `setSubtype ["Elk"]`         — CR 205.1a's subtype-set arm;
//                the non-land primitive replaces the subtype line wholesale,
//                which is also what removes an artifact type left correlated
//                to the card type just dropped ("It's just a green Elk").
//       layer 5  `setColor ["G"]`             — CR 613.1e, replaces every
//                colour the permanent had.
//       layer 6  `loseAllAbilities`           — CR 613.1f. Written FIRST in
//                the list only because that is the order the Oracle sentence
//                reads; the Ops are independent per-layer writes, not a
//                pipeline, so their relative order in `effects[]` is not
//                load-bearing.
//       layer 7b `setBasePT 3/3`              — CR 613.4b BASE P/T, so a
//                +1/+1 counter (7c) and any pump (7d) still apply ON TOP, and
//                a LATER base-P/T set overwrites this one — both printed
//                rulings.
//     Four of the five Ops were already shipped; only the layer-4 card-type
//     SET and the layer-6 ability strip were missing verbs, and both went
//     through the full seven-site Op path rather than a card-shaped closure
//     (primitive-reuse mandate).
//
//   • −5 — "Exchange control of target artifact or creature you control and
//     target creature an opponent controls with power 3 or less."
//     CR 701.12b: when control of two permanents is exchanged, each player
//     simultaneously gains control of the other's; if BOTH are controlled by
//     the same player the exchange does nothing. Decomposed as TWO shipped
//     `gainControl` Ops (the Phyrexian Infiltrator pattern, `sets/inv/black.ts`
//     — no `exchange` Op, primitive-reuse mandate). `ctx.controller` is
//     captured once per resolution (CR 608.2b) and stays fixed across both
//     Ops, so the order is load-bearing:
//       1. target 0 (yours) -> whoever CURRENTLY controls target 1, read live
//          via `{ controllerOf: { target: 1 } }` BEFORE either mutation lands;
//       2. target 1 (theirs) -> the resolving controller.
//     The same-controller no-op of CR 701.12b falls out for free: if both
//     targets are already yours, step 1 reassigns target 0 to you and step 2
//     reassigns target 1 to you — two writes of the controller each permanent
//     already had. The two target slots are INDEPENDENT groups
//     (`additionalTargetRequirements`, issue #2361): "you control" /
//     "an opponent controls with power 3 or less" are ANNOUNCE-time target
//     restrictions (CR 602.2b), so the power ≤ 3 filter is enforced when the
//     ability is activated and never re-checked at resolution — the printed
//     ruling: "It doesn't expire ... if the creature you take has its power
//     raised above 3 later."
export const oko: CardDefinition = {
    id: "3462a3d0-5552-49fa-9eb7-100960c55891", // ELD 197 (scryfallId)
    name: "Oko, Thief of Crowns",
    rarity: "mythic",
    manaCost: { generic: 1, G: 1, U: 1 },
    types: ["Planeswalker"],
    subtypes: ["Oko"],
    supertypes: ["Legendary"],
    loyalty: 4,
    oracleText:
        "+2: Create a Food token.\n+1: Target artifact or creature loses all abilities and becomes a green Elk creature with base power and toughness 3/3.\n−5: Exchange control of target artifact or creature you control and target creature an opponent controls with power 3 or less.",
    activatedAbilities: [
        {
            id: "oko-thief-of-crowns-plus2",
            // CR 606.2 / 606.4 — loyalty ability; `+2` adds two counters.
            cost: { loyalty: 2 },
            useStack: true,
            oracleText: "+2: Create a Food token.",
            // CR 111.10b — the predefined Food token, one shared spec.
            effects: [
                {
                    op: "createToken",
                    token: FOOD_TOKEN,
                    controller: "controller",
                },
            ],
        },
        {
            id: "oko-thief-of-crowns-plus1",
            // CR 606.2 / 606.4 — `+1` adds one counter.
            cost: { loyalty: 1 },
            useStack: true,
            oracleText:
                "+1: Target artifact or creature loses all abilities and becomes a green Elk creature with base power and toughness 3/3.",
            // CR 601.2c — one target that is EITHER an artifact OR a creature
            // (an artifact creature qualifies under both halves and is one
            // legal target, not two).
            targetRequirement: { type: ["Artifact", "Creature"], count: 1 },
            effects: [
                // CR 613.1f layer 6.
                { op: "loseAllAbilities", target: { target: 0 } },
                // CR 205.1a layer 4 — card types REPLACED (loses Artifact).
                {
                    op: "setCardTypes",
                    target: { target: 0 },
                    types: ["Creature"],
                },
                // CR 205.1a layer 4 — subtype line REPLACED ("It's just a
                // green Elk"). No `duration` = indefinite (CR 611.2b).
                {
                    op: "setSubtype",
                    target: { target: 0 },
                    subtypes: ["Elk"],
                },
                // CR 613.1e layer 5 — replaces every colour it had.
                { op: "setColor", target: { target: 0 }, colors: ["G"] },
                // CR 613.4b layer 7b — BASE P/T, so counters/pumps stack on
                // top. No `duration` = indefinite.
                {
                    op: "setBasePT",
                    target: { target: 0 },
                    power: 3,
                    toughness: 3,
                },
            ],
        },
        {
            id: "oko-thief-of-crowns-minus5",
            // CR 606.2 / 606.4 — `-5` removes five counters.
            cost: { loyalty: -5 },
            useStack: true,
            oracleText:
                "−5: Exchange control of target artifact or creature you control and target creature an opponent controls with power 3 or less.",
            // Group 0 — "target artifact or creature you control".
            targetRequirement: {
                type: ["Artifact", "Creature"],
                count: 1,
                controller: "you",
            },
            // Group 1 — "target creature an opponent controls with power 3 or
            // less" (CR 613 layer 7c effective power, read at announcement).
            additionalTargetRequirements: [
                {
                    type: "Creature",
                    count: 1,
                    controller: "opponent",
                    powerFilter: { max: 3 },
                },
            ],
            // CR 613.1b — indefinite layer-2 control changes (no `duration`).
            effects: [
                {
                    op: "gainControl",
                    target: { target: 0 },
                    controller: { controllerOf: { target: 1 } },
                },
                {
                    op: "gainControl",
                    target: { target: 1 },
                    controller: "controller",
                },
            ],
        },
    ],
};
