// Per-card behavior tests for white cards in `convex/cards/sets/dsk/white.ts`
// (Duskmourn: House of Horror, split by colour per ADR 0043). Fixtures from
// convex/cards/__tests__/setup.ts.
//
// Enduring Innocence (issue #2084, ADR 0087) is the DSK "Enduring" cycle's
// tracer for a ONE-SHOT LAYER-4 CARD-TYPE SET (CR 205.1a / 613.1d) generated by
// the resolution of a triggered ability (CR 611.2c). Nothing transforms: the
// card is `layout: normal` on Scryfall (CR 712 is not involved).
//
// Its body introduces no new Op — it composes `moveZone` / `setCardTypes` /
// `setSubtype`, all already exercised — so under the per-Op test regime
// (ADR 0045/0046) what earns tests here is what is NOT covered by the static
// sweep: the CR 205.1a subtype fallout, the "under its OWNER's control"
// clause, the CR 400.7 re-entry reset on the real bounce path, the CR 603.2
// per-turn trigger cap and the loop-safety argument.

import { describe, it, expect } from "vitest";
import { enduringInnocence } from "..";
import { grizzlyBears } from "../../lea/green";
import { serraAngel } from "../../lea/white";
import {
    makeInstance,
    makePlayer,
    makeState,
    resolveTriggerOrder,
} from "../../../__tests__/setup";
import {
    removePermanentTo,
    resolveTopOfStack,
    processPendingActionTriggers,
    flushPendingEvents,
    putReanimatedSetOnBattlefield,
} from "../../../../gre/state";
import { projectPublicState } from "../../../../gameProjections";
import { withTemporaryDefinition } from "../../../registry";
import type { CardInstanceState, GameState } from "../../../../gre/state";
import type { CardDefinition, TriggeredAbility } from "../../../types";

/** Board with Enduring Innocence on `controllerId`'s battlefield, owned by
 *  `ownerId` (they differ only in the Control-Magic case). */
function boardWith(overrides: Partial<CardInstanceState> = {}): {
    state: GameState;
    innocence: CardInstanceState;
} {
    const innocence = makeInstance(enduringInnocence.id, {
        id: "innocence",
        controllerId: "p1",
        ownerId: "p1",
        ...overrides,
    });
    const controllerId = innocence.controllerId;
    const state = makeState({
        players: [
            makePlayer("p1", {
                battlefield: controllerId === "p1" ? [innocence] : [],
            }),
            makePlayer("p2", {
                battlefield: controllerId === "p2" ? [innocence] : [],
            }),
        ],
    });
    return { state, innocence };
}

/** Kills the permanent through the real production departure funnel and runs
 *  the resulting death trigger to resolution. */
function killAndResolve(state: GameState, id: string): void {
    removePermanentTo(state, id, "graveyard", "destroy");
    processPendingActionTriggers(state);
    resolveTriggerOrder(state);
    while (state.stack.length > 0) {
        resolveTopOfStack(state);
    }
}

function findOnBattlefield(
    state: GameState,
    id: string
): CardInstanceState | undefined {
    for (const p of state.players) {
        const found = p.battlefield.find((c) => c.id === id);
        if (found) return found;
    }
    return undefined;
}

describe("Enduring Innocence — dies trigger returns it as an enchantment (CR 205.1a / 613.1d, issue #2084)", () => {
    it("returns to the battlefield with card types SET to Enchantment only (CR 205.1a — the new type replaces every existing one)", () => {
        const { state } = boardWith();

        killAndResolve(state, "innocence");

        const back = findOnBattlefield(state, "innocence");
        expect(back).toBeDefined();
        // CR 205.1a — a SET, not a `remove: ["Creature"]`. The Gatherer ruling
        // for a nontoken copy is explicit: "It won't have any card types other
        // than enchantment."
        expect(back!.types).toEqual(["Enchantment"]);
        expect(back!.types).not.toContain("Creature");
        // It is out of the graveyard: the return actually happened.
        expect(
            state.players[0].graveyard.some((c) => c.id === "innocence")
        ).toBe(false);
    });

    it("drops Sheep and Glimmer — CR 205.1a correlated subtypes leave with the removed card type", () => {
        const { state } = boardWith();
        // Printed line, before it dies.
        expect(state.players[0].battlefield[0].subtypes).toEqual([
            "Sheep",
            "Glimmer",
        ]);

        killAndResolve(state, "innocence");

        // Gatherer: "Sheep and Glimmer are both creature types. Enduring
        // Innocence won't have those creature types when its last ability
        // returns it to the battlefield because it won't be a creature."
        // Enchantment claims neither, so both are removed (CR 205.1a).
        expect(findOnBattlefield(state, "innocence")!.subtypes).toEqual([]);
    });

    it("returns under its OWNER's control, not the thief's (CR 108.3 / 400.7)", () => {
        // Control Magic'd: p2 controls it, p1 owns it. CR 400.7 puts the card
        // into ITS OWNER's graveyard; the leaves-the-battlefield trigger is
        // controlled by the last controller (p2), and the Oracle text
        // deliberately hands the returning permanent to the OWNER anyway.
        const { state } = boardWith({ controllerId: "p2", ownerId: "p1" });

        killAndResolve(state, "innocence");

        expect(
            state.players[1].battlefield.some((c) => c.id === "innocence")
        ).toBe(false);
        const back = state.players[0].battlefield.find(
            (c) => c.id === "innocence"
        );
        expect(back).toBeDefined();
        expect(back!.controllerId).toBe("p1");
        expect(back!.types).toEqual(["Enchantment"]);
    });

    it("does not loop: back as an enchantment it cannot die as a creature (CR 700.4 / 603.4)", () => {
        const { state } = boardWith();
        killAndResolve(state, "innocence");
        expect(findOnBattlefield(state, "innocence")!.types).toEqual([
            "Enchantment",
        ]);
        flushPendingEvents(state);

        // Kill the enchantment. CREATURE_DIED is only emitted for a permanent
        // that was a creature, and the intervening-if ("if it was a creature")
        // reads the death event's CR 603.10 type line — both gates close.
        removePermanentTo(state, "innocence", "graveyard", "destroy");
        processPendingActionTriggers(state);
        resolveTriggerOrder(state);

        const events = flushPendingEvents(state);
        expect(
            events.some(
                (e) =>
                    e.type === "CREATURE_DIED" &&
                    e.creatureInstanceId === "innocence"
            )
        ).toBe(false);
        expect(state.stack).toHaveLength(0);
        // It stays in the graveyard — exactly one return, then it is done.
        expect(
            state.players[0].graveyard.some((c) => c.id === "innocence")
        ).toBe(true);
        expect(findOnBattlefield(state, "innocence")).toBeUndefined();
    });

    it("CR 400.7 — bounced to hand and put back, it is a 2/1 Sheep Glimmer creature again", () => {
        const { state } = boardWith();
        killAndResolve(state, "innocence");
        expect(findOnBattlefield(state, "innocence")!.types).toEqual([
            "Enchantment",
        ]);

        // The real bounce path: the same departure funnel every "return target
        // permanent to its owner's hand" spell calls, which is what runs
        // `resetBattlefieldTransientState` (and through it
        // `revertTypeProvenance` + the `indefiniteSubtypeSet` restore).
        removePermanentTo(state, "innocence", "hand");
        const inHand = state.players[0].hand.find((c) => c.id === "innocence");
        expect(inHand).toBeDefined();
        expect(inHand!.types).toEqual(["Enchantment", "Creature"]);
        expect(inHand!.subtypes).toEqual(["Sheep", "Glimmer"]);

        // …and it re-enters as the printed card, not a permanently blanked
        // enchantment (the issue #1746 bug class).
        putReanimatedSetOnBattlefield(state, [
            { card: inHand!, controllerId: "p1" },
        ]);
        const back = findOnBattlefield(state, "innocence")!;
        expect(back.types).toEqual(["Enchantment", "Creature"]);
        expect(back.subtypes).toEqual(["Sheep", "Glimmer"]);
        expect(back.power).toBe(2);
        expect(back.toughness).toBe(1);
    });

    it("wire format: the projection reports the returned permanent as a subtype-less enchantment", () => {
        const { state } = boardWith();
        killAndResolve(state, "innocence");

        // SURFACE (per `.claude/rules/gre-development.md`) — the client sees
        // only the projection, so a GRE-only assertion would pass while the
        // board still drew a 2/1 Sheep.
        const view = projectPublicState(state, 1, "p1");
        const seat = view.players.find((p) => p.id === "p1")!;
        const card = seat.battlefield.find((c) => c.id === "innocence");
        expect(card).toBeDefined();
        expect(card!.types).toEqual(["Enchantment"]);
        expect(card!.subtypes).toEqual([]);
    });
});

describe("Enduring Innocence — the once-each-turn draw trigger (CR 603.2 / 603.3b)", () => {
    /** Puts `cards` onto p1's battlefield through the real entry funnel and
     *  runs whatever triggered off the batch. */
    function enterAndResolve(
        state: GameState,
        cards: CardInstanceState[]
    ): void {
        putReanimatedSetOnBattlefield(
            state,
            cards.map((card) => ({ card, controllerId: "p1" }))
        );
        processPendingActionTriggers(state);
        resolveTriggerOrder(state);
        while (state.stack.length > 0) {
            resolveTopOfStack(state);
        }
    }

    function stateWithLibrary(n: number): {
        state: GameState;
        innocence: CardInstanceState;
    } {
        const innocence = makeInstance(enduringInnocence.id, {
            id: "innocence",
            controllerId: "p1",
            ownerId: "p1",
        });
        const library = Array.from({ length: n }, (_, i) =>
            makeInstance(grizzlyBears.id, {
                id: `lib${i}`,
                controllerId: "p1",
                ownerId: "p1",
                zone: "library",
            })
        );
        const state = makeState({
            players: [
                makePlayer("p1", { battlefield: [innocence], library }),
                makePlayer("p2"),
            ],
        });
        return { state, innocence };
    }

    it("draws one card when another creature you control with power 2 or less enters", () => {
        const { state } = stateWithLibrary(4);
        const bear = makeInstance(grizzlyBears.id, {
            id: "bear",
            controllerId: "p1",
            ownerId: "p1",
            zone: "graveyard",
        });

        enterAndResolve(state, [bear]);

        expect(state.players[0].hand).toHaveLength(1);
    });

    it("CR 603.3b — one or more entering at once collapses to a SINGLE trigger, so one card", () => {
        const { state } = stateWithLibrary(4);
        const bears = [0, 1, 2].map((i) =>
            makeInstance(grizzlyBears.id, {
                id: `bear${i}`,
                controllerId: "p1",
                ownerId: "p1",
                zone: "graveyard",
            })
        );

        enterAndResolve(state, bears);

        // "Whenever ONE OR MORE … enter" — not one draw per entering creature.
        expect(state.players[0].hand).toHaveLength(1);
    });

    // The assertion above cannot tell WHICH clause produced the single draw:
    // `maxTriggersPerTurn: 1` alone caps a three-creature batch to one trigger
    // too, so deleting `oncePerEventBatch` from the card leaves it green. The
    // two clauses are independent CR rules on independent Oracle sentences, so
    // the batch half is proven here where the cap cannot mask it — a variant
    // definition (`withTemporaryDefinition`, the catalogue is frozen) carrying
    // the same ability with NO per-turn cap.
    function innocenceWithoutCap(oncePerEventBatch: boolean): CardDefinition {
        const draw = enduringInnocence.triggeredAbilities!.find(
            (t) => t.id === "enduring-innocence-draw"
        )!;
        const uncapped: TriggeredAbility = { ...draw };
        delete uncapped.maxTriggersPerTurn;
        if (!oncePerEventBatch) delete uncapped.oncePerEventBatch;
        return {
            ...enduringInnocence,
            triggeredAbilities: [uncapped],
        };
    }

    it("CR 603.3b — the batch collapse is load-bearing on its own: three simultaneous entries draw ONE card with it, THREE without", () => {
        const withBatch = withTemporaryDefinition(
            innocenceWithoutCap(true),
            () => {
                const { state } = stateWithLibrary(6);
                enterAndResolve(
                    state,
                    [0, 1, 2].map((i) =>
                        makeInstance(grizzlyBears.id, {
                            id: `bear${i}`,
                            controllerId: "p1",
                            ownerId: "p1",
                            zone: "graveyard",
                        })
                    )
                );
                return state.players[0].hand.length;
            }
        );
        const withoutBatch = withTemporaryDefinition(
            innocenceWithoutCap(false),
            () => {
                const { state } = stateWithLibrary(6);
                enterAndResolve(
                    state,
                    [0, 1, 2].map((i) =>
                        makeInstance(grizzlyBears.id, {
                            id: `bear${i}`,
                            controllerId: "p1",
                            ownerId: "p1",
                            zone: "graveyard",
                        })
                    )
                );
                return state.players[0].hand.length;
            }
        );

        expect(withBatch).toBe(1);
        // Without the clause the same batch triggers once PER entering
        // creature (CR 603.2, the Soul Warden shape) — the difference the
        // shipped card's per-turn cap would otherwise hide.
        expect(withoutBatch).toBe(3);
    });

    it("CR 603.2 — the per-turn cap means a SECOND, separate batch this turn draws nothing", () => {
        const { state } = stateWithLibrary(4);
        const first = makeInstance(grizzlyBears.id, {
            id: "bearA",
            controllerId: "p1",
            ownerId: "p1",
            zone: "graveyard",
        });
        const second = makeInstance(grizzlyBears.id, {
            id: "bearB",
            controllerId: "p1",
            ownerId: "p1",
            zone: "graveyard",
        });

        enterAndResolve(state, [first]);
        expect(state.players[0].hand).toHaveLength(1);

        // "This ability triggers only once each turn" — past the cap no stack
        // item is created at all.
        enterAndResolve(state, [second]);
        expect(state.players[0].hand).toHaveLength(1);
    });

    it("power 3 or more does not trigger it (the CR 613.4 effective-power read)", () => {
        const { state } = stateWithLibrary(4);
        // Serra Angel is a 4/4 — above the "power 2 or less" bound.
        const angel = makeInstance(serraAngel.id, {
            id: "angel",
            controllerId: "p1",
            ownerId: "p1",
            zone: "graveyard",
        });

        enterAndResolve(state, [angel]);

        expect(state.players[0].hand).toHaveLength(0);
    });

    it("does not fire on ITS OWN entry — the trigger says OTHER creatures (CR 109.2)", () => {
        const library = Array.from({ length: 4 }, (_, i) =>
            makeInstance(grizzlyBears.id, {
                id: `lib${i}`,
                controllerId: "p1",
                ownerId: "p1",
                zone: "library",
            })
        );
        const innocence = makeInstance(enduringInnocence.id, {
            id: "innocence",
            controllerId: "p1",
            ownerId: "p1",
            zone: "graveyard",
        });
        const state = makeState({
            players: [makePlayer("p1", { library }), makePlayer("p2")],
        });

        enterAndResolve(state, [innocence]);

        expect(state.players[0].hand).toHaveLength(0);
    });

    it("does not fire on an OPPONENT's small creature (CR 109.2 — creatures YOU control)", () => {
        const { state } = stateWithLibrary(4);
        const bear = makeInstance(grizzlyBears.id, {
            id: "oppBear",
            controllerId: "p2",
            ownerId: "p2",
            zone: "graveyard",
        });

        putReanimatedSetOnBattlefield(state, [
            { card: bear, controllerId: "p2" },
        ]);
        processPendingActionTriggers(state);
        resolveTriggerOrder(state);
        while (state.stack.length > 0) resolveTopOfStack(state);

        expect(state.players[0].hand).toHaveLength(0);
    });
});
