// Bestow (CR 702.103) — the LAYER-4 half of the keyword, expanded implicitly
// from `CardDefinition.bestow` at the `getDefinition` seam (ADR 0054, the
// `expandHideaway` / `expandFadingVanishing` / `expandAnnihilator` chain).
//
// CR 702.103b: "As a spell cast bestowed is put onto the stack, it becomes an
//   Aura enchantment and gains enchant creature. It is a bestowed Aura spell,
//   and the permanent it becomes as it resolves will be a bestowed Aura. These
//   effects last until the spell or the permanent it becomes ceases to be
//   bestowed."
//
// WHY A CONTINUOUS EFFECT AND NOT A STORED REWRITE (ADR 0084). That type change
// is a continuous effect generated by an ABILITY, which CR 613.1d puts in layer
// 4 and CR 613.1 requires be recomputed at every read — it is NOT a change to
// the object's copiable values, so face-down (ADR 0013) and transform
// (ADR 0067), which do mutate stored characteristics, are not precedents for
// it. Declaring it here rather than stamping `types` at the cast commit is what
// makes "ceases to be bestowed" (CR 702.103e/f/g) fall out of the effect no
// longer applying, instead of needing a restore-from-definition routine that
// can drift from the printed card.
//
// The effect is SELF-APPLYING — a bestowed object generates it on itself — so
// it is the first layer-2-to-5 entry whose source can be an object ON THE
// STACK. `gre/layers2to5.ts` derives stack objects for exactly this reason (CR
// 613.1 governs objects, not only permanents): a bestowed spell has to read as
// an Aura spell while it is still on the stack, which is what makes it illegal
// for "target creature spell" and invisible to "whenever you cast a creature
// spell".
//
// Expanding from the `bestow` field rather than letting each card declare the
// two entries by hand is the Guard A inertness shape: the keyword can never be
// printed with nothing enforcing it, and its rules text lives in one place.

import type { CardDefinition, PermanentView, StaticEffect } from "../types";

/** CR 702.103b — the effect applies to the bestowed object ITSELF and to
 *  nothing else, for exactly as long as it is bestowed.
 *
 *  `bestowed` is `CardInstanceState.bestowed`, read LIVE off the source view:
 *  every boundary at which the object ceases to be bestowed (CR 702.103e — an
 *  illegal target on resolution; 702.103f — becoming unattached; CR 400.7 — any
 *  zone change) clears that one flag, and the type line comes back on the next
 *  derivation with nothing else to undo. */
const appliesToBestowedSelf = (
    target: PermanentView,
    source: PermanentView
): boolean =>
    target.id === source.id &&
    (source as { bestowed?: boolean }).bestowed === true;

/** CR 702.103b / 205.1a / 613.1d — the two layer-4 entries a bestowed object
 *  generates on itself.
 *
 *  CR 205.1a governs the shape: "the new card type(s) replaces any existing
 *  card types … when an effect sets one or more of an object's subtypes, the
 *  new subtype(s) replaces any existing subtypes from the appropriate set." A
 *  bestowed Springheart Nantuko is therefore an `Enchantment — Aura`, not an
 *  `Enchantment Creature — Insect Monk Aura`.
 *
 *  Expressed as REMOVE-Creature rather than SET-to-Enchantment because every
 *  printed bestow card is an Enchantment Creature (CR 702.103b's "it becomes an
 *  Aura enchantment" has nothing to add to a card that is already an
 *  enchantment), and because layer 4's static-effect vocabulary has a type
 *  removal — the one the reconfigure cards already use (`neo/white.ts`) — while
 *  a wholesale type SET is a resolved-spell ledger (`typeLineHolds`), not a
 *  static ability's to declare. */
export const BESTOW_STATIC_EFFECTS: readonly StaticEffect[] = [
    {
        kind: "type-remove",
        types: ["Creature"],
        applies: appliesToBestowedSelf,
    },
    { kind: "subtype-set", subtypes: ["Aura"], applies: appliesToBestowedSelf },
];

/** The `StaticEffect.kind`s {@link BESTOW_STATIC_EFFECTS} injects. Read by
 *  `cards/registry.ts`'s layer precheck, which indexes the RAW definition —
 *  i.e. BEFORE this expansion runs — and would otherwise answer a stale FALSE
 *  for every bestow card and drop it from the layer-4 walk entirely. Same
 *  hazard, same shape, as `compiledStaticEffects`. */
export const BESTOW_STATIC_EFFECT_KINDS: readonly string[] =
    BESTOW_STATIC_EFFECTS.map((e) => e.kind);

/** ADR 0054 — a no-op unless the card declares a bestow cost. Appends rather
 *  than replaces: a bestow card may declare static effects of its own
 *  (Springheart Nantuko's "enchanted creature gets +1/+1" is a layer-7
 *  `pt-buff`), and CR 613.7a gives every effect from the same object the same
 *  timestamp, so the two orders are indistinguishable. */
export function expandBestow(def: CardDefinition): CardDefinition {
    if (!def.bestow) return def;
    return {
        ...def,
        staticEffects: [...(def.staticEffects ?? []), ...BESTOW_STATIC_EFFECTS],
    };
}
