// `enduringReturnTrigger` — the DSK "Enduring" cycle's shared dies-trigger
// (issue #2084 shipped the shape on Enduring Innocence; issue #2085 extracts
// it here for the remaining four, per the extract-on-the-second rule).
//
// Every card in the cycle ends with the SAME clause, differing only in the
// card name the modern Scryfall oracle spells out (ADR 0004 — the oracle names
// the card rather than using the "this creature" shorthand):
//
//   "When <name> dies, if it was a creature, return it to the battlefield
//    under its owner's control. It's an enchantment. (It's not a creature.)"
//
// The rules derivation lives here once instead of five times over. What the
// trigger creates is a continuous type-changing effect generated by the
// resolution of a triggered ability (CR 611.2c), applied in layer 4
// (CR 613.1d): a card-type SET, not a transform and not a removal. Each card
// is `layout: normal` on Scryfall — single-faced, nothing transforms (CR 712).
//
// The whole body is ONE already-exercised Op (per-Op test regime, ADR
// 0045/0046) — `moveZone`'s self-reanimation shape carrying the `entersAs`
// type line (issue #2993):
//
//   The self-reanimation half is the issue #737 Ashen Ghoul / #1469 shape: the
//   `$source` recovery re-derives the card in the graveyard the trigger fired
//   from. "Under its OWNER's control" needs NO `controller` field — `moveZone`'s
//   reanimation branch already defaults the new controller to the source pile's
//   owner (CR 400.7 / 108.3: a card is always put into ITS OWNER's graveyard, so
//   a Control-Magic'd Glimmer comes back to the player who owns it, not the
//   thief who last controlled it). Naming `controller: "controller"` here would
//   be the BUG — the trigger is controlled by the last controller (CR 603.6d),
//   which is exactly the player the Oracle text declines to give it to.
//
//   `entersAs.types: ["Enchantment"]` — CR 205.1a, "the new card type(s)
//   replaces any existing card types". A SET, never a `remove: ["Creature"]`:
//   the Gatherer ruling for a nontoken COPY of an Enduring card is explicit —
//   "It won't have any card types other than enchantment" — so a copy carrying
//   extra printed types loses those too. Encoding a card's own printed type
//   line into the effect would also be the card-shaped-primitive mistake
//   (ADR 0102), which is precisely why this factory takes no type argument.
//
//   `entersAs.subtypes: []` — CR 205.1a's correlated-subtype clause: "If an
//   object's card type is removed, the subtypes correlated with that card type
//   will remain if they are also the subtypes of a card type the object
//   currently has; otherwise, they are also removed." Every printed subtype in
//   the cycle (Sheep, Cat, Snake, Dog, Elk — and Glimmer itself) is a creature
//   type only, and Enchantment claims none of them, so all of them leave.
//   Stated by the author, not derived: the engine has no subtype → card-type
//   classifier (ADR 0087 § Amendment), which is why the field is REQUIRED
//   rather than optional.
//
// IT ENTERS AS AN ENCHANTMENT — it does not enter and then stop being a
// creature (issue #2993). The type line is applied inside the entry funnel,
// after the CR 400.7 entry-side reset and before `emitPermanentEntered`, so the
// PERMANENT_ENTERED event announces `types: ["Enchantment"]` with no `power`.
// The shipped composition — `moveZone` then `setCardTypes` then `setSubtype` —
// could not: the entry-side reset (`resetBattlefieldTransientState` →
// `revertTypeLine`) wipes a line set BEFORE the move, and a line set AFTER it
// arrives too late for the entry event, so Enduring Innocence's own sibling
// ("whenever one or more OTHER creatures you control with power 2 or less
// enter") drew a card off a permanent that is not a creature (CR 603.6a).
// Enduring Courage's own entry trigger ("whenever another creature you control
// enters") is the same shape and depends on the same ordering.
//
// LOOP SAFETY. Once back as an enchantment it is not a creature, so it cannot
// die AS a creature: `CREATURE_DIED` is only emitted for a permanent that
// `wasCreature` (gre/state.ts), and the intervening-if would fail regardless
// (CR 603.4 — checked at trigger AND again at resolution). The cycle
// terminates after exactly one return, for every card that calls this.

import type { EffectOp, TriggeredAbility } from "../types";
import { diedTrigger } from "./triggers/diedTrigger";

/** The cycle's shared Effect Script (ADR 0045). Card-agnostic by
 *  construction: `$source` names whichever Glimmer just died, and the type
 *  line it enters with is the printed clause's own "It's an enchantment",
 *  not the card's printed types.
 *
 *  Built FRESH per call rather than shared as one module-level array across
 *  five definitions — the discipline every other factory in
 *  `abilities/index.ts` already follows. Nothing writes through a
 *  `TriggeredAbility.effects` reference today, so a shared array would be safe
 *  right now; five definitions aliasing one mutable object is a bug class
 *  worth not having rather than a bug worth finding. */
const returnAsEnchantment = (): EffectOp[] => [
    {
        op: "moveZone",
        target: { ref: "$source" },
        from: "graveyard",
        to: "battlefield",
        entersAs: { types: ["Enchantment"], subtypes: [] },
    },
];

export interface EnduringReturnArgs {
    /** Stable id within the card's `triggeredAbilities` array. */
    id: string;
    /** The card's printed name, spelled into the oracle text (CR 201.2 —
     *  the modern oracle names the card, ADR 0004). */
    cardName: string;
}

/** Builds the DSK Enduring cycle's dies-trigger (CR 700.4 / 603.2 / 603.4,
 *  CR 205.1a / 613.1d). Add it as the LAST entry of the card's
 *  `triggeredAbilities`, matching the printed order. */
export function enduringReturnTrigger(
    args: EnduringReturnArgs
): TriggeredAbility {
    return diedTrigger({
        id: args.id,
        oracleText: `When ${args.cardName} dies, if it was a creature, return it to the battlefield under its owner's control. It's an enchantment. (It's not a creature.)`,
        scope: "self",
        // CR 700.4 / 603.4 — "if it WAS a creature" is an intervening-if read
        // off the death event's CR 603.10 last-known-information type line,
        // not off the card in the graveyard: the object that died is gone, and
        // re-reading the graveyard card would answer with its PRINTED types.
        // Re-checked at resolution (CR 603.4); the event snapshot is immutable,
        // so a trigger that fired legally never fizzles here.
        interveningIf: (event) => event.creatureTypes.includes("Creature"),
        effects: returnAsEnchantment(),
    });
}
