/**
 * The Oracle lockfile — shape, hashing, and a deterministic serializer.
 *
 * Shared by `oracle-compile.ts` (writes it), `oracle-report.ts` (reads it) and
 * `check-oracle-lockfile.ts` (guards it), so there is exactly one definition of
 * what the file is.
 */

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import {
    EFFECT_OP_REGISTRY,
    MECHANICS_REGISTRY,
} from "../../convex/cards/mechanicsRegistry";
import type {
    CompiledDefinition,
    CompileState,
    QuarantineReason,
} from "../../convex/oracle/types";
import type { CorpusPin, ReportedFormat } from "../oracle-corpus";

export interface LockfileHeader {
    readonly grammarVersion: string;
    /** sha256 of every non-test source file under `convex/oracle/`. */
    readonly grammarHash: string;
    /** sha256 of the Mechanics Registry's names and statuses. */
    readonly registryHash: string;
    readonly corpus: CorpusPin;
    readonly counts: Record<CompileState, number> & { readonly total: number };
}

export interface FormatRow {
    readonly total: number;
    readonly ready: number;
    readonly quarantine: number;
    readonly unparsed: number;
    /** Cards of this format covered by a HAND-WRITTEN definition today. */
    readonly pool: number;
}

/** A distinct unconsumed fragment and how many cards it blocks. */
export interface FragmentRow {
    readonly text: string;
    readonly reason: string;
    readonly cards: number;
}

export interface CardRow {
    readonly oracleId: string;
    readonly name: string;
    readonly state: CompileState;
    /** Indexes into `fragments`. Present iff `state === "unparsed"`. */
    readonly gaps?: readonly number[];
    readonly slots?: readonly string[];
    readonly opsUsed?: readonly string[];
    readonly quarantineReasons?: readonly QuarantineReason[];
    readonly definition?: CompiledDefinition;
}

export interface Lockfile {
    readonly generator: string;
    readonly header: LockfileHeader;
    readonly formats: Record<ReportedFormat, FormatRow>;
    readonly fragments: readonly FragmentRow[];
    readonly cards: readonly CardRow[];
}

export const LOCKFILE_GENERATOR =
    "generated by `bun run oracle:compile` — never hand-edited (see docs/adr/0105-oracle-compiler-fail-closed.md)";

const ORACLE_MODULE_DIR = "convex/oracle";

/** Every source file the grammar's behaviour depends on, in a stable order. */
export function oracleSourceFiles(root: string): string[] {
    const out: string[] = [];
    const walk = (dir: string): void => {
        for (const entry of readdirSync(join(root, dir)).sort()) {
            const rel = `${dir}/${entry}`;
            if (statSync(join(root, rel)).isDirectory()) {
                if (entry === "__tests__") continue;
                walk(rel);
            } else if (entry.endsWith(".ts")) {
                out.push(rel);
            }
        }
    };
    walk(ORACLE_MODULE_DIR);
    return out;
}

/**
 * Hash of the compiler's own source.
 *
 * This is what makes the drift guard work OFFLINE. The full regenerate-and-diff
 * needs the 24 MB corpus, which is gitignored and absent on a clean checkout;
 * the gate is offline by contract (CLAUDE.md). Hashing the grammar catches the
 * case that actually happens — someone changed a rule and did not regenerate —
 * without any network at all.
 */
export function grammarHash(root: string): string {
    const hash = createHash("sha256");
    for (const file of oracleSourceFiles(root)) {
        hash.update(file);
        hash.update(readFileSync(join(root, file)));
    }
    return `sha256:${hash.digest("hex")}`;
}

/**
 * Hash of the Mechanics Registry's NAMES and STATUSES — the two things that
 * change what the compiler emits and what it lets through the `ready` gate. A
 * keyword flipped from `planned` to `implemented` moves cards between states,
 * so it must invalidate the lockfile exactly like a grammar edit.
 */
export function registryHash(): string {
    const mechanics = MECHANICS_REGISTRY.map((r) => [
        r.id,
        r.name,
        r.kind,
        r.status,
    ]);
    const ops = EFFECT_OP_REGISTRY.map((r) => [r.op, r.status]);
    return `sha256:${createHash("sha256").update(JSON.stringify({ mechanics, ops })).digest("hex")}`;
}

/**
 * Deterministic serializer.
 *
 * `JSON.stringify(x, null, 4)` would already be deterministic, but it puts a
 * 38,000-element array on 400,000 lines and makes every regeneration an
 * unreadable diff. One row per line keeps the file diffable — the point of
 * committing it at all is that a card moving `ready` → `unparsed` shows up as a
 * single changed line in review (PRD #2693 user stories 28/29).
 */
export function serializeLockfile(lock: Lockfile): string {
    const lines: string[] = ["{"];
    lines.push(`    "generator": ${JSON.stringify(lock.generator)},`);
    lines.push(
        `    "header": ${indentBlock(JSON.stringify(lock.header, null, 4), 4)},`
    );
    lines.push(
        `    "formats": ${indentBlock(JSON.stringify(lock.formats, null, 4), 4)},`
    );
    lines.push(`    "fragments": [`);
    lines.push(...rowsOf(lock.fragments));
    lines.push(`    ],`);
    lines.push(`    "cards": [`);
    lines.push(...rowsOf(lock.cards));
    lines.push(`    ]`);
    lines.push("}");
    return lines.join("\n") + "\n";
}

function rowsOf(rows: readonly unknown[]): string[] {
    return rows.map(
        (row, i) =>
            `        ${JSON.stringify(row)}${i === rows.length - 1 ? "" : ","}`
    );
}

function indentBlock(text: string, spaces: number): string {
    const pad = " ".repeat(spaces);
    return text
        .split("\n")
        .map((line, i) => (i === 0 ? line : pad + line))
        .join("\n");
}

export function parseLockfile(text: string): Lockfile {
    return JSON.parse(text) as Lockfile;
}
