/**
 * The Oracle lockfile — shape, hashing, and a deterministic serializer.
 *
 * Shared by `oracle-compile.ts` (writes it), `oracle-report.ts` (reads it) and
 * `check-oracle-lockfile.ts` (guards it), so there is exactly one definition of
 * what the file is.
 */

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import {
    EFFECT_OP_REGISTRY,
    MECHANICS_REGISTRY,
} from "../../convex/cards/mechanicsRegistry";
import type {
    CompiledDefinition,
    CompileState,
    QuarantineReason,
} from "../../convex/oracle/types";
import type { CorpusPin, ReportedFormat } from "../oracle-corpus";
import {
    RETIREMENT_LEDGER_PATH,
    type RetirementMarker,
} from "./oracle-retirements";

/**
 * The header's three DERIVED hashes — the whole of the drift guard's offline
 * tier, and the only part of the header a clean checkout can re-derive.
 *
 * Named as its own type so the guard's comparison takes exactly these three
 * and `tsc` reds when a fourth is added to {@link LockfileHeader} without the
 * guard learning to compare it (issue #3068 shipped the third, and the reason
 * it was missing for so long is that nothing forced the two to agree).
 */
export interface HeaderHashes {
    /**
     * sha256 of every source file whose edit can change the bytes of this
     * lockfile: `convex/oracle/**` (non-test) plus the corpus reader, the
     * compile driver and this serializer.
     */
    readonly compilerHash: string;
    /** sha256 of the Mechanics Registry's names and statuses. */
    readonly registryHash: string;
    /**
     * sha256 of the POOL PROJECTION — the sorted set of non-compiled oracle
     * ids read from `data/card-index.json`, i.e. exactly the cards the
     * per-format `pool` figure counts.
     */
    readonly poolHash: string;
}

export interface LockfileHeader extends HeaderHashes {
    readonly grammarVersion: string;
    readonly corpus: CorpusPin;
    readonly counts: Record<CompileState, number> & { readonly total: number };
}

export interface FormatRow {
    readonly total: number;
    readonly ready: number;
    readonly quarantine: number;
    readonly unparsed: number;
    /** Cards of this format covered by a HAND-WRITTEN definition today. */
    readonly pool: number;
}

/** A distinct unconsumed fragment and how many cards it blocks. */
export interface FragmentRow {
    readonly text: string;
    readonly reason: string;
    readonly cards: number;
}

export interface CardRow {
    readonly oracleId: string;
    readonly name: string;
    readonly state: CompileState;
    /** Indexes into `fragments`. Present iff `state === "unparsed"`. */
    readonly gaps?: readonly number[];
    readonly slots?: readonly string[];
    readonly opsUsed?: readonly string[];
    readonly quarantineReasons?: readonly QuarantineReason[];
    readonly definition?: CompiledDefinition;
    /**
     * Present iff this card's hand-written definition has been RETIRED
     * (issue #3049, ADR 0114 §1) — this row is then the only copy of the
     * card's behaviour, and a diff touching it is a behaviour change with no
     * hand-written twin to fall back on.
     *
     * Stamped from `data/oracle-retirements.json` by `buildLockfile`, never
     * hand-written into this file (the whole file is regenerated, so a
     * hand-edit here does not survive the next `oracle:compile` — see
     * `lib/oracle-retirements.ts` for why provenance lives in an input).
     * Always the LAST key of the row, so marking a card changes exactly one
     * row and nothing about the rest of the file's bytes.
     *
     * Provenance is on the LOCKFILE, never on the served asset: ADR 0114 §2
     * keeps `data/oracle-compiled-pool.json` a resolved catalogue with nothing
     * left to resolve at runtime, and a marker is read by review, not by the
     * engine.
     */
    readonly retired?: RetirementMarker;
}

export interface Lockfile {
    readonly generator: string;
    readonly header: LockfileHeader;
    readonly formats: Record<ReportedFormat, FormatRow>;
    readonly fragments: readonly FragmentRow[];
    readonly cards: readonly CardRow[];
}

export const LOCKFILE_GENERATOR =
    "generated by `bun run oracle:compile` — never hand-edited (see docs/adr/0105-oracle-compiler-fail-closed.md)";

const ORACLE_MODULE_DIR = "convex/oracle";

/**
 * The DRIVER half of the compiler: files outside `convex/oracle/**` that still
 * decide what the lockfile says.
 *
 * `oracle-corpus.ts` shapes every input row and names the reported formats,
 * `oracle-compile.ts` builds the fragment table and the per-format tallies, and
 * this file serializes the result. An edit to any of them changes the output
 * with the grammar untouched — so hashing the grammar alone left tier 1 green
 * on a lockfile it should have rejected, which is the same "guard that is not
 * there" shape the tiering exists to avoid (review of #2795, round 2).
 */
const DRIVER_FILES = [
    "scripts/oracle-corpus.ts",
    "scripts/oracle-compile.ts",
    "scripts/lib/oracle-lockfile.ts",
] as const;

/**
 * Committed INPUTS that are not compiler source but still decide the
 * lockfile's bytes.
 *
 * The retirement ledger (issue #3049) is stamped onto rows by `buildLockfile`,
 * so editing it without regenerating leaves the lockfile stale in exactly the
 * way tier 1 exists to catch — and tier 1 is the only tier that runs on a
 * clean checkout, where the corpus is gitignored and absent. Leaving it out of
 * the hash would make "add a retirement, forget to compile" invisible offline,
 * which is the same "guard that is not there" shape that put the driver files
 * above into this hash (review of #2795, round 2).
 */
const DATA_INPUT_FILES = [RETIREMENT_LEDGER_PATH] as const;

/**
 * The card index, read as the POOL PROJECTION and hashed as
 * {@link poolHash} — not as a file in {@link DATA_INPUT_FILES}.
 *
 * It is an input to the lockfile like the ledger is, but only through one
 * derived value: the set of oracle ids a hand-written definition covers, which
 * is what the per-format `pool` figure counts. Hashing the whole FILE would
 * red on changes that cannot move a `pool` figure — the compiler's own
 * `source: "compiled"` rows, a `firstPrintId` correction — and the only way to
 * clear that red is a corpus download for a lockfile whose bytes would not
 * change, which is exactly the unsatisfiable-offline red the tiering exists to
 * avoid (issue #3068).
 */
export const POOL_PROJECTION_SOURCE = "data/card-index.json";

/**
 * The files {@link compilerHash} covers, as ONE reader-facing line, derived
 * from the two lists above.
 *
 * The drift message used to hand-type this list, and the retirement ledger was
 * added to the hash without being added to the sentence — so the one red a
 * ledger edit causes named only the compiler sources, and the reader had no
 * way to connect it to the file they had just edited. A list that CAN be
 * derived is not a sentence someone maintains.
 *
 * {@link POOL_PROJECTION_SOURCE} is deliberately NOT here: it reaches the
 * lockfile through a different hash, so a compiler-hash red can never be the
 * card index and listing it would send the reader to a file they did not
 * touch. Every input a reader could have edited is still named in the red it
 * causes — by the tier that owns it (issue #3068).
 */
export const LOCKFILE_INPUT_SUMMARY = [
    `${ORACLE_MODULE_DIR}/**`,
    ...DRIVER_FILES,
    ...DATA_INPUT_FILES,
].join(", ");

/** Every file the lockfile's contents depend on, in a stable order. */
export function compilerSourceFiles(root: string): string[] {
    const out: string[] = [];
    const walk = (dir: string): void => {
        for (const entry of readdirSync(join(root, dir)).sort()) {
            const rel = `${dir}/${entry}`;
            if (statSync(join(root, rel)).isDirectory()) {
                if (entry === "__tests__") continue;
                walk(rel);
            } else if (entry.endsWith(".ts")) {
                out.push(rel);
            }
        }
    };
    walk(ORACLE_MODULE_DIR);
    out.push(...DRIVER_FILES);
    out.push(...DATA_INPUT_FILES);
    return out;
}

/**
 * Hash of the compiler's own source — grammar AND driver — plus the committed
 * data inputs in {@link DATA_INPUT_FILES}.
 *
 * This is what makes the drift guard work OFFLINE. The full regenerate-and-diff
 * needs the 24 MB corpus, which is gitignored and absent on a clean checkout;
 * the gate is offline by contract (CLAUDE.md). Hashing the sources catches the
 * case that actually happens — someone changed the compiler and did not
 * regenerate — without any network at all.
 *
 * It has to cover the driver as well as the grammar, and the clean checkout is
 * precisely where that bites: with only `convex/oracle/**` hashed, a change to
 * `buildLockfile` that genuinely alters the output left tier 1 passing and tier
 * 3 unable to run, so `check:oracle` exited 0 on a stale lockfile.
 */
export function compilerHash(root: string): string {
    const hash = createHash("sha256");
    for (const file of compilerSourceFiles(root)) {
        hash.update(file);
        hash.update(readFileSync(join(root, file)));
    }
    return `sha256:${hash.digest("hex")}`;
}

/**
 * Hash of the Mechanics Registry's NAMES and STATUSES — the two things that
 * change what the compiler emits and what it lets through the `ready` gate. A
 * keyword flipped from `planned` to `implemented` moves cards between states,
 * so it must invalidate the lockfile exactly like a grammar edit.
 */
export function registryHash(): string {
    const mechanics = MECHANICS_REGISTRY.map((r) => [
        r.id,
        r.name,
        r.kind,
        r.status,
    ]);
    const ops = EFFECT_OP_REGISTRY.map((r) => [r.op, r.status]);
    return `sha256:${createHash("sha256").update(JSON.stringify({ mechanics, ops })).digest("hex")}`;
}

/**
 * Hash of the POOL PROJECTION — the sorted set of oracle ids the card index
 * covers with a hand-written definition, which is exactly what the per-format
 * `pool` figure counts.
 *
 * Without it the card index was the one lockfile input no offline tier saw
 * (issue #3068): shipping a card moved the true `pool` while the committed
 * lockfile kept the old number, tiers 1 and 2 stayed green, and only the
 * corpus-dependent tier 3 noticed — on a machine that happened to have the
 * 24 MB gitignored cache. So the drift merged, and the next person with a
 * corpus paid for it as a conflict in a generated file they never touched.
 *
 * The caller passes the set, never a path: it is computed by the SAME exported
 * helper the compiler uses (`poolOracleIdsFromIndex`), so the guard and the
 * compiler cannot disagree about what the pool is.
 *
 * Sorted, because a `Set`'s iteration order is insertion order — hashing it
 * raw would make the hash depend on the card index's row order rather than on
 * its membership, and a pure reordering would then red a lockfile whose bytes
 * do not change.
 */
export function poolHash(poolOracleIds: ReadonlySet<string>): string {
    const hash = createHash("sha256");
    for (const id of [...poolOracleIds].sort()) {
        hash.update(id);
        hash.update("\n");
    }
    return `sha256:${hash.digest("hex")}`;
}

/**
 * Deterministic serializer.
 *
 * `JSON.stringify(x, null, 4)` would already be deterministic, but it puts a
 * 38,000-element array on 400,000 lines and makes every regeneration an
 * unreadable diff. One row per line keeps the file diffable — the point of
 * committing it at all is that a card moving `ready` → `unparsed` shows up as a
 * single changed line in review (PRD #2693 user stories 28/29).
 */
export function serializeLockfile(lock: Lockfile): string {
    const lines: string[] = ["{"];
    lines.push(`    "generator": ${JSON.stringify(lock.generator)},`);
    lines.push(
        `    "header": ${indentBlock(JSON.stringify(lock.header, null, 4), 4)},`
    );
    lines.push(
        `    "formats": ${indentBlock(JSON.stringify(lock.formats, null, 4), 4)},`
    );
    lines.push(`    "fragments": [`);
    lines.push(...rowsOf(lock.fragments));
    lines.push(`    ],`);
    lines.push(`    "cards": [`);
    lines.push(...rowsOf(lock.cards));
    lines.push(`    ]`);
    lines.push("}");
    return lines.join("\n") + "\n";
}

function rowsOf(rows: readonly unknown[]): string[] {
    return rows.map(
        (row, i) =>
            `        ${JSON.stringify(row)}${i === rows.length - 1 ? "" : ","}`
    );
}

function indentBlock(text: string, spaces: number): string {
    const pad = " ".repeat(spaces);
    return text
        .split("\n")
        .map((line, i) => (i === 0 ? line : pad + line))
        .join("\n");
}

export function parseLockfile(text: string): Lockfile {
    return JSON.parse(text) as Lockfile;
}
