// Reads the hand-written `CardPrint` literals under `convex/cards/sets/**`
// (ADR 0140, issue #4116) — the population `--equivalence` proves the sync
// reproduces before they are ever deleted. The PRD's "1,409" is a naive
// `export const .*: CardPrint = {` line count; 6 of those lines are
// commented-out ante stubs (ADR 0010) inside a comment that still contains the
// literal text — this scanner's `^` line anchor excludes them, leaving 1,403
// LIVE records, the number `--equivalence` actually checks.
//
// Regex over source, mirroring `scripts/fetch-token-prints.mjs`'s id scan:
// every literal is generated by `scripts/generate-print-set.mts` in the same
// four-field shape, so a field-order-independent scan of each
// `CardPrint`-typed object is exact without importing the runtime registry.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

export interface HandwrittenPrint {
    printId: string;
    definitionId: string;
    setCode: string;
    rarity: string;
    file: string;
}

// Const names are Unicode identifiers, never plain `\w+` — Arabian Nights
// gives real examples (`elHajjâj3ed`, `junúnEfreet4ed`), and `\w` alone
// silently drops both (issue #4116 investigation, 4 of the 1,409 records).
// Anchored to the START of the line: `//     export const … CardPrint = {`
// inside a commented-out stub (ADR 0010 ante exclusions) contains this exact
// text too, and must never be read as a live record.
const IDENT = "[\\p{L}\\p{N}_$]+";
const OBJECT_RE = new RegExp(
    `^export const ${IDENT}\\s*:\\s*CardPrint\\s*=\\s*\\{([\\s\\S]*?)\\n\\};`,
    "gmu"
);
// A 100%-reprint set file (4ED-style, ADR 0014) resolves `definitionId`
// straight to a literal Scryfall UUID. A multi-art set (FEM's b/c/d prints)
// instead points every extra printing at the CANONICAL art's own
// `CardDefinition` via `definitionId: someCard.id` — this file's `id` is that
// definition's own field, never a second literal, so a per-object regex over
// `CardPrint` blocks alone would miss it (74 of the 1,409 records, issue
// #4116 investigation).
const DEFINITION_RE = new RegExp(
    `^export const (${IDENT})\\s*:\\s*CardDefinition\\s*=\\s*\\{([\\s\\S]*?)\\n\\};`,
    "gmu"
);

function field(body: string, name: string): string | undefined {
    return body.match(new RegExp(`${name}:\\s*"([^"]+)"`))?.[1];
}

// A hoisted `const FOO_ID = "<uuid>";` reused both by a `CardDefinition`'s own
// `id:` field and by a card that needs the same id elsewhere in the file
// (`scripts/fetch-token-prints.mjs` names the same shape: Retrofitter
// Foundry, Third Path Iconoclast, The Hive). `id: FOO_ID,` carries no quotes,
// so `field(body, "id")` alone walks straight past it to whatever the first
// QUOTED `id:` in the body happens to be — a nested `activatedAbilities[].id`
// slug, not the card's own id (issue #4116 investigation, 2 of the 1,403
// records).
const HOISTED_ID_RE = /^const ([A-Za-z0-9_$]+)\s*=\s*"([^"]+)";/gm;

/** The `id:` value at the FIRST occurrence in `body` — the top-level field,
 *  since it is always declared before any nested ability's own `id`. Either
 *  a literal or a hoisted-const reference; `constIdByName` resolves the
 *  latter. */
function ownId(
    body: string,
    constIdByName: ReadonlyMap<string, string>
): string | undefined {
    const m = body.match(/id:\s*(?:"([^"]+)"|([A-Za-z0-9_$]+))/);
    if (!m) return undefined;
    return m[1] ?? constIdByName.get(m[2]);
}

/** `const NAME` -> its own `CardDefinition.id`, scanned once per file so a
 *  `definitionId: NAME.id` reference resolves without importing the
 *  runtime registry (this module stays a pure source-text reader). */
function definitionIdsByName(source: string): Map<string, string> {
    const constIdByName = new Map<string, string>();
    for (const match of source.matchAll(HOISTED_ID_RE)) {
        constIdByName.set(match[1], match[2]);
    }
    const map = new Map<string, string>();
    for (const match of source.matchAll(DEFINITION_RE)) {
        const id = ownId(match[2], constIdByName);
        if (id) map.set(match[1], id);
    }
    return map;
}

function definitionIdField(
    body: string,
    idsByName: ReadonlyMap<string, string>
): string | undefined {
    const literal = field(body, "definitionId");
    if (literal) return literal;
    const ref = body.match(/definitionId:\s*(\w+)\.id/)?.[1];
    return ref ? idsByName.get(ref) : undefined;
}

export function extractHandwrittenPrints(
    source: string,
    file: string
): HandwrittenPrint[] {
    const idsByName = definitionIdsByName(source);
    const out: HandwrittenPrint[] = [];
    for (const match of source.matchAll(OBJECT_RE)) {
        const body = match[1];
        const printId = field(body, "printId");
        const definitionId = definitionIdField(body, idsByName);
        const setCode = field(body, "setCode");
        const rarity = field(body, "rarity");
        if (printId && definitionId && setCode && rarity) {
            out.push({ printId, definitionId, setCode, rarity, file });
        }
    }
    return out;
}

function walkTs(dir: string): string[] {
    const out: string[] = [];
    for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) out.push(...walkTs(full));
        else if (entry.endsWith(".ts") && !entry.endsWith(".test.ts"))
            out.push(full);
    }
    return out;
}

export function collectHandwrittenPrints(setsRoot: string): HandwrittenPrint[] {
    const out: HandwrittenPrint[] = [];
    for (const file of walkTs(setsRoot)) {
        out.push(...extractHandwrittenPrints(readFileSync(file, "utf8"), file));
    }
    return out;
}

export type EquivalenceDiffField = "cardId" | "set" | "rarity" | "missing";

export interface EquivalenceDiff {
    printId: string;
    field: EquivalenceDiffField;
    file: string;
    handwritten: string;
    generated?: string;
}

/**
 * Every hand-written record must match the generated row on Card ID, Set and
 * Rarity — except a Rarity mismatch the override file's `printOverrides`
 * names for this exact printId, which is "covered": the mismatch was
 * reviewed, not missed (ADR 0140 §2, issue #4116 AC5).
 */
export function diffAgainstHandwritten(
    handwritten: readonly HandwrittenPrint[],
    generatedByPrintId: ReadonlyMap<
        string,
        { cardId: string; set: string; rarity: string }
    >,
    coveredRarityOverridePrintIds: ReadonlySet<string>
): EquivalenceDiff[] {
    const diffs: EquivalenceDiff[] = [];
    for (const hw of handwritten) {
        const generated = generatedByPrintId.get(hw.printId);
        if (!generated) {
            diffs.push({
                printId: hw.printId,
                field: "missing",
                file: hw.file,
                handwritten: hw.definitionId,
            });
            continue;
        }
        if (generated.cardId !== hw.definitionId) {
            diffs.push({
                printId: hw.printId,
                field: "cardId",
                file: hw.file,
                handwritten: hw.definitionId,
                generated: generated.cardId,
            });
        }
        if (generated.set !== hw.setCode) {
            diffs.push({
                printId: hw.printId,
                field: "set",
                file: hw.file,
                handwritten: hw.setCode,
                generated: generated.set,
            });
        }
        if (
            generated.rarity !== hw.rarity &&
            !coveredRarityOverridePrintIds.has(hw.printId)
        ) {
            diffs.push({
                printId: hw.printId,
                field: "rarity",
                file: hw.file,
                handwritten: hw.rarity,
                generated: generated.rarity,
            });
        }
    }
    return diffs;
}
