// The Continuous Effects Registry (ADR 0082, PRD #2064) — slice S1.
//
// One list on `GameState` holding every CHARACTERISTIC-CHANGING continuous
// effect (CR 613), whatever generated it. CR 611.1: "A continuous effect
// modifies characteristics of objects, modifies control of objects, or affects
// players or the rules of the game, for a fixed or indefinite period." The CR
// knows only continuous effects with timestamps; it does NOT distinguish an
// effect generated by a permanent's static ability from one left behind by a
// resolved spell. The engine does — three provenances materialise into three
// different shapes on `CardInstanceState` — and that split, which has no CR
// counterpart, is what makes a uniform per-read recompute impossible today.
// The registry deletes the split: provenance survives only as EXPIRY.
//
// SCOPE (ADR 0082 decision 2): characteristic-changing effects only. The
// rules-modifying effects of CR 611.3 (`attack-restriction`,
// `block-requirement`, `cost-modifier`, `cast-restriction`,
// `cast-timing-lock`, `untap-restriction`, `hand-size-override`,
// `permanent-guard`, `mana-substitution`, `landwalk-negation`,
// `enters-tapped-restriction`) are deliberately OUT — the CR keeps them out of
// the layer system, and so does this registry. They share the `StaticEffect`
// union today; that is the incoherence, not a reason to widen the boundary.
//
// STATUS — every CR 613 layer now derives from this registry: layer 7 (S2,
// #3003), layer 6 (S3, #3004), layers 2-5 (S4, #3005). S5 (#3094) put the
// registry ON THE WIRE and made `projectPublicState` derive its snapshot from
// it (`gre/wireCharacteristics.ts`), so the client-side engine run reads the
// same entries the server does. What remains is deleting the materialised
// fields and the old helpers (S6) and the perf pass (S7).

import type {
    CardSupertype,
    CardType,
    Color,
    TextChange,
} from "../cards/types";
import type { Duration, GameState } from "./state";

/** CR 613.1b-g — the layers this registry covers. Layer 1 (copiable values,
 *  CR 613.1a) is deliberately absent: copy effects are applied BEFORE the
 *  layer system reads anything, and the engine models them on the card
 *  instance (`gre/copy.ts`), not as continuous effects to be ordered. */
export type ContinuousEffectLayer = 2 | 3 | 4 | 5 | 6 | 7;

/** CR 613.4a-d — layer 7's sublayers, and the ONLY layer the CR gives
 *  sublayers to. There is no 7e: CR 613.4c is "effects AND COUNTERS that
 *  modify power and/or toughness" (CR 122.1a points +X/+Y counters straight at
 *  it) and CR 613.4d is the switch sublayer. Several older comments in this
 *  codebase call counters "613.4d" — pre-CR-renumbering rot; it must not be
 *  frozen into this union, which discriminates PERSISTED rows and could only
 *  be corrected by a data migration. Named with their layer prefix so a
 *  sublayer can never be read as belonging to another layer. */
export type ContinuousEffectSublayer = "7a" | "7b" | "7c" | "7d";

/** Layer + sublayer as ONE field pair, so `tsc` rejects both halves of the
 *  invariant: a layer-7 entry MUST name its sublayer (CR 613.4 orders within
 *  sublayers, so an unsublayered layer-7 entry has no defined position), and
 *  no other layer may carry one. */
export type ContinuousEffectSlot =
    | { layer: Exclude<ContinuousEffectLayer, 7>; sublayer?: undefined }
    | { layer: 7; sublayer: ContinuousEffectSublayer };

/** How an entry ends. This is the ONLY thing the three provenances that
 *  materialise into `staticAbilities` today still differ by, plus the
 *  source-independent case they cannot express together (PRD #2064, the S3
 *  counter-gate x source-independence conformance case).
 *
 *  - `source`   — generated by a static ability of an object (CR 604.1). Ends
 *                 when that object stops generating it: it leaves the
 *                 battlefield, unattaches, or its `applies` / `condition`
 *                 stops holding. Its timestamp follows CR 613.7a. The only
 *                 provenance derivable by walking the board.
 *  - `duration` — generated by a resolving spell or ability with a stated
 *                 duration (CR 611.2a). The spell has LEFT; there is no source
 *                 to walk, which is precisely why "walk the battlefield and
 *                 recompute" is not expressible without this registry.
 *  - `counter`  — borne by counters on an object (CR 122.1a for +X/+Y,
 *                 CR 122.1b for keyword counters). Ends when the last counter
 *                 of that kind is removed. Neither duration-bounded nor tied
 *                 to a live source. Its timestamp follows CR 613.7c.
 *  - `indefinite` — CR 611.2a: "If no duration is stated, it lasts until the
 *                 end of the game." Source-independent by construction.
 *  - `while-source-tapped` — CR 611.2b, the state-tied "for as long as ..."
 *                 duration this union deliberately lacked at S1 ("a later slice
 *                 adding it adds a variant"). Ends the moment `sourceId` stops
 *                 being a tapped battlefield permanent (ATQ Ashnod's Battle
 *                 Gear, Tawnos's Weaponry). NOT `source` expiry: the source's
 *                 mere presence is not the condition, its tapped status is, and
 *                 the effect is not generated by a static ability of it.
 *
 *  Source-independence and condition-gating are INDEPENDENT properties here:
 *  an `indefinite` or `counter` entry is not tied to a source's lifetime, and
 *  a `source` entry is. Under the two-channel model they were a choice
 *  (`staticEffects[]` gave the gate, the `*Permanent` grant primitives gave
 *  source-independence, neither gave both).
 *
 *  NOT exhaustive of the CR: a "for as long as ..." duration (CR 611.2b,
 *  Master Thief) has no variant here, because the engine's stored `Duration`
 *  is phase-boundary-only. That is a pre-existing limitation this slice
 *  neither introduces nor closes — a later slice adding it adds a variant.
 *
 *  `controllerId` rides on the two RESOLUTION-generated variants and only
 *  those. The controller of a continuous effect from a resolving spell or
 *  ability is fixed when that effect is created and the spell is gone, so it
 *  must be stored. A `source` / `counter` entry's controller is the LIVE
 *  controller of the object (every `applies(target, source, ctx)` closure
 *  already reads `source.controllerId` off a live `PermanentView`): storing a
 *  snapshot there would go stale the moment a Control Magic flips the source
 *  of a "creatures you control" lord, so `tsc` forbids it. */
export type ContinuousEffectExpiry =
    | { kind: "source"; sourceId: string }
    | { kind: "counter"; permanentId: string; counterType: string }
    | { kind: "duration"; duration: Duration; controllerId: string }
    | { kind: "indefinite"; controllerId: string }
    | { kind: "while-source-tapped"; sourceId: string };

/** An effect declared in a card (or emblem) definition's `staticEffects[]`,
 *  referenced by index rather than embedded — the `applies` / `condition` /
 *  `compute` closures stay on the definition, so the registry stays plain data
 *  and survives the DB round-trip.
 *
 *  `effectIndex` indexes `getEffectiveStaticEffects(def, modeId)`
 *  (`gre/state.ts`) — the CONCATENATION of the definition's own effects and
 *  the chosen mode's (CR 700.2), NOT a mode's array on its own. Resolve it
 *  through that function and no other, or a modal card with base static
 *  effects reads the wrong entry. */
export type ContinuousEffectTemplatePayload = {
    kind: "template";
    sourceCardId: string;
    effectIndex: number;
    /** The mode chosen for the source (`CardInstanceState.chosenModeId`), when
     *  it has one — it selects which effects `getEffectiveStaticEffects`
     *  concatenates, so it is part of resolving `effectIndex`, not a scope. */
    modeId?: string;
};

/** What an entry generated by a resolving spell or ability DOES. Concrete
 *  values, no closure: everything here is already a scalar in the materialised
 *  fields these entries replace, so nothing needs one. Shapes mirror the
 *  `StaticEffect` variants in `cards/types.ts` they will absorb — where that
 *  type distinguishes add from remove, so does this one. */
export type ContinuousEffectInlinePayload =
    /** CR 613.1b layer 2 */
    | { kind: "control-change"; controllerId: string }
    /** CR 613.1c layer 3 — see CR 612 and `gre/textChanges.ts`. */
    | { kind: "text-change"; change: TextChange }
    /** CR 613.1d layer 4. `set` is CR 205.1a's whole-line REPLACEMENT (issue
     *  #2084 — "return it to the battlefield. It's an enchantment."), which
     *  neither `add` nor `remove` can express: it must suppress every type the
     *  object had, including ones the entry cannot name. Added by PRD #2064 S4,
     *  the slice that migrates layer 4 — S1 deliberately shipped only the two
     *  variants layer 4's static-ability kinds needed. */
    | {
          kind: "type-change";
          add?: CardType[];
          remove?: CardType[];
          set?: CardType[];
      }
    | { kind: "subtype-change"; add?: string[]; set?: string[] }
    | {
          kind: "supertype-change";
          add?: CardSupertype[];
          remove?: CardSupertype[];
      }
    /** CR 613.1e layer 5. CR 105.3 — a new colour REPLACES every colour the
     *  object had (`set`); a grant UNIONS (`add`). */
    | { kind: "color-change"; add?: Color[]; set?: Color[] }
    /** CR 613.1f layer 6 */
    | {
          kind: "keyword-grant";
          keyword: string;
          parameter?: ContinuousEffectKeywordParameter;
      }
    | { kind: "keyword-remove"; keyword: string }
    | { kind: "ability-loss" }
    | { kind: "activated-grant"; sourceCardId: string; abilityId: string }
    | { kind: "triggered-grant"; sourceCardId: string; abilityId: string }
    /** CR 613.4 layer 7 — `pt-set` is 7b, `pt-modify` 7c, `pt-switch` 7d.
     *  CR 613.4b sets power AND/OR toughness, so both halves of `pt-set` are
     *  independently optional: Island of Wak-Wak sets power 0 and leaves
     *  toughness to the 7a value. */
    | { kind: "pt-set"; power?: number; toughness?: number }
    | { kind: "pt-modify"; power: number; toughness: number }
    | { kind: "pt-switch" };

/** The STRUCTURED parameter of a parameterised keyword (CR 702), kept beside
 *  the keyword rather than pre-rendered into its string.
 *
 *  The engine's keyword vocabulary is stringly typed — `"protection from red"`,
 *  `"islandwalk"`, `"rampage 2"` — and roughly ninety consult sites read those
 *  strings, so the strings themselves are not going away in this slice (PRD
 *  #2064 S6 owns deleting the old fields, and with them the grammar). What DOES
 *  go away here is the parameter being FROZEN: a grant used to render its
 *  string once, at materialisation time, and nothing ever recomputed the colour
 *  set, the landwalk subtype or the N. An entry that carries its parameter
 *  structurally is rendered at every read (`renderKeyword`), so a board change
 *  after the grant was created moves the grant with it.
 *
 *  `keyword` stays REQUIRED alongside it and stays the rendered form: the
 *  parameter is what the entry knows, the string is what the consult sites
 *  read, and rendering is a total function of the two. An entry with no
 *  parameter is an unparameterised keyword (`"flying"`) — not a missing
 *  parameter. */
export type ContinuousEffectKeywordParameter =
    /** CR 702.16a — protection from one or more qualities, as the QUALITY
     *  words ("red", "colorless", "artifacts"), joined by " and " on render.
     *  Stored as words rather than `Color[]` because CR 702.16a's quality
     *  vocabulary is wider than colour (a card type, a supertype), and the
     *  single parser that reads them back (`gre/protection.ts`) is defined
     *  over words. */
    | { kind: "protection"; qualities: string[] }
    /** CR 702.14 — landwalk, parameterised by the land SUBTYPE it names
     *  ("Island" -> "islandwalk"). */
    | { kind: "landwalk"; subtype: string }
    /** Every keyword whose parameter is a bare count, rendered
     *  `"<keyword> <n>"` — CR 702.23 is Rampage, CR 702.21 is Ward. */
    | { kind: "count"; count: number };

/** Renders a keyword payload to the string every layer-6 consult site reads.
 *  Total: a payload with no `parameter` renders its `keyword` unchanged, so an
 *  unparameterised grant costs nothing.
 *
 *  The inverse of the parsers in `gre/protection.ts` /
 *  `gre/constants.ts` — deliberately NOT their replacement. Those parse
 *  PRINTED keywords off a card definition, which this registry does not
 *  produce; this renders a GRANT's structured parameter into the same
 *  vocabulary so both arrive at a consult site indistinguishable. */
export function renderKeyword(payload: {
    keyword: string;
    parameter?: ContinuousEffectKeywordParameter;
}): string {
    const parameter = payload.parameter;
    if (!parameter) return payload.keyword;
    switch (parameter.kind) {
        case "protection":
            // CR 702.16a — "protection from red and from black" is TWO
            // instances of the ability (CR 702.16i), but the engine's string
            // vocabulary spells a multi-quality grant with " and from ", which
            // is what `parseProtectionQuality` reads back.
            return `protection from ${parameter.qualities.join(" and from ")}`;
        case "landwalk":
            return `${parameter.subtype.toLowerCase()}walk`;
        case "count":
            return `${payload.keyword} ${parameter.count}`;
    }
}

export type ContinuousEffectPayload =
    | ContinuousEffectTemplatePayload
    | ContinuousEffectInlinePayload;

/** Which objects an entry applies to, paired with what it can be and how it
 *  can end — CR 611.2c draws all three lines at once and the registry follows
 *  it exactly.
 *
 *  A continuous effect from a STATIC ability re-evaluates its predicate at
 *  every read ("Note that this works differently than a continuous effect from
 *  a static ability"). So the `predicate` arm is pinned to `source` expiry and
 *  a `template` payload: the predicate IS the template's `applies` /
 *  `condition`, evaluated against the live source, and a predicate with no
 *  source to evaluate against — or no template to evaluate — is made
 *  unrepresentable rather than merely discouraged.
 *
 *  A continuous effect from a RESOLVING spell or ability that modifies
 *  characteristics or control has its affected set "determined when that
 *  continuous effect begins. After that point, the set won't change" — a fixed
 *  `instances` list, which any expiry and any payload may carry (a static
 *  ability's effect can also be snapshotted this way when a slice needs to). */
export type ContinuousEffectScope =
    | {
          affected: { kind: "predicate" };
          expiry: { kind: "source"; sourceId: string };
          payload: ContinuousEffectTemplatePayload;
      }
    | {
          affected: { kind: "instances"; instanceIds: string[] };
          expiry: ContinuousEffectExpiry;
          payload: ContinuousEffectPayload;
      };

/** One continuous effect. */
export type ContinuousEffect = ContinuousEffectSlot &
    ContinuousEffectScope & {
        /** Stable identity for removal and for the S2-S4 migrations to key
         *  their own bookkeeping off. Deterministic (`ce-N`) so replays
         *  reproduce it. */
        id: string;
        /** CR 613.7 layer timestamp. The SAME monotonic sequence the engine
         *  already mints for `staticSeq` / `grantedStaticAbilities[].seq` /
         *  `abilitiesSuppressedBy[].seq` (`allocStaticTimestamp`,
         *  `gre/state.ts`) — deliberately not a second counter, or a registry
         *  entry and a materialised grant could tie instead of ordering. */
        timestamp: number;
        /** CR 604.3 — this effect comes from a characteristic-defining
         *  ability. Load-bearing for CR 613.8a clause (c), which makes a
         *  dependency exist only when NEITHER effect is from a CDA or BOTH
         *  are. The dependency algorithm itself is a documented divergence
         *  tracked by #2068; the flag ships now because retrofitting it onto
         *  entries the migrations have already written would mean a second
         *  pass over every producer. */
        characteristicDefining: boolean;
    };

/** CR 400.7 — every registry entry that applies to `instanceId` and to nothing
 *  else, gone; and `instanceId` struck from the affected set of every entry
 *  that also applies to others.
 *
 *  A permanent that leaves the battlefield is a NEW object when it comes back,
 *  and the engine reuses the instance id across that boundary (the object is
 *  the same JS record; `resetBattlefieldTransientState` is what makes it a new
 *  object). So a residue entry that is not purged here would re-attach itself
 *  to the returning permanent: a bounced Figure of Destiny would come back with
 *  the base P/T an `indefinite` `pt-set` gave it, which is precisely the bug
 *  `delete card.temporaryPTSet` used to prevent while the countdown lived on
 *  the instance (PRD #2064 S6 moved it here).
 *
 *  A `predicate`-affected entry is NOT touched: its affected set is the live
 *  board evaluated at every read (CR 611.2c), so a departure removes the
 *  permanent from it for free and there is nothing to purge. Entries are
 *  SPLICED rather than blanked — `id` is the removal handle, and
 *  `nextContinuousEffectOrdinal` mints past the highest suffix in use so a
 *  removal cannot let a later entry re-issue a live id. */
export function purgeContinuousEffectsForInstance(
    state: GameState,
    instanceId: string
): void {
    const entries = state.continuousEffects;
    if (!entries?.length) return;
    let changed = false;
    const kept: ContinuousEffect[] = [];
    for (const entry of entries) {
        if (entry.affected.kind === "predicate") {
            kept.push(entry);
            continue;
        }
        if (!entry.affected.instanceIds.includes(instanceId)) {
            kept.push(entry);
            continue;
        }
        changed = true;
        const remaining = entry.affected.instanceIds.filter(
            (id) => id !== instanceId
        );
        if (remaining.length === 0) continue;
        kept.push({
            ...entry,
            affected: { kind: "instances", instanceIds: remaining },
        });
    }
    if (!changed) return;
    state.continuousEffects = kept.length > 0 ? kept : undefined;
}

/** CR 613.7 — the ONE timestamp comparison in the codebase. "An effect with an
 *  earlier timestamp is applied before an effect with a later timestamp."
 *
 *  Ties are impossible by construction (`allocStaticTimestamp` mints strictly
 *  greater than every live stamp), so `id` breaks them only to keep the sort
 *  total and deterministic — never as a rule. */
export function compareContinuousEffects(
    a: ContinuousEffect,
    b: ContinuousEffect
): number {
    if (a.timestamp !== b.timestamp) return a.timestamp - b.timestamp;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

/** CR 613.7 — the LATEST layer timestamp among `entries`, or `null` when there
 *  are none. The reduction every "does a later effect outrank this one?"
 *  question is asked through, so no call site re-implements the max.
 *
 *  Takes bare stamps rather than `ContinuousEffect`s so the records that still
 *  live on a card instance until PRD #2064 S6 deletes them
 *  (`abilitiesSuppressedBy`, `removedKeywords`) can be ordered by the SAME
 *  authority as a registry entry — the point of #1715's hardening was that two
 *  sites comparing `seq` by hand are two sites that can disagree. */
export function latestTimestamp(
    stamps: Iterable<number | undefined>
): number | null {
    let latest: number | null = null;
    for (const stamp of stamps) {
        if (stamp === undefined) continue;
        if (latest === null || stamp > latest) latest = stamp;
    }
    return latest;
}

/** CR 613.7 — true when the record stamped `timestamp` is applied BEFORE the
 *  effect stamped `rival`, i.e. the rival outranks it.
 *
 *  STRICT: equal timestamps do not outrank, and `allocStaticTimestamp`
 *  (`gre/state.ts`) mints strictly-increasing stamps precisely so a tie can
 *  only mean "the same effect". An absent `timestamp` reads as 0 — a record
 *  written before this codebase stamped anything, which every stamped effect
 *  outranks — and an absent `rival` (no such effect) outranks nothing.
 *
 *  This is the ONE comparison behind `grantOutrankedByAbilityLoss`
 *  (`gre/activatedAbilities.ts`) and the layer-6 grant-vs-removal decision in
 *  `gre/layer6.ts`. #1715 had to harden those one site at a time because each
 *  wrote the comparison inline; PRD #2064 S3 leaves exactly one. */
export function outrankedBy(
    timestamp: number | undefined,
    rival: number | null
): boolean {
    if (rival === null) return false;
    return (timestamp ?? 0) < rival;
}

/** Every registry entry applying in `layer` (and, for layer 7, `sublayer`),
 *  in CR 613.7 timestamp order.
 *
 *  This is the single ordering authority the S2-S4 migrations consume. No
 *  slice may re-derive ordering by comparing `staticSeq` inline — that ad-hoc
 *  per-site comparison is exactly what #1715 had to harden one site at a time.
 *
 *  Layer 7 REQUIRES a sublayer (CR 613.4 orders within sublayers), so the
 *  overloads make an unsublayered layer-7 query a type error rather than a
 *  silently-wrong whole-layer sweep. */
export function continuousEffectsInLayer(
    state: GameState,
    layer: 7,
    sublayer: ContinuousEffectSublayer
): ContinuousEffect[];
export function continuousEffectsInLayer(
    state: GameState,
    layer: Exclude<ContinuousEffectLayer, 7>
): ContinuousEffect[];
export function continuousEffectsInLayer(
    state: GameState,
    layer: ContinuousEffectLayer,
    sublayer?: ContinuousEffectSublayer
): ContinuousEffect[] {
    const entries = state.continuousEffects;
    if (!entries?.length) return [];
    return entries
        .filter(
            (e) =>
                e.layer === layer &&
                (sublayer === undefined || e.sublayer === sublayer)
        )
        .sort(compareContinuousEffects);
}
