// The Continuous Effects Registry (ADR 0082, PRD #2064) — slice S1.
//
// One list on `GameState` holding every CHARACTERISTIC-CHANGING continuous
// effect (CR 613), whatever generated it. CR 611.1: "A continuous effect
// modifies characteristics of objects, modifies control of objects, or affects
// players or the rules of the game, for a fixed or indefinite period." The CR
// knows only continuous effects with timestamps; it does NOT distinguish an
// effect generated by a permanent's static ability from one left behind by a
// resolved spell. The engine does — three provenances materialise into three
// different shapes on `CardInstanceState` — and that split, which has no CR
// counterpart, is what makes a uniform per-read recompute impossible today.
// The registry deletes the split: provenance survives only as EXPIRY.
//
// SCOPE (ADR 0082 decision 2): characteristic-changing effects only. The
// rules-modifying effects of CR 611.3 (`attack-restriction`,
// `block-requirement`, `cost-modifier`, `cast-restriction`,
// `cast-timing-lock`, `untap-restriction`, `hand-size-override`,
// `permanent-guard`, `mana-substitution`, `landwalk-negation`,
// `enters-tapped-restriction`) are deliberately OUT — the CR keeps them out of
// the layer system, and so does this registry. They share the `StaticEffect`
// union today; that is the incoherence, not a reason to widen the boundary.
//
// STATUS — this slice ships the data structure and its ordering contract ONLY.
// Nothing in production writes or reads the registry yet: layer 7 migrates in
// S2 (#3003), layer 6 in S3 (#3004), layers 2-5 in S4 (#3005).

import type { CardType, Color } from "../cards/types";
import type { Duration, GameState } from "./state";

/** CR 613.1b-g — the layers this registry covers. Layer 1 (copiable values,
 *  CR 613.1a) is deliberately absent: copy effects are applied BEFORE the
 *  layer system reads anything, and the engine models them on the card
 *  instance (`gre/copy.ts`), not as continuous effects to be ordered. */
export type ContinuousEffectLayer = 2 | 3 | 4 | 5 | 6 | 7;

/** CR 613.4a-e — layer 7's sublayers. Named with their layer prefix so a
 *  sublayer can never be read as belonging to another layer. Layer 7 is the
 *  only layer the CR gives sublayers to. */
export type ContinuousEffectSublayer = "7a" | "7b" | "7c" | "7d" | "7e";

/** Layer + sublayer as ONE field pair, so `tsc` rejects both halves of the
 *  invariant: a layer-7 entry MUST name its sublayer (CR 613.4 orders within
 *  sublayers, so an unsublayered layer-7 entry has no defined position), and
 *  no other layer may carry one. */
export type ContinuousEffectSlot =
    | { layer: Exclude<ContinuousEffectLayer, 7>; sublayer?: undefined }
    | { layer: 7; sublayer: ContinuousEffectSublayer };

/** How an entry ends. This is the ONLY thing the three provenances that
 *  materialise into `staticAbilities` today still differ by, plus the
 *  source-independent case they cannot express together (PRD #2064, the S3
 *  counter-gate x source-independence conformance case).
 *
 *  - `source`   — CR 613.7a: generated by a static ability of an object.
 *                 Ends when that object stops generating it (it leaves the
 *                 battlefield, unattaches, or its `applies`/`condition` stops
 *                 holding). The only provenance derivable by walking the board.
 *  - `duration` — CR 611.2a: generated by a resolving spell or ability with a
 *                 stated duration. The spell has LEFT; there is no source to
 *                 walk, which is precisely why "walk the battlefield and
 *                 recompute" is not expressible without this registry.
 *  - `counter`  — CR 613.7c / 122.1c: borne by counters on an object. Ends
 *                 when the last counter of that kind is removed. Neither
 *                 duration-bounded nor tied to a live source.
 *  - `indefinite` — CR 611.2a: "If no duration is stated, it lasts until the
 *                 end of the game." Source-independent by construction.
 *
 *  Source-independence and condition-gating are INDEPENDENT properties here:
 *  an `indefinite` or `counter` entry is not tied to a source's lifetime, and
 *  a `source` entry is. Under the two-channel model they were a choice
 *  (`staticEffects[]` gave the gate, the `*Permanent` grant primitives gave
 *  source-independence, neither gave both). */
export type ContinuousEffectExpiry =
    | { kind: "source"; sourceId: string }
    | { kind: "duration"; duration: Duration }
    | { kind: "counter"; permanentId: string; counterType: string }
    | { kind: "indefinite" };

/** Which objects the entry applies to.
 *
 *  CR 611.2c draws the line and the registry follows it exactly: a continuous
 *  effect from a RESOLVING spell or ability that modifies characteristics or
 *  control has its affected set "determined when that continuous effect
 *  begins. After that point, the set won't change" — a fixed `instances` list.
 *  A continuous effect from a STATIC ability re-evaluates its predicate at
 *  every read ("Note that this works differently than a continuous effect from
 *  a static ability") — `predicate`, decided by the referenced template's
 *  `applies`/`condition`, which is why a `predicate` entry's payload must be a
 *  template reference. */
export type ContinuousEffectAffected =
    | { kind: "predicate" }
    | { kind: "instances"; instanceIds: string[] };

/** What the entry DOES.
 *
 *  The registry is persisted (see `serialize.ts`), so a payload is PLAIN DATA:
 *  it never embeds a closure. An effect declared on a card definition
 *  references its template by `(sourceCardId, effectIndex)` — the `applies` /
 *  `condition` / `compute` closures stay on the definition and are resolved by
 *  registry lookup at read time. Only effects a resolving spell generated with
 *  no template behind them carry their concrete values inline; those values are
 *  already scalars in today's materialised fields, so nothing needs a closure.
 *
 *  `template` is the sole payload for `affected: "predicate"` entries — a
 *  predicate with no template to evaluate is unrepresentable, which is the
 *  point. */
export type ContinuousEffectPayload =
    /** An entry in a card (or emblem, or chosen mode) definition's
     *  `staticEffects[]`. `modeId` scopes the index to a mode's own array
     *  (CR 700.2c), mirroring `getEffectiveStaticEffects`. */
    | {
          kind: "template";
          sourceCardId: string;
          effectIndex: number;
          modeId?: string;
      }
    /** CR 613.1b layer 2 */
    | { kind: "control-change"; controllerId: string }
    /** CR 613.1d layer 4 */
    | { kind: "type-add"; types: CardType[] }
    | { kind: "type-remove"; types: CardType[] }
    | { kind: "subtype-add"; subtypes: string[] }
    | { kind: "subtype-set"; subtypes: string[] }
    | { kind: "supertype-set"; supertypes: string[] }
    /** CR 613.1e layer 5. CR 105.3 — a new colour REPLACES every colour the
     *  object had (`color-set`); a grant UNIONS (`color-add`). */
    | { kind: "color-set"; colors: Color[] }
    | { kind: "color-add"; colors: Color[] }
    /** CR 613.1f layer 6 */
    | { kind: "keyword-grant"; keyword: string }
    | { kind: "keyword-remove"; keyword: string }
    | { kind: "ability-loss" }
    | { kind: "activated-grant"; sourceCardId: string; abilityId: string }
    | { kind: "triggered-grant"; sourceCardId: string; abilityId: string }
    /** CR 613.4 layer 7 */
    | { kind: "pt-set"; power: number; toughness: number }
    | { kind: "pt-modify"; power: number; toughness: number }
    | { kind: "pt-switch" };

/** One continuous effect. */
export type ContinuousEffect = ContinuousEffectSlot & {
    /** Stable identity for removal and for the S2-S4 migrations to key their
     *  own bookkeeping off. Deterministic (`ce-N`) so replays reproduce it. */
    id: string;
    /** CR 613.7 layer timestamp. The SAME monotonic sequence the engine
     *  already mints for `staticSeq` / `grantedStaticAbilities[].seq` /
     *  `abilitiesSuppressedBy[].seq` (`allocStaticTimestamp`, `gre/state.ts`)
     *  — deliberately not a second counter, or a registry entry and a
     *  materialised grant could tie instead of ordering. */
    timestamp: number;
    expiry: ContinuousEffectExpiry;
    affected: ContinuousEffectAffected;
    payload: ContinuousEffectPayload;
    /** CR 604.3 — this effect comes from a characteristic-defining ability.
     *  Load-bearing for CR 613.8a clause (c), which makes a dependency exist
     *  only when NEITHER effect is from a CDA or BOTH are. The dependency
     *  algorithm itself is a documented divergence tracked by #2068; the flag
     *  ships now because retrofitting it onto entries the migrations have
     *  already written would mean a second pass over every producer. */
    characteristicDefining: boolean;
    /** The player the effect's controller-scoped predicates resolve against
     *  (CR 611.2 — the controller of the spell or ability that created it, or
     *  the controller of the object whose static ability generates it).
     *  Optional: an effect with no controller-relative clause needs none. */
    controllerId?: string;
};

/** CR 613.7 — the ONE timestamp comparison in the codebase. "An effect with an
 *  earlier timestamp is applied before an effect with a later timestamp."
 *
 *  Ties are impossible by construction (`allocStaticTimestamp` mints strictly
 *  greater than every live stamp), so `id` breaks them only to keep the sort
 *  total and deterministic — never as a rule. */
export function compareContinuousEffects(
    a: ContinuousEffect,
    b: ContinuousEffect
): number {
    if (a.timestamp !== b.timestamp) return a.timestamp - b.timestamp;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

/** Every registry entry applying in `layer` (and, for layer 7, `sublayer`),
 *  in CR 613.7 timestamp order.
 *
 *  This is the single ordering authority the S2-S4 migrations consume. No
 *  slice may re-derive ordering by comparing `staticSeq` inline — that ad-hoc
 *  per-site comparison is exactly what #1715 had to harden one site at a time.
 *
 *  Layer 7 REQUIRES a sublayer (CR 613.4 orders within sublayers), so the
 *  overloads make an unsublayered layer-7 query a type error rather than a
 *  silently-wrong whole-layer sweep. */
export function continuousEffectsInLayer(
    state: GameState,
    layer: 7,
    sublayer: ContinuousEffectSublayer
): ContinuousEffect[];
export function continuousEffectsInLayer(
    state: GameState,
    layer: Exclude<ContinuousEffectLayer, 7>
): ContinuousEffect[];
export function continuousEffectsInLayer(
    state: GameState,
    layer: ContinuousEffectLayer,
    sublayer?: ContinuousEffectSublayer
): ContinuousEffect[] {
    const entries = state.continuousEffects;
    if (!entries?.length) return [];
    return entries
        .filter(
            (e) =>
                e.layer === layer &&
                (sublayer === undefined || e.sublayer === sublayer)
        )
        .sort(compareContinuousEffects);
}
