// Limited Event play phase opens (PRD #1628, ADR 0076, issue #1644):
// "completing the last seat's deck moves the event to `playing` and creates
// round 1 with exactly one pairing slot per seat".
//
// The project has no convex-test harness (see `convex/__tests__/adminAuth.test.ts`),
// so — exactly as `limitedEvents.test.ts` and `limitedChallenge.test.ts` do —
// this drives the EXACT exported functions `openPlayPhaseIfReady`
// (`convex/limitedEvents.ts`) calls, in the SAME order, against the REAL card
// registry and the REAL checked-in LEA Booster Config. Every observable claim
// is then asserted THROUGH `projectLimitedEvent`, the seam the client actually
// receives — never a hand-built view.
import { describe, it, expect } from "vitest";
import { resolveDeckCardMeta, tryGetDefinition } from "../cards";
import { getCardColorIdentity } from "../cards/colors";
import { manaValue } from "../gre/constants";
import { makeRng } from "../gre/rng";
import { computeBotAutoBuiltDeck } from "../limited/autoBuild";
import type { GetCardEvalMeta } from "../limited/botDrafter";
import { computeEventCompletion } from "../limited/completion";
import {
    projectLimitedEvent,
    type LimitedEventRow,
} from "../limited/eventProjection";
import {
    buildEmptySeats,
    assignFreeSeat,
    fillBotSeats,
    generateSealedPools,
    type ResolveCardMeta,
} from "../limited/eventLogic";
import { resolveMatchFormat } from "../limited/matchFormat";
import { evaluateDeckStrength, type DeckStrength } from "../limited/matchSim";
import { getRuntimeBoosterConfig } from "../limited/registry";
import { openRound, type ResolveSeatStrength } from "../limited/rounds";
import { basicLandsForColors } from "../cards/colors";
import { getCardByName, getPrintingsForCard } from "../cards";
import type { Color } from "../cards/types";
import type { ResolveBasicLand } from "../limited/autoBuild";

// ── The exact resolver wiring `convex/limitedEvents.ts` injects ──────────────

const resolveCardMeta: ResolveCardMeta = (scryfallId) => {
    const def = tryGetDefinition(scryfallId);
    if (!def) return null;
    const meta = resolveDeckCardMeta(scryfallId);
    return meta ? { cardId: meta.cardId, cardName: def.name } : null;
};

const getCardEvalMeta: GetCardEvalMeta = (scryfallId) => {
    const meta = resolveDeckCardMeta(scryfallId);
    if (!meta) return null;
    const def = tryGetDefinition(meta.cardId);
    if (!def) return null;
    return {
        cardId: meta.cardId,
        colors: getCardColorIdentity(def),
        manaValue: manaValue(def.manaCost),
        rarity: meta.rarity,
    };
};

const getAutoBuildCardMeta = (scryfallId: string) => {
    const meta = resolveDeckCardMeta(scryfallId);
    if (!meta) return null;
    const def = tryGetDefinition(meta.cardId);
    if (!def) return null;
    return {
        cardId: meta.cardId,
        colors: getCardColorIdentity(def),
        manaValue: manaValue(def.manaCost),
        rarity: meta.rarity,
        isLand: def.types.includes("Land"),
    };
};

function resolveBasicLandFor(setCode: string): ResolveBasicLand {
    return (color: Color) => {
        const name = basicLandsForColors([color])[0];
        const def = getCardByName(name);
        const printing = getPrintingsForCard(def.id).find(
            (p) => p.setCode === setCode
        );
        return { cardId: printing?.printId ?? def.id, cardName: name };
    };
}

/** A real 8-seat LEA Sealed event with one human (seat 0) and seven bots,
 *  Pools generated by the seeded generator off the checked-in Booster Config —
 *  i.e. the state `startLimitedEvent` leaves behind. */
function startedEvent(seatCount = 8): LimitedEventRow {
    const packSlots = ["lea"];
    const sealedBoosterCount = 6;
    const seats = generateSealedPools(
        fillBotSeats(
            assignFreeSeat(buildEmptySeats(seatCount), "user1", "Alice")
        ),
        packSlots,
        sealedBoosterCount,
        getRuntimeBoosterConfig,
        resolveCardMeta,
        makeRng(1644)
    );
    return {
        _id: "event-1644",
        createdBy: "user1",
        type: "sealed",
        status: "started",
        seatCount,
        packSlots,
        sealedBoosterCount,
        matchFormat: "bo3",
        seats,
        createdAt: 0,
        updatedAt: 0,
    };
}

/** `openPlayPhaseIfReady`'s body, minus the three `ctx.db` calls (read the
 *  row, read the human decks, write the patch) — the pure core, wired with the
 *  same real resolvers the mutation injects. `humanSeatsWithDeck` stands in
 *  for `loadHumanDecksBySeat`'s result. */
function openPlayPhase(
    event: LimitedEventRow,
    humanSeatsWithDeck: ReadonlySet<number>,
    now = 1_700_000_000_000
): LimitedEventRow | null {
    const eventContext = {
        type: event.type,
        status: event.status,
        draftCompletedAt: event.draftCompletedAt,
    };
    const completion = computeEventCompletion(
        event.seats,
        eventContext,
        (seatIndex) => humanSeatsWithDeck.has(seatIndex)
    );
    if (!completion.completed) return null;

    const resolveBasicLand = resolveBasicLandFor(event.packSlots[0] ?? "");
    const cache = new Map<number, DeckStrength>();
    const seatStrength: ResolveSeatStrength = (seatIndex) => {
        const cached = cache.get(seatIndex);
        if (cached) return cached;
        const seat = event.seats.find((s) => s.seatIndex === seatIndex);
        const deck = seat
            ? computeBotAutoBuiltDeck(
                  seat,
                  eventContext,
                  getAutoBuildCardMeta,
                  resolveBasicLand
              )
            : null;
        const strength = evaluateDeckStrength(
            deck?.cards ?? [],
            getCardEvalMeta
        );
        cache.set(seatIndex, strength);
        return strength;
    };

    const round = openRound({
        eventId: event._id,
        roundNumber: 1,
        seats: event.seats,
        previousRounds: [],
        matchFormat: resolveMatchFormat(event.matchFormat),
        startedAt: now,
        roundDeadlineMinutes: event.roundDeadlineMinutes,
        seatStrength,
    });

    return {
        ...event,
        status: "playing",
        currentRound: round.roundNumber,
        rounds: [round],
        updatedAt: now,
    };
}

describe("Limited Event play phase opens (PRD #1628, issue #1644)", () => {
    it("stays in the deckbuild phase while the human seat has no deck", () => {
        // Every bot seat is deck-ready the instant the Pool is final; the one
        // human seat is what the table is waiting on.
        expect(openPlayPhase(startedEvent(), new Set())).toBeNull();
    });

    it("the last seat's deck flips the event to playing with round 1 paired", () => {
        const opened = openPlayPhase(startedEvent(), new Set([0]))!;

        expect(opened.status).toBe("playing");
        expect(opened.currentRound).toBe(1);
        expect(opened.rounds).toHaveLength(1);
        // Exactly one pairing slot per seat: 8 seats -> 4 pairings.
        const seatsPaired = opened.rounds![0].pairings.flatMap((p) =>
            p.seatB === undefined ? [p.seatA] : [p.seatA, p.seatB]
        );
        expect(seatsPaired.sort((a, b) => a - b)).toEqual([
            0, 1, 2, 3, 4, 5, 6, 7,
        ]);
    });

    it("a table of 1 human + 7 bots leaves ONLY the human's pairing pending", () => {
        const opened = openPlayPhase(startedEvent(), new Set([0]))!;
        const pairings = opened.rounds![0].pairings;

        const undecided = pairings.filter((p) => p.result === undefined);
        expect(undecided).toHaveLength(1);
        expect(undecided[0].seatA === 0 || undecided[0].seatB === 0).toBe(true);
        for (const decided of pairings.filter((p) => p.result !== undefined)) {
            expect(decided.result!.source).toBe("simulated");
            // Bo3: someone reached two game wins.
            expect(Math.max(decided.result!.winsA, decided.result!.winsB)).toBe(
                2
            );
        }
    });

    it("an odd table records the bye as a win, and the round still covers every seat", () => {
        const opened = openPlayPhase(startedEvent(7), new Set([0]))!;
        const byes = opened.rounds![0].pairings.filter(
            (p) => p.seatB === undefined
        );

        expect(byes).toHaveLength(1);
        expect(byes[0].result).toEqual({ winsA: 2, winsB: 0, source: "bye" });
    });

    it("re-running the open on the SAME event reproduces every simulated result", () => {
        const first = openPlayPhase(startedEvent(), new Set([0]))!;
        const second = openPlayPhase(startedEvent(), new Set([0]))!;

        expect(second.rounds).toEqual(first.rounds);
    });

    it("stores the round deadline only when the event configured one", () => {
        const noDeadline = openPlayPhase(startedEvent(), new Set([0]))!;
        expect(noDeadline.rounds![0].deadlineAt).toBeUndefined();

        const withDeadline = openPlayPhase(
            { ...startedEvent(), roundDeadlineMinutes: 50 },
            new Set([0]),
            1000
        )!;
        expect(withDeadline.rounds![0].deadlineAt).toBe(1000 + 50 * 60_000);
    });
});

describe("the opened round reaches the client through the projection (issue #1644)", () => {
    const opened = openPlayPhase(startedEvent(), new Set([0]))!;

    it("gives the human viewer their own pairing, opponent flagged as a bot", () => {
        const view = projectLimitedEvent(opened, "user1");

        expect(view.status).toBe("playing");
        expect(view.currentRound).toBe(1);
        expect(view.viewerPairing).not.toBeNull();
        expect(view.viewerPairing!.seatIndex).toBe(0);
        expect(view.viewerPairing!.opponentIsBot).toBe(true);
        // Undecided: this is the one match the human still has to play.
        expect(view.viewerPairing!.result).toBeNull();
        expect(view.viewerPairing!.outcome).toBeNull();
        expect(view.viewerPairing!.roundComplete).toBe(false);
    });

    it("puts every pairing and its result on the wire (they are public)", () => {
        const view = projectLimitedEvent(opened, "user1");

        expect(view.rounds).toHaveLength(1);
        expect(view.rounds[0].pairings).toHaveLength(4);
        expect(
            view.rounds[0].pairings.filter((p) => p.result !== undefined)
        ).toHaveLength(3);
    });

    it("feeds the derived standings — the three simulated matches are already scored", () => {
        const view = projectLimitedEvent(opened, "user1");

        expect(view.standings).toHaveLength(8);
        // 3 decided bot pairings = 3 winners at 3 points, 3 losers at 0, and
        // the two seats of the human's undecided pairing at 0.
        expect(view.standings.filter((r) => r.points === 3)).toHaveLength(3);
        expect(
            view.standings.reduce(
                (sum, r) => sum + r.gameWins + r.gameLosses,
                0
            )
            // Every decided Bo3 played 2 or 3 games, counted twice (once per
            // seat).
        ).toBeGreaterThanOrEqual(3 * 2 * 2);
    });
});
