#!/usr/bin/env bun
/**
 * Makes a fresh git worktree runnable.
 *
 * WHY. Three inputs this repo needs at runtime are gitignored, so `git worktree
 * add` produces a tree that looks complete and is not:
 *
 *   - `node_modules/`        — no deps at all.
 *   - `convex/_generated/`   — codegen output. Without it ~216 test FILES fail at
 *                              *import* (`Cannot find module './_generated/api'`).
 *                              The tell is `216 files failed, 0 tests failed`: it
 *                              reads as a catastrophic red baseline and sends you
 *                              debugging the wrong thing for half an hour.
 *   - `.env.local`           — deployment URL; `convex codegen` needs it.
 *   - `.husky/_/`            — husky's hook shims, generated by `prepare`. Absent
 *                              → `core.hooksPath` points at nothing → pre-commit
 *                              never runs → prettier drift reaches the merge-train.
 *
 * It also registers the ONE piece of repo behaviour git refuses to take from a
 * committed file: the merge drivers `.gitattributes` names — `merge=regenerated`
 * (issue #3069) and `merge=cr-ledger` (issue #3768). Merge drivers live in local
 * config by design, so `.gitattributes` can name one but nothing in the repo can
 * define it — this is the only repo-controlled place that can.
 *
 * The rule "copy these from the main checkout" lived in prose in the
 * process-gh-issues skill and was measurably ignored (twice: a phantom red
 * baseline, and a re-gate on format drift). This makes it one idempotent command.
 *
 * Run: bun run worktree:init        (safe to re-run; only fills what's missing)
 *      bun run worktree:init --force  (re-copy even if present)
 *
 * It also seeds the per-tree build caches — `node_modules/.tmp/*.tsbuildinfo`
 * and the eslint result cache — from the primary checkout (issue #3776, ADR
 * 0136 §9), so the first `check:ts` and `lint` in this tree are incremental
 * instead of cold. Both validate by content, so a stale seed is safe; the
 * mechanism and the measurements live in `scripts/lib/worktree-seed.ts`.
 *
 * Zero imports beyond node builtins ON PURPOSE (transitively — the one repo
 * module it imports is builtins-only too, and the test pins both) — it must
 * run in a worktree that has no node_modules yet.
 */
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { seedWorktreeCaches } from "./lib/worktree-seed";

const force = process.argv.includes("--force");
const cwd = process.cwd();

function git(...args: string[]): string {
    const r = spawnSync("git", args, { encoding: "utf8", cwd });
    if (r.status !== 0) {
        throw new Error(`git ${args.join(" ")} failed: ${r.stderr.trim()}`);
    }
    return r.stdout.trim();
}

function run(cmd: string, args: string[]): boolean {
    const r = spawnSync(cmd, args, { stdio: "inherit", cwd });
    return r.status === 0;
}

/**
 * The primary checkout, i.e. the one that owns `.git/`. In a linked worktree
 * `--git-common-dir` is an absolute path to `<primary>/.git`; in the primary
 * itself it is the relative `.git`. That difference IS the "am I a worktree?"
 * test — no path-name heuristics.
 */
function primaryCheckout(): string | null {
    const common = git("rev-parse", "--git-common-dir");
    if (!common.startsWith("/")) return null; // we ARE the primary checkout
    return dirname(resolve(common));
}

const done: string[] = [];
const skipped: string[] = [];
const failed: string[] = [];

const primary = primaryCheckout();

// ── gitignored inputs copied from the primary checkout ──────────────────────
// node_modules is deliberately NOT copied — `bun install` below is correct and
// nearly free once bun's global cache is warm, and a copied tree can carry
// stale platform binaries.
// `optional` entries are nice-to-have: the Full Catalogue is regenerable
// (`bun run catalogue:ensure`, which `dev`/`build` run anyway), so a primary
// checkout that never generated it must not fail the bootstrap — copying just
// saves this worktree a ~1 MB Scryfall download.
//
// The Full Catalogue is a DIRECTORY holding one content-addressed artifact
// since issue #3500, and it is copied whole rather than by file name — the name
// is a content hash, so the primary's differs from this worktree's whenever the
// two branches carry different generations. It is skipped outright when the
// destination already exists (the normal case: the artifact is committed), so
// this can never leave two artifacts behind, which is the one state the
// client's build-time glob refuses to resolve.
const COPIES = [
    { from: "convex/_generated", to: "convex/_generated" },
    { from: ".env.local", to: ".env.local" },
    {
        from: "data/full-catalogue",
        to: "data/full-catalogue",
        optional: true,
    },
] as const;

if (primary) {
    for (const entry of COPIES) {
        const { from, to } = entry;
        const optional = "optional" in entry && entry.optional;
        const src = join(primary, from);
        const dst = join(cwd, to);
        if (existsSync(dst) && !force) {
            skipped.push(`${to} (present)`);
            continue;
        }
        if (!existsSync(src)) {
            if (optional) {
                skipped.push(`${to} (not in primary — regenerable)`);
            } else {
                failed.push(`${to} — not in primary checkout (${src})`);
            }
            continue;
        }
        // `--force` means REPLACE, not merge: copying a directory over an
        // existing one unions their contents, which for the content-addressed
        // Full Catalogue would leave two artifacts and a build-time glob with
        // no way to choose.
        if (existsSync(dst)) rmSync(dst, { recursive: true, force: true });
        mkdirSync(dirname(dst), { recursive: true });
        cpSync(src, dst, { recursive: true });
        done.push(to);
    }
} else {
    skipped.push("copies (this IS the primary checkout)");
}

// ── deps ────────────────────────────────────────────────────────────────────
// `bun install` also fires the `prepare` script, which is what regenerates
// `.husky/_`. Order matters: deps before the husky check below.
if (!existsSync(join(cwd, "node_modules")) || force) {
    if (run("bun", ["install"])) done.push("node_modules (bun install)");
    else failed.push("bun install");
} else {
    skipped.push("node_modules (present)");
}

// ── build caches seeded from the primary (issue #3776) ──────────────────────
// After deps on purpose: `bun install` owns `node_modules/`, and the caches
// live under it. A cache is an optimisation, never an input — a missing or
// unusable source is a skip, and so is anything unexpected: this step cannot
// fail the bootstrap.
if (primary) {
    try {
        const seeded = seedWorktreeCaches({ primary, cwd, force });
        done.push(...seeded.done);
        skipped.push(...seeded.skipped);
    } catch (err) {
        skipped.push(`build caches (seed failed — cold run: ${String(err)})`);
    }
}

// ── git hooks ───────────────────────────────────────────────────────────────
// core.hooksPath is repo-level config SHARED by every worktree, and its value
// (`.husky/_`) is RELATIVE — git resolves it per working tree. So each worktree
// needs its own `.husky/_`, or its commits silently skip lint-staged.
if (!existsSync(join(cwd, ".husky", "_")) || force) {
    if (run("bunx", ["husky"])) done.push(".husky/_ (hook shims)");
    else failed.push("bunx husky");
} else {
    skipped.push(".husky/_ (present)");
}

// ── merge driver for regenerated artifacts (issue #3069) ────────────────────
// `.gitattributes` marks the generated `data/` artifacts that carry whole-file
// state with `merge=regenerated`; git resolves that name against LOCAL config,
// which is not committed, so without this step the attribute silently falls
// back to the default text merge and every such rebase conflicts by hand again.
//
// Written to the COMMON config on purpose (no `--worktree`): the object store
// and `config` are shared by every linked worktree, so bootstrapping any one of
// them arms all of them. Idempotent — `git config` overwrites the key.
//
// The name is hand-typed here rather than imported from
// `scripts/lib/generated-artifacts.ts` because this script is node-builtins-only
// so it can run before `bun install`; `generated-artifact-merge.test.ts` pins
// the two together.
const MERGE_DRIVER_NAME = "regenerated";
const MERGE_DRIVER_COMMAND =
    "bun scripts/merge-driver-regenerated.ts %O %A %B %P";
try {
    git(
        "config",
        `merge.${MERGE_DRIVER_NAME}.name`,
        "regenerate generated data/ artifacts instead of merging them (issue #3069)"
    );
    git("config", `merge.${MERGE_DRIVER_NAME}.driver`, MERGE_DRIVER_COMMAND);
    done.push(`merge.${MERGE_DRIVER_NAME} driver (git config)`);
} catch (err) {
    failed.push(
        `git config merge.${MERGE_DRIVER_NAME}.driver — ${String(err)}`
    );
}

// ── merge driver for the CR citation ledger (issue #3768) ───────────────────
// A SECOND, independent driver, for the same reason: `.gitattributes` names
// `merge=cr-ledger` for `data/cr/citations-ledger.json` and git resolves that
// name against local config only. Without this step the ledger falls back to
// the default text merge, where two branches confirming two citations under
// the same rule id collide in the same sorted hunk.
//
// It is NOT the regenerated driver and must never be aliased to it: that one
// takes ours and defers to a regeneration, and this file has no generator —
// taking a side would silently drop the other branch's confirmations.
const LEDGER_MERGE_DRIVER_NAME = "cr-ledger";
const LEDGER_MERGE_DRIVER_COMMAND =
    "bun scripts/merge-driver-cr-ledger.ts %O %A %B %P";
try {
    git(
        "config",
        `merge.${LEDGER_MERGE_DRIVER_NAME}.name`,
        "merge the CR citation ledger as a keyed set of facts (issue #3768)"
    );
    git(
        "config",
        `merge.${LEDGER_MERGE_DRIVER_NAME}.driver`,
        LEDGER_MERGE_DRIVER_COMMAND
    );
    done.push(`merge.${LEDGER_MERGE_DRIVER_NAME} driver (git config)`);
} catch (err) {
    failed.push(
        `git config merge.${LEDGER_MERGE_DRIVER_NAME}.driver — ${String(err)}`
    );
}

// ── receipt ─────────────────────────────────────────────────────────────────
const label = primary ? `worktree of ${primary}` : "primary checkout";
console.log(`\nworktree:init — ${label}`);
for (const d of done) console.log(`  ✓ ${d}`);
for (const s of skipped) console.log(`  · ${s}`);
for (const f of failed) console.log(`  ✗ ${f}`);

if (failed.length > 0) {
    console.error(
        `\n✗ ${failed.length} step(s) failed — this tree is not runnable yet.`
    );
    process.exit(1);
}
console.log("\n✓ ready — run: bunx vitest run <paths> && bun run check:pr\n");
