#!/usr/bin/env bun
/**
 * Makes a fresh git worktree runnable.
 *
 * WHY. Three inputs this repo needs at runtime are gitignored, so `git worktree
 * add` produces a tree that looks complete and is not:
 *
 *   - `node_modules/`        — no deps at all.
 *   - `convex/_generated/`   — codegen output. Without it ~216 test FILES fail at
 *                              *import* (`Cannot find module './_generated/api'`).
 *                              The tell is `216 files failed, 0 tests failed`: it
 *                              reads as a catastrophic red baseline and sends you
 *                              debugging the wrong thing for half an hour.
 *   - `.env.local`           — deployment URL; `convex codegen` needs it.
 *   - `.husky/_/`            — husky's hook shims, generated by `prepare`. Absent
 *                              → `core.hooksPath` points at nothing → pre-commit
 *                              never runs → prettier drift reaches the merge-train.
 *
 * The rule "copy these from the main checkout" lived in prose in the
 * process-gh-issues skill and was measurably ignored (twice: a phantom red
 * baseline, and a re-gate on format drift). This makes it one idempotent command.
 *
 * Run: bun run worktree:init        (safe to re-run; only fills what's missing)
 *      bun run worktree:init --force  (re-copy even if present)
 *
 * Zero imports beyond node builtins ON PURPOSE — it must run in a worktree that
 * has no node_modules yet.
 */
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const force = process.argv.includes("--force");
const cwd = process.cwd();

function git(...args: string[]): string {
    const r = spawnSync("git", args, { encoding: "utf8", cwd });
    if (r.status !== 0) {
        throw new Error(`git ${args.join(" ")} failed: ${r.stderr.trim()}`);
    }
    return r.stdout.trim();
}

function run(cmd: string, args: string[]): boolean {
    const r = spawnSync(cmd, args, { stdio: "inherit", cwd });
    return r.status === 0;
}

/**
 * The primary checkout, i.e. the one that owns `.git/`. In a linked worktree
 * `--git-common-dir` is an absolute path to `<primary>/.git`; in the primary
 * itself it is the relative `.git`. That difference IS the "am I a worktree?"
 * test — no path-name heuristics.
 */
function primaryCheckout(): string | null {
    const common = git("rev-parse", "--git-common-dir");
    if (!common.startsWith("/")) return null; // we ARE the primary checkout
    return dirname(resolve(common));
}

const done: string[] = [];
const skipped: string[] = [];
const failed: string[] = [];

const primary = primaryCheckout();

// ── gitignored inputs copied from the primary checkout ──────────────────────
// node_modules is deliberately NOT copied — `bun install` below is correct and
// nearly free once bun's global cache is warm, and a copied tree can carry
// stale platform binaries.
// `optional` entries are nice-to-have: the Full Catalogue is regenerable
// (`bun run catalogue:ensure`, which `dev`/`build` run anyway), so a primary
// checkout that never generated it must not fail the bootstrap — copying just
// saves this worktree a ~1 MB Scryfall download.
const COPIES = [
    { from: "convex/_generated", to: "convex/_generated" },
    { from: ".env.local", to: ".env.local" },
    {
        from: "public/data/full-catalogue.json.gz",
        to: "public/data/full-catalogue.json.gz",
        optional: true,
    },
] as const;

if (primary) {
    for (const entry of COPIES) {
        const { from, to } = entry;
        const optional = "optional" in entry && entry.optional;
        const src = join(primary, from);
        const dst = join(cwd, to);
        if (existsSync(dst) && !force) {
            skipped.push(`${to} (present)`);
            continue;
        }
        if (!existsSync(src)) {
            if (optional) {
                skipped.push(`${to} (not in primary — regenerable)`);
            } else {
                failed.push(`${to} — not in primary checkout (${src})`);
            }
            continue;
        }
        mkdirSync(dirname(dst), { recursive: true });
        cpSync(src, dst, { recursive: true });
        done.push(to);
    }
} else {
    skipped.push("copies (this IS the primary checkout)");
}

// ── deps ────────────────────────────────────────────────────────────────────
// `bun install` also fires the `prepare` script, which is what regenerates
// `.husky/_`. Order matters: deps before the husky check below.
if (!existsSync(join(cwd, "node_modules")) || force) {
    if (run("bun", ["install"])) done.push("node_modules (bun install)");
    else failed.push("bun install");
} else {
    skipped.push("node_modules (present)");
}

// ── git hooks ───────────────────────────────────────────────────────────────
// core.hooksPath is repo-level config SHARED by every worktree, and its value
// (`.husky/_`) is RELATIVE — git resolves it per working tree. So each worktree
// needs its own `.husky/_`, or its commits silently skip lint-staged.
if (!existsSync(join(cwd, ".husky", "_")) || force) {
    if (run("bunx", ["husky"])) done.push(".husky/_ (hook shims)");
    else failed.push("bunx husky");
} else {
    skipped.push(".husky/_ (present)");
}

// ── receipt ─────────────────────────────────────────────────────────────────
const label = primary ? `worktree of ${primary}` : "primary checkout";
console.log(`\nworktree:init — ${label}`);
for (const d of done) console.log(`  ✓ ${d}`);
for (const s of skipped) console.log(`  · ${s}`);
for (const f of failed) console.log(`  ✗ ${f}`);

if (failed.length > 0) {
    console.error(
        `\n✗ ${failed.length} step(s) failed — this tree is not runnable yet.`
    );
    process.exit(1);
}
console.log("\n✓ ready — run: bunx vitest run <paths> && bun run check:pr\n");
