#!/usr/bin/env bun
/**
 * Generate the committed Vintage Cube name list module from the worklist.
 *
 * Cubes are seeded into the `cubeLists` DB table by an `internalMutation`
 * (`cubes:seedVintageCube`), but a Convex function can't read the filesystem —
 * so the card NAMES must live in a TS module it can import. The worklist
 * `data/worklists/vintage-cube.txt` (one name per line, `#` comments) is the
 * human-editable source; this script projects it into
 * `convex/cubes/vintageCubeNames.ts`.
 *
 * Run after editing the worklist:
 *   bun run scripts/gen-vintage-cube.ts
 * then re-seed the DB:
 *   npx convex run cubes:seedVintageCube
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const SRC = resolve(import.meta.dir, "../data/worklists/vintage-cube.txt");
const OUT = resolve(import.meta.dir, "../convex/cubes/vintageCubeNames.ts");

const names = readFileSync(SRC, "utf8")
    .split("\n")
    .map((line) => line.replace(/#.*$/, "").trim())
    .filter((line) => line.length > 0);

const seen = new Set<string>();
const deduped = names.filter((n) => {
    const key = n.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
});

const body = deduped.map((n) => `    ${JSON.stringify(n)},`).join("\n");
const content = `// GENERATED by scripts/gen-vintage-cube.ts from
// data/worklists/vintage-cube.txt — do not edit by hand. Re-run the script
// after editing the worklist, then \`npx convex run cubes:seedVintageCube\`.
//
// The Vintage Cube card NAMES, resolved to the built pool at read time by
// \`resolveCubeMembership\` (unbuilt names are dropped from the filter).

export const VINTAGE_CUBE_NAMES: readonly string[] = [
${body}
];
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, content);
console.log(`Wrote ${deduped.length} names to ${OUT}`);
