#!/usr/bin/env npx tsx
/**
 * Generates the 4ED (Fourth Edition) print set — colour-split modules under
 * `convex/cards/sets/4ed/`.
 *
 * Fourth Edition is a white-bordered core reprint set: it introduces no new
 * cards, so every module is entirely `CardPrint` rows. Each declares the
 * per-edition Scryfall UUID (`printId`) and resolves printId -> definitionId ->
 * a shared CardDefinition that already lives in an implemented set
 * (lea/leb/arn/atq/leg/drk/fem/ice/2ed/3ed). See ADR 0014 and ADR 0043
 * (colour-split directory layout).
 *
 * The script reads the MTGJSON `4ED.json` set file and matches each card by
 * oracle name to its existing CardDefinition via the live catalogue registry
 * (`tryGetCardByName`) — the same resolver the engine uses, so the match is
 * authoritative. It partitions the resulting rows by colour identity derived
 * from the printed mana cost (CR 202.2): monocoloured cards go to their colour
 * module; lands, artifacts and other colourless cards go to colorless.ts;
 * multicoloured cards go to multicolor.ts. Per-printing rarity comes from the
 * 4ED JSON entry.
 *
 * Excluded: the ante cards (ADR 0010) — they carry no print row. Any 4ED card
 * whose CardDefinition is not yet implemented is skipped with a warning; its
 * 4ED print lands automatically once the definition exists.
 *
 * Usage: npx tsx scripts/generate-4ed-prints.mts
 * Output: convex/cards/sets/4ed/{white,blue,black,red,green,multicolor,colorless}.ts
 *         convex/cards/sets/4ed/index.ts (barrel)
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { tryGetCardByName } from "../convex/cards/index.ts";

const SET_CODE = "4ed";
const JSON_PATH = "data/json/4ED.json";
const OUT_DIR = "convex/cards/sets/4ed";

// Ante cards — permanently out of scope (ADR 0010). Documented, never printed.
const ANTE_EXCLUSIONS = ["Bronze Tablet", "Rebirth", "Tempest Efreet"];

const BASIC_LANDS = ["Plains", "Island", "Swamp", "Mountain", "Forest"];

type Colour =
    | "white"
    | "blue"
    | "black"
    | "red"
    | "green"
    | "multicolor"
    | "colorless";

const COLOUR_ORDER: Colour[] = [
    "white",
    "blue",
    "black",
    "red",
    "green",
    "multicolor",
    "colorless",
];

const COLOUR_NAME: Record<string, Colour> = {
    W: "white",
    U: "blue",
    B: "black",
    R: "red",
    G: "green",
};

interface MtgJsonCard {
    name: string;
    number: string;
    rarity?: string;
    colors?: string[];
    supertypes?: string[];
    identifiers: { scryfallId: string };
}

/** camelCase export identifier from a card name, suffixed with the set code.
 *  "Air Elemental" -> airElemental4ed,
 *  "Circle of Protection: Black" -> circleOfProtectionBlack4ed. */
function exportName(name: string, suffixIndex: number): string {
    const cleaned = name
        .replace(/[':,.()/]/g, " ")
        .replace(/-/g, " ")
        .replace(/&/g, " and ");
    const parts = cleaned.split(/\s+/).filter(Boolean);
    let ident = parts
        .map((p, i) =>
            i === 0
                ? p.charAt(0).toLowerCase() + p.slice(1)
                : p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()
        )
        .join("");
    if (/^[0-9]/.test(ident)) ident = "_" + ident;
    return `${ident}${suffixIndex > 1 ? suffixIndex : ""}${SET_CODE}`;
}

/** Colour identity from printed mana cost colours (CR 202.2). */
function colourOf(c: MtgJsonCard): Colour {
    const cols = c.colors ?? [];
    if (cols.length === 0) return "colorless";
    if (cols.length >= 2) return "multicolor";
    return COLOUR_NAME[cols[0]] ?? "colorless";
}

interface Row {
    ident: string;
    printId: string;
    definitionId: string;
    name: string;
    rarity: string;
    colour: Colour;
    isBasic: boolean;
}

const COLOUR_LABEL: Record<Colour, string> = {
    white: "white",
    blue: "blue",
    black: "black",
    red: "red",
    green: "green",
    multicolor: "multicoloured",
    colorless: "colourless (lands, artifacts)",
};

function moduleHeader(colour: Colour): string {
    return `import type { CardPrint } from "../../types";

// 4ED (Fourth Edition) ${COLOUR_LABEL[colour]} cards, split by colour per ADR 0043.
//
// Fourth Edition is a 100% reprint core set — it introduces no new cards — so
// this module is entirely CardPrint entries: each declares the per-edition
// Scryfall UUID (printId) and resolves printId -> definitionId -> a shared
// CardDefinition already implemented in lea/leb/arn/atq/leg/drk/fem/ice/2ed/3ed.
// See ADR 0014. 4ED is the earliest Premodern-legal set (issue #980).
//
// Generated by scripts/generate-4ed-prints.mts from data/json/4ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 4ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: ante cards — ${ANTE_EXCLUSIONS.join(", ")} — are permanently out of
// scope (ADR 0010) and carry no print row. Cards whose CardDefinition is not
// yet implemented are omitted; each lands automatically once its definition
// exists.
`;
}

function emit(r: Row): string {
    return `export const ${r.ident}: CardPrint = {
    printId: "${r.printId}",
    definitionId: "${r.definitionId}", // ${r.name}
    setCode: "${SET_CODE}",
    rarity: "${r.rarity}",
};
`;
}

function main(): void {
    const raw = JSON.parse(readFileSync(resolve(JSON_PATH), "utf-8"));
    const cards: MtgJsonCard[] = raw.data.cards;
    const ante = new Set(ANTE_EXCLUSIONS);
    const numOf = (c: MtgJsonCard) => parseInt(c.number, 10) || 0;

    const nonBasic = cards
        .filter((c) => !c.supertypes?.includes("Basic"))
        .sort((a, b) => numOf(a) - numOf(b));
    const basics = cards
        .filter((c) => c.supertypes?.includes("Basic"))
        .sort((a, b) => numOf(a) - numOf(b));

    const skipped: string[] = [];
    const seen = new Map<string, number>();
    const rows: Row[] = [];

    const makeRow = (c: MtgJsonCard, isBasic: boolean): Row => {
        const count = (seen.get(c.name) ?? 0) + 1;
        seen.set(c.name, count);
        return {
            ident: exportName(c.name, count),
            printId: c.identifiers.scryfallId,
            definitionId: tryGetCardByName(c.name)!.id,
            name: c.name,
            rarity: c.rarity ?? "common",
            colour: isBasic ? "colorless" : colourOf(c),
            isBasic,
        };
    };

    for (const c of nonBasic) {
        if (ante.has(c.name)) continue; // ADR 0010
        if (!tryGetCardByName(c.name)) {
            skipped.push(c.name);
            continue;
        }
        rows.push(makeRow(c, false));
    }
    for (const c of basics) {
        if (!BASIC_LANDS.includes(c.name)) continue;
        if (!tryGetCardByName(c.name)) {
            skipped.push(c.name);
            continue;
        }
        rows.push(makeRow(c, true));
    }

    mkdirSync(resolve(OUT_DIR), { recursive: true });

    const nonEmpty: Colour[] = [];
    for (const colour of COLOUR_ORDER) {
        const colourRows = rows.filter(
            (r) => r.colour === colour && !r.isBasic
        );
        const basicRows =
            colour === "colorless" ? rows.filter((r) => r.isBasic) : [];
        if (colourRows.length === 0 && basicRows.length === 0) continue;
        nonEmpty.push(colour);

        let body = colourRows.map(emit).join("\n");
        if (basicRows.length) {
            body +=
                "\n// Basic lands (art variants — one print per collector number).\n\n" +
                basicRows.map(emit).join("\n");
        }
        writeFileSync(
            resolve(OUT_DIR, `${colour}.ts`),
            moduleHeader(colour) + "\n" + body
        );
    }

    const barrel = `// 4ED set barrel — re-exports every colour module so the registry's
// \`import * as fourthEdition from "./sets/4ed"\` resolves here unchanged
// (ADR 0043). 4ED is a reprint-only core set; only the colour modules with
// CardPrint entries exist.
//
// Generated by scripts/generate-4ed-prints.mts — re-run to regenerate.

${nonEmpty.map((c) => `export * from "./${c}";`).join("\n")}
`;
    writeFileSync(resolve(OUT_DIR, "index.ts"), barrel);

    const total = rows.length;
    console.log(
        `✓ wrote ${OUT_DIR}/: ${total} prints across ${nonEmpty.length} colour module(s) [${nonEmpty.join(", ")}]`
    );
    console.log(`  ante exclusions (ADR 0010): ${ANTE_EXCLUSIONS.join(", ")}`);
    if (skipped.length) {
        console.warn(
            `  ⚠ ${skipped.length} card(s) skipped (no CardDefinition yet):\n    ` +
                skipped.sort().join("\n    ")
        );
    }
}

main();
