import { describe, expect, it } from "vitest";
import { getDefinition, registerTokenDefinition } from "../../cards";
import type { ActivatedAbility, CardDefinition } from "../../cards/types";
import {
    makeInstance,
    makePlayer,
    makeState,
    pushSpell,
} from "../../cards/__tests__/setup";
import type { CardInstanceState, GameState } from "../state";
import { resolveTopOfStack } from "../state";
import { finalizeCleanup } from "../phases";
import { getEffectiveActivatedAbilities } from "../activatedAbilities";
import {
    getEffectiveActivatedAbilities as gameGetEffectiveActivatedAbilities,
    tapForPayment,
    tapSourceIntoPayment,
} from "../../game";
import {
    getActivatedManaAbility,
    getManaTapOptionsDetailed,
    getProducibleColors,
    hasManaAbility,
    isUntappedManaSource,
    manaGateBattlefields,
} from "../constants";
import { getProducibleManaOptions, getLegalActions } from "../rules";
import { validateEffectScript } from "../effects/validate";
import { projectPublicState } from "../../gameProjections";
import { forest } from "../../cards/sets/lea/colorless";
import type { Id } from "../../_generated/dataModel";
import {
    gameStateSeed,
    makeMutationCtx,
    runMutation,
} from "../../__tests__/gameMutationHarness";

// ── Fixtures ────────────────────────────────────────────────────────────────
//
// No shipped card grants a MANA ability (issue #1880: the gap is latent, which
// is exactly why it went unnoticed), so the scenario is built from synthetic
// definitions registered into the same registry `getDefinition` reads — the
// pattern `transform.test.ts` already uses.

const MANA_TEMPLATE_ID = "test-1880-add-c";
const MANA_TEMPLATE: ActivatedAbility = {
    id: MANA_TEMPLATE_ID,
    oracleText: "{T}: Add {C}.",
    cost: { tap: true },
    useStack: false,
    manaProduced: { C: 1 },
};

/** "Target permanent gains '{T}: Add {C}.'" — NO duration clause, so the grant
 *  is INDEFINITE (CR 611.2c: generated by a resolving ability, it does not
 *  depend on its source and never expires on its own). This is the Urza's Saga
 *  chapter I shape. */
const INDEFINITE_GRANTER_ID = "test-1880-indefinite-granter";
const indefiniteGranter: CardDefinition = {
    id: INDEFINITE_GRANTER_ID,
    name: "Test Indefinite Mana Grant",
    rarity: "common",
    manaCost: { G: 1 },
    types: ["Sorcery"],
    oracleText: 'Target permanent gains "{T}: Add {C}."',
    targetRequirement: { type: "Creature", count: 1 },
    effects: [
        {
            op: "grantAbility",
            target: { target: 0 },
            grantedActivatedId: MANA_TEMPLATE_ID,
        },
    ],
    grantTemplates: [MANA_TEMPLATE],
};
registerTokenDefinition(indefiniteGranter);

/** The duration-scoped sibling (Touch of Vitae's shape) — same grant, "until
 *  end of turn". */
const EOT_GRANTER_ID = "test-1880-eot-granter";
const eotGranter: CardDefinition = {
    id: EOT_GRANTER_ID,
    name: "Test Until-EOT Mana Grant",
    rarity: "common",
    manaCost: { G: 1 },
    types: ["Sorcery"],
    oracleText: 'Target permanent gains "{T}: Add {C}." until end of turn.',
    targetRequirement: { type: "Creature", count: 1 },
    effects: [
        {
            op: "grantAbility",
            target: { target: 0 },
            grantedActivatedId: MANA_TEMPLATE_ID,
            duration: { phase: "end-of-turn" },
        },
    ],
    grantTemplates: [MANA_TEMPLATE],
};
registerTokenDefinition(eotGranter);

/** A vanilla recipient with NO mana ability and NO native activated ability. */
const RECIPIENT_ID = "test-1880-recipient";
registerTokenDefinition({
    id: RECIPIENT_ID,
    name: "Test Recipient",
    rarity: "common",
    manaCost: { G: 1 },
    types: ["Creature"],
    subtypes: ["Bear"],
    power: 2,
    toughness: 2,
});

/** A recipient that DOES have a native activated ability, so the
 *  `abilitiesSuppressedBy` drop is observable as "native gone, granted kept". */
const NATIVE_ABILITY_ID = "test-1880-native-pump";
const ABILITY_HOST_ID = "test-1880-ability-host";
registerTokenDefinition({
    id: ABILITY_HOST_ID,
    name: "Test Ability Host",
    rarity: "common",
    manaCost: { R: 1 },
    types: ["Creature"],
    subtypes: ["Goblin"],
    power: 1,
    toughness: 1,
    activatedAbilities: [
        {
            id: NATIVE_ABILITY_ID,
            oracleText: "{R}: This creature gets +1/+0 until end of turn.",
            cost: { mana: { R: 1 } },
            useStack: true,
            effects: [
                {
                    op: "pump",
                    target: { ref: "$source" },
                    power: 1,
                    toughness: 0,
                    duration: { phase: "end-of-turn" },
                },
            ],
        },
    ],
});

/** A granted mana ability that carries a RIDER — its own `{1}` activation
 *  cost. The mana-tap CHOICE branch (`resolveManaTapChoice`) must resolve the
 *  option's `abilityId` against the POST-LAYER set to find it; resolving
 *  against the printed list alone returned `null`, which the caller cannot
 *  tell apart from an intrinsic basic-subtype pick, so the `{1}` (and every
 *  other rider) was silently skipped and this granted ability made FREE mana. */
const COSTED_TEMPLATE_ID = "test-1880-pay-1-add-w";
const COSTED_TEMPLATE: ActivatedAbility = {
    id: COSTED_TEMPLATE_ID,
    oracleText: "{1}, {T}: Add {W}.",
    cost: { tap: true, mana: { X: 1 } },
    useStack: false,
    manaProduced: { W: 1 },
};

const COSTED_GRANTER_ID = "test-1880-costed-granter";
const costedGranter: CardDefinition = {
    id: COSTED_GRANTER_ID,
    name: "Test Costed Mana Grant",
    rarity: "common",
    manaCost: { G: 1 },
    types: ["Sorcery"],
    oracleText: 'Target land gains "{1}, {T}: Add {W}."',
    targetRequirement: { type: "Land", count: 1 },
    effects: [
        {
            op: "grantAbility",
            target: { target: 0 },
            grantedActivatedId: COSTED_TEMPLATE_ID,
        },
    ],
    grantTemplates: [COSTED_TEMPLATE],
};
registerTokenDefinition(costedGranter);

/** A {1} spell — payable ONLY by the granted `{T}: Add {C}` in these tests. */
const ONE_MANA_SPELL_ID = "test-1880-one-mana-spell";
registerTokenDefinition({
    id: ONE_MANA_SPELL_ID,
    name: "Test One Mana Artifact",
    rarity: "common",
    manaCost: { X: 1 },
    types: ["Artifact"],
});

/** Resolves `granterId` targeting `recipient`, returning the mutated state. */
function resolveGrant(
    granterId: string,
    recipient: CardInstanceState,
    state: GameState
): void {
    pushSpell(state, granterId, "p1", [
        { type: "permanent", id: recipient.id },
    ]);
    resolveTopOfStack(state);
}

function boardWithGrant(granterId: string | null): {
    state: GameState;
    recipient: CardInstanceState;
} {
    const recipient = makeInstance(RECIPIENT_ID, {
        id: "recipient",
        controllerId: "p1",
        ownerId: "p1",
        isSummoningSick: false,
    });
    const state = makeState({
        players: [
            makePlayer("p1", {
                battlefield: [recipient],
                hand: [
                    makeInstance(ONE_MANA_SPELL_ID, {
                        id: "spell",
                        controllerId: "p1",
                        ownerId: "p1",
                        zone: "hand",
                    }),
                ],
            }),
            makePlayer("p2"),
        ],
    });
    if (granterId) resolveGrant(granterId, recipient, state);
    return { state, recipient: state.players[0].battlefield[0] };
}

// ── Half 1 — indefinite activated grants (CR 611.2c) ─────────────────────────

describe("grantAbility: indefinite activated-ability grant (CR 611.2c, issue #1880)", () => {
    it("validates with `grantedActivatedId` and NO `duration`", () => {
        expect(validateEffectScript(indefiniteGranter)).toEqual([]);
        // The duration-scoped form stays legal — this relaxes the validator,
        // it does not move the requirement to the other side.
        expect(validateEffectScript(eotGranter)).toEqual([]);
    });

    it("records the grant with no duration and SURVIVES an end-of-turn boundary", () => {
        const { state, recipient } = boardWithGrant(INDEFINITE_GRANTER_ID);
        expect(recipient.grantedActivatedAbilities).toEqual([
            {
                sourceCardId: INDEFINITE_GRANTER_ID,
                abilityId: MANA_TEMPLATE_ID,
            },
        ]);

        // CR 514.2 — the cleanup step's duration purge.
        state.phase = "CLEANUP";
        finalizeCleanup(state);
        expect(
            state.players[0].battlefield[0].grantedActivatedAbilities
        ).toEqual([
            {
                sourceCardId: INDEFINITE_GRANTER_ID,
                abilityId: MANA_TEMPLATE_ID,
            },
        ]);
    });

    it("the duration-scoped sibling still expires at that same boundary (CR 611.2)", () => {
        const { state, recipient } = boardWithGrant(EOT_GRANTER_ID);
        expect(recipient.grantedActivatedAbilities?.[0]?.duration).toEqual({
            phase: "end-of-turn",
        });

        state.phase = "CLEANUP";
        finalizeCleanup(state);
        expect(
            state.players[0].battlefield[0].grantedActivatedAbilities
        ).toBeUndefined();
    });

    it("is idempotent — resolving the same indefinite grant twice adds one entry (CR 113.1)", () => {
        const { state, recipient } = boardWithGrant(INDEFINITE_GRANTER_ID);
        resolveGrant(INDEFINITE_GRANTER_ID, recipient, state);
        expect(
            state.players[0].battlefield[0].grantedActivatedAbilities
        ).toHaveLength(1);
    });

    it("is skipped when the target has left the battlefield (CR 608.2b)", () => {
        const { state, recipient } = boardWithGrant(null);
        pushSpell(state, INDEFINITE_GRANTER_ID, "p1", [
            { type: "permanent", id: recipient.id },
        ]);
        state.players[0].battlefield = [];
        expect(() => resolveTopOfStack(state)).not.toThrow();
        // Not merely "doesn't throw" (which would pass even if the grant were
        // applied anyway): the departed target carries NO grant, and putting
        // it back on the battlefield does not resurrect one.
        expect(recipient.grantedActivatedAbilities).toBeUndefined();
        expect(hasManaAbility(recipient)).toBe(false);
        // The spell left the stack (CR 608.2m) with the whole effect skipped.
        expect(state.stack).toHaveLength(0);
    });
});

// ── Half 2 — a granted mana ability is visible to the planner ────────────────

describe("granted mana abilities reach the mana probes (CR 605.1a, issue #1880)", () => {
    it("without the grant the recipient is not a mana source at all", () => {
        const { state, recipient } = boardWithGrant(null);
        expect(hasManaAbility(recipient)).toBe(false);
        expect(getActivatedManaAbility(recipient)).toBeNull();
        expect(
            getManaTapOptionsDetailed(
                recipient,
                "p1",
                manaGateBattlefields(state),
                { requireTap: true }
            )
        ).toEqual([]);
    });

    it("a permanent granted `{T}: Add {C}` reports hasManaAbility === true", () => {
        const { recipient } = boardWithGrant(INDEFINITE_GRANTER_ID);
        expect(hasManaAbility(recipient)).toBe(true);
        expect(getActivatedManaAbility(recipient)?.id).toBe(MANA_TEMPLATE_ID);
        expect(isUntappedManaSource(recipient)).toBe(true);
    });

    it("the auto-tap solver sees the granted option and its produced mana", () => {
        const { state, recipient } = boardWithGrant(INDEFINITE_GRANTER_ID);
        const battlefields = manaGateBattlefields(state);
        expect(
            getManaTapOptionsDetailed(recipient, "p1", battlefields, {
                requireTap: true,
            })
        ).toEqual([
            {
                mana: { C: 1 },
                source: { kind: "activated", abilityId: MANA_TEMPLATE_ID },
            },
        ]);
        // The planner's own view (`getProducibleManaOptions`) — the list
        // `planManaPayment` pays out of. The map VALUE is the mana-choice
        // index (undefined for a single index-free option), so the assertion
        // is on the produced colour being present at all.
        const producible = getProducibleManaOptions(
            recipient,
            "p1",
            battlefields
        );
        expect(producible.has("C")).toBe(true);
        expect(producible.get("C")).toBeUndefined();
    });

    it("makes an otherwise-unpayable spell castable", () => {
        const before = boardWithGrant(null);
        expect(
            getLegalActions(
                before.state,
                before.state.players[0],
                before.state.players[0].hand[0]
            )
        ).not.toContain("cast");

        const after = boardWithGrant(INDEFINITE_GRANTER_ID);
        expect(
            getLegalActions(
                after.state,
                after.state.players[0],
                after.state.players[0].hand[0]
            )
        ).toContain("cast");
    });

    it("survives the wire projection (the client sees the same mana source)", () => {
        const { state } = boardWithGrant(INDEFINITE_GRANTER_ID);
        const projected = projectPublicState(state, 1, "p1");
        const slim = projected.players
            .flatMap((p) => p.battlefield)
            .find((c) => c.id === "recipient")!;
        expect(hasManaAbility(slim as unknown as CardInstanceState)).toBe(true);
        expect(
            getManaTapOptionsDetailed(
                slim as unknown as CardInstanceState,
                "p1",
                undefined,
                { requireTap: true }
            )
        ).toEqual([
            {
                mana: { C: 1 },
                source: { kind: "activated", abilityId: MANA_TEMPLATE_ID },
            },
        ]);
    });

    it("a permanent under `abilitiesSuppressedBy` has NO mana ability (CR 613.1f)", () => {
        const { state, recipient } = boardWithGrant(INDEFINITE_GRANTER_ID);
        recipient.abilitiesSuppressedBy = ["titanias-song"];
        expect(hasManaAbility(recipient)).toBe(false);
        expect(getActivatedManaAbility(recipient)).toBeNull();
        expect(
            getManaTapOptionsDetailed(
                recipient,
                "p1",
                manaGateBattlefields(state),
                { requireTap: true }
            )
        ).toEqual([]);
    });
});

// ── The `getEffectiveActivatedAbilities` move ────────────────────────────────

describe("getEffectiveActivatedAbilities moved to gre/activatedAbilities (issue #1880)", () => {
    it("`game.ts` re-exports the very same function (every existing caller resolves the same set)", () => {
        expect(gameGetEffectiveActivatedAbilities).toBe(
            getEffectiveActivatedAbilities
        );
    });

    it("returns native + granted abilities, tagging the granted one's source", () => {
        const host = makeInstance(ABILITY_HOST_ID, {
            id: "host",
            controllerId: "p1",
            ownerId: "p1",
            grantedActivatedAbilities: [
                {
                    sourceCardId: INDEFINITE_GRANTER_ID,
                    abilityId: MANA_TEMPLATE_ID,
                },
            ],
        });
        expect(
            getEffectiveActivatedAbilities(host).map((e) => [
                e.ability.id,
                e.grantedSourceCardId,
            ])
        ).toEqual([
            [NATIVE_ABILITY_ID, undefined],
            [MANA_TEMPLATE_ID, INDEFINITE_GRANTER_ID],
        ]);
    });

    it("drops the NATIVE abilities under `abilitiesSuppressedBy` (CR 613.1f) — the drop survived the move", () => {
        const host = makeInstance(ABILITY_HOST_ID, {
            id: "host",
            controllerId: "p1",
            ownerId: "p1",
            abilitiesSuppressedBy: ["titanias-song"],
            grantedActivatedAbilities: [
                {
                    sourceCardId: INDEFINITE_GRANTER_ID,
                    abilityId: MANA_TEMPLATE_ID,
                },
            ],
        });
        expect(
            getEffectiveActivatedAbilities(host).map((e) => e.ability.id)
        ).toEqual([MANA_TEMPLATE_ID]);
    });

    it("ignores a grant whose template id doesn't exist on the granting card", () => {
        const host = makeInstance(RECIPIENT_ID, {
            id: "host",
            controllerId: "p1",
            ownerId: "p1",
            grantedActivatedAbilities: [
                {
                    sourceCardId: INDEFINITE_GRANTER_ID,
                    abilityId: "no-such-template",
                },
            ],
        });
        expect(getEffectiveActivatedAbilities(host)).toEqual([]);
        expect(
            getDefinition(INDEFINITE_GRANTER_ID).grantTemplates
        ).toHaveLength(1);
    });
});

// ── Half 3 — the granted source pays a REAL cost (GRE → game.ts) ─────────────
//
// The mana PRODUCTION readers (`getActivatedManaColor`, `getFixedManaAmount`,
// `getDynamicManaProduced`) were left on `cardDef.activatedAbilities` while the
// DISCOVERY probes above were rewired, so the planner committed to a source
// the payment path then rejected ("Card does not produce mana") — and the
// priority tap silently tapped the permanent for ZERO mana. Half 2 asserts
// only discovery; these drive the real payment.

describe("a granted mana ability pays a REAL cost (CR 605.1a, issue #1880)", () => {
    it("tapSourceIntoPayment adds the granted ability's mana to the pool", () => {
        const { state, recipient } = boardWithGrant(INDEFINITE_GRANTER_ID);
        const player = state.players[0];
        tapSourceIntoPayment(state, player, recipient, undefined, []);
        expect(player.manaPool.C).toBe(1);
        expect(recipient.isTapped).toBe(true);
    });

    it("without the grant the very same call is rejected (the assertion above isn't vacuous)", () => {
        const { state, recipient } = boardWithGrant(null);
        expect(() =>
            tapSourceIntoPayment(
                state,
                state.players[0],
                recipient,
                undefined,
                []
            )
        ).toThrow(/does not produce mana/);
    });

    it("the registered `tapForPayment` mutation funds a {1} spell entirely off the granted source", async () => {
        const { state } = boardWithGrant(INDEFINITE_GRANTER_ID);
        state.pendingCast = {
            playerId: "p1",
            cardInstanceId: "spell",
            manaCost: { X: 1 },
            tappedLandIds: [],
        };
        const harness = makeMutationCtx("p1", [gameStateSeed(state)]);
        await runMutation<
            {
                gameId: Id<"games">;
                playerId: string;
                payments: { cardInstanceId: string }[];
            },
            void
        >(tapForPayment, harness.ctx, {
            gameId: "game-1" as Id<"games">,
            playerId: "p1",
            payments: [{ cardInstanceId: "recipient" }],
        });
        const after = harness.state();
        // The cost was covered, so the cast auto-committed: the spell left the
        // hand for the stack and the granted source is tapped.
        expect(after.pendingCast).toBeUndefined();
        expect(after.players[0].hand).toHaveLength(0);
        expect(after.stack.map((s) => s.id)).toContain("spell");
        expect(
            after.players[0].battlefield.find((c) => c.id === "recipient")
                ?.isTapped
        ).toBe(true);
    });
});

/** A Forest granted "{1}, {T}: Add {W}" — TWO mana-tap options (the granted
 *  activated one and the intrinsic Forest subtype, CR 305.6), so the tap routes
 *  through the CHOICE branch that `resolveManaTapChoice` serves. */
function forestWithCostedGrant(): {
    state: GameState;
    land: CardInstanceState;
} {
    const land = makeInstance(forest.id, {
        id: "granted-land",
        controllerId: "p1",
        ownerId: "p1",
    });
    const state = makeState({
        players: [
            makePlayer("p1", {
                battlefield: [land],
                manaPool: { W: 0, U: 0, B: 0, R: 0, G: 1, C: 0 },
            }),
            makePlayer("p2"),
        ],
    });
    resolveGrant(COSTED_GRANTER_ID, land, state);
    return { state, land: state.players[0].battlefield[0] };
}

describe("the mana-tap CHOICE branch honours a GRANTED option's riders (CR 605.1a, issue #1880)", () => {
    it("enumerates the granted option alongside the intrinsic basic-subtype one", () => {
        const { state, land } = forestWithCostedGrant();
        expect(
            getManaTapOptionsDetailed(land, "p1", manaGateBattlefields(state), {
                requireTap: true,
            })
        ).toEqual([
            {
                mana: { W: 1 },
                source: { kind: "activated", abilityId: COSTED_TEMPLATE_ID },
            },
            { mana: { G: 1 }, source: { kind: "basic", subtype: "Forest" } },
        ]);
    });

    it("picking the granted option PAYS its {1} (it used to make free mana)", () => {
        const { state, land } = forestWithCostedGrant();
        const player = state.players[0];
        tapSourceIntoPayment(state, player, land, 0, []);
        expect(player.manaPool.W).toBe(1);
        // The floating {G} funded the granted ability's own {1} activation cost.
        expect(player.manaPool.G ?? 0).toBe(0);
    });

    it("rejects the granted option when its {1} can't be paid", () => {
        const { state, land } = forestWithCostedGrant();
        const player = state.players[0];
        player.manaPool = { W: 0, U: 0, B: 0, R: 0, G: 0, C: 0 };
        expect(() => tapSourceIntoPayment(state, player, land, 0, [])).toThrow(
            /Not enough mana/
        );
        expect(land.isTapped).not.toBe(true);
    });

    it("the intrinsic basic-subtype option next to it stays rider-free (CR 305.6)", () => {
        const { state, land } = forestWithCostedGrant();
        const player = state.players[0];
        tapSourceIntoPayment(state, player, land, 1, []);
        expect(player.manaPool.G).toBe(2); // the floating {G} plus the tapped one
        expect(player.manaPool.W).toBe(0);
    });
});

// ── CR 106.4 "could produce" sees the grant too ──────────────────────────────

describe("getProducibleColors includes a granted mana ability (CR 106.4, issue #1880)", () => {
    it("a Forest granted `{1}, {T}: Add {W}` could produce BOTH {G} and {W}", () => {
        const { land } = forestWithCostedGrant();
        expect([...getProducibleColors(land)].sort()).toEqual(["G", "W"]);
    });

    it("without the grant it could produce only {G}", () => {
        const plain = makeInstance(forest.id, {
            id: "plain-forest",
            controllerId: "p1",
            ownerId: "p1",
        });
        expect([...getProducibleColors(plain)]).toEqual(["G"]);
    });
});
