import { describe, it, expect } from "vitest";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
    bladeDeckKnowledge,
    buildBladeState,
    seatPlayerId,
    BLADE_SCENARIOS,
    type BladeScenario,
} from "../ai/blade";
import { DEFAULT_EVAL_WEIGHTS } from "../ai/evalWeights";
import { cloneGameState } from "../clone";
import { evaluate, materialMargin } from "../evaluate";
import { makeRng } from "../rng";
import { reward, rollout, searchWithTrace } from "../search";
import snapshot from "./fixtures/searchLeafScore.snapshot.json";

/**
 * Byte-identity pin for the search's leaf scoring (issue #4459, PRD #4454).
 *
 * A leaf is scored by `scoreLeaf`: the bounded reward that drives UCB1 plus the
 * saturation-proof material margin that breaks outcome-equal ties. Issue #4459
 * computes both from ONE evaluation instead of two; this file proves the
 * arithmetic did not move. The snapshot JSON was recorded on the code BEFORE
 * that change and is never regenerated by a passing run:
 *
 *   - the root position's `evaluate` / `materialMargin` / `reward`;
 *   - five rollouts from the root, each returning `scoreLeaf`'s `Leaf` directly;
 *   - a fixed-seed, fixed-iteration search: every root candidate's visits and
 *     its MEAN reward and margin — sums over every leaf the tree scored, so one
 *     leaf drifting by one ulp moves them.
 *
 * Positions: the three of the perf fixture (`search.perf.test.ts`, issue #4458).
 * Floats round-trip exactly through JSON (shortest round-trip repr), so
 * `toEqual` is a bit-for-bit comparison. `RECORD_LEAF_SNAPSHOT=1` rewrites the
 * file — only ever on a change that is MEANT to move the evaluation.
 */

const ITERATIONS = 100;
const SEED = 0xb1ade;
const ROLLOUT_SEEDS = [1, 2, 3, 4, 5];

const POSITIONS = [
    "adventure: casts Stomp to kill the blocker",
    "depletion land: spends the last charge because it",
    "redirection shield: shields ITS OWN side and point",
];

function scenarioFor(prefix: string): BladeScenario {
    const found = BLADE_SCENARIOS.filter((s) => s.label.startsWith(prefix));
    expect(found).toHaveLength(1);
    return found[0];
}

function record(prefix: string) {
    const scenario = scenarioFor(prefix);
    const state = buildBladeState(scenario);
    const botId = seatPlayerId(state, scenario.bot);
    const weights = DEFAULT_EVAL_WEIGHTS;
    const root = {
        evaluate: evaluate(state, botId, weights),
        materialMargin: materialMargin(state, botId, weights),
        reward: reward(state, botId, weights),
    };
    const rollouts = ROLLOUT_SEEDS.map((seed) =>
        rollout(cloneGameState(state), botId, makeRng(seed), weights)
    );
    const { trace } = searchWithTrace(
        state,
        botId,
        { iterations: ITERATIONS },
        SEED,
        bladeDeckKnowledge(state, scenario)
    );
    return {
        root,
        rollouts,
        search: {
            chosen: trace?.chosen ?? null,
            iterationsCompleted: trace?.iterationsCompleted ?? 0,
            candidates: (trace?.candidates ?? []).map((c) => ({
                label: c.label,
                visits: c.visits,
                meanReward: c.meanReward,
                meanMargin: c.meanMargin,
            })),
        },
    };
}

describe("search leaf scoring is byte-identical (issue #4459)", () => {
    const actual = Object.fromEntries(POSITIONS.map((p) => [p, record(p)]));

    if (process.env.RECORD_LEAF_SNAPSHOT === "1") {
        writeFileSync(
            join(__dirname, "fixtures/searchLeafScore.snapshot.json"),
            JSON.stringify(actual, null, 4) + "\n"
        );
    }

    for (const position of POSITIONS) {
        it(`${position}: root values, rollout leaves and search means unchanged`, () => {
            expect(actual[position]).toEqual(
                (snapshot as Record<string, unknown>)[position]
            );
        });
    }
});
