import type { CardPrint } from "../../types";

// 4ED (Fourth Edition) black cards, split by colour per ADR 0043.
//
// Fourth Edition is a 100% reprint core set — it introduces no new cards — so
// this module is entirely CardPrint entries: each declares the per-edition
// Scryfall UUID (printId) and resolves printId -> definitionId -> a shared
// CardDefinition already implemented in lea/leb/arn/atq/leg/drk/fem/ice/2ed/3ed.
// See ADR 0014. 4ED is the earliest Premodern-legal set (issue #980).
//
// Generated by scripts/generate-4ed-prints.mts from data/json/4ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 4ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: ante cards — Bronze Tablet, Rebirth, Tempest Efreet — are permanently out of
// scope (ADR 0010) and carry no print row. Cards whose CardDefinition is not
// yet implemented are omitted; each lands automatically once its definition
// exists.

export const drudgeSkeletons4ed: CardPrint = {
    printId: "0c59579a-326b-4f82-ac33-1f4912db367b",
    definitionId: "23614289-0d73-4747-a849-5cb67cc97d6a", // Drudge Skeletons
    setCode: "4ed",
    rarity: "common",
};

export const animateDead4ed: CardPrint = {
    printId: "cc1dc456-1f64-4f24-a646-84c57e641b3b",
    definitionId: "8fd7861d-925f-4b4c-a4ab-60be6f43d50b", // Animate Dead
    setCode: "4ed",
    rarity: "uncommon",
};

export const ashesToAshes4ed: CardPrint = {
    printId: "28f40650-9dd5-473d-a660-448672d475a5",
    definitionId: "825496e5-19c7-4f50-8070-0265a58608dc", // Ashes to Ashes
    setCode: "4ed",
    rarity: "uncommon",
};

export const badMoon4ed: CardPrint = {
    printId: "aca216e2-27a5-40e1-bb61-0ddcd8ee02ae",
    definitionId: "43572906-ea74-4411-a549-5dc401591d2a", // Bad Moon
    setCode: "4ed",
    rarity: "rare",
};

export const blackKnight4ed: CardPrint = {
    printId: "47716cf4-f35c-4613-9686-4e00b5063408",
    definitionId: "c1662949-0d69-49a3-8c69-daf10717ed4e", // Black Knight
    setCode: "4ed",
    rarity: "uncommon",
};

export const blight4ed: CardPrint = {
    printId: "59365350-d149-4c0d-a08f-eabdfb7cce3d",
    definitionId: "9ca19b39-4201-463c-bd40-fbffa31c9eda", // Blight
    setCode: "4ed",
    rarity: "uncommon",
};

export const bogImp4ed: CardPrint = {
    printId: "c50c3053-3cf3-40d3-bc9e-2fc292f11c34",
    definitionId: "e3bb7271-634a-4612-9073-7a5438e8c2b8", // Bog Imp
    setCode: "4ed",
    rarity: "common",
};

export const bogWraith4ed: CardPrint = {
    printId: "fbf82ad6-b32e-41ea-abea-22b8eef69e67",
    definitionId: "6701874e-986e-4b81-9268-90b6171e6187", // Bog Wraith
    setCode: "4ed",
    rarity: "uncommon",
};

export const carrionAnts4ed: CardPrint = {
    printId: "f5de329d-fb08-4c4a-883f-1d77dc64470d",
    definitionId: "cbc0b009-3951-4aa3-985a-97139882da7e", // Carrion Ants
    setCode: "4ed",
    rarity: "uncommon",
};

export const cosmicHorror4ed: CardPrint = {
    printId: "07e975cc-e89d-4ac3-b9dc-dad202dacc14",
    definitionId: "18bc6ac2-19e0-4765-852b-e303a5bb4040", // Cosmic Horror
    setCode: "4ed",
    rarity: "rare",
};

export const cursedLand4ed: CardPrint = {
    printId: "23d9fb0a-1087-43cd-9e14-24c1685a2057",
    definitionId: "cf5f3c61-1e54-4eea-bf82-311cfa988e6a", // Cursed Land
    setCode: "4ed",
    rarity: "uncommon",
};

export const cyclopeanMummy4ed: CardPrint = {
    printId: "8201b51b-da03-4207-805c-134e527c42e1",
    definitionId: "479ccc50-2d72-4adc-901e-fbd4eef2cf92", // Cyclopean Mummy
    setCode: "4ed",
    rarity: "common",
};

export const darkRitual4ed: CardPrint = {
    printId: "3477f601-5374-4316-a74e-b5e198af482b",
    definitionId: "ebb6664d-23ca-456e-9916-afcd6f26aa7f", // Dark Ritual
    setCode: "4ed",
    rarity: "common",
};

export const deathgrip4ed: CardPrint = {
    printId: "74e2ae05-29ec-4005-8d78-280a190601c4",
    definitionId: "2371c126-f19a-472a-ba5f-3b1366274ea0", // Deathgrip
    setCode: "4ed",
    rarity: "uncommon",
};

export const deathlace4ed: CardPrint = {
    printId: "237e37fb-383d-432c-8ac3-1332096567db",
    definitionId: "6ff1cefc-62cb-4525-b0c5-2b09603b4314", // Deathlace
    setCode: "4ed",
    rarity: "rare",
};

export const drainLife4ed: CardPrint = {
    printId: "b9d10677-36f0-4339-a2c3-213e8ee1c51d",
    definitionId: "5d077a49-73d4-4958-b42a-31b814e110e8", // Drain Life
    setCode: "4ed",
    rarity: "common",
};

export const drudgeSkeletons24ed: CardPrint = {
    printId: "d3d223d3-72c1-4240-9323-84484167c5e0",
    definitionId: "23614289-0d73-4747-a849-5cb67cc97d6a", // Drudge Skeletons
    setCode: "4ed",
    rarity: "common",
};

export const elHajjâj4ed: CardPrint = {
    printId: "cf371bd2-89ad-487e-8f27-37a6e75ca0f5",
    definitionId: "c4b610d3-2005-4347-bcda-c30b5b7972e5", // El-Hajjâj
    setCode: "4ed",
    rarity: "rare",
};

export const elHajjâj24ed: CardPrint = {
    printId: "320906ee-791a-41c0-9b28-9a287cdb3340",
    definitionId: "c4b610d3-2005-4347-bcda-c30b5b7972e5", // El-Hajjâj
    setCode: "4ed",
    rarity: "rare",
};

export const ergRaiders4ed: CardPrint = {
    printId: "472c83ff-66aa-485b-9ca7-aef8731de20a",
    definitionId: "35c73a97-531d-4dd5-8236-39b89c183c38", // Erg Raiders
    setCode: "4ed",
    rarity: "common",
};

export const evilPresence4ed: CardPrint = {
    printId: "5cbca45f-7b08-408b-9445-e3f2b9563f1b",
    definitionId: "0551d66e-8cd4-48f0-aa17-15f26be9d85f", // Evil Presence
    setCode: "4ed",
    rarity: "uncommon",
};

export const fear4ed: CardPrint = {
    printId: "126c1b02-01bd-4b70-9293-a89173b4cd32",
    definitionId: "0cd927be-e63f-4371-a1d8-7a0489cb187e", // Fear
    setCode: "4ed",
    rarity: "common",
};

export const frozenShade4ed: CardPrint = {
    printId: "95547c2a-c01b-45ed-b775-f33c157b17a5",
    definitionId: "d0bd76c8-4cff-4c15-9686-7a299b589814", // Frozen Shade
    setCode: "4ed",
    rarity: "common",
};

export const gloom4ed: CardPrint = {
    printId: "f5a8573d-0e2d-4a7f-a47f-7e1bc472d4fa",
    definitionId: "a8d10bc7-daeb-4c0d-9e4a-8eae8d11699f", // Gloom
    setCode: "4ed",
    rarity: "uncommon",
};

export const greed4ed: CardPrint = {
    printId: "76fb0c62-1c53-464e-a2df-59285f2d593d",
    definitionId: "111a16a2-e875-4756-80db-290f9e8606db", // Greed
    setCode: "4ed",
    rarity: "rare",
};

export const howlFromBeyond4ed: CardPrint = {
    printId: "5dba7b1e-90a0-419e-bcba-a6b19beacf29",
    definitionId: "67ec17e1-174b-4d07-a27f-91a333c4b2fb", // Howl from Beyond
    setCode: "4ed",
    rarity: "common",
};

export const hypnoticSpecter4ed: CardPrint = {
    printId: "b5900350-be08-4904-8f1b-cc180ed08485",
    definitionId: "b43b900f-2d9b-442b-9699-058483604ec9", // Hypnotic Specter
    setCode: "4ed",
    rarity: "uncommon",
};

export const junúnEfreet4ed: CardPrint = {
    printId: "398a2b0f-0b91-408c-8083-3bc89873b69f",
    definitionId: "5f46783a-b91e-4829-a173-5515b09ca615", // Junún Efreet
    setCode: "4ed",
    rarity: "uncommon",
};

export const lordOfThePit4ed: CardPrint = {
    printId: "9691e76c-770d-4721-b758-805574227de1",
    definitionId: "2926777a-4f6e-4965-ba83-22cf7df02602", // Lord of the Pit
    setCode: "4ed",
    rarity: "rare",
};

export const lostSoul4ed: CardPrint = {
    printId: "66b875b1-e534-4ed8-9ebd-8f4d5a066e7d",
    definitionId: "601eed5c-436d-425b-a45f-07881ad893c8", // Lost Soul
    setCode: "4ed",
    rarity: "common",
};

export const marshGas4ed: CardPrint = {
    printId: "c8c65bf9-cbab-45ee-9c6e-f8ee832dbe61",
    definitionId: "b80ecb15-258b-4fc9-86e4-c2bf01891606", // Marsh Gas
    setCode: "4ed",
    rarity: "common",
};

export const mindTwist4ed: CardPrint = {
    printId: "bbb6765c-a052-46dc-a589-200b8ba8c99f",
    definitionId: "eee9e106-a248-49d2-b8c8-6bbcd56ce739", // Mind Twist
    setCode: "4ed",
    rarity: "rare",
};

export const murkDwellers4ed: CardPrint = {
    printId: "7731dc37-2eac-4e60-bb0f-6230205a5323",
    definitionId: "a213450f-02f4-4c08-8da8-891ebfa8e237", // Murk Dwellers
    setCode: "4ed",
    rarity: "common",
};

export const netherShadow4ed: CardPrint = {
    printId: "1b6d9e96-0c7f-45c5-b6d0-6444ef84bab1",
    definitionId: "f13ad58a-6f9b-420a-bac1-40929f5e616a", // Nether Shadow
    setCode: "4ed",
    rarity: "rare",
};

export const nightmare4ed: CardPrint = {
    printId: "db11b832-7584-4e4b-8d02-b03fe76dcbc3",
    definitionId: "b8cdd6a7-f772-4ccb-914f-63f52ed54d6b", // Nightmare
    setCode: "4ed",
    rarity: "rare",
};

export const paralyze4ed: CardPrint = {
    printId: "d0bcad9a-b69c-434a-8d48-6b727bd8e382",
    definitionId: "be33a155-de26-43d1-88f1-c926f1b7cb7c", // Paralyze
    setCode: "4ed",
    rarity: "common",
};

export const pestilence4ed: CardPrint = {
    printId: "90886a02-4c1f-48ea-8563-6d80c97d9f58",
    definitionId: "d42a6350-b16b-4e10-a273-e6cbb55dcb7a", // Pestilence
    setCode: "4ed",
    rarity: "common",
};

export const plagueRats4ed: CardPrint = {
    printId: "901591cb-a7e9-47c1-96ff-3de7b39b1055",
    definitionId: "b3724e40-0622-4aee-9334-6c9fff88bcd5", // Plague Rats
    setCode: "4ed",
    rarity: "common",
};

export const ragMan4ed: CardPrint = {
    printId: "018a02f9-81f7-412b-8e98-d7be3eb73eca",
    definitionId: "f4c133b8-8383-433f-be96-c47a937287b7", // Rag Man
    setCode: "4ed",
    rarity: "rare",
};

export const raiseDead4ed: CardPrint = {
    printId: "2096e54e-1a55-4fd7-8415-a6f2fdb2a536",
    definitionId: "ce07bede-2219-427c-a61a-56518751de42", // Raise Dead
    setCode: "4ed",
    rarity: "common",
};

export const royalAssassin4ed: CardPrint = {
    printId: "b2d51bdf-f118-4a1e-9060-bdf3c78697f2",
    definitionId: "59590768-fa96-4869-8763-9d5ab6ac22ad", // Royal Assassin
    setCode: "4ed",
    rarity: "rare",
};

export const scatheZombies4ed: CardPrint = {
    printId: "dbd55d32-e969-4d12-b101-a35db8a53921",
    definitionId: "e9be6dcf-5e25-4b8c-9cd0-badf3771f81e", // Scathe Zombies
    setCode: "4ed",
    rarity: "common",
};

export const scavengingGhoul4ed: CardPrint = {
    printId: "df0baaa9-c42b-413a-b10d-95689e4ddb50",
    definitionId: "426984e0-88e1-4a2d-9a1c-798b95864df3", // Scavenging Ghoul
    setCode: "4ed",
    rarity: "uncommon",
};

export const sengirVampire4ed: CardPrint = {
    printId: "2e29882a-c194-48b8-ba18-439b0bda395e",
    definitionId: "510840f4-7c0e-4b47-8ebf-23c20cac4bd9", // Sengir Vampire
    setCode: "4ed",
    rarity: "uncommon",
};

export const simulacrum4ed: CardPrint = {
    printId: "7c23232c-a264-4df9-824b-4111a5c6524c",
    definitionId: "35c3a78d-cc79-4187-929a-8aa1d1469990", // Simulacrum
    setCode: "4ed",
    rarity: "uncommon",
};

export const sorceressQueen4ed: CardPrint = {
    printId: "e4855db6-570c-4845-9074-a9df7611307a",
    definitionId: "94742003-f0f1-4483-b1a0-e7163995db1b", // Sorceress Queen
    setCode: "4ed",
    rarity: "rare",
};

export const spiritShackle4ed: CardPrint = {
    printId: "1df0c902-3fe1-4de7-9777-7ddb563b6cec",
    definitionId: "a30bb266-5bd1-4998-ae94-56f0f3354167", // Spirit Shackle
    setCode: "4ed",
    rarity: "uncommon",
};

export const terror4ed: CardPrint = {
    printId: "deb5d44d-977d-4d0d-8242-17c8ffa7247c",
    definitionId: "21004958-2c7e-4a55-bc80-411c4d780106", // Terror
    setCode: "4ed",
    rarity: "common",
};

export const uncleIstvan4ed: CardPrint = {
    printId: "cbf5aa58-f68b-4197-9697-1e6653760853",
    definitionId: "848ad6d5-3a7e-4d6b-9929-36465796871f", // Uncle Istvan
    setCode: "4ed",
    rarity: "uncommon",
};

export const unholyStrength4ed: CardPrint = {
    printId: "f52c3c85-1462-406c-8e3b-c25deda9c4e6",
    definitionId: "90563f90-0127-4164-b43b-f0321dc63a1d", // Unholy Strength
    setCode: "4ed",
    rarity: "common",
};

export const wallOfBone4ed: CardPrint = {
    printId: "36ce3251-017f-4834-9935-0985c56cccb7",
    definitionId: "ae20d442-a544-4a03-9ebf-5ecb137c67dd", // Wall of Bone
    setCode: "4ed",
    rarity: "uncommon",
};

export const warpArtifact4ed: CardPrint = {
    printId: "edc2fcd5-e7a5-4a66-b385-82726ee6e3cc",
    definitionId: "9e5e07a2-fbdf-4c4c-996a-fce40bab5de5", // Warp Artifact
    setCode: "4ed",
    rarity: "rare",
};

export const weakness4ed: CardPrint = {
    printId: "548d4cd1-7cc6-44ee-872e-68e5bcc608fb",
    definitionId: "36ca06a1-9b9a-49a2-9c47-9b72228621bc", // Weakness
    setCode: "4ed",
    rarity: "common",
};

export const willOTheWisp4ed: CardPrint = {
    printId: "583ef317-8105-4917-ba3c-93de3eebd944",
    definitionId: "a1a6f8e9-7bc1-4151-b55f-acf877b1a7a6", // Will-o'-the-Wisp
    setCode: "4ed",
    rarity: "rare",
};

export const wordOfBinding4ed: CardPrint = {
    printId: "715472e1-585b-4379-b335-8f3b5e572d83",
    definitionId: "ee30efdb-f1f1-497f-80a6-ec961db67c1d", // Word of Binding
    setCode: "4ed",
    rarity: "common",
};

export const xenicPoltergeist4ed: CardPrint = {
    printId: "a3c546db-0871-4a13-8654-c26ae9f9b50a",
    definitionId: "5149ffff-d38f-458e-bcfa-a4b6b332a0b4", // Xenic Poltergeist
    setCode: "4ed",
    rarity: "rare",
};

export const zombieMaster4ed: CardPrint = {
    printId: "d86753ae-c8da-47d7-b97a-3c75f83ee929",
    definitionId: "3d4255a0-d445-4c00-b936-bbf07851e1c8", // Zombie Master
    setCode: "4ed",
    rarity: "rare",
};
