import type { CardPrint } from "../../types";

// 4ED (Fourth Edition) blue cards, split by colour per ADR 0043.
//
// Fourth Edition is a 100% reprint set — it introduces no new cards — so this
// module is entirely CardPrint entries: each declares the per-edition Scryfall
// UUID (printId) and resolves printId -> definitionId -> a shared CardDefinition
// already implemented in arn/atq/drk/lea/leb/leg. See ADR 0014.
// 4ED is the earliest Premodern-legal set (issue #980).
//
// Generated by scripts/generate-print-set.mts 4ed from data/json/4ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 4ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: ante cards — Bronze Tablet, Rebirth, Tempest Efreet — are permanently out of
// scope (ADR 0010) and carry no print row. Cards whose CardDefinition is not
// yet implemented are omitted; each lands automatically once its definition
// exists.

export const airElemental4ed: CardPrint = {
    printId: "e5cfaefb-764c-4c56-bdb3-5f0375168597",
    definitionId: "69c3b2a3-0daa-4d42-832d-fcdfda6555ea", // Air Elemental
    setCode: "4ed",
    rarity: "uncommon",
};

export const animateArtifact4ed: CardPrint = {
    printId: "ea613c48-258b-499d-975b-f56fbef3c665",
    definitionId: "664b46f5-0424-4f4e-9f26-6bd2cf5e0357", // Animate Artifact
    setCode: "4ed",
    rarity: "uncommon",
};

export const apprenticeWizard4ed: CardPrint = {
    printId: "c9ef569e-91e7-45f5-83b0-5a820242c628",
    definitionId: "151b332e-164b-4646-8f52-741984cd71ad", // Apprentice Wizard
    setCode: "4ed",
    rarity: "common",
};

export const backfire4ed: CardPrint = {
    printId: "ad34094d-a7ec-4b04-a288-4d4f1a07fc6b",
    definitionId: "04bc57aa-d4d9-4bd9-ba09-984370c7e23b", // Backfire
    setCode: "4ed",
    rarity: "uncommon",
};

export const blueElementalBlast4ed: CardPrint = {
    printId: "988f7b31-24b2-45c2-89e4-ff6bd9e0c8c7",
    definitionId: "20d666ef-39bf-4fbf-8201-5f1056539da2", // Blue Elemental Blast
    setCode: "4ed",
    rarity: "common",
};

export const controlMagic4ed: CardPrint = {
    printId: "1bb371e5-424e-42dd-9966-732c22e8ece8",
    definitionId: "7b52f459-c703-4a0b-9114-ff69eec61287", // Control Magic
    setCode: "4ed",
    rarity: "uncommon",
};

export const counterspell4ed: CardPrint = {
    printId: "e8493631-6c9c-40a8-b7de-ecf26ba6bf7d",
    definitionId: "0df55e3f-14de-46ef-b6b1-616618724d9e", // Counterspell
    setCode: "4ed",
    rarity: "uncommon",
};

export const creatureBond4ed: CardPrint = {
    printId: "717c5ee5-a033-4a58-bdcb-ef54e6c8b7a9",
    definitionId: "ee4bd7d1-77e5-46e5-a594-c24469e88c4c", // Creature Bond
    setCode: "4ed",
    rarity: "common",
};

export const drainPower4ed: CardPrint = {
    printId: "e3009237-fb96-497f-9a6e-b93b8115528a",
    definitionId: "ea3830c5-cc66-453e-9e53-0636e00ee0ee", // Drain Power
    setCode: "4ed",
    rarity: "rare",
};

export const energyFlux4ed: CardPrint = {
    printId: "fbfa8400-1820-4108-a7f3-6ae8a1897f0c",
    definitionId: "bd1f624b-e8f2-462f-838a-7cb9e8fda988", // Energy Flux
    setCode: "4ed",
    rarity: "uncommon",
};

export const energyTap4ed: CardPrint = {
    printId: "9f67692d-9df6-4841-a36b-26c28110b63b",
    definitionId: "37e69940-bdc8-48ff-a296-540343910adf", // Energy Tap
    setCode: "4ed",
    rarity: "common",
};

export const erosion4ed: CardPrint = {
    printId: "8dc539ff-03f5-4bec-877a-061fb5d40de9",
    definitionId: "5f4b6507-89ee-482e-aafd-8e05ada8f1ce", // Erosion
    setCode: "4ed",
    rarity: "common",
};

export const feedback4ed: CardPrint = {
    printId: "eb5a60e6-be5f-454e-a354-ab736839f092",
    definitionId: "0eb8f591-d763-49bf-8ef9-86265aaa72f7", // Feedback
    setCode: "4ed",
    rarity: "uncommon",
};

export const flight4ed: CardPrint = {
    printId: "1867cb70-f615-4583-bf0b-fb1016209785",
    definitionId: "67c7784b-6b79-4268-a714-895c82809aff", // Flight
    setCode: "4ed",
    rarity: "common",
};

export const flood4ed: CardPrint = {
    printId: "ba099785-bfa0-4224-be19-0dcded94fba5",
    definitionId: "fabc3267-b59b-4f36-8873-5b4b072711ca", // Flood
    setCode: "4ed",
    rarity: "common",
};

export const ghostShip4ed: CardPrint = {
    printId: "3af0b9ce-0a9c-4619-95c1-bbbfffa7fcec",
    definitionId: "db591b28-37e5-4e7c-ae4d-d761262b12d0", // Ghost Ship
    setCode: "4ed",
    rarity: "uncommon",
};

export const giantTortoise4ed: CardPrint = {
    printId: "f512addb-5888-49f3-985b-53cc11831e5e",
    definitionId: "096f7ac8-c639-4347-9767-7305eaf490ba", // Giant Tortoise
    setCode: "4ed",
    rarity: "common",
};

export const hurkylSRecall4ed: CardPrint = {
    printId: "bee569a6-20b0-4d37-91d6-db18de4b90c6",
    definitionId: "f32373dd-06d8-45d1-8777-3b1411bcb30a", // Hurkyl's Recall
    setCode: "4ed",
    rarity: "rare",
};

export const islandFishJasconius4ed: CardPrint = {
    printId: "84f18188-70fa-433e-a114-2f1dd49388ed",
    definitionId: "8537cb0f-4821-417b-80cc-ea57d51ee9b8", // Island Fish Jasconius
    setCode: "4ed",
    rarity: "rare",
};

export const jump4ed: CardPrint = {
    printId: "7b994bf9-5b3d-42c7-b4c6-f1029d78dd80",
    definitionId: "cb3f4b11-ad1b-48e2-a500-787d351b0174", // Jump
    setCode: "4ed",
    rarity: "common",
};

export const lifetap4ed: CardPrint = {
    printId: "634dd3bd-d29b-4481-990b-f320e60c4f91",
    definitionId: "11add837-7ee4-4104-b031-c161bce459ae", // Lifetap
    setCode: "4ed",
    rarity: "uncommon",
};

export const lordOfAtlantis4ed: CardPrint = {
    printId: "846572ce-c8fd-402c-9212-8288336c75e8",
    definitionId: "210c4a90-fc7a-4c76-aeaa-20a005e45386", // Lord of Atlantis
    setCode: "4ed",
    rarity: "rare",
};

export const magicalHack4ed: CardPrint = {
    printId: "41c57f8a-6592-49b4-acb1-9b30500d1e8c",
    definitionId: "2bd4202c-0477-45aa-82fd-83c85d6d4bef", // Magical Hack
    setCode: "4ed",
    rarity: "rare",
};

export const mahamotiDjinn4ed: CardPrint = {
    printId: "71935f14-d7ca-4406-9263-b2c7f5f5b94f",
    definitionId: "36204ddd-ddf7-4b44-ae3c-b4a5a41ac9cb", // Mahamoti Djinn
    setCode: "4ed",
    rarity: "rare",
};

export const manaShort4ed: CardPrint = {
    printId: "dd84fdcc-5463-45e9-9421-1d554ecdb8ae",
    definitionId: "73e3e0b3-5284-464f-8c62-0f7801c966f5", // Mana Short
    setCode: "4ed",
    rarity: "rare",
};

export const merfolkOfThePearlTrident4ed: CardPrint = {
    printId: "93661c9f-b529-4d82-b68d-3ce050f77e0d",
    definitionId: "2b871039-6a66-4ac3-95e7-24759c1f2f92", // Merfolk of the Pearl Trident
    setCode: "4ed",
    rarity: "common",
};

export const mindBomb4ed: CardPrint = {
    printId: "2ae30614-f558-4627-8e08-bf8a30ecd5b9",
    definitionId: "0ee810a5-f0f9-4b73-8194-3d1344784050", // Mind Bomb
    setCode: "4ed",
    rarity: "uncommon",
};

export const phantasmalForces4ed: CardPrint = {
    printId: "0bc15dcf-6f78-4968-8af9-c115dfa10e4c",
    definitionId: "0631c7c8-9aa5-4333-8e20-20247fc47033", // Phantasmal Forces
    setCode: "4ed",
    rarity: "uncommon",
};

export const phantasmalTerrain4ed: CardPrint = {
    printId: "0d7b3b65-e1f9-4a0d-95a6-42c2c4a358e5",
    definitionId: "1c371aa1-1619-41e3-8364-7bc9b8cf5d14", // Phantasmal Terrain
    setCode: "4ed",
    rarity: "common",
};

export const phantomMonster4ed: CardPrint = {
    printId: "daa120ce-63a6-4d5e-9801-123d5e05646e",
    definitionId: "e46d2cf5-e8d0-4fb2-b950-252d52084b63", // Phantom Monster
    setCode: "4ed",
    rarity: "uncommon",
};

export const pirateShip4ed: CardPrint = {
    printId: "0d7f104a-fb06-41a4-abd9-38f2c6017bbf",
    definitionId: "d0a7cb23-d229-43c5-addd-dcf423984b0c", // Pirate Ship
    setCode: "4ed",
    rarity: "rare",
};

export const powerLeak4ed: CardPrint = {
    printId: "99f235d7-8f6b-4d17-bc36-6f2cb6d5deec",
    definitionId: "ccc982b6-35b2-4e33-ace2-86cb79123e4f", // Power Leak
    setCode: "4ed",
    rarity: "common",
};

export const powerSink4ed: CardPrint = {
    printId: "e91c51ab-c8b1-47be-8169-7f842712771c",
    definitionId: "1b342dd3-09b9-4108-bf12-a65d4cef4eb9", // Power Sink
    setCode: "4ed",
    rarity: "common",
};

export const prodigalSorcerer4ed: CardPrint = {
    printId: "dc4e1161-5008-427f-a88e-5497a8eb84cd",
    definitionId: "e4dc1103-7bf1-47f6-9006-d3ed9ccd7a6a", // Prodigal Sorcerer
    setCode: "4ed",
    rarity: "common",
};

export const psionicEntity4ed: CardPrint = {
    printId: "6641a587-c066-4f0a-a951-b91d3f749eb2",
    definitionId: "ec082062-5394-4340-bc29-0efd2af4b822", // Psionic Entity
    setCode: "4ed",
    rarity: "rare",
};

export const psychicVenom4ed: CardPrint = {
    printId: "138db623-393d-485a-8fa8-f1b1b933fce5",
    definitionId: "f3f5b68a-6b0e-431e-89f0-ff60f17687a5", // Psychic Venom
    setCode: "4ed",
    rarity: "common",
};

export const seaSerpent4ed: CardPrint = {
    printId: "e474391c-9ff0-4db4-9352-3fc07eeb4b51",
    definitionId: "d0b333b7-db4d-4439-b0de-60414cbf8d7b", // Sea Serpent
    setCode: "4ed",
    rarity: "common",
};

export const segovianLeviathan4ed: CardPrint = {
    printId: "22e6e890-d1d0-4a9b-a453-5b51974a9dff",
    definitionId: "e5a814f1-7f8d-4c2c-b706-ee0ed5892f7b", // Segovian Leviathan
    setCode: "4ed",
    rarity: "uncommon",
};

export const sirenSCall4ed: CardPrint = {
    printId: "51832cfb-0a2e-4674-bb36-38027a71ac6d",
    definitionId: "d992b336-3b6e-43e1-8662-d85664349b44", // Siren's Call
    setCode: "4ed",
    rarity: "uncommon",
};

export const sleightOfMind4ed: CardPrint = {
    printId: "cd21dc3d-c9e6-4592-a655-1a20ee13ae73",
    definitionId: "d427790c-e322-446e-8d7d-a6b48ad41a42", // Sleight of Mind
    setCode: "4ed",
    rarity: "rare",
};

export const spellBlast4ed: CardPrint = {
    printId: "008df307-f010-47bc-8548-65a1c7b1c4b8",
    definitionId: "845734da-ab03-4dbc-bb5f-96481d3b8e88", // Spell Blast
    setCode: "4ed",
    rarity: "common",
};

export const stasis4ed: CardPrint = {
    printId: "f3d29fed-248d-4547-9455-3d69b1f2787d",
    definitionId: "b6cef408-5b4b-49f6-9531-be544815b93f", // Stasis
    setCode: "4ed",
    rarity: "rare",
};

export const stealArtifact4ed: CardPrint = {
    printId: "dcd9ee1d-d1c5-4725-98fc-f6cff3a79512",
    definitionId: "83316930-d6ad-46ce-9b40-48eea856d95b", // Steal Artifact
    setCode: "4ed",
    rarity: "uncommon",
};

export const sunkenCity4ed: CardPrint = {
    printId: "226f89b4-cf98-4354-a2f4-3f63fe2dd99e",
    definitionId: "f1e0f9ec-2b06-4bda-8b80-a716d82d1f13", // Sunken City
    setCode: "4ed",
    rarity: "common",
};

export const thoughtlace4ed: CardPrint = {
    printId: "185674a4-db97-444d-b0e9-7dcfc245ce4b",
    definitionId: "23749375-1416-47a4-9251-52f41fe2fae9", // Thoughtlace
    setCode: "4ed",
    rarity: "rare",
};

export const twiddle4ed: CardPrint = {
    printId: "db401643-6114-4254-8e40-ea7605e5ed82",
    definitionId: "576e811f-26a3-4a7c-bd13-3b1cc3e184eb", // Twiddle
    setCode: "4ed",
    rarity: "common",
};

export const unstableMutation4ed: CardPrint = {
    printId: "841ae3a3-30b5-4f0c-ad2f-af3d5e0da2e9",
    definitionId: "a79e9236-a39e-471a-b18a-2c2ba16e7774", // Unstable Mutation
    setCode: "4ed",
    rarity: "common",
};

export const unsummon4ed: CardPrint = {
    printId: "338948aa-463d-4af4-a0d6-64132512334c",
    definitionId: "8512f2c1-6361-4b79-843f-80b6bceeeb99", // Unsummon
    setCode: "4ed",
    rarity: "common",
};

export const volcanicEruption4ed: CardPrint = {
    printId: "5828713a-edb3-4b11-b1f9-8f1bfc3c103f",
    definitionId: "a80582b1-09db-45f8-b362-0e5207a5a8e6", // Volcanic Eruption
    setCode: "4ed",
    rarity: "rare",
};

export const wallOfAir4ed: CardPrint = {
    printId: "239435c8-3380-4556-9618-09fc0e40b69d",
    definitionId: "da56fdf3-6a8f-4833-a5c3-197650cc4889", // Wall of Air
    setCode: "4ed",
    rarity: "uncommon",
};

export const wallOfWater4ed: CardPrint = {
    printId: "78028eda-61b0-408c-b3fc-adc968d39b47",
    definitionId: "41faed1a-ded8-49ee-8e2a-c60d377775d7", // Wall of Water
    setCode: "4ed",
    rarity: "uncommon",
};

export const waterElemental4ed: CardPrint = {
    printId: "dadea972-714e-4f6d-8fb7-a59c0ac1e028",
    definitionId: "8de940d6-98c0-46a9-b5fd-e2b0899ea19e", // Water Elemental
    setCode: "4ed",
    rarity: "uncommon",
};

export const zephyrFalcon4ed: CardPrint = {
    printId: "032ee0fd-9eb3-4d81-9972-9e7f4c4d64e4",
    definitionId: "25a173fd-e10c-45f8-a6e5-ad7a747a8050", // Zephyr Falcon
    setCode: "4ed",
    rarity: "common",
};
