import type { CardPrint } from "../../types";

// 4ED (Fourth Edition) colourless (lands, artifacts) cards, split by colour per ADR 0043.
//
// Fourth Edition is a 100% reprint core set — it introduces no new cards — so
// this module is entirely CardPrint entries: each declares the per-edition
// Scryfall UUID (printId) and resolves printId -> definitionId -> a shared
// CardDefinition already implemented in lea/leb/arn/atq/leg/drk/fem/ice/2ed/3ed.
// See ADR 0014. 4ED is the earliest Premodern-legal set (issue #980).
//
// Generated by scripts/generate-4ed-prints.mts from data/json/4ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 4ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: ante cards — Bronze Tablet, Rebirth, Tempest Efreet — are permanently out of
// scope (ADR 0010) and carry no print row. Cards whose CardDefinition is not
// yet implemented are omitted; each lands automatically once its definition
// exists.

export const aladdinSLamp4ed: CardPrint = {
    printId: "42e7cf40-c136-4fcb-a947-558b713b39f6",
    definitionId: "8fecc5d2-5298-4d47-b085-f160603f220e", // Aladdin's Lamp
    setCode: "4ed",
    rarity: "rare",
};

export const aladdinSRing4ed: CardPrint = {
    printId: "d9907bbb-12aa-4826-9a65-b2ddda5fc1e2",
    definitionId: "bb2b74a2-cb74-4b54-b9c6-78c63f14cf5b", // Aladdin's Ring
    setCode: "4ed",
    rarity: "rare",
};

export const amuletOfKroog4ed: CardPrint = {
    printId: "3fc1716d-5817-49f4-a9db-c162e6ceacbf",
    definitionId: "b094f8dd-0184-41a2-9767-e848a6e4eac1", // Amulet of Kroog
    setCode: "4ed",
    rarity: "common",
};

export const ankhOfMishra4ed: CardPrint = {
    printId: "44135b17-69e7-4002-a6e0-d76f4c0c423b",
    definitionId: "f594b7aa-d44e-47c4-989b-565f881e25f1", // Ankh of Mishra
    setCode: "4ed",
    rarity: "rare",
};

export const armageddonClock4ed: CardPrint = {
    printId: "2fa3fe10-0f6e-4b7f-98fc-3a21c399c38a",
    definitionId: "44a31889-6a8d-450c-a73d-381a7ff28bf9", // Armageddon Clock
    setCode: "4ed",
    rarity: "rare",
};

export const ashnodSBattleGear4ed: CardPrint = {
    printId: "0bc11285-0891-4cc3-a056-b698911166c7",
    definitionId: "aeeec853-dd3f-4ac3-8b20-c07fada8888f", // Ashnod's Battle Gear
    setCode: "4ed",
    rarity: "uncommon",
};

export const batteringRam4ed: CardPrint = {
    printId: "ebf5ea1c-0ea7-4b84-b886-ebd346f4e154",
    definitionId: "f7a69e35-d209-41c0-aa3c-c78414617075", // Battering Ram
    setCode: "4ed",
    rarity: "common",
};

export const blackManaBattery4ed: CardPrint = {
    printId: "a81f7a0f-183f-438b-b252-738d8d30c245",
    definitionId: "d0c66e64-e357-457d-8302-b3a1fc0c56ce", // Black Mana Battery
    setCode: "4ed",
    rarity: "rare",
};

export const blackVise4ed: CardPrint = {
    printId: "196b83a1-2a25-498d-83b8-8faacd79909d",
    definitionId: "76ac72f8-5b1e-4d67-a796-ef69cde27424", // Black Vise
    setCode: "4ed",
    rarity: "uncommon",
};

export const blueManaBattery4ed: CardPrint = {
    printId: "cd2cb84e-c079-486e-87ad-d188fe38bc76",
    definitionId: "35393661-2c53-46f0-bb33-2390d552b060", // Blue Mana Battery
    setCode: "4ed",
    rarity: "rare",
};

export const bottleOfSuleiman4ed: CardPrint = {
    printId: "d1924860-4532-40c2-b0e8-28584d22ccb5",
    definitionId: "c474cd6b-5610-49eb-ac98-918d900efe8b", // Bottle of Suleiman
    setCode: "4ed",
    rarity: "rare",
};

export const brassMan4ed: CardPrint = {
    printId: "7ab18c6d-2705-473e-b404-75660ff28736",
    definitionId: "1a364362-e42b-415c-9d95-b6ec7139f5e7", // Brass Man
    setCode: "4ed",
    rarity: "uncommon",
};

export const celestialPrism4ed: CardPrint = {
    printId: "e7ca1534-0049-4672-9677-99f1ba00fb78",
    definitionId: "a47417cb-1ea7-4f65-ba06-e27a99373114", // Celestial Prism
    setCode: "4ed",
    rarity: "uncommon",
};

export const clayStatue4ed: CardPrint = {
    printId: "0dd9b203-fa4c-4383-a671-265101f4453a",
    definitionId: "64975352-8d35-4d02-94ac-fa0c6ee12409", // Clay Statue
    setCode: "4ed",
    rarity: "common",
};

export const clockworkAvian4ed: CardPrint = {
    printId: "4a92484b-064c-4588-a1ea-6de8fd485ca4",
    definitionId: "1dea8c2f-4aea-478d-aee7-cba1f74edd6c", // Clockwork Avian
    setCode: "4ed",
    rarity: "rare",
};

export const clockworkBeast4ed: CardPrint = {
    printId: "40dc8595-32b9-4045-bae3-5078c9a17527",
    definitionId: "27f916a2-0ace-44b5-99dc-72979af34db9", // Clockwork Beast
    setCode: "4ed",
    rarity: "rare",
};

export const colossusOfSardia4ed: CardPrint = {
    printId: "063acc0f-8062-4461-b0f5-8c3a835e1fbf",
    definitionId: "067c44e9-1b23-42fd-9acb-daafb62c32a2", // Colossus of Sardia
    setCode: "4ed",
    rarity: "rare",
};

export const conservator4ed: CardPrint = {
    printId: "f6639eea-d0ae-4f0d-a8da-1b863b482b68",
    definitionId: "c7824e2a-4eff-4f72-9216-0db30a4f4252", // Conservator
    setCode: "4ed",
    rarity: "uncommon",
};

export const coralHelm4ed: CardPrint = {
    printId: "6065242b-e14e-44fa-bbe0-00f070f0140a",
    definitionId: "6c6df9db-0a46-40a5-ae9d-59f47dae9056", // Coral Helm
    setCode: "4ed",
    rarity: "rare",
};

export const crystalRod4ed: CardPrint = {
    printId: "c05c17c7-49c2-41f2-842e-d980e7d62613",
    definitionId: "76693233-7961-4b7e-80f2-ed90e494c4aa", // Crystal Rod
    setCode: "4ed",
    rarity: "uncommon",
};

export const cursedRack4ed: CardPrint = {
    printId: "28cbcab8-5593-4ef0-8689-77e71fb1c41a",
    definitionId: "720d871d-1e7b-482e-bd1e-8ec79519fb86", // Cursed Rack
    setCode: "4ed",
    rarity: "uncommon",
};

export const dancingScimitar4ed: CardPrint = {
    printId: "c0662881-664f-47d2-8164-b4727125ba0b",
    definitionId: "1eb2e494-1414-4d1f-91d2-7cb20acdb128", // Dancing Scimitar
    setCode: "4ed",
    rarity: "rare",
};

export const diabolicMachine4ed: CardPrint = {
    printId: "23d2c7c2-5696-49a0-b6b0-789bfe839f8d",
    definitionId: "c3b0f228-6b06-4426-a557-1225d547b908", // Diabolic Machine
    setCode: "4ed",
    rarity: "uncommon",
};

export const dingusEgg4ed: CardPrint = {
    printId: "b9c44bba-5eaa-41a6-a11a-0bc8fb751ad8",
    definitionId: "65eb6cda-e512-40a8-9c1f-335b713409ff", // Dingus Egg
    setCode: "4ed",
    rarity: "rare",
};

export const disruptingScepter4ed: CardPrint = {
    printId: "fb9b9085-6dd7-44fc-b3a5-7f797c34f8dc",
    definitionId: "ca571ee8-07a2-43b8-9acf-89cbfd3cf7c9", // Disrupting Scepter
    setCode: "4ed",
    rarity: "rare",
};

export const dragonEngine4ed: CardPrint = {
    printId: "80ecbbb3-2d0d-49dc-90b3-1b396d47bf56",
    definitionId: "07793a71-1106-4303-b620-e403bd378020", // Dragon Engine
    setCode: "4ed",
    rarity: "rare",
};

export const ebonyHorse4ed: CardPrint = {
    printId: "b665f9dc-a5df-4ad7-9067-9b48f942bdde",
    definitionId: "9ae81ec7-2b7d-4301-8114-032be5e6b663", // Ebony Horse
    setCode: "4ed",
    rarity: "rare",
};

export const fellwarStone4ed: CardPrint = {
    printId: "6f7a41cc-277a-4d95-a30c-91bf5aa7ac11",
    definitionId: "dc47e322-f8b8-4685-b035-fda0cc433e6b", // Fellwar Stone
    setCode: "4ed",
    rarity: "uncommon",
};

export const flyingCarpet4ed: CardPrint = {
    printId: "300428ea-7909-4c2b-81cc-a03d51030bcb",
    definitionId: "4b71ff49-ee0a-4065-9131-380468d62a30", // Flying Carpet
    setCode: "4ed",
    rarity: "rare",
};

export const glassesOfUrza4ed: CardPrint = {
    printId: "4d71a210-eb2c-4bcc-ae3b-f60a6fb615cb",
    definitionId: "cafc2350-5d64-4379-9198-79a114654d45", // Glasses of Urza
    setCode: "4ed",
    rarity: "uncommon",
};

export const grapeshotCatapult4ed: CardPrint = {
    printId: "d0f96f18-8340-4b50-9b4c-3c72c0bbc2f2",
    definitionId: "4c7a7348-c82e-453c-975c-e5365e152a3a", // Grapeshot Catapult
    setCode: "4ed",
    rarity: "common",
};

export const greenManaBattery4ed: CardPrint = {
    printId: "d0a6e224-72df-4f1f-93d1-5114779aed2c",
    definitionId: "4671fa01-4a9e-4cd9-8154-b0d45e11b702", // Green Mana Battery
    setCode: "4ed",
    rarity: "rare",
};

export const helmOfChatzuk4ed: CardPrint = {
    printId: "673c0a08-1aaf-4976-8eea-c93a9f9486fa",
    definitionId: "3792c6ef-c4e6-4923-9a51-7d28fbc5c393", // Helm of Chatzuk
    setCode: "4ed",
    rarity: "rare",
};

export const howlingMine4ed: CardPrint = {
    printId: "a4df1be4-364e-4582-929a-05f2905f8ce6",
    definitionId: "51f8f6e1-a451-4262-90d3-5107caf54175", // Howling Mine
    setCode: "4ed",
    rarity: "rare",
};

export const ironStar4ed: CardPrint = {
    printId: "b8846e66-fd42-4e74-80fe-858944108d40",
    definitionId: "5786de12-cade-43c2-a6b0-0c5b294b9d0e", // Iron Star
    setCode: "4ed",
    rarity: "uncommon",
};

export const ivoryCup4ed: CardPrint = {
    printId: "14f378af-ea54-4035-9e3e-e8cf980d1e84",
    definitionId: "9964d8d8-dc97-4e5f-9f52-173f7e2c37fd", // Ivory Cup
    setCode: "4ed",
    rarity: "uncommon",
};

export const ivoryTower4ed: CardPrint = {
    printId: "eff5624d-fffa-48c1-91f3-f03585e45c69",
    definitionId: "a5f23039-45ca-4c15-af50-bfd40ea26453", // Ivory Tower
    setCode: "4ed",
    rarity: "rare",
};

export const jadeMonolith4ed: CardPrint = {
    printId: "044e5475-4ab5-45c5-b86d-9b4720e7ba0c",
    definitionId: "4a77e0f1-449d-4a7d-9fa0-ba7598f7a73a", // Jade Monolith
    setCode: "4ed",
    rarity: "rare",
};

export const jandorSSaddlebags4ed: CardPrint = {
    printId: "ac15b58c-80b4-4da7-8ed6-d963702eda3a",
    definitionId: "bc4f4b92-7d4e-4b03-8cb4-e6b356c338b4", // Jandor's Saddlebags
    setCode: "4ed",
    rarity: "rare",
};

export const jayemdaeTome4ed: CardPrint = {
    printId: "4009fceb-9140-457b-b980-875f6a2f70fd",
    definitionId: "cac8c421-5b92-481d-b2de-560c0231ab58", // Jayemdae Tome
    setCode: "4ed",
    rarity: "rare",
};

export const kormusBell4ed: CardPrint = {
    printId: "3bd054ed-9c91-4bc6-9d0d-0c045c089bd9",
    definitionId: "3f4ef7a1-148d-44ac-89ed-0ef379cca0c6", // Kormus Bell
    setCode: "4ed",
    rarity: "rare",
};

export const libraryOfLeng4ed: CardPrint = {
    printId: "b811a515-87a2-4dee-8689-48bfba12e6c5",
    definitionId: "2340edcb-8cd5-4ccd-99e2-b9a29f72c495", // Library of Leng
    setCode: "4ed",
    rarity: "uncommon",
};

export const manaVault4ed: CardPrint = {
    printId: "3be9942c-89b3-422f-bb9d-b55f51a22a37",
    definitionId: "19499cb7-eccb-4e69-af32-6002d447a160", // Mana Vault
    setCode: "4ed",
    rarity: "rare",
};

export const meekstone4ed: CardPrint = {
    printId: "c9714ce0-7fc3-4bf3-ad65-68555a9d2f35",
    definitionId: "13a68a17-22ee-47c9-870a-83e911862b94", // Meekstone
    setCode: "4ed",
    rarity: "rare",
};

export const millstone4ed: CardPrint = {
    printId: "f16f7d28-1bc2-44b6-973b-c60d966101a6",
    definitionId: "107646bc-2181-49f4-8821-1eaa46291855", // Millstone
    setCode: "4ed",
    rarity: "rare",
};

export const mishraSWarMachine4ed: CardPrint = {
    printId: "0f7b5921-3e10-47e7-98a7-8411a18313bf",
    definitionId: "8f6b4652-a1d4-418f-a89b-6a977a920a9e", // Mishra's War Machine
    setCode: "4ed",
    rarity: "rare",
};

export const nevinyrralSDisk4ed: CardPrint = {
    printId: "d427396c-f1ef-46ac-b130-ed1e51e826a3",
    definitionId: "12926dc8-8e6f-4a47-a12b-4d674189615a", // Nevinyrral's Disk
    setCode: "4ed",
    rarity: "rare",
};

export const obsianusGolem4ed: CardPrint = {
    printId: "837605e3-f4c2-4b60-8478-f21ca8734ef2",
    definitionId: "4c8e9f5c-deba-4443-bf9d-fb2be75c5418", // Obsianus Golem
    setCode: "4ed",
    rarity: "uncommon",
};

export const onulet4ed: CardPrint = {
    printId: "c64c2dff-9c11-4c91-a606-b5de704f18d4",
    definitionId: "d77fe8e2-8438-473e-ace5-01baddd2c4ed", // Onulet
    setCode: "4ed",
    rarity: "rare",
};

export const ornithopter4ed: CardPrint = {
    printId: "2aeb3ce1-1e7f-4269-a326-700f27e9e932",
    definitionId: "59cc9bdb-7cf2-4795-bac7-ffff605c9eb0", // Ornithopter
    setCode: "4ed",
    rarity: "uncommon",
};

export const primalClay4ed: CardPrint = {
    printId: "cc49d724-b46d-449b-bd2b-03551e130a06",
    definitionId: "ab9d0e3f-cf7c-41f8-bcd7-bb08ea8cc2f8", // Primal Clay
    setCode: "4ed",
    rarity: "rare",
};

export const redManaBattery4ed: CardPrint = {
    printId: "e4e507bc-441d-4f44-85d4-cf93ca199d2e",
    definitionId: "363cc5d6-70f8-4a3c-92bd-8f49774bdce2", // Red Mana Battery
    setCode: "4ed",
    rarity: "rare",
};

export const rodOfRuin4ed: CardPrint = {
    printId: "88bf9da4-4647-4c66-a3ce-fab7ca9618d1",
    definitionId: "af957200-c538-4f52-b105-6db7a7abb4dc", // Rod of Ruin
    setCode: "4ed",
    rarity: "uncommon",
};

export const shapeshifter4ed: CardPrint = {
    printId: "0b9d1526-9888-41bc-b77d-88d62325e0b2",
    definitionId: "cc278af4-b60d-41b7-b9d7-36c8aefca1a7", // Shapeshifter
    setCode: "4ed",
    rarity: "uncommon",
};

export const soulNet4ed: CardPrint = {
    printId: "8ccacae0-f8db-45e0-b25a-35418fd24389",
    definitionId: "2b814198-814b-4619-a158-327af675f8f2", // Soul Net
    setCode: "4ed",
    rarity: "uncommon",
};

export const sunglassesOfUrza4ed: CardPrint = {
    printId: "6a225462-947c-49d7-81b2-91f875664dca",
    definitionId: "c0d433a4-76c0-4f27-836d-4c0c13a511fb", // Sunglasses of Urza
    setCode: "4ed",
    rarity: "rare",
};

export const tawnosSWand4ed: CardPrint = {
    printId: "d566993f-18a6-4e5c-abc3-0fe9a03e97d2",
    definitionId: "978f09dd-121a-4da5-ba16-5c03fbdce084", // Tawnos's Wand
    setCode: "4ed",
    rarity: "uncommon",
};

export const tawnosSWeaponry4ed: CardPrint = {
    printId: "4750787e-9fef-4bdf-b2e3-e410c84999f2",
    definitionId: "3035cead-a501-4204-9154-5fd648577d32", // Tawnos's Weaponry
    setCode: "4ed",
    rarity: "uncommon",
};

export const tetravus4ed: CardPrint = {
    printId: "49c1a2b2-50f0-4ed0-bd8f-06cd6aada04f",
    definitionId: "23eb19f9-2e8f-4bf0-9bf8-868e6da70e2d", // Tetravus
    setCode: "4ed",
    rarity: "rare",
};

export const theHive4ed: CardPrint = {
    printId: "f9d01a2e-2687-4b37-aed6-63202cd81231",
    definitionId: "544a7138-eae8-4ff9-9e17-680bfa717183", // The Hive
    setCode: "4ed",
    rarity: "rare",
};

export const theRack4ed: CardPrint = {
    printId: "1e19104f-55d5-40e5-a61d-ddba2cf5a527",
    definitionId: "ec0686ba-1277-4412-a397-7a6227808311", // The Rack
    setCode: "4ed",
    rarity: "uncommon",
};

export const throneOfBone4ed: CardPrint = {
    printId: "98e77be1-3c29-40b4-9c47-44fa2d9d4454",
    definitionId: "a2931ae0-7836-4000-b9ec-f2029ebf5d96", // Throne of Bone
    setCode: "4ed",
    rarity: "uncommon",
};

export const triskelion4ed: CardPrint = {
    printId: "09294401-a895-4084-8302-196a946863d6",
    definitionId: "a79c99e1-722a-44b6-8fa3-2be3f0c193d8", // Triskelion
    setCode: "4ed",
    rarity: "rare",
};

export const urzaSAvenger4ed: CardPrint = {
    printId: "97dd1daa-0b5d-4d0c-9a67-a59083038f2d",
    definitionId: "448e1811-fb16-4390-ac22-b7066a4a019c", // Urza's Avenger
    setCode: "4ed",
    rarity: "rare",
};

export const wallOfSpears4ed: CardPrint = {
    printId: "ad580bfc-8827-4a8a-a5ec-b6195b3146bb",
    definitionId: "b1dda179-c49a-4995-ba5a-db93ac43dbe7", // Wall of Spears
    setCode: "4ed",
    rarity: "common",
};

export const whiteManaBattery4ed: CardPrint = {
    printId: "b622e694-858d-482f-a67d-0e52d268708c",
    definitionId: "35fbbe41-d21b-4028-905f-054c44d30eb2", // White Mana Battery
    setCode: "4ed",
    rarity: "rare",
};

export const winterOrb4ed: CardPrint = {
    printId: "d60ee90d-5f7b-4294-8d52-9744fada8d36",
    definitionId: "9359f60c-9a27-4e53-b35b-964a121a6fba", // Winter Orb
    setCode: "4ed",
    rarity: "rare",
};

export const woodenSphere4ed: CardPrint = {
    printId: "6a51abf0-8661-4776-929d-35b7bd345e21",
    definitionId: "bcae01a2-171b-47cd-87be-f1e4e5314326", // Wooden Sphere
    setCode: "4ed",
    rarity: "uncommon",
};

export const yotianSoldier4ed: CardPrint = {
    printId: "aaab84be-bb96-437b-a9a7-aa7a11ffd21d",
    definitionId: "27cf53e3-76f6-4831-800e-1259394d779d", // Yotian Soldier
    setCode: "4ed",
    rarity: "common",
};

export const mishraSFactory4ed: CardPrint = {
    printId: "aff8d4f1-eaad-4afb-9097-2afab133f707",
    definitionId: "a696c5b6-f216-454d-8029-74e84bbd1428", // Mishra's Factory
    setCode: "4ed",
    rarity: "uncommon",
};

export const oasis4ed: CardPrint = {
    printId: "1d51a6de-7bb4-4e3d-82a7-a298c8d742ef",
    definitionId: "6f38565e-88b9-433d-b0e9-a3b9734f183f", // Oasis
    setCode: "4ed",
    rarity: "uncommon",
};

export const stripMine4ed: CardPrint = {
    printId: "a5899b46-226b-4be6-8e80-d2396f54210d",
    definitionId: "e7880157-7f27-4f1b-9cdc-ab36a6252376", // Strip Mine
    setCode: "4ed",
    rarity: "uncommon",
};

// Basic lands (art variants — one print per collector number).

export const plains4ed: CardPrint = {
    printId: "639e47dc-c90f-4f55-9b3a-721240ec04ed",
    definitionId: "b1623d57-4729-4796-b3f7-f1837a05c6ed", // Plains
    setCode: "4ed",
    rarity: "common",
};

export const plains24ed: CardPrint = {
    printId: "d17f8abd-c087-4039-8dfd-c6168f7db0a6",
    definitionId: "b1623d57-4729-4796-b3f7-f1837a05c6ed", // Plains
    setCode: "4ed",
    rarity: "common",
};

export const plains34ed: CardPrint = {
    printId: "ad1317da-9e81-4aff-8c04-9155d14be90c",
    definitionId: "b1623d57-4729-4796-b3f7-f1837a05c6ed", // Plains
    setCode: "4ed",
    rarity: "common",
};

export const island4ed: CardPrint = {
    printId: "b06bbd6e-eb0d-45fc-88ef-0e085d6505ef",
    definitionId: "90a57c0e-fa61-45ef-955d-d296403967d5", // Island
    setCode: "4ed",
    rarity: "common",
};

export const island24ed: CardPrint = {
    printId: "6e5e3819-3d75-40d4-9a93-1147834dfd69",
    definitionId: "90a57c0e-fa61-45ef-955d-d296403967d5", // Island
    setCode: "4ed",
    rarity: "common",
};

export const island34ed: CardPrint = {
    printId: "33a05f9a-1285-4d14-b827-8b81968e09df",
    definitionId: "90a57c0e-fa61-45ef-955d-d296403967d5", // Island
    setCode: "4ed",
    rarity: "common",
};

export const swamp4ed: CardPrint = {
    printId: "84634023-5c94-4dcc-9449-abf73ecea542",
    definitionId: "6176936d-72e2-4205-8871-4c5a4f1cb2d8", // Swamp
    setCode: "4ed",
    rarity: "common",
};

export const swamp24ed: CardPrint = {
    printId: "ddaa0be1-7358-4ea2-8c40-be6d699a6631",
    definitionId: "6176936d-72e2-4205-8871-4c5a4f1cb2d8", // Swamp
    setCode: "4ed",
    rarity: "common",
};

export const swamp34ed: CardPrint = {
    printId: "7ac4979a-5b2f-4db1-b665-9d8ccc15ba82",
    definitionId: "6176936d-72e2-4205-8871-4c5a4f1cb2d8", // Swamp
    setCode: "4ed",
    rarity: "common",
};

export const mountain4ed: CardPrint = {
    printId: "0c5c9379-b686-4823-b85a-eaf2c4b63205",
    definitionId: "eace2c85-976c-425e-9800-5a6ccbd91b56", // Mountain
    setCode: "4ed",
    rarity: "common",
};

export const mountain24ed: CardPrint = {
    printId: "10478e22-d1dd-4e02-81a7-d93ce71ed81d",
    definitionId: "eace2c85-976c-425e-9800-5a6ccbd91b56", // Mountain
    setCode: "4ed",
    rarity: "common",
};

export const mountain34ed: CardPrint = {
    printId: "50352268-88a6-4575-a5e1-cd8bef7f8286",
    definitionId: "eace2c85-976c-425e-9800-5a6ccbd91b56", // Mountain
    setCode: "4ed",
    rarity: "common",
};

export const forest4ed: CardPrint = {
    printId: "119c4d73-5b71-446a-a739-25d494591aa1",
    definitionId: "6f1c8cb0-38eb-408b-94e8-16db83999b3b", // Forest
    setCode: "4ed",
    rarity: "common",
};

export const forest24ed: CardPrint = {
    printId: "ddb35995-0298-4281-88d1-2531c93a4916",
    definitionId: "6f1c8cb0-38eb-408b-94e8-16db83999b3b", // Forest
    setCode: "4ed",
    rarity: "common",
};

export const forest34ed: CardPrint = {
    printId: "b794073f-4188-45c9-9e65-c9d7f2ecc24b",
    definitionId: "6f1c8cb0-38eb-408b-94e8-16db83999b3b", // Forest
    setCode: "4ed",
    rarity: "common",
};
