import type { CardPrint } from "../../types";

// 4ED (Fourth Edition) green cards, split by colour per ADR 0043.
//
// Fourth Edition is a 100% reprint set — it introduces no new cards — so this
// module is entirely CardPrint entries: each declares the per-edition Scryfall
// UUID (printId) and resolves printId -> definitionId -> a shared CardDefinition
// already implemented in arn/atq/drk/lea/leb/leg. See ADR 0014.
// 4ED is the earliest Premodern-legal set (issue #980).
//
// Generated by scripts/generate-print-set.mts 4ed from data/json/4ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 4ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: ante cards — Bronze Tablet, Rebirth, Tempest Efreet — are permanently out of
// scope (ADR 0010) and carry no print row. Cards whose CardDefinition is not
// yet implemented are omitted; each lands automatically once its definition
// exists.

export const aspectOfWolf4ed: CardPrint = {
    printId: "58e780b8-8002-47d4-9d0c-bd65a40ea34e",
    definitionId: "fd9ac9e6-1395-4fbd-80e2-645f0d910c29", // Aspect of Wolf
    setCode: "4ed",
    rarity: "rare",
};

export const birdsOfParadise4ed: CardPrint = {
    printId: "b8852e36-204c-4b3a-a4f8-33a98548fa7b",
    definitionId: "55fe6449-1f23-43dc-adee-d144cd505b5c", // Birds of Paradise
    setCode: "4ed",
    rarity: "rare",
};

export const carnivorousPlant4ed: CardPrint = {
    printId: "6f449835-5e20-4244-b7f4-c22838910076",
    definitionId: "6a615650-4da3-4efc-aa5e-c1f2c4f79478", // Carnivorous Plant
    setCode: "4ed",
    rarity: "common",
};

export const channel4ed: CardPrint = {
    printId: "e42eb95f-638d-410c-a830-a414fb2494ec",
    definitionId: "c1862c47-71cc-45a3-8805-a5ddc62e55ea", // Channel
    setCode: "4ed",
    rarity: "uncommon",
};

export const cockatrice4ed: CardPrint = {
    printId: "3406dfe1-68e9-4757-9487-0b556c97d07a",
    definitionId: "9cd91814-6177-4a3d-a1c1-a3be7d7c7957", // Cockatrice
    setCode: "4ed",
    rarity: "rare",
};

export const crawWurm4ed: CardPrint = {
    printId: "57e9cf07-a335-4725-a124-0e983721f2f8",
    definitionId: "bfed1a95-bd67-4e16-a781-81866028af2f", // Craw Wurm
    setCode: "4ed",
    rarity: "common",
};

export const crumble4ed: CardPrint = {
    printId: "86873be9-21eb-496c-b278-4c9847563b0f",
    definitionId: "d2101f86-8d3c-4ba8-ac42-bd3df0644280", // Crumble
    setCode: "4ed",
    rarity: "uncommon",
};

export const desertTwister4ed: CardPrint = {
    printId: "5603ce3f-3b39-4433-8ccf-44b44dc99de5",
    definitionId: "0d77c149-cca2-45c7-bc83-5ba1872ad5e0", // Desert Twister
    setCode: "4ed",
    rarity: "uncommon",
};

export const durkwoodBoars4ed: CardPrint = {
    printId: "e85ab895-d2b9-47f5-91f0-07b0cb43fc7c",
    definitionId: "8d41f08b-68fb-45f2-bdc9-488baedc7d6f", // Durkwood Boars
    setCode: "4ed",
    rarity: "common",
};

export const elvenRiders4ed: CardPrint = {
    printId: "906095f6-25c7-4f61-8513-9d75e32aab02",
    definitionId: "ad1d349b-b5ab-4b2b-9b39-f8d8f6374aa5", // Elven Riders
    setCode: "4ed",
    rarity: "uncommon",
};

export const elvishArchers4ed: CardPrint = {
    printId: "efd21750-856f-4017-a728-dcbf3f506f20",
    definitionId: "1cb9d405-f2b5-4e10-a405-feafd2a87d90", // Elvish Archers
    setCode: "4ed",
    rarity: "rare",
};

export const fog4ed: CardPrint = {
    printId: "a1959de7-e945-438c-a90a-158e21c4d5bf",
    definitionId: "cfba606d-bb55-43ba-aa0c-299649958788", // Fog
    setCode: "4ed",
    rarity: "common",
};

export const forceOfNature4ed: CardPrint = {
    printId: "ccef1a44-faf8-42bd-aaff-778f65d18ae9",
    definitionId: "21551cb6-3a53-42dd-9bbd-4bc56304d6d3", // Force of Nature
    setCode: "4ed",
    rarity: "rare",
};

export const fungusaur4ed: CardPrint = {
    printId: "7d9ff903-176f-45e7-82fd-e9705c1c719f",
    definitionId: "5ad89f0d-b09b-40a0-84d6-3ee60dec7e23", // Fungusaur
    setCode: "4ed",
    rarity: "rare",
};

export const gaeaSLiege4ed: CardPrint = {
    printId: "4d9e1c1b-bc7c-41b8-a983-b1c60f558547",
    definitionId: "e2b15221-c8b0-4861-9f8b-8a65834ad499", // Gaea's Liege
    setCode: "4ed",
    rarity: "rare",
};

export const giantGrowth4ed: CardPrint = {
    printId: "c6ce96a5-76f1-48ca-854d-a37fb6a023a0",
    definitionId: "367dbefe-3366-408e-9fcf-7dc00f8cc201", // Giant Growth
    setCode: "4ed",
    rarity: "common",
};

export const giantSpider4ed: CardPrint = {
    printId: "9dd711db-661d-4e2c-b817-0905e26ed929",
    definitionId: "77636b4c-faea-4bf5-b88c-dd5bb88dc930", // Giant Spider
    setCode: "4ed",
    rarity: "common",
};

export const grizzlyBears4ed: CardPrint = {
    printId: "38fc72de-2093-477b-b39e-696339d2fdbc",
    definitionId: "ce2d603a-3231-4a8c-bf39-1617586ea870", // Grizzly Bears
    setCode: "4ed",
    rarity: "common",
};

export const hurricane4ed: CardPrint = {
    printId: "8457f271-4075-4694-a1c0-280aff910953",
    definitionId: "52f5a19f-16e4-4d35-89e1-969ac8202f88", // Hurricane
    setCode: "4ed",
    rarity: "uncommon",
};

export const instillEnergy4ed: CardPrint = {
    printId: "0eeb4671-e6f6-4f64-83f8-8c2a56defa1b",
    definitionId: "5bd38716-874c-4e3c-a315-837839a6258c", // Instill Energy
    setCode: "4ed",
    rarity: "uncommon",
};

export const ironrootTreefolk4ed: CardPrint = {
    printId: "c6c93c85-5263-4770-b937-704e57912478",
    definitionId: "b93c5869-7777-44bb-967a-e9439b25ced4", // Ironroot Treefolk
    setCode: "4ed",
    rarity: "common",
};

export const killerBees4ed: CardPrint = {
    printId: "e4e748b0-4041-4266-a777-e1b8a5533e80",
    definitionId: "2e30b5ff-1239-4c4d-ac7c-554ecf8e1e27", // Killer Bees
    setCode: "4ed",
    rarity: "uncommon",
};

export const landLeeches4ed: CardPrint = {
    printId: "71f1d97c-5bfa-4791-9004-5f2464908c30",
    definitionId: "ff99543d-86a1-44f8-88ec-aaec071d6c05", // Land Leeches
    setCode: "4ed",
    rarity: "common",
};

export const leyDruid4ed: CardPrint = {
    printId: "925adfb2-cfe3-4847-9db0-20bbe4e7baf1",
    definitionId: "f9232508-d363-4ef3-987a-741f6bff331f", // Ley Druid
    setCode: "4ed",
    rarity: "uncommon",
};

export const lifeforce4ed: CardPrint = {
    printId: "e1ca1cc3-e588-4ef7-b846-d5dba3c875a0",
    definitionId: "e292577e-6232-44fa-a9c2-cc09949c6ed3", // Lifeforce
    setCode: "4ed",
    rarity: "uncommon",
};

export const lifelace4ed: CardPrint = {
    printId: "bf312acb-2fa6-440a-964b-424ad8abc331",
    definitionId: "38cb601b-a35c-412e-b386-e77dad3daa54", // Lifelace
    setCode: "4ed",
    rarity: "rare",
};

export const livingArtifact4ed: CardPrint = {
    printId: "2cbe717c-313c-4a8c-85a5-d23d3796ff26",
    definitionId: "c9e753a2-a7d0-4d37-ae65-b5a1b5039a6e", // Living Artifact
    setCode: "4ed",
    rarity: "rare",
};

export const livingLands4ed: CardPrint = {
    printId: "36d5c0df-3db4-4e2d-9688-223383e02b02",
    definitionId: "80be0580-7948-4d8e-8c0f-5e2797ac411b", // Living Lands
    setCode: "4ed",
    rarity: "rare",
};

export const llanowarElves4ed: CardPrint = {
    printId: "75d972d7-5ed9-49c1-8d27-ec162771284d",
    definitionId: "d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb", // Llanowar Elves
    setCode: "4ed",
    rarity: "common",
};

export const lure4ed: CardPrint = {
    printId: "7abc17aa-8f6b-4156-b148-fc049e1d316a",
    definitionId: "2a87b26e-0431-42e9-b44f-94ba8546111a", // Lure
    setCode: "4ed",
    rarity: "uncommon",
};

export const marshViper4ed: CardPrint = {
    printId: "16524bd2-0d88-451c-a394-7d5fe204dfc6",
    definitionId: "109cce7a-96f7-4e67-878a-bd5c93ea8643", // Marsh Viper
    setCode: "4ed",
    rarity: "common",
};

export const nafsAsp4ed: CardPrint = {
    printId: "0db4a4ef-20a8-415f-8d7d-a6740b482f73",
    definitionId: "965f722c-2b18-4c22-8c30-12552def5940", // Nafs Asp
    setCode: "4ed",
    rarity: "common",
};

export const pradeshGypsies4ed: CardPrint = {
    printId: "2338aeec-63f6-4cc1-833e-77d44994a7ca",
    definitionId: "0370330d-83d9-44d2-a1ed-c4827edc60fd", // Pradesh Gypsies
    setCode: "4ed",
    rarity: "common",
};

export const regeneration4ed: CardPrint = {
    printId: "5697b2e7-25c5-4ae0-a9ac-48cbc6a94c15",
    definitionId: "b7b7aa34-b4f8-41b4-82ce-ab2e204c3bf4", // Regeneration
    setCode: "4ed",
    rarity: "common",
};

export const sandstorm4ed: CardPrint = {
    printId: "ca9af432-3997-426a-b532-52333c3c50c4",
    definitionId: "73cba9cd-73d9-442e-bd99-9cba9f398b64", // Sandstorm
    setCode: "4ed",
    rarity: "common",
};

export const scrybSprites4ed: CardPrint = {
    printId: "281e8da8-1383-460e-b74e-ad56f1b6d007",
    definitionId: "6d929c38-91e6-457c-937a-d1884f4bba44", // Scryb Sprites
    setCode: "4ed",
    rarity: "common",
};

export const shanodinDryads4ed: CardPrint = {
    printId: "8d8f8c01-6f1c-4902-a7fd-c9cf04b28461",
    definitionId: "814cf35c-f1ad-4bf4-8c10-a5592c3b1be8", // Shanodin Dryads
    setCode: "4ed",
    rarity: "common",
};

export const streamOfLife4ed: CardPrint = {
    printId: "ca367627-9be3-4e80-a214-0b3f0f2ab867",
    definitionId: "aa1c4d4b-2645-4cd9-823e-3c9bb2eb48f9", // Stream of Life
    setCode: "4ed",
    rarity: "common",
};

export const sylvanLibrary4ed: CardPrint = {
    printId: "b1a9682c-ecca-4caa-9e5a-17874167082b",
    definitionId: "f486df00-7c4a-4ff0-bb0b-c8b5432ac742", // Sylvan Library
    setCode: "4ed",
    rarity: "rare",
};

export const thicketBasilisk4ed: CardPrint = {
    printId: "c63c16a5-588e-4ef1-9e79-4d36127cd84b",
    definitionId: "e92cce01-b3bd-4307-aae5-9a7c8fa386ab", // Thicket Basilisk
    setCode: "4ed",
    rarity: "uncommon",
};

export const timberWolves4ed: CardPrint = {
    printId: "d8f84fc8-69b4-4756-9634-4d6c17ec88a1",
    definitionId: "bc2570a4-eef9-430d-b6c2-cd51d29b9d01", // Timber Wolves
    setCode: "4ed",
    rarity: "rare",
};

export const titaniaSSong4ed: CardPrint = {
    printId: "19dd44e3-d62c-405d-a620-7dc871eef81c",
    definitionId: "583a53af-2e2a-4f3f-8eab-bd874c6ed80a", // Titania's Song
    setCode: "4ed",
    rarity: "rare",
};

export const tranquility4ed: CardPrint = {
    printId: "b1c8b995-f3d9-435a-8360-4047a619b23b",
    definitionId: "774cc5a6-3a69-4812-add4-eb5eb6389238", // Tranquility
    setCode: "4ed",
    rarity: "common",
};

export const tsunami4ed: CardPrint = {
    printId: "227c2abc-d484-4198-863c-3266a83249c6",
    definitionId: "9ed67d61-cf47-446b-b454-eb404a8686b7", // Tsunami
    setCode: "4ed",
    rarity: "uncommon",
};

export const venom4ed: CardPrint = {
    printId: "c7a314a0-14cb-4df1-8f2f-653455f13b09",
    definitionId: "bb0480f5-6aae-4297-afa6-3f7a5801bf95", // Venom
    setCode: "4ed",
    rarity: "common",
};

export const verduranEnchantress4ed: CardPrint = {
    printId: "96e30d22-da86-49a1-a319-22e8a909d443",
    definitionId: "9f87178b-1221-4d7a-a7a5-20d7f01b8089", // Verduran Enchantress
    setCode: "4ed",
    rarity: "rare",
};

export const wallOfBrambles4ed: CardPrint = {
    printId: "bbd66c7c-19fb-4daa-996e-70107d732732",
    definitionId: "af2a4558-db6e-41b2-aff6-b164d93282a0", // Wall of Brambles
    setCode: "4ed",
    rarity: "uncommon",
};

export const wallOfIce4ed: CardPrint = {
    printId: "d702bd22-6079-4f4c-9540-42cf2a29f4a3",
    definitionId: "cc743a03-867c-4bb0-8fb0-2bcaa0a8a756", // Wall of Ice
    setCode: "4ed",
    rarity: "uncommon",
};

export const wallOfWood4ed: CardPrint = {
    printId: "39f236da-8391-487b-88d4-a45342bfff62",
    definitionId: "8df80424-3bd9-4982-ad79-e55d9ba3b43d", // Wall of Wood
    setCode: "4ed",
    rarity: "common",
};

export const wanderlust4ed: CardPrint = {
    printId: "f4144ca4-4817-4bb9-929b-613fc609bdb5",
    definitionId: "220a03ca-8c9b-4acb-821d-f6577fbb20fb", // Wanderlust
    setCode: "4ed",
    rarity: "uncommon",
};

export const warMammoth4ed: CardPrint = {
    printId: "2137757c-161c-4a3b-9a99-0fd23aa0c847",
    definitionId: "c8d6081e-f686-4263-a0a2-21c0d9af5fdb", // War Mammoth
    setCode: "4ed",
    rarity: "common",
};

export const web4ed: CardPrint = {
    printId: "0547a390-ceee-4b8a-9d0e-36d8778ec693",
    definitionId: "37c7890a-86dc-4a97-a7ce-1436fa22d0c0", // Web
    setCode: "4ed",
    rarity: "rare",
};

export const whirlingDervish4ed: CardPrint = {
    printId: "b0f4724e-f22e-4156-97fd-1adfccc47be3",
    definitionId: "eba294e7-7097-4bc3-b396-72e85dd4f441", // Whirling Dervish
    setCode: "4ed",
    rarity: "uncommon",
};

export const wildGrowth4ed: CardPrint = {
    printId: "4aea57a2-2753-4014-9724-2701455a6be8",
    definitionId: "fd896dfa-66c0-4327-8e5b-489bbe350c95", // Wild Growth
    setCode: "4ed",
    rarity: "common",
};

export const winterBlast4ed: CardPrint = {
    printId: "3d4f72de-51e9-45c2-853b-1b6668416417",
    definitionId: "fb846366-2105-4999-8af1-a11687f42e17", // Winter Blast
    setCode: "4ed",
    rarity: "uncommon",
};
