// 4ED set barrel — re-exports every colour module so the registry's
// `import * from "./sets/4ed"` resolves here unchanged (ADR 0043).
// Fourth Edition is a reprint-only set; only the colour modules with CardPrint
// entries exist.
//
// Generated by scripts/generate-print-set.mts 4ed — re-run to regenerate.

export * from "./white";
export * from "./blue";
export * from "./black";
export * from "./red";
export * from "./green";
export * from "./colorless";
