// 4ED set barrel — re-exports every colour module so the registry's
// `import * from "./sets/4ed/index.cards"` resolves here (ADR 0043).
// Fourth Edition is a reprint-only set; only the colour modules with CardPrint
// entries exist.
//
// Generated by scripts/generate-print-set.mts 4ed — re-run to regenerate.

export * from "./white.cards";
export * from "./blue.cards";
export * from "./black.cards";
export * from "./red.cards";
export * from "./green.cards";
export * from "./colorless.cards";
