// 4ED set barrel — re-exports every colour module so the registry's
// `import * as fourthEdition from "./sets/4ed"` resolves here unchanged
// (ADR 0043). 4ED is a reprint-only core set; only the colour modules with
// CardPrint entries exist.
//
// Generated by scripts/generate-4ed-prints.mts — re-run to regenerate.

export * from "./white";
export * from "./blue";
export * from "./black";
export * from "./red";
export * from "./green";
export * from "./colorless";
