import type { CardPrint } from "../../types";

// 4ED (Fourth Edition) red cards, split by colour per ADR 0043.
//
// Fourth Edition is a 100% reprint set — it introduces no new cards — so this
// module is entirely CardPrint entries: each declares the per-edition Scryfall
// UUID (printId) and resolves printId -> definitionId -> a shared CardDefinition
// already implemented in arn/atq/drk/lea/leb/leg. See ADR 0014.
// 4ED is the earliest Premodern-legal set (issue #980).
//
// Generated by scripts/generate-print-set.mts 4ed from data/json/4ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 4ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: ante cards — Bronze Tablet, Rebirth, Tempest Efreet — are permanently out of
// scope (ADR 0010) and carry no print row. Cards whose CardDefinition is not
// yet implemented are omitted; each lands automatically once its definition
// exists.

export const aliBaba4ed: CardPrint = {
    printId: "92191f72-e3d7-4679-97a2-f0c2d19d7738",
    definitionId: "29cd7064-3703-43e0-8702-d1ba13703fd8", // Ali Baba
    setCode: "4ed",
    rarity: "uncommon",
};

export const ballLightning4ed: CardPrint = {
    printId: "6bccf9a0-8d93-4b5e-ada0-1f19f260e5a8",
    definitionId: "c1ba83ab-83f5-421d-bba1-0f925870b5c8", // Ball Lightning
    setCode: "4ed",
    rarity: "rare",
};

export const birdMaiden4ed: CardPrint = {
    printId: "fc81a99a-0380-456f-8e81-753add511dbe",
    definitionId: "5c1ba0b9-db01-447f-90cc-a2fc2c24146e", // Bird Maiden
    setCode: "4ed",
    rarity: "common",
};

export const bloodLust4ed: CardPrint = {
    printId: "426e477f-2873-4115-9527-a50a97769dd1",
    definitionId: "fbbf1a9c-8b94-4ee7-92db-65b531149990", // Blood Lust
    setCode: "4ed",
    rarity: "common",
};

export const brothersOfFire4ed: CardPrint = {
    printId: "66674f3a-e882-44f1-addc-d74605150c39",
    definitionId: "ba2cc4a6-fdcc-4082-801a-d2c50e560e8d", // Brothers of Fire
    setCode: "4ed",
    rarity: "common",
};

export const burrowing4ed: CardPrint = {
    printId: "946f1a83-6fcc-45b0-91fc-9c75504a16f3",
    definitionId: "a14c05e4-8df3-450b-8a98-5028e73b14c1", // Burrowing
    setCode: "4ed",
    rarity: "uncommon",
};

export const cavePeople4ed: CardPrint = {
    printId: "99e9ff47-b98c-4ab6-a4bc-8914360c3f6d",
    definitionId: "72746a5d-faa1-44b7-97b5-0ef9302a3c13", // Cave People
    setCode: "4ed",
    rarity: "uncommon",
};

export const chaoslace4ed: CardPrint = {
    printId: "476180df-8b88-4ead-b6c5-6ccb3e8a2cfd",
    definitionId: "72ea2048-57bc-43d5-8987-33ca727f1a97", // Chaoslace
    setCode: "4ed",
    rarity: "rare",
};

export const detonate4ed: CardPrint = {
    printId: "26e23d23-92ca-4d74-88e8-e1137d7faaf1",
    definitionId: "ffd7eb90-ae95-49df-898a-9510187bce1c", // Detonate
    setCode: "4ed",
    rarity: "uncommon",
};

export const disintegrate4ed: CardPrint = {
    printId: "5f41f868-454e-4075-9ef4-bcf3754d421c",
    definitionId: "8712c49e-f171-4669-bed9-87575a37af11", // Disintegrate
    setCode: "4ed",
    rarity: "common",
};

export const dragonWhelp4ed: CardPrint = {
    printId: "349ff6e6-b914-4787-bb90-ea77a3550d23",
    definitionId: "6bbf1eab-bc32-4835-b566-8634b1fe81b0", // Dragon Whelp
    setCode: "4ed",
    rarity: "uncommon",
};

export const dwarvenWarriors4ed: CardPrint = {
    printId: "3616f381-ca10-4945-b95e-96dfefa3c303",
    definitionId: "2d4d87a3-5f8b-4152-9a8b-538ab49d62e8", // Dwarven Warriors
    setCode: "4ed",
    rarity: "common",
};

export const earthElemental4ed: CardPrint = {
    printId: "a5a859fd-28a3-470f-adf4-c6431ced27e1",
    definitionId: "b24b5864-44c0-4bc8-8705-9504f83b2c03", // Earth Elemental
    setCode: "4ed",
    rarity: "uncommon",
};

export const earthquake4ed: CardPrint = {
    printId: "19ec03ce-a8a3-42c3-a895-21cce1657411",
    definitionId: "e68ac362-6cdc-48a6-bdd3-4f8ea32add64", // Earthquake
    setCode: "4ed",
    rarity: "rare",
};

export const eternalWarrior4ed: CardPrint = {
    printId: "9d574075-9909-444a-817f-d6ad419aa62c",
    definitionId: "97cdc38e-1d96-4de2-98e2-713f5d4d2180", // Eternal Warrior
    setCode: "4ed",
    rarity: "common",
};

export const fireElemental4ed: CardPrint = {
    printId: "0261cd0f-e763-49b5-96ed-5e5767a3d8d7",
    definitionId: "da237992-2919-4e37-8f56-2164095f59b5", // Fire Elemental
    setCode: "4ed",
    rarity: "uncommon",
};

export const fireball4ed: CardPrint = {
    printId: "afe078d7-cdde-44bb-942e-417123ebeccb",
    definitionId: "b7623c00-144b-4a8f-9c6c-f5e9e4f65ece", // Fireball
    setCode: "4ed",
    rarity: "common",
};

export const firebreathing4ed: CardPrint = {
    printId: "294892cb-3927-4bf0-97ca-f37bdd0b9de5",
    definitionId: "3eb27381-505d-4e47-bf66-9e7ba91a5075", // Firebreathing
    setCode: "4ed",
    rarity: "common",
};

export const fissure4ed: CardPrint = {
    printId: "7601b15a-53d8-499f-837b-abf369d1e3f4",
    definitionId: "aa2d778d-d74b-45ec-a86b-5d52ffad6ba5", // Fissure
    setCode: "4ed",
    rarity: "common",
};

export const flashfires4ed: CardPrint = {
    printId: "ed0de18a-1dad-49f1-8127-09aa07b69eb0",
    definitionId: "ee8a05a4-0ce3-4abe-bb60-08af53cf08e5", // Flashfires
    setCode: "4ed",
    rarity: "uncommon",
};

export const giantStrength4ed: CardPrint = {
    printId: "f1aebd61-311c-4269-aa75-5c004639178d",
    definitionId: "a86190bb-1f41-4128-b9fb-dfb1d178359d", // Giant Strength
    setCode: "4ed",
    rarity: "common",
};

export const goblinBalloonBrigade4ed: CardPrint = {
    printId: "866df71c-856c-451d-a11b-c2086c265868",
    definitionId: "5129b422-7a35-4bc5-b14b-c814012a0d8f", // Goblin Balloon Brigade
    setCode: "4ed",
    rarity: "uncommon",
};

export const goblinKing4ed: CardPrint = {
    printId: "92dd4aef-6d15-4d74-96cf-1cc51812b541",
    definitionId: "5873672d-37ea-4c0f-97f3-12b74fde112d", // Goblin King
    setCode: "4ed",
    rarity: "rare",
};

export const goblinRockSled4ed: CardPrint = {
    printId: "25f4f0c1-a43e-4282-b20e-91c711c57521",
    definitionId: "91e0b59d-8f9b-4a76-9845-bcb0dc32523d", // Goblin Rock Sled
    setCode: "4ed",
    rarity: "common",
};

export const grayOgre4ed: CardPrint = {
    printId: "11bf2cc0-799f-4eb8-b338-ed7543f469e7",
    definitionId: "73ae5276-b607-4f23-a9d2-e8cc7b8e3693", // Gray Ogre
    setCode: "4ed",
    rarity: "common",
};

export const hillGiant4ed: CardPrint = {
    printId: "6ac25236-c2f2-48df-8dbb-d4f9ce790cfb",
    definitionId: "0ddb98e8-13fe-4786-83f7-b72c56db135a", // Hill Giant
    setCode: "4ed",
    rarity: "common",
};

export const hurloonMinotaur4ed: CardPrint = {
    printId: "5c2c27de-e788-4ad7-b1e3-030e7ef00471",
    definitionId: "78a9088f-8755-47cb-aa93-51d992ccab90", // Hurloon Minotaur
    setCode: "4ed",
    rarity: "common",
};

export const immolation4ed: CardPrint = {
    printId: "f9dbfdc1-a598-4c72-9b0d-91207bd067ab",
    definitionId: "9b3d34fa-398c-4ea0-a392-6690bd3a615c", // Immolation
    setCode: "4ed",
    rarity: "common",
};

export const inferno4ed: CardPrint = {
    printId: "3db90782-fa89-4470-bec5-27614e88a0a9",
    definitionId: "a6b61512-5b24-424c-966f-36b595781e14", // Inferno
    setCode: "4ed",
    rarity: "rare",
};

export const ironclawOrcs4ed: CardPrint = {
    printId: "d882105f-2de0-46ae-b673-01508c016cc6",
    definitionId: "d56421a8-34ae-4033-943f-c59a7bf2b6f9", // Ironclaw Orcs
    setCode: "4ed",
    rarity: "common",
};

export const keldonWarlord4ed: CardPrint = {
    printId: "b1a32db7-e1a8-47d8-a708-987bcbf0636e",
    definitionId: "8fe3fd83-969c-4add-888f-86f4306b067c", // Keldon Warlord
    setCode: "4ed",
    rarity: "uncommon",
};

export const lightningBolt4ed: CardPrint = {
    printId: "9521375e-0bc1-45ef-b513-6d332a25f9d2",
    definitionId: "d573ef03-4730-45aa-93dd-e45ac1dbaf4a", // Lightning Bolt
    setCode: "4ed",
    rarity: "common",
};

export const magneticMountain4ed: CardPrint = {
    printId: "993a14d5-a33d-426e-ab49-c3226a6fcdca",
    definitionId: "95fde48b-e40a-4183-b324-1ec276dde015", // Magnetic Mountain
    setCode: "4ed",
    rarity: "rare",
};

export const manaClash4ed: CardPrint = {
    printId: "a01f27b7-f1d0-4fb6-b743-ca7a810ef85c",
    definitionId: "72955141-d990-459f-adbe-7d3d0f5f6c95", // Mana Clash
    setCode: "4ed",
    rarity: "rare",
};

export const manaFlare4ed: CardPrint = {
    printId: "e7169e26-e700-4e71-b959-4592a03f3c9f",
    definitionId: "7fb99a26-beeb-4aca-bb02-b2d2ce0595f9", // Mana Flare
    setCode: "4ed",
    rarity: "rare",
};

export const manabarbs4ed: CardPrint = {
    printId: "ffb4f505-bc05-44ac-9190-60101f813c65",
    definitionId: "6121f72f-680f-4bb4-ae4d-37ee4ebed4d8", // Manabarbs
    setCode: "4ed",
    rarity: "rare",
};

export const monsSGoblinRaiders4ed: CardPrint = {
    printId: "9f31c715-9ab8-4578-989f-141099b6750c",
    definitionId: "b4eb3db3-6a7c-488a-9433-d5d1d3133816", // Mons's Goblin Raiders
    setCode: "4ed",
    rarity: "common",
};

export const orcishArtillery4ed: CardPrint = {
    printId: "19281eb4-f5b6-4b27-8c65-7e56d2a8ab77",
    definitionId: "a97208b1-a91b-4129-8a00-2f97b418accc", // Orcish Artillery
    setCode: "4ed",
    rarity: "uncommon",
};

export const orcishOriflamme4ed: CardPrint = {
    printId: "56cc0d8b-2d4b-4c3b-a9af-b5fae35e6ec5",
    definitionId: "911538ea-322c-4c40-a9c3-35e47fe60fce", // Orcish Oriflamme
    setCode: "4ed",
    rarity: "uncommon",
};

export const powerSurge4ed: CardPrint = {
    printId: "0b5717af-a1a3-45cb-8b05-7543eed5532a",
    definitionId: "62858604-ca5a-4f69-a045-a7515ebfabf2", // Power Surge
    setCode: "4ed",
    rarity: "rare",
};

export const redElementalBlast4ed: CardPrint = {
    printId: "a54246c9-5e5c-484e-a546-ae1f9fd020f3",
    definitionId: "776ad9be-3309-4f1d-9f27-6219d9477662", // Red Elemental Blast
    setCode: "4ed",
    rarity: "common",
};

export const shatter4ed: CardPrint = {
    printId: "bbd44196-aa28-4143-872d-592c6fc175a9",
    definitionId: "50dc7fc1-cb6a-4c68-b993-1a25cf16226e", // Shatter
    setCode: "4ed",
    rarity: "common",
};

export const shivanDragon4ed: CardPrint = {
    printId: "70846483-9c23-42c4-9f9f-1fc5cda17c77",
    definitionId: "fefbf149-f988-4f8b-9f53-56f5878116a6", // Shivan Dragon
    setCode: "4ed",
    rarity: "rare",
};

export const sistersOfTheFlame4ed: CardPrint = {
    printId: "a39ab53c-133a-4211-8499-aea00ed3ee1d",
    definitionId: "564e0ccd-decb-48d2-981f-cefa8045340f", // Sisters of the Flame
    setCode: "4ed",
    rarity: "common",
};

export const smoke4ed: CardPrint = {
    printId: "c2069f9b-578a-45da-bd52-3c208465be88",
    definitionId: "7c67788e-d713-47c3-ab9f-b8a6212ae24f", // Smoke
    setCode: "4ed",
    rarity: "rare",
};

export const stoneGiant4ed: CardPrint = {
    printId: "265de55e-63d2-4a5d-9078-858da70f2a08",
    definitionId: "7ffaedb9-25f8-4304-9085-e12505b93312", // Stone Giant
    setCode: "4ed",
    rarity: "uncommon",
};

export const stoneRain4ed: CardPrint = {
    printId: "b9029bfb-fcff-4f80-a423-c2cfdc881c61",
    definitionId: "57ff74cb-a2ed-4123-ac42-f72f9820049e", // Stone Rain
    setCode: "4ed",
    rarity: "common",
};

export const theBrute4ed: CardPrint = {
    printId: "4b58ca62-6532-45e5-ad51-84a388d5cc4d",
    definitionId: "f9ffb265-872f-47b3-974c-92bcbebd557e", // The Brute
    setCode: "4ed",
    rarity: "common",
};

export const tunnel4ed: CardPrint = {
    printId: "9483f5d0-c627-43ed-bfaa-1559855c8a6d",
    definitionId: "b21ebc9f-a93e-4d18-b3e8-8459e3abbf31", // Tunnel
    setCode: "4ed",
    rarity: "uncommon",
};

export const uthdenTroll4ed: CardPrint = {
    printId: "28dea433-2dee-4faf-a868-6af664c6af4a",
    definitionId: "2ff21a6f-83a7-4bf3-a078-294e303232cc", // Uthden Troll
    setCode: "4ed",
    rarity: "uncommon",
};

export const wallOfFire4ed: CardPrint = {
    printId: "ccd7753b-0f01-42f3-9a5b-fe1ac6e7441d",
    definitionId: "efcf12cd-fb70-444e-9641-73ffa0e8f16e", // Wall of Fire
    setCode: "4ed",
    rarity: "uncommon",
};

export const wallOfStone4ed: CardPrint = {
    printId: "8c4b68e0-ec8b-4dad-91ee-dc1da5db6251",
    definitionId: "140e567c-6e4a-42b0-8084-d6c9695ae802", // Wall of Stone
    setCode: "4ed",
    rarity: "uncommon",
};

export const windsOfChange4ed: CardPrint = {
    printId: "77071f4c-d00b-4c79-a2e6-6be0720af36b",
    definitionId: "186fd917-8d65-4de5-8546-a32a5f6d3bab", // Winds of Change
    setCode: "4ed",
    rarity: "rare",
};
