import type { CardPrint } from "../../types";

// 4ED (Fourth Edition) white cards, split by colour per ADR 0043.
//
// Fourth Edition is a 100% reprint core set — it introduces no new cards — so
// this module is entirely CardPrint entries: each declares the per-edition
// Scryfall UUID (printId) and resolves printId -> definitionId -> a shared
// CardDefinition already implemented in lea/leb/arn/atq/leg/drk/fem/ice/2ed/3ed.
// See ADR 0014. 4ED is the earliest Premodern-legal set (issue #980).
//
// Generated by scripts/generate-4ed-prints.mts from data/json/4ED.json
// (name -> definitionId match via the live registry, printId + rarity from the
// 4ED Scryfall entry). Re-run that script to regenerate.
//
// Excluded: ante cards — Bronze Tablet, Rebirth, Tempest Efreet — are permanently out of
// scope (ADR 0010) and carry no print row. Cards whose CardDefinition is not
// yet implemented are omitted; each lands automatically once its definition
// exists.

export const alabasterPotion4ed: CardPrint = {
    printId: "51c931a4-297a-4f7f-8f71-6bdcbe4e94b7",
    definitionId: "2806c7f6-8fdd-4e65-9c71-f2e8b0cdede2", // Alabaster Potion
    setCode: "4ed",
    rarity: "common",
};

export const amrouKithkin4ed: CardPrint = {
    printId: "27de9b02-1810-41ee-aa90-5d89b6e1bf87",
    definitionId: "cbce1c55-123c-4a05-bde4-18a1601fcc5a", // Amrou Kithkin
    setCode: "4ed",
    rarity: "common",
};

export const angryMob4ed: CardPrint = {
    printId: "a26d1c4d-af95-4b40-83a5-b51f8b2506db",
    definitionId: "9e14db1c-0a05-47d2-9f27-df881f7f37ab", // Angry Mob
    setCode: "4ed",
    rarity: "uncommon",
};

export const animateWall4ed: CardPrint = {
    printId: "b6ee58e5-f493-4e27-9639-5599a9573387",
    definitionId: "d5c83259-9b90-47c2-b48e-c7d78519e792", // Animate Wall
    setCode: "4ed",
    rarity: "rare",
};

export const armageddon4ed: CardPrint = {
    printId: "0794bc35-a8e1-4268-87b2-af5483ca6e5e",
    definitionId: "5b6ddce7-b9c5-431d-a0b0-46d4aa93cbcb", // Armageddon
    setCode: "4ed",
    rarity: "rare",
};

export const balance4ed: CardPrint = {
    printId: "db3e219d-8e5e-44c7-97b3-2d489e2808b9",
    definitionId: "6f9ea46a-411f-40ce-a873-a905180093f4", // Balance
    setCode: "4ed",
    rarity: "rare",
};

export const benalishHero4ed: CardPrint = {
    printId: "fd204832-5f3b-4213-9c06-b89a296a9d47",
    definitionId: "11600105-56c6-4073-a4a6-8469030b39c9", // Benalish Hero
    setCode: "4ed",
    rarity: "common",
};

export const blackWard4ed: CardPrint = {
    printId: "218b1327-5f76-4ee2-a93d-d2ba412043c2",
    definitionId: "15967a39-303f-457d-bcde-51837c8d63e1", // Black Ward
    setCode: "4ed",
    rarity: "uncommon",
};

export const blessing4ed: CardPrint = {
    printId: "eea35ac3-071d-4a42-9a7a-9104fe63bddc",
    definitionId: "f131fd27-18da-47ca-b59f-135bcac83abd", // Blessing
    setCode: "4ed",
    rarity: "rare",
};

export const blueWard4ed: CardPrint = {
    printId: "de62c833-c66b-442e-99ed-99ccd8eca024",
    definitionId: "93f9f0f2-e1cc-4740-888c-1336c6de0a27", // Blue Ward
    setCode: "4ed",
    rarity: "uncommon",
};

export const castle4ed: CardPrint = {
    printId: "870ee86b-222b-4d7a-9c5b-ea10e1d73756",
    definitionId: "b0da8d56-3178-44c2-9344-95d2346d326f", // Castle
    setCode: "4ed",
    rarity: "uncommon",
};

export const circleOfProtectionArtifacts4ed: CardPrint = {
    printId: "6bfddcee-704f-4189-8cb0-6025fe98d7e9",
    definitionId: "22ebd5a3-fef8-4097-b038-89a6cb38227d", // Circle of Protection: Artifacts
    setCode: "4ed",
    rarity: "uncommon",
};

export const circleOfProtectionBlack4ed: CardPrint = {
    printId: "9971cbae-3f08-48c6-955a-76ce8ed41c6c",
    definitionId: "fa47b4cd-8da4-4544-b011-ba92b7009203", // Circle of Protection: Black
    setCode: "4ed",
    rarity: "common",
};

export const circleOfProtectionBlue4ed: CardPrint = {
    printId: "4b7cdfd5-bef9-4f33-b81a-2a395c9bba29",
    definitionId: "848b1a7f-e8ba-40b5-92b7-af1e963a0319", // Circle of Protection: Blue
    setCode: "4ed",
    rarity: "common",
};

export const circleOfProtectionGreen4ed: CardPrint = {
    printId: "192c50c5-ef98-47bd-9cab-cb3feaf6080b",
    definitionId: "1ae32d20-b438-4f43-b603-e8f706ecfb03", // Circle of Protection: Green
    setCode: "4ed",
    rarity: "common",
};

export const circleOfProtectionRed4ed: CardPrint = {
    printId: "f3575259-b019-47d0-a6d3-3fe4963294ae",
    definitionId: "b3dd94c5-42f6-4148-be6e-2a3a4226cc0e", // Circle of Protection: Red
    setCode: "4ed",
    rarity: "common",
};

export const circleOfProtectionWhite4ed: CardPrint = {
    printId: "92e1e153-cf5c-429a-9680-53b7c89dbd88",
    definitionId: "92df19c9-e127-42d9-8dd2-7fa5a7095428", // Circle of Protection: White
    setCode: "4ed",
    rarity: "common",
};

export const conversion4ed: CardPrint = {
    printId: "5df33281-bebc-4c2a-97ce-528a67574670",
    definitionId: "13186bc9-8d9c-433b-ba15-121ef94dd68a", // Conversion
    setCode: "4ed",
    rarity: "uncommon",
};

export const crusade4ed: CardPrint = {
    printId: "fb5428ef-847d-4ac1-b9a9-31afe155650f",
    definitionId: "057986c7-20c0-4157-b4df-beae4ef5c66d", // Crusade
    setCode: "4ed",
    rarity: "rare",
};

export const deathWard4ed: CardPrint = {
    printId: "e9c54ffe-2479-4178-a5dc-dca7b564efce",
    definitionId: "fa5466cc-aa57-4a7f-8b21-d92b2fe02e13", // Death Ward
    setCode: "4ed",
    rarity: "common",
};

export const disenchant4ed: CardPrint = {
    printId: "a915f261-2cdc-499c-9163-da5b628b0127",
    definitionId: "2722d7e2-61c6-4934-9c21-875ee78fd06c", // Disenchant
    setCode: "4ed",
    rarity: "common",
};

export const divineTransformation4ed: CardPrint = {
    printId: "f59605bf-27d8-47ca-805e-527aab6ddf70",
    definitionId: "a89ad9fd-33a6-4d31-9f4c-8bf192882f21", // Divine Transformation
    setCode: "4ed",
    rarity: "uncommon",
};

export const eyeForAnEye4ed: CardPrint = {
    printId: "acc41bca-73fc-42da-b639-b73a8de8a9c6",
    definitionId: "2933ca2a-097b-44f4-ae56-ad524d26fd06", // Eye for an Eye
    setCode: "4ed",
    rarity: "rare",
};

export const fortifiedArea4ed: CardPrint = {
    printId: "8f89968f-0182-4639-96fd-0dc94b6ad926",
    definitionId: "dc64f19c-5b2b-4697-b4dc-2be9c3790794", // Fortified Area
    setCode: "4ed",
    rarity: "common",
};

export const greenWard4ed: CardPrint = {
    printId: "b7548dc7-11dc-4611-85a5-71bdb48d8a62",
    definitionId: "1f6118b2-fe01-425a-a2ed-6d7c42286c8e", // Green Ward
    setCode: "4ed",
    rarity: "uncommon",
};

export const healingSalve4ed: CardPrint = {
    printId: "afd08b3b-196e-43a5-9318-9dae9edc6d12",
    definitionId: "e28de37e-84d5-4dc7-b36c-e14da5924729", // Healing Salve
    setCode: "4ed",
    rarity: "common",
};

export const holyArmor4ed: CardPrint = {
    printId: "3a0b9dba-f621-4700-8a36-bf326e04cbac",
    definitionId: "b01041d2-687e-4972-81c8-16690809275b", // Holy Armor
    setCode: "4ed",
    rarity: "common",
};

export const holyStrength4ed: CardPrint = {
    printId: "77af9f19-66d1-44e5-9aed-955e6bfd9902",
    definitionId: "e945a4cd-0eb1-4f54-898d-169ce2748a03", // Holy Strength
    setCode: "4ed",
    rarity: "common",
};

export const islandSanctuary4ed: CardPrint = {
    printId: "c0eff4d1-4ce6-48b1-84ae-a95bd1d04d16",
    definitionId: "c15e8a42-89de-42bc-8d5f-33426d207c3a", // Island Sanctuary
    setCode: "4ed",
    rarity: "rare",
};

export const karma4ed: CardPrint = {
    printId: "2acd8dd7-f561-487f-abae-4ad910db9d27",
    definitionId: "6f30ad61-fcb7-4d55-ba86-94de1bf545e4", // Karma
    setCode: "4ed",
    rarity: "uncommon",
};

export const kismet4ed: CardPrint = {
    printId: "f2381234-cf5a-4baf-89f9-cdec15557cf4",
    definitionId: "7e0651ad-6901-4f9b-8807-d66e53a4ada8", // Kismet
    setCode: "4ed",
    rarity: "uncommon",
};

export const mesaPegasus4ed: CardPrint = {
    printId: "60c0faf1-0c16-441a-97fd-6d4e91c894a5",
    definitionId: "eaac88da-d19e-4771-944c-3709963d04e7", // Mesa Pegasus
    setCode: "4ed",
    rarity: "common",
};

export const morale4ed: CardPrint = {
    printId: "b52cdfe3-fca1-420c-b5c0-2366ea58345b",
    definitionId: "c4104546-abd9-4bfb-a65e-5928cdd4522f", // Morale
    setCode: "4ed",
    rarity: "common",
};

export const northernPaladin4ed: CardPrint = {
    printId: "09e97dce-6bef-480d-939e-d35cfbf6b989",
    definitionId: "6303233b-35eb-49ca-b844-ba6b9fe1cbd2", // Northern Paladin
    setCode: "4ed",
    rarity: "rare",
};

export const osaiVultures4ed: CardPrint = {
    printId: "da915d3c-8d43-44c2-9052-08c1cd2afa7b",
    definitionId: "f85614b3-62a3-4da9-a74a-7ea40fad1b52", // Osai Vultures
    setCode: "4ed",
    rarity: "uncommon",
};

export const pearledUnicorn4ed: CardPrint = {
    printId: "6acc78fc-1eab-47aa-993d-6781b2d2408a",
    definitionId: "6daf1aab-1e58-4a5a-bc66-cb3f7c86e0e8", // Pearled Unicorn
    setCode: "4ed",
    rarity: "common",
};

export const personalIncarnation4ed: CardPrint = {
    printId: "0b107c80-0c9a-46cd-8f00-26c37f080ce7",
    definitionId: "caf9cef4-0f2d-478a-b119-fe1967687f74", // Personal Incarnation
    setCode: "4ed",
    rarity: "rare",
};

export const piety4ed: CardPrint = {
    printId: "d4942a9f-6b8f-438b-a2ea-366228038ed8",
    definitionId: "f649c571-d7ec-4ebc-9e18-b0657cab495b", // Piety
    setCode: "4ed",
    rarity: "common",
};

export const pikemen4ed: CardPrint = {
    printId: "015cc1ad-8b9f-484c-aa7d-d44f7bc914d2",
    definitionId: "bf2f6936-b50c-4907-9b55-ebf8a3fba8f5", // Pikemen
    setCode: "4ed",
    rarity: "common",
};

export const purelace4ed: CardPrint = {
    printId: "5736fcc7-fa95-4ef4-b821-392ec00e03bf",
    definitionId: "2facf462-55cd-4da4-997f-2cf4add75628", // Purelace
    setCode: "4ed",
    rarity: "rare",
};

export const redWard4ed: CardPrint = {
    printId: "543e8ec0-f36a-46a6-b7b1-e983e90a091a",
    definitionId: "e0c64c01-c2aa-470b-88c6-3d3e4a969649", // Red Ward
    setCode: "4ed",
    rarity: "uncommon",
};

export const reverseDamage4ed: CardPrint = {
    printId: "cd458c66-0183-4bad-a651-6fe52a6d14c4",
    definitionId: "943baea8-b173-4863-a3ab-dd217d483cd9", // Reverse Damage
    setCode: "4ed",
    rarity: "rare",
};

export const righteousness4ed: CardPrint = {
    printId: "3fccc7f2-b317-40c4-9b55-658d67dca843",
    definitionId: "d0ba7b76-f3d0-47d0-8a35-0c08e67200fb", // Righteousness
    setCode: "4ed",
    rarity: "rare",
};

export const samiteHealer4ed: CardPrint = {
    printId: "b354858f-d25b-4264-8a0b-fecc3a58db6d",
    definitionId: "efba235e-04e5-449c-906c-0ac33f6d7929", // Samite Healer
    setCode: "4ed",
    rarity: "common",
};

export const savannahLions4ed: CardPrint = {
    printId: "a2ee9127-d007-48e8-b797-88ef72bc7c8b",
    definitionId: "d05b92bd-797e-413f-a8b0-32e0937a1ee0", // Savannah Lions
    setCode: "4ed",
    rarity: "rare",
};

export const seeker4ed: CardPrint = {
    printId: "7052825f-d9fc-4820-b8c4-dbc204730b7c",
    definitionId: "df608b59-cc07-4e1d-b6d6-f15e69b15b92", // Seeker
    setCode: "4ed",
    rarity: "common",
};

export const serraAngel4ed: CardPrint = {
    printId: "8072d00a-82ff-4406-bdf8-1af20cd3a170",
    definitionId: "f8ac5006-91bd-4803-93da-f87cf196dd2f", // Serra Angel
    setCode: "4ed",
    rarity: "uncommon",
};

export const spiritLink4ed: CardPrint = {
    printId: "58838b77-3bac-41b7-8055-5737c07df12e",
    definitionId: "5e2d35f8-3cf6-4843-9030-0e9a885d836c", // Spirit Link
    setCode: "4ed",
    rarity: "uncommon",
};

export const swordsToPlowshares4ed: CardPrint = {
    printId: "8bd501ae-5814-4336-a45b-2b88cb85d29e",
    definitionId: "386ea9eb-abc1-4862-aa2d-8fb808d79490", // Swords to Plowshares
    setCode: "4ed",
    rarity: "uncommon",
};

export const tundraWolves4ed: CardPrint = {
    printId: "0c8527ac-27c3-4e2d-b46c-bfd6a1e1f778",
    definitionId: "8f649cb5-e19c-453f-b062-4fd452d92257", // Tundra Wolves
    setCode: "4ed",
    rarity: "common",
};

export const visions4ed: CardPrint = {
    printId: "b0fed0e6-0e56-4987-b0dd-b294156c0233",
    definitionId: "21d00299-e183-4b3d-b015-18808e7135b9", // Visions
    setCode: "4ed",
    rarity: "uncommon",
};

export const wallOfSwords4ed: CardPrint = {
    printId: "18ffa85c-61c4-49b7-8946-ab353355a11c",
    definitionId: "99ec4723-b36c-4015-b361-736a6523e8f5", // Wall of Swords
    setCode: "4ed",
    rarity: "uncommon",
};

export const whiteKnight4ed: CardPrint = {
    printId: "2e8f8a10-6984-46a7-a641-5f712dab5c57",
    definitionId: "50abfba8-c9f9-4ebf-965a-4b425fe83129", // White Knight
    setCode: "4ed",
    rarity: "uncommon",
};

export const whiteWard4ed: CardPrint = {
    printId: "2d3c467f-0e33-43e8-b108-0ea00d6adcc2",
    definitionId: "49b22665-1501-420a-82ad-f71f6768bcf8", // White Ward
    setCode: "4ed",
    rarity: "uncommon",
};

export const wrathOfGod4ed: CardPrint = {
    printId: "4566f6a3-4d25-4df0-84be-fe4201138955",
    definitionId: "a2788d69-6a3a-42f0-8736-cc6b57755ecd", // Wrath of God
    setCode: "4ed",
    rarity: "rare",
};
